; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-none-linux-gnu -verify-machineinstrs | FileCheck --check-prefixes=CHECK-LE,CHECK-SD-LE %s
; RUN: llc < %s -mtriple=aarch64-none-linux-gnu -verify-machineinstrs -global-isel | FileCheck --check-prefixes=CHECK-LE,CHECK-GI-LE %s
; RUN: llc < %s -mtriple=aarch64_be-none-linux-gnu -verify-machineinstrs | FileCheck --check-prefixes=CHECK-SD-BE %s

; Check for the crash in https://github.com/llvm/llvm-project/issues/173483
define void @f(<2 x i8> %1) {
; CHECK-SD-LE-LABEL: f:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    sub sp, sp, #16
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-LE-NEXT:    mov s1, v0.s[1]
; CHECK-SD-LE-NEXT:    str b0, [sp, #12]
; CHECK-SD-LE-NEXT:    stur b1, [sp, #13]
; CHECK-SD-LE-NEXT:    ldrh w8, [sp, #12]
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    //APP
; CHECK-SD-LE-NEXT:    //NO_APP
; CHECK-SD-LE-NEXT:    add sp, sp, #16
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: f:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    uzp1 v0.4h, v0.4h, v0.4h
; CHECK-GI-LE-NEXT:    uzp1 v0.8b, v0.8b, v0.8b
; CHECK-GI-LE-NEXT:    //APP
; CHECK-GI-LE-NEXT:    //NO_APP
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: f:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    sub sp, sp, #16
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    mov s1, v0.s[1]
; CHECK-SD-BE-NEXT:    str b0, [sp, #12]
; CHECK-SD-BE-NEXT:    stur b1, [sp, #13]
; CHECK-SD-BE-NEXT:    ldrh w8, [sp, #12]
; CHECK-SD-BE-NEXT:    fmov s0, w8
; CHECK-SD-BE-NEXT:    //APP
; CHECK-SD-BE-NEXT:    //NO_APP
; CHECK-SD-BE-NEXT:    add sp, sp, #16
; CHECK-SD-BE-NEXT:    ret
  call void asm sideeffect "", "w"(<2 x i8> %1)
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-LE: {{.*}}
