; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64--linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be--linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc -mtriple=aarch64--linux-gnu -global-isel < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc -mtriple=aarch64_be--linux-gnu -global-isel < %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE

@vec_v8i16 = dso_local global <8 x i16> <i16 1, i16 2, i16 3, i16 4, i16 5, i16 6, i16 7, i16 8>

define dso_local void @movi_modimm_t1() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t1:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.4s, #1
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t1:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.4s, #1
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t1:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI0_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t1:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI0_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t2() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t2:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.4s, #1, lsl #8
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t2:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.4s, #1, lsl #8
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t2:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI1_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI1_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t2:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI1_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI1_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 256, i16 0, i16 256, i16 0, i16 256, i16 0, i16 256, i16 0>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t3() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t3:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.4s, #1, lsl #16
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t3:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.4s, #1, lsl #16
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t3:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI2_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI2_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t3:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI2_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI2_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t4() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t4:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.4s, #1, lsl #24
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t4:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.4s, #1, lsl #24
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t4:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI3_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI3_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t4:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI3_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI3_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 0, i16 256, i16 0, i16 256, i16 0, i16 256, i16 0, i16 256>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t5() nounwind {
; CHECK-LE-LABEL: movi_modimm_t5:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    movi v0.8h, #1
; CHECK-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: movi_modimm_t5:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    movi v0.8h, #1
; CHECK-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t6() nounwind {
; CHECK-LE-LABEL: movi_modimm_t6:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    movi v0.8h, #1, lsl #8
; CHECK-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: movi_modimm_t6:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    movi v0.8h, #1, lsl #8
; CHECK-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 256, i16 256, i16 256, i16 256, i16 256, i16 256, i16 256, i16 256>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t7() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t7:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.4s, #1, msl #8
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t7:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.4s, #1, msl #8
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t7:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI6_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI6_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t7:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI6_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI6_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 511, i16 0, i16 511, i16 0, i16 511, i16 0, i16 511, i16 0>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t8() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t8:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.4s, #1, msl #16
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t8:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.4s, #1, msl #16
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t8:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI7_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI7_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t8:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI7_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI7_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65535, i16 1, i16 65535, i16 1, i16 65535, i16 1, i16 65535, i16 1>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t9() nounwind {
; CHECK-LE-LABEL: movi_modimm_t9:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    movi v0.16b, #1
; CHECK-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: movi_modimm_t9:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    movi v0.16b, #1
; CHECK-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 257, i16 257, i16 257, i16 257, i16 257, i16 257, i16 257, i16 257>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @movi_modimm_t10() nounwind {
; CHECK-SD-LE-LABEL: movi_modimm_t10:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    movi v0.2d, #0x00ffff0000ffff
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: movi_modimm_t10:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    movi v0.2d, #0x00ffff0000ffff
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: movi_modimm_t10:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI9_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI9_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: movi_modimm_t10:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI9_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI9_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 -1, i16 0, i16 -1, i16 0, i16 -1, i16 0, i16 -1, i16 0>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @fmov_modimm_t11() nounwind {
; CHECK-SD-LE-LABEL: fmov_modimm_t11:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    fmov v0.4s, #3.00000000
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: fmov_modimm_t11:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    fmov v0.4s, #3.00000000
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: fmov_modimm_t11:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI10_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI10_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: fmov_modimm_t11:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI10_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI10_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 0, i16 16448, i16 0, i16 16448, i16 0, i16 16448, i16 0, i16 16448>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @fmov_modimm_t12() nounwind {
; CHECK-SD-LE-LABEL: fmov_modimm_t12:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    fmov v0.2d, #0.17968750
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: fmov_modimm_t12:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    fmov v0.2d, #0.17968750
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: fmov_modimm_t12:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI11_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI11_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: fmov_modimm_t12:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI11_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI11_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 0, i16 0, i16 0, i16 16327, i16 0, i16 0, i16 0, i16 16327>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t1() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t1:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.4s, #1
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t1:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.4s, #1
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t1:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI12_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI12_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t1:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI12_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI12_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65534, i16 65535, i16 65534, i16 65535, i16 65534, i16 65535, i16 65534, i16 65535>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t2() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t2:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.4s, #1, lsl #8
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t2:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.4s, #1, lsl #8
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t2:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI13_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI13_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t2:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI13_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI13_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65279, i16 65535, i16 65279, i16 65535, i16 65279, i16 65535, i16 65279, i16 65535>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t3() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t3:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.4s, #1, lsl #16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t3:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.4s, #1, lsl #16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t3:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI14_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI14_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t3:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI14_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI14_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65535, i16 65534, i16 65535, i16 65534, i16 65535, i16 65534, i16 65535, i16 65534>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t4() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t4:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.4s, #1, lsl #24
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t4:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.4s, #1, lsl #24
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t4:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI15_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI15_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t4:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI15_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI15_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65535, i16 65279, i16 65535, i16 65279, i16 65535, i16 65279, i16 65535, i16 65279>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t5() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t5:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.8h, #1
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t5:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.8h, #1
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t5:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    mvni v0.8h, #1
; CHECK-GI-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t5:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    mvni v0.8h, #1
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-GI-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65534, i16 65534, i16 65534, i16 65534, i16 65534, i16 65534, i16 65534, i16 65534>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t6() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t6:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.8h, #1, lsl #8
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t6:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.8h, #1, lsl #8
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t6:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    mvni v0.8h, #1, lsl #8
; CHECK-GI-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t6:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    mvni v0.8h, #1, lsl #8
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-GI-BE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65279, i16 65279, i16 65279, i16 65279, i16 65279, i16 65279, i16 65279, i16 65279>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t7() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t7:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.4s, #1, msl #8
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t7:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.4s, #1, msl #8
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t7:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI18_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI18_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t7:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI18_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI18_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 65024, i16 65535, i16 65024, i16 65535, i16 65024, i16 65535, i16 65024, i16 65535>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @mvni_modimm_t8() nounwind {
; CHECK-SD-LE-LABEL: mvni_modimm_t8:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    mvni v0.4s, #1, msl #16
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mvni_modimm_t8:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    mvni v1.4s, #1, msl #16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: mvni_modimm_t8:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI19_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI19_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    add v0.8h, v1.8h, v0.8h
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mvni_modimm_t8:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI19_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI19_0]
; CHECK-GI-BE-NEXT:    add v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = add <8 x i16> %in, <i16 0, i16 65534, i16 0, i16 65534, i16 0, i16 65534, i16 0, i16 65534>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @bic_modimm_t1() nounwind {
; CHECK-SD-LE-LABEL: bic_modimm_t1:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    bic v0.4s, #1
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bic_modimm_t1:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    bic v0.4s, #1
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bic_modimm_t1:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI20_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI20_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bic_modimm_t1:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI20_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI20_0]
; CHECK-GI-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = and <8 x i16> %in, <i16 65534, i16 65535, i16 65534, i16 65535, i16 65534, i16 65535, i16 65534, i16 65535>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @bic_modimm_t2() nounwind {
; CHECK-SD-LE-LABEL: bic_modimm_t2:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    bic v0.4s, #1, lsl #8
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bic_modimm_t2:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    bic v0.4s, #1, lsl #8
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bic_modimm_t2:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI21_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI21_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bic_modimm_t2:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI21_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI21_0]
; CHECK-GI-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = and <8 x i16> %in, <i16 65279, i16 65535, i16 65279, i16 65535, i16 65279, i16 65535, i16 65279, i16 65535>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @bic_modimm_t3() nounwind {
; CHECK-SD-LE-LABEL: bic_modimm_t3:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    bic v0.4s, #1, lsl #16
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bic_modimm_t3:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    bic v0.4s, #1, lsl #16
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bic_modimm_t3:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI22_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI22_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bic_modimm_t3:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI22_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI22_0]
; CHECK-GI-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = and <8 x i16> %in, <i16 65535, i16 65534, i16 65535, i16 65534, i16 65535, i16 65534, i16 65535, i16 65534>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @bic_modimm_t4() nounwind {
; CHECK-SD-LE-LABEL: bic_modimm_t4:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    bic v0.4s, #1, lsl #24
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bic_modimm_t4:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    bic v0.4s, #1, lsl #24
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bic_modimm_t4:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI23_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI23_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bic_modimm_t4:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI23_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI23_0]
; CHECK-GI-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = and <8 x i16> %in, <i16 65535, i16 65279, i16 65535, i16 65279, i16 65535, i16 65279, i16 65535, i16 65279>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @bic_modimm_t5() nounwind {
; CHECK-SD-LE-LABEL: bic_modimm_t5:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    bic v0.8h, #1
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bic_modimm_t5:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    bic v0.8h, #1
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bic_modimm_t5:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    mvni v0.8h, #1
; CHECK-GI-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bic_modimm_t5:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    mvni v0.8h, #1
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-GI-BE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = and <8 x i16> %in, <i16 65534, i16 65534, i16 65534, i16 65534, i16 65534, i16 65534, i16 65534, i16 65534>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @bic_modimm_t6() nounwind {
; CHECK-SD-LE-LABEL: bic_modimm_t6:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    bic v0.8h, #1, lsl #8
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bic_modimm_t6:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    bic v0.8h, #1, lsl #8
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bic_modimm_t6:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    mvni v0.8h, #1, lsl #8
; CHECK-GI-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bic_modimm_t6:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    mvni v0.8h, #1, lsl #8
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-GI-BE-NEXT:    and v0.16b, v1.16b, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = and <8 x i16> %in, <i16 65279, i16 65279, i16 65279, i16 65279, i16 65279, i16 65279, i16 65279, i16 65279>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @orr_modimm_t1() nounwind {
; CHECK-SD-LE-LABEL: orr_modimm_t1:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    orr v0.4s, #1
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: orr_modimm_t1:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    orr v0.4s, #1
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: orr_modimm_t1:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI26_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI26_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: orr_modimm_t1:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI26_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI26_0]
; CHECK-GI-BE-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = or <8 x i16> %in, <i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @orr_modimm_t2() nounwind {
; CHECK-SD-LE-LABEL: orr_modimm_t2:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    orr v0.4s, #1, lsl #8
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: orr_modimm_t2:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    orr v0.4s, #1, lsl #8
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: orr_modimm_t2:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI27_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI27_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: orr_modimm_t2:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI27_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI27_0]
; CHECK-GI-BE-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = or <8 x i16> %in, <i16 256, i16 0, i16 256, i16 0, i16 256, i16 0, i16 256, i16 0>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @orr_modimm_t3() nounwind {
; CHECK-SD-LE-LABEL: orr_modimm_t3:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    orr v0.4s, #1, lsl #16
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: orr_modimm_t3:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    orr v0.4s, #1, lsl #16
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: orr_modimm_t3:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI28_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI28_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: orr_modimm_t3:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI28_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI28_0]
; CHECK-GI-BE-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = or <8 x i16> %in, <i16 0, i16 1, i16 0, i16 1, i16 0, i16 1, i16 0, i16 1>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @orr_modimm_t4() nounwind {
; CHECK-SD-LE-LABEL: orr_modimm_t4:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    orr v0.4s, #1, lsl #24
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: orr_modimm_t4:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    orr v0.4s, #1, lsl #24
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: orr_modimm_t4:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI29_0
; CHECK-GI-LE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI29_0]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x9, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: orr_modimm_t4:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    adrp x9, vec_v8i16
; CHECK-GI-BE-NEXT:    add x9, x9, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI29_0
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI29_0]
; CHECK-GI-BE-NEXT:    orr v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = or <8 x i16> %in, <i16 0, i16 256, i16 0, i16 256, i16 0, i16 256, i16 0, i16 256>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @orr_modimm_t5() nounwind {
; CHECK-SD-LE-LABEL: orr_modimm_t5:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    orr v0.8h, #1
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: orr_modimm_t5:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    orr v0.8h, #1
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: orr_modimm_t5:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    movi v0.8h, #1
; CHECK-GI-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: orr_modimm_t5:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    movi v0.8h, #1
; CHECK-GI-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-GI-BE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = or <8 x i16> %in, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

define dso_local void @orr_modimm_t6() nounwind {
; CHECK-SD-LE-LABEL: orr_modimm_t6:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-LE-NEXT:    ldr q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    orr v0.8h, #1, lsl #8
; CHECK-SD-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: orr_modimm_t6:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    orr v0.8h, #1, lsl #8
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: orr_modimm_t6:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    movi v0.8h, #1, lsl #8
; CHECK-GI-LE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-LE-NEXT:    str q0, [x8, :lo12:vec_v8i16]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: orr_modimm_t6:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    movi v0.8h, #1, lsl #8
; CHECK-GI-BE-NEXT:    adrp x8, vec_v8i16
; CHECK-GI-BE-NEXT:    add x8, x8, :lo12:vec_v8i16
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x8]
; CHECK-GI-BE-NEXT:    orr v0.16b, v1.16b, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %in = load <8 x i16>, ptr @vec_v8i16
  %rv = or <8 x i16> %in, <i16 256, i16 256, i16 256, i16 256, i16 256, i16 256, i16 256, i16 256>
  store <8 x i16> %rv, ptr @vec_v8i16
  ret void
}

declare i8 @f_v8i8(<8 x i8> %arg)
declare i16 @f_v4i16(<4 x i16> %arg)
declare i32 @f_v2i32(<2 x i32> %arg)
declare i64 @f_v1i64(<1 x i64> %arg)
declare i8 @f_v16i8(<16 x i8> %arg)
declare i16 @f_v8i16(<8 x i16> %arg)
declare i32 @f_v4i32(<4 x i32> %arg)
declare i64 @f_v2i64(<2 x i64> %arg)

define dso_local void @modimm_t1_call() {
; CHECK-SD-LE-LABEL: modimm_t1_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.2s, #8
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.2s, #7
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2s, #6
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2s, #5
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.4s, #5
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.4s, #4
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.4s, #3
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.4s, #2
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t1_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.2s, #8
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.2s, #7
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2s, #6
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2s, #5
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.4s, #5
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.4s, #4
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.4s, #3
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.4s, #2
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t1_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI32_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI32_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI32_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI32_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI32_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI32_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI32_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI32_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.2s, #6
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #5 // =0x5
; CHECK-GI-LE-NEXT:    movk x8, #5, lsl #32
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.4s, #3
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.4s, #2
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t1_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI32_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI32_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI32_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI32_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI32_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI32_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI32_2]
; CHECK-GI-BE-NEXT:    movi v8.2s, #6
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI32_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #5 // =0x5
; CHECK-GI-BE-NEXT:    movk x8, #5, lsl #32
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.4s, #3
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.4s, #2
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 8, i8 0, i8 0, i8 0, i8 8, i8 0, i8 0, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 7, i16 0, i16 7, i16 0>)
  call i32 @f_v2i32(<2 x i32> <i32 6, i32 6>)
  call i64 @f_v1i64(<1 x i64> <i64 21474836485>)
  call i8 @f_v16i8(<16 x i8> <i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 4, i16 0, i16 4, i16 0, i16 4, i16 0, i16 4, i16 0>)
  call i32 @f_v4i32(<4 x i32> <i32 3, i32 3, i32 3, i32 3>)
  call i64 @f_v2i64(<2 x i64> <i64 8589934594, i64 8589934594>)

  ret void
}

define dso_local void @modimm_t2_call() {
; CHECK-SD-LE-LABEL: modimm_t2_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.2s, #8, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.2s, #7, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2s, #6, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2s, #5, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.4s, #5, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.4s, #4, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.4s, #3, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.4s, #2, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t2_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.2s, #8, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.2s, #7, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2s, #6, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2s, #5, lsl #8
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.4s, #5, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.4s, #4, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.4s, #3, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.4s, #2, lsl #8
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t2_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI33_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI33_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI33_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI33_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI33_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI33_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI33_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI33_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.2s, #6, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #1280 // =0x500
; CHECK-GI-LE-NEXT:    movk x8, #1280, lsl #32
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.4s, #3, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.4s, #2, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t2_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI33_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI33_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI33_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI33_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI33_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI33_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI33_2]
; CHECK-GI-BE-NEXT:    movi v8.2s, #6, lsl #8
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI33_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #1280 // =0x500
; CHECK-GI-BE-NEXT:    movk x8, #1280, lsl #32
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.4s, #3, lsl #8
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.4s, #2, lsl #8
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 0, i8 8, i8 0, i8 0, i8 0, i8 8, i8 0, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 1792, i16 0, i16 1792, i16 0>)
  call i32 @f_v2i32(<2 x i32> <i32 1536, i32 1536>)
  call i64 @f_v1i64(<1 x i64> <i64 5497558140160>)
  call i8 @f_v16i8(<16 x i8> <i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 1024, i16 0, i16 1024, i16 0, i16 1024, i16 0, i16 1024, i16 0>)
  call i32 @f_v4i32(<4 x i32> <i32 768, i32 768, i32 768, i32 768>)
  call i64 @f_v2i64(<2 x i64> <i64 2199023256064, i64 2199023256064>)

  ret void
}

define dso_local void @modimm_t3_call() {
; CHECK-SD-LE-LABEL: modimm_t3_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.2s, #8, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.2s, #7, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2s, #6, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2s, #5, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.4s, #5, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.4s, #4, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.4s, #3, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.4s, #2, lsl #16
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t3_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.2s, #8, lsl #16
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.2s, #7, lsl #16
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2s, #6, lsl #16
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2s, #5, lsl #16
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.4s, #5, lsl #16
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.4s, #4, lsl #16
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.4s, #3, lsl #16
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.4s, #2, lsl #16
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t3_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI34_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI34_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI34_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI34_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI34_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI34_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI34_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI34_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.2s, #6, lsl #16
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #327680 // =0x50000
; CHECK-GI-LE-NEXT:    movk x8, #5, lsl #48
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.4s, #3, lsl #16
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.4s, #2, lsl #16
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t3_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI34_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI34_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI34_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI34_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI34_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI34_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI34_2]
; CHECK-GI-BE-NEXT:    movi v8.2s, #6, lsl #16
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI34_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #327680 // =0x50000
; CHECK-GI-BE-NEXT:    movk x8, #5, lsl #48
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.4s, #3, lsl #16
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.4s, #2, lsl #16
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 0, i8 0, i8 8, i8 0, i8 0, i8 0, i8 8, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 0, i16 7, i16 0, i16 7>)
  call i32 @f_v2i32(<2 x i32> <i32 393216, i32 393216>)
  call i64 @f_v1i64(<1 x i64> <i64 1407374883880960>)
  call i8 @f_v16i8(<16 x i8> <i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 0, i16 4, i16 0, i16 4, i16 0, i16 4, i16 0, i16 4>)
  call i32 @f_v4i32(<4 x i32> <i32 196608, i32 196608, i32 196608, i32 196608>)
  call i64 @f_v2i64(<2 x i64> <i64 562949953552384, i64 562949953552384>)

  ret void
}

define dso_local void @modimm_t4_call() {
; CHECK-SD-LE-LABEL: modimm_t4_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.2s, #8, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.2s, #7, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2s, #6, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2s, #5, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.4s, #5, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.4s, #4, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.4s, #3, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.4s, #2, lsl #24
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t4_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.2s, #8, lsl #24
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.2s, #7, lsl #24
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2s, #6, lsl #24
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2s, #5, lsl #24
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.4s, #5, lsl #24
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.4s, #4, lsl #24
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.4s, #3, lsl #24
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.4s, #2, lsl #24
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t4_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI35_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI35_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI35_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI35_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI35_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI35_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI35_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI35_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.2s, #6, lsl #24
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #83886080 // =0x5000000
; CHECK-GI-LE-NEXT:    movk x8, #1280, lsl #48
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.4s, #3, lsl #24
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.4s, #2, lsl #24
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t4_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI35_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI35_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI35_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI35_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI35_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI35_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI35_2]
; CHECK-GI-BE-NEXT:    movi v8.2s, #6, lsl #24
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI35_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #83886080 // =0x5000000
; CHECK-GI-BE-NEXT:    movk x8, #1280, lsl #48
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.4s, #3, lsl #24
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.4s, #2, lsl #24
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 0, i8 0, i8 0, i8 8, i8 0, i8 0, i8 0, i8 8>)
  call i16 @f_v4i16(<4 x i16> <i16 0, i16 1792, i16 0, i16 1792>)
  call i32 @f_v2i32(<2 x i32> <i32 100663296, i32 100663296>)
  call i64 @f_v1i64(<1 x i64> <i64 360287970273525760>)
  call i8 @f_v16i8(<16 x i8> <i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5, i8 0, i8 0, i8 0, i8 5>)
  call i16 @f_v8i16(<8 x i16> <i16 0, i16 1024, i16 0, i16 1024, i16 0, i16 1024, i16 0, i16 1024>)
  call i32 @f_v4i32(<4 x i32> <i32 50331648, i32 50331648, i32 50331648, i32 50331648>)
  call i64 @f_v2i64(<2 x i64> <i64 144115188109410304, i64 144115188109410304>)

  ret void
}

define dso_local void @modimm_t5_call() {
; CHECK-SD-LE-LABEL: modimm_t5_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.4h, #8
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.4h, #7
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.4h, #6
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.4h, #5
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.8h, #5
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.8h, #4
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.8h, #3
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.8h, #2
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t5_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.4h, #8
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.4h, #7
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.4h, #6
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.4h, #5
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.8h, #5
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.8h, #4
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.8h, #3
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.8h, #2
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t5_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #32
; CHECK-GI-LE-NEXT:    str x30, [sp, #16] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 32
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI36_1
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI36_0
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI36_1]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:.LCPI36_0]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    movi v0.4h, #7
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.4h, #6
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #1125917086973956 // =0x4000400040004
; CHECK-GI-LE-NEXT:    orr x8, x8, #0x1000100010001
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    movi v0.8h, #4
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.8h, #3
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.8h, #2
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #32
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t5_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #48
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #16] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI36_1
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI36_0
; CHECK-GI-BE-NEXT:    movi v8.4h, #7
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI36_1]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI36_0]
; CHECK-GI-BE-NEXT:    movi v9.4h, #6
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v8.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v9.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #1125917086973956 // =0x4000400040004
; CHECK-GI-BE-NEXT:    orr x8, x8, #0x1000100010001
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    movi v0.8h, #4
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.8h, #3
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.8h, #2
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #16] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #48
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 8, i8 0, i8 8, i8 0, i8 8, i8 0, i8 8, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 7, i16 7, i16 7, i16 7>)
  call i32 @f_v2i32(<2 x i32> <i32 393222, i32 393222>)
  call i64 @f_v1i64(<1 x i64> <i64 1407396358717445>)
  call i8 @f_v16i8(<16 x i8> <i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 4, i16 4, i16 4, i16 4, i16 4, i16 4, i16 4, i16 4>)
  call i32 @f_v4i32(<4 x i32> <i32 196611, i32 196611, i32 196611, i32 196611>)
  call i64 @f_v2i64(<2 x i64> <i64 562958543486978, i64 562958543486978>)

  ret void
}

define dso_local void @modimm_t6_call() {
; CHECK-SD-LE-LABEL: modimm_t6_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.4h, #8, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.4h, #7, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.4h, #6, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.4h, #5, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.8h, #5, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.8h, #4, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.8h, #3, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.8h, #2, lsl #8
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t6_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.4h, #8, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.4h, #7, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.4h, #6, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.4h, #5, lsl #8
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.8h, #5, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.8h, #4, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.8h, #3, lsl #8
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.8h, #2, lsl #8
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t6_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #32
; CHECK-GI-LE-NEXT:    str x30, [sp, #16] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 32
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI37_1
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI37_0
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI37_1]
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:.LCPI37_0]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    movi v0.4h, #7, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.4h, #6, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #72058693566333184 // =0x100010001000100
; CHECK-GI-LE-NEXT:    orr x8, x8, #0x400040004000400
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    movi v0.8h, #4, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.8h, #3, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.8h, #2, lsl #8
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #32
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t6_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #48
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #16] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI37_1
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI37_0
; CHECK-GI-BE-NEXT:    movi v8.4h, #7, lsl #8
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI37_1]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI37_0]
; CHECK-GI-BE-NEXT:    movi v9.4h, #6, lsl #8
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v8.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v9.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #72058693566333184 // =0x100010001000100
; CHECK-GI-BE-NEXT:    orr x8, x8, #0x400040004000400
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    movi v0.8h, #4, lsl #8
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.8h, #3, lsl #8
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.8h, #2, lsl #8
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #16] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #48
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 0, i8 8, i8 0, i8 8, i8 0, i8 8, i8 0, i8 8>)
  call i16 @f_v4i16(<4 x i16> <i16 1792, i16 1792, i16 1792, i16 1792>)
  call i32 @f_v2i32(<2 x i32> <i32 100664832, i32 100664832>)
  call i64 @f_v1i64(<1 x i64> <i64 360293467831665920>)
  call i8 @f_v16i8(<16 x i8> <i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5, i8 0, i8 5>)
  call i16 @f_v8i16(<8 x i16> <i16 1024, i16 1024, i16 1024, i16 1024, i16 1024, i16 1024, i16 1024, i16 1024>)
  call i32 @f_v4i32(<4 x i32> <i32 50332416, i32 50332416, i32 50332416, i32 50332416>)
  call i64 @f_v2i64(<2 x i64> <i64 144117387132666368, i64 144117387132666368>)

  ret void
}

define dso_local void @modimm_t7_call() {
; CHECK-SD-LE-LABEL: modimm_t7_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.2s, #8, msl #8
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.2s, #7, msl #8
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2s, #6, msl #8
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2s, #5, msl #8
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.4s, #5, msl #8
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.4s, #4, msl #8
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.4s, #3, msl #8
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.4s, #2, msl #8
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t7_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.2s, #8, msl #8
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.2s, #7, msl #8
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2s, #6, msl #8
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2s, #5, msl #8
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.4s, #5, msl #8
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.4s, #4, msl #8
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.4s, #3, msl #8
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.4s, #2, msl #8
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t7_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI38_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI38_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI38_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI38_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI38_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI38_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI38_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI38_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.2s, #6, msl #8
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #1535 // =0x5ff
; CHECK-GI-LE-NEXT:    movk x8, #1535, lsl #32
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.4s, #3, msl #8
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.4s, #2, msl #8
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t7_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI38_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI38_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI38_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI38_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI38_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI38_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI38_2]
; CHECK-GI-BE-NEXT:    movi v8.2s, #6, msl #8
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI38_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #1535 // =0x5ff
; CHECK-GI-BE-NEXT:    movk x8, #1535, lsl #32
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.4s, #3, msl #8
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.4s, #2, msl #8
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 255, i8 8, i8 0, i8 0, i8 255, i8 8, i8 0, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 2047, i16 0, i16 2047, i16 0>)
  call i32 @f_v2i32(<2 x i32> <i32 1791, i32 1791>)
  call i64 @f_v1i64(<1 x i64> <i64 6592774800895>)
  call i8 @f_v16i8(<16 x i8> <i8 255, i8 5, i8 0, i8 0, i8 255, i8 5, i8 0, i8 0, i8 255, i8 5, i8 0, i8 0, i8 255, i8 5, i8 0, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 1279, i16 0, i16 1279, i16 0, i16 1279, i16 0, i16 1279, i16 0>)
  call i32 @f_v4i32(<4 x i32> <i32 1023, i32 1023, i32 1023, i32 1023>)
  call i64 @f_v2i64(<2 x i64> <i64 3294239916799, i64 3294239916799>)

  ret void
}

define dso_local void @modimm_t8_call() {
; CHECK-SD-LE-LABEL: modimm_t8_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi v0.2s, #8, msl #16
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi v0.2s, #7, msl #16
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2s, #6, msl #16
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2s, #5, msl #16
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    movi v0.4s, #5, msl #16
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.4s, #4, msl #16
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.4s, #3, msl #16
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    movi v0.4s, #2, msl #16
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t8_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.2s, #8, msl #16
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.2s, #7, msl #16
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2s, #6, msl #16
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2s, #5, msl #16
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    movi v0.4s, #5, msl #16
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.4s, #4, msl #16
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.4s, #3, msl #16
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    movi v0.4s, #2, msl #16
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t8_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI39_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI39_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI39_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI39_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI39_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI39_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI39_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI39_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi v0.2s, #6, msl #16
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #-4294574081 // =0xffffffff0005ffff
; CHECK-GI-LE-NEXT:    movk x8, #5, lsl #48
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    movi v0.4s, #3, msl #16
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    movi v0.4s, #2, msl #16
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t8_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI39_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI39_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI39_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI39_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI39_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI39_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI39_2]
; CHECK-GI-BE-NEXT:    movi v8.2s, #6, msl #16
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI39_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #-4294574081 // =0xffffffff0005ffff
; CHECK-GI-BE-NEXT:    movk x8, #5, lsl #48
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.4s, #3, msl #16
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    movi v0.4s, #2, msl #16
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 255, i8 255, i8 8, i8 0, i8 255, i8 255, i8 8, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 65535, i16 7, i16 65535, i16 7>)
  call i32 @f_v2i32(<2 x i32> <i32 458751, i32 458751>)
  call i64 @f_v1i64(<1 x i64> <i64 1688845565689855>)
  call i8 @f_v16i8(<16 x i8> <i8 255, i8 255, i8 5, i8 0, i8 255, i8 255, i8 5, i8 0, i8 255, i8 255, i8 5, i8 0, i8 255, i8 255, i8 5, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 65535, i16 4, i16 65535, i16 4, i16 65535, i16 4, i16 65535, i16 4>)
  call i32 @f_v4i32(<4 x i32> <i32 262143, i32 262143, i32 262143, i32 262143>)
  call i64 @f_v2i64(<2 x i64> <i64 844420635361279, i64 844420635361279>)

  ret void
}

define dso_local void @modimm_t9_call() {
; CHECK-LE-LABEL: modimm_t9_call:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-LE-NEXT:    .cfi_offset w30, -16
; CHECK-LE-NEXT:    movi v0.8b, #8
; CHECK-LE-NEXT:    bl f_v8i8
; CHECK-LE-NEXT:    movi v0.8b, #7
; CHECK-LE-NEXT:    bl f_v4i16
; CHECK-LE-NEXT:    movi v0.8b, #6
; CHECK-LE-NEXT:    bl f_v2i32
; CHECK-LE-NEXT:    movi v0.16b, #5
; CHECK-LE-NEXT:    bl f_v16i8
; CHECK-LE-NEXT:    movi v0.16b, #4
; CHECK-LE-NEXT:    bl f_v8i16
; CHECK-LE-NEXT:    movi v0.16b, #3
; CHECK-LE-NEXT:    bl f_v4i32
; CHECK-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t9_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi v0.8b, #8
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi v0.8b, #7
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.8b, #6
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.16b, #5
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.16b, #4
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.16b, #3
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t9_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #-32]! // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #16] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 32
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    movi v0.8b, #8
; CHECK-GI-BE-NEXT:    movi v8.8b, #7
; CHECK-GI-BE-NEXT:    movi v9.8b, #6
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v8.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v9.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    movi v0.16b, #5
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    movi v0.16b, #4
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    movi v0.16b, #3
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #16] // 8-byte Reload
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp], #32 // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8>)
  call i16 @f_v4i16(<4 x i16> <i16 1799, i16 1799, i16 1799, i16 1799>)
  call i32 @f_v2i32(<2 x i32> <i32 101058054, i32 101058054>)
  call i8 @f_v16i8(<16 x i8> <i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5, i8 5>)
  call i16 @f_v8i16(<8 x i16> <i16 1028, i16 1028, i16 1028, i16 1028, i16 1028, i16 1028, i16 1028, i16 1028>)
  call i32 @f_v4i32(<4 x i32> <i32 50529027, i32 50529027, i32 50529027, i32 50529027>)

  ret void
}

define dso_local void @modimm_t10_call() {
; CHECK-SD-LE-LABEL: modimm_t10_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    movi d0, #0x00ffff0000ffff
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    movi v0.2d, #0xffffffffffffffff
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    movi v0.2d, #0xffffff00ffffff
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    movi v0.2d, #0xffffffffffff0000
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    movi v0.2d, #0xffffffff00000000
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t10_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    movi d0, #0x00ffff0000ffff
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    movi v0.2d, #0xffffffffffffffff
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    movi v0.2d, #0xffffff00ffffff
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    movi v0.2d, #0xffffffffffff0000
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    movi v0.2d, #0xffffffff00000000
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t10_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #64
; CHECK-GI-LE-NEXT:    str d8, [sp, #48] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #56] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI41_2
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI41_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI41_4
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI41_2]
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI41_4]
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI41_0
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI41_3
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI41_1]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI41_3]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI41_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #32] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    movi d0, #0xffffffffffffffff
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #32] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #56] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #48] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #64
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t10_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #80
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #48] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #64] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 80
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI41_4
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI41_3
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI41_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI41_4]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI41_2
; CHECK-GI-BE-NEXT:    ldr d9, [x9, :lo12:.LCPI41_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x8, :lo12:.LCPI41_2]
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI41_1
; CHECK-GI-BE-NEXT:    movi d8, #0xffffffffffffffff
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI41_1]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI41_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #32] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #32] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #48] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #64] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #80
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 -1, i8 0, i8 0, i8 0, i8 -1, i8 0, i8 0, i8 0>)
  call i16 @f_v4i16(<4 x i16> <i16 -1, i16 0, i16 -1, i16 0>)
  call i32 @f_v2i32(<2 x i32> <i32 -1, i32 -1>)
  call i8 @f_v16i8(<16 x i8> <i8 -1, i8 -1, i8 -1, i8 0, i8 -1, i8 -1, i8 -1, i8 0, i8 -1, i8 -1, i8 -1, i8 0, i8 -1, i8 -1, i8 -1, i8 0>)
  call i16 @f_v8i16(<8 x i16> <i16 0, i16 -1, i16 -1, i16 -1, i16 0, i16 -1, i16 -1, i16 -1>)
  call i32 @f_v4i32(<4 x i32> <i32 0, i32 -1, i32 0, i32 -1>)

  ret void
}

define dso_local void @modimm_t11_call() {
; CHECK-SD-LE-LABEL: modimm_t11_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    fmov v0.2s, #4.00000000
; CHECK-SD-LE-NEXT:    bl f_v8i8
; CHECK-SD-LE-NEXT:    fmov v0.2s, #3.75000000
; CHECK-SD-LE-NEXT:    bl f_v4i16
; CHECK-SD-LE-NEXT:    fmov v0.2s, #3.50000000
; CHECK-SD-LE-NEXT:    bl f_v2i32
; CHECK-SD-LE-NEXT:    fmov v0.2s, #0.39062500
; CHECK-SD-LE-NEXT:    bl f_v1i64
; CHECK-SD-LE-NEXT:    fmov v0.4s, #3.25000000
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    fmov v0.4s, #3.00000000
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    fmov v0.4s, #2.75000000
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    fmov v0.4s, #2.50000000
; CHECK-SD-LE-NEXT:    bl f_v2i64
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t11_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    fmov v0.2s, #4.00000000
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    bl f_v8i8
; CHECK-SD-BE-NEXT:    fmov v0.2s, #3.75000000
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    bl f_v4i16
; CHECK-SD-BE-NEXT:    fmov v0.2s, #3.50000000
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    bl f_v2i32
; CHECK-SD-BE-NEXT:    fmov v0.2s, #0.39062500
; CHECK-SD-BE-NEXT:    bl f_v1i64
; CHECK-SD-BE-NEXT:    fmov v0.4s, #3.25000000
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    fmov v0.4s, #3.00000000
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    fmov v0.4s, #2.75000000
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    fmov v0.4s, #2.50000000
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v2i64
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t11_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str d8, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    str x30, [sp, #40] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -8
; CHECK-GI-LE-NEXT:    .cfi_offset b8, -16
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI42_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI42_3
; CHECK-GI-LE-NEXT:    adrp x11, .LCPI42_0
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI42_1]
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI42_2
; CHECK-GI-LE-NEXT:    ldr d0, [x8, :lo12:.LCPI42_3]
; CHECK-GI-LE-NEXT:    ldr d8, [x9, :lo12:.LCPI42_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x11, :lo12:.LCPI42_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v8i8
; CHECK-GI-LE-NEXT:    fmov d0, d8
; CHECK-GI-LE-NEXT:    bl f_v4i16
; CHECK-GI-LE-NEXT:    fmov v0.2s, #3.50000000
; CHECK-GI-LE-NEXT:    bl f_v2i32
; CHECK-GI-LE-NEXT:    mov x8, #1053294592 // =0x3ec80000
; CHECK-GI-LE-NEXT:    movk x8, #16072, lsl #48
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    bl f_v1i64
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    fmov v0.4s, #2.75000000
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    fmov v0.4s, #2.50000000
; CHECK-GI-LE-NEXT:    bl f_v2i64
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #40] // 8-byte Reload
; CHECK-GI-LE-NEXT:    ldr d8, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t11_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #64
; CHECK-GI-BE-NEXT:    stp d9, d8, [sp, #32] // 16-byte Folded Spill
; CHECK-GI-BE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 64
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    .cfi_offset b8, -24
; CHECK-GI-BE-NEXT:    .cfi_offset b9, -32
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI42_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI42_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI42_0
; CHECK-GI-BE-NEXT:    ldr d0, [x8, :lo12:.LCPI42_3]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI42_1]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI42_2
; CHECK-GI-BE-NEXT:    ldr d9, [x8, :lo12:.LCPI42_2]
; CHECK-GI-BE-NEXT:    fmov v8.2s, #3.50000000
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI42_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    bl f_v8i8
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v9.4h
; CHECK-GI-BE-NEXT:    bl f_v4i16
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v8.2s
; CHECK-GI-BE-NEXT:    bl f_v2i32
; CHECK-GI-BE-NEXT:    mov x8, #1053294592 // =0x3ec80000
; CHECK-GI-BE-NEXT:    movk x8, #16072, lsl #48
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    bl f_v1i64
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    fmov v0.4s, #2.75000000
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    fmov v0.4s, #2.50000000
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v2i64
; CHECK-GI-BE-NEXT:    ldp d9, d8, [sp, #32] // 16-byte Folded Reload
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #64
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v8i8(<8 x i8> <i8 0, i8 0, i8 128, i8 64, i8 0, i8 0, i8 128, i8 64>)
  call i16 @f_v4i16(<4 x i16> <i16 0, i16 16496, i16 0, i16 16496>)
  call i32 @f_v2i32(<2 x i32> <i32 1080033280, i32 1080033280>)
  call i64 @f_v1i64(<1 x i64> <i64 4523865826746957824>)
  call i8 @f_v16i8(<16 x i8> <i8 0, i8 0, i8 80, i8 64, i8 0, i8 0, i8 80, i8 64, i8 0, i8 0, i8 80, i8 64, i8 0, i8 0, i8 80, i8 64>)
  call i16 @f_v8i16(<8 x i16> <i16 0, i16 16448, i16 0, i16 16448, i16 0, i16 16448, i16 0, i16 16448>)
  call i32 @f_v4i32(<4 x i32> <i32 1076887552, i32 1076887552, i32 1076887552, i32 1076887552>)
  call i64 @f_v2i64(<2 x i64> <i64 4620693218757967872, i64 4620693218757967872>)

  ret void
}

define dso_local void @modimm_t12_call() {
; CHECK-SD-LE-LABEL: modimm_t12_call:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-LE-NEXT:    fmov v0.2d, #0.18750000
; CHECK-SD-LE-NEXT:    bl f_v16i8
; CHECK-SD-LE-NEXT:    fmov v0.2d, #0.17968750
; CHECK-SD-LE-NEXT:    bl f_v8i16
; CHECK-SD-LE-NEXT:    fmov v0.2d, #0.17187500
; CHECK-SD-LE-NEXT:    bl f_v4i32
; CHECK-SD-LE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: modimm_t12_call:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-SD-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-BE-NEXT:    .cfi_offset w30, -16
; CHECK-SD-BE-NEXT:    fmov v0.2d, #0.18750000
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v16i8
; CHECK-SD-BE-NEXT:    fmov v0.2d, #0.17968750
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v8i16
; CHECK-SD-BE-NEXT:    fmov v0.2d, #0.17187500
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    bl f_v4i32
; CHECK-SD-BE-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: modimm_t12_call:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    sub sp, sp, #48
; CHECK-GI-LE-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-GI-LE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-LE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-LE-NEXT:    adrp x9, .LCPI43_1
; CHECK-GI-LE-NEXT:    adrp x8, .LCPI43_2
; CHECK-GI-LE-NEXT:    adrp x10, .LCPI43_0
; CHECK-GI-LE-NEXT:    ldr q1, [x9, :lo12:.LCPI43_1]
; CHECK-GI-LE-NEXT:    ldr q0, [x8, :lo12:.LCPI43_2]
; CHECK-GI-LE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-LE-NEXT:    ldr q1, [x10, :lo12:.LCPI43_0]
; CHECK-GI-LE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-LE-NEXT:    bl f_v16i8
; CHECK-GI-LE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v8i16
; CHECK-GI-LE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-LE-NEXT:    bl f_v4i32
; CHECK-GI-LE-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-GI-LE-NEXT:    add sp, sp, #48
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: modimm_t12_call:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    sub sp, sp, #48
; CHECK-GI-BE-NEXT:    str x30, [sp, #32] // 8-byte Spill
; CHECK-GI-BE-NEXT:    .cfi_def_cfa_offset 48
; CHECK-GI-BE-NEXT:    .cfi_offset w30, -16
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI43_2
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI43_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI43_0
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI43_2]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI43_1]
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ldr q1, [x10, :lo12:.LCPI43_0]
; CHECK-GI-BE-NEXT:    str q1, [sp, #16] // 16-byte Spill
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v16i8
; CHECK-GI-BE-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v8i16
; CHECK-GI-BE-NEXT:    ldr q0, [sp, #16] // 16-byte Reload
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    bl f_v4i32
; CHECK-GI-BE-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; CHECK-GI-BE-NEXT:    add sp, sp, #48
; CHECK-GI-BE-NEXT:    ret
  call i8 @f_v16i8(<16 x i8> <i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 200, i8 63, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 200, i8 63>)
  call i16 @f_v8i16(<8 x i16> <i16 0, i16 0, i16 0, i16 16327, i16 0, i16 0, i16 0, i16 16327>)
  call i32 @f_v4i32(<4 x i32> <i32 0, i32 1069940736, i32 0, i32 1069940736>)

  ret void
}

define <2 x double> @test_v1f64(<1 x double> %0, ptr %1) {
; CHECK-SD-LE-LABEL: test_v1f64:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    mvni v1.2s, #31, msl #16
; CHECK-SD-LE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-LE-NEXT:    mov v1.d[1], v0.d[0]
; CHECK-SD-LE-NEXT:    mov v0.16b, v1.16b
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test_v1f64:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    mvni v1.2s, #31, msl #16
; CHECK-SD-BE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-BE-NEXT:    mov v1.d[1], v0.d[0]
; CHECK-SD-BE-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: test_v1f64:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    mov x8, #-9007194961870848 // =0xffe00000ffe00000
; CHECK-GI-LE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-LE-NEXT:    fmov d1, x8
; CHECK-GI-LE-NEXT:    mov v1.d[1], v0.d[0]
; CHECK-GI-LE-NEXT:    mov v0.16b, v1.16b
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test_v1f64:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    mov x8, #-9007194961870848 // =0xffe00000ffe00000
; CHECK-GI-BE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-GI-BE-NEXT:    fmov d1, x8
; CHECK-GI-BE-NEXT:    mov v1.d[1], v0.d[0]
; CHECK-GI-BE-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECK-GI-BE-NEXT:    ret
  %vec = shufflevector <1 x double> <double 0xFFE00000FFE00000>, <1 x double> %0, <2 x i32> <i32 0, i32 1>
  ret <2 x double> %vec
}
