; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-LE-SD
; RUN: llc -mtriple=aarch64_be-unknown-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-BE-SD
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -global-isel < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-LE-GI

define <3 x i32> @fsext_v3i32(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v3i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-LE-SD-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v3i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-BE-SD-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v3i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    sxtb w8, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b2, v0.b[2]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    fmov w9, s1
; CHECK-LE-GI-NEXT:    fmov w8, s2
; CHECK-LE-GI-NEXT:    sxtb w9, w9
; CHECK-LE-GI-NEXT:    sxtb w8, w8
; CHECK-LE-GI-NEXT:    mov v0.s[1], w9
; CHECK-LE-GI-NEXT:    mov v0.s[2], w8
; CHECK-LE-GI-NEXT:    ret
  %x = load <3 x i8>, ptr %a
  %y = sext <3 x i8> %x to <3 x i32>
  ret <3 x i32> %y
}

define <3 x i16> @fsext_v3i16(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v3i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-LE-SD-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-LE-SD-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v3i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-BE-SD-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v3i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    sxtb w8, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b2, v0.b[2]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    fmov w9, s1
; CHECK-LE-GI-NEXT:    fmov w8, s2
; CHECK-LE-GI-NEXT:    sxtb w9, w9
; CHECK-LE-GI-NEXT:    sxtb w8, w8
; CHECK-LE-GI-NEXT:    mov v0.h[1], w9
; CHECK-LE-GI-NEXT:    mov v0.h[2], w8
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
  %x = load <3 x i8>, ptr %a
  %y = sext <3 x i8> %x to <3 x i16>
  ret <3 x i16> %y
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-LE: {{.*}}
