; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-LE-SD
; RUN: llc -mtriple=aarch64_be-unknown-linux-gnu < %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-BE-SD
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -global-isel < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-LE-GI
; RUN: llc -mtriple=aarch64_be-unknown-linux-gnu -global-isel < %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-BE-GI

define <2 x i16> @test0(ptr %i16_ptr, i64 %inc) {
; CHECK-LE-LABEL: test0:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-LE-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: test0:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-NEXT:    ret
  %i_0 = load i16, ptr %i16_ptr
  %v0 = insertelement <2 x i16> undef, i16 %i_0, i32 0
  ret <2 x i16> %v0
}

define <2 x i16> @test1(ptr %v2i16_ptr) {
; CHECK-LE-SD-LABEL: test1:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test1:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test1:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr h1, [x0, #2]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test1:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #2
; CHECK-BE-GI-NEXT:    ldr h1, [x0]
; CHECK-BE-GI-NEXT:    ld1 { v0.h }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %v2i16 = load <2 x i16>, ptr %v2i16_ptr
  ret <2 x i16> %v2i16
}

define <2 x i16> @test2(ptr %i16_ptr, i64 %inc) {
; CHECK-LE-SD-LABEL: test2:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-LE-SD-NEXT:    add x8, x0, x1, lsl #1
; CHECK-LE-SD-NEXT:    ld1 { v0.h }[2], [x8]
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test2:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-BE-SD-NEXT:    add x8, x0, x1, lsl #1
; CHECK-BE-SD-NEXT:    ld1 { v0.h }[2], [x8]
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test2:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr h1, [x0, x1, lsl #1]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test2:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-BE-GI-NEXT:    ldr h1, [x0, x1, lsl #1]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %i_0 = load i16, ptr %i16_ptr
  %i16_ptr_inc = getelementptr i16, ptr %i16_ptr, i64 %inc
  %i_1 = load i16, ptr %i16_ptr_inc
  %v0 = insertelement <2 x i16> undef, i16 %i_0, i32 0
  %v1 = insertelement <2 x i16> %v0, i16 %i_1, i32 1
  ret <2 x i16> %v1
}

define <2 x i8> @test3(ptr %v2i8_ptr) {
; CHECK-LE-SD-LABEL: test3:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test3:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test3:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v0.b }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr b1, [x0, #1]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test3:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #1
; CHECK-BE-GI-NEXT:    ldr b1, [x0]
; CHECK-BE-GI-NEXT:    ld1 { v0.b }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %v2i8 = load <2 x i8>, ptr %v2i8_ptr
  ret <2 x i8> %v2i8
}

define <4 x i8> @test4(ptr %v4i8_ptr) {
; CHECK-LE-SD-LABEL: test4:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test4:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test4:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b2, v0.b[2]
; CHECK-LE-GI-NEXT:    fmov w8, s1
; CHECK-LE-GI-NEXT:    mov b1, v0.b[3]
; CHECK-LE-GI-NEXT:    mov v0.h[1], w8
; CHECK-LE-GI-NEXT:    fmov w8, s2
; CHECK-LE-GI-NEXT:    mov v0.h[2], w8
; CHECK-LE-GI-NEXT:    fmov w8, s1
; CHECK-LE-GI-NEXT:    mov v0.h[3], w8
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test4:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-BE-GI-NEXT:    mov b2, v0.b[2]
; CHECK-BE-GI-NEXT:    fmov w8, s1
; CHECK-BE-GI-NEXT:    mov b1, v0.b[3]
; CHECK-BE-GI-NEXT:    mov v0.h[1], w8
; CHECK-BE-GI-NEXT:    fmov w8, s2
; CHECK-BE-GI-NEXT:    mov v0.h[2], w8
; CHECK-BE-GI-NEXT:    fmov w8, s1
; CHECK-BE-GI-NEXT:    mov v0.h[3], w8
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    ret
  %v4i8 = load <4 x i8>, ptr %v4i8_ptr
  ret <4 x i8> %v4i8
}

define <2 x i32> @fsext_v2i32(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v2i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v2i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v2i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldrb w8, [x0]
; CHECK-LE-GI-NEXT:    ldrb w9, [x0, #1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov v0.h[1], w9
; CHECK-LE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    smov w8, v0.h[0]
; CHECK-LE-GI-NEXT:    smov w9, v0.h[1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov v0.s[1], w9
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fsext_v2i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldrb w8, [x0, #1]
; CHECK-BE-GI-NEXT:    ldrb w9, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov v0.h[1], w9
; CHECK-BE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    smov w8, v0.h[0]
; CHECK-BE-GI-NEXT:    smov w9, v0.h[1]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov v0.s[1], w9
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i8>, ptr %a
  %y = sext <2 x i8> %x to <2 x i32>
  ret <2 x i32> %y
}

define <4 x i32> @fsext_v4i32(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v4i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v4i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v4i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    sxtb w8, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[2]
; CHECK-LE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b3, v0.b[3]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    fmov w9, s1
; CHECK-LE-GI-NEXT:    fmov w10, s2
; CHECK-LE-GI-NEXT:    fmov w11, s3
; CHECK-LE-GI-NEXT:    sxtb w9, w9
; CHECK-LE-GI-NEXT:    sxtb w10, w10
; CHECK-LE-GI-NEXT:    sxtb w11, w11
; CHECK-LE-GI-NEXT:    fmov s1, w9
; CHECK-LE-GI-NEXT:    mov v0.h[1], w10
; CHECK-LE-GI-NEXT:    mov v1.h[1], w11
; CHECK-LE-GI-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-GI-NEXT:    sshll v1.4s, v1.4h, #0
; CHECK-LE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fsext_v4i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    sxtb w8, w8
; CHECK-BE-GI-NEXT:    mov b1, v0.b[2]
; CHECK-BE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-BE-GI-NEXT:    mov b3, v0.b[3]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    fmov w9, s1
; CHECK-BE-GI-NEXT:    fmov w10, s2
; CHECK-BE-GI-NEXT:    fmov w11, s3
; CHECK-BE-GI-NEXT:    sxtb w9, w9
; CHECK-BE-GI-NEXT:    sxtb w10, w10
; CHECK-BE-GI-NEXT:    sxtb w11, w11
; CHECK-BE-GI-NEXT:    fmov s1, w9
; CHECK-BE-GI-NEXT:    mov v0.h[1], w10
; CHECK-BE-GI-NEXT:    mov v1.h[1], w11
; CHECK-BE-GI-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-GI-NEXT:    sshll v1.4s, v1.4h, #0
; CHECK-BE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <4 x i8>, ptr %a
  %y = sext <4 x i8> %x to <4 x i32>
  ret <4 x i32> %y
}

define <8 x i32> @fsext_v8i32(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v8i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr d0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    sshll2 v1.4s, v0.8h, #0
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v8i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ld1 { v0.8b }, [x0]
; CHECK-BE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    sshll v1.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    sshll2 v0.4s, v0.8h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v8i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr d0, [x0]
; CHECK-LE-GI-NEXT:    sshll v1.8h, v0.8b, #0
; CHECK-LE-GI-NEXT:    sshll v0.4s, v1.4h, #0
; CHECK-LE-GI-NEXT:    sshll2 v1.4s, v1.8h, #0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fsext_v8i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ld1 { v0.8b }, [x0]
; CHECK-BE-GI-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-GI-NEXT:    sshll v1.4s, v0.4h, #0
; CHECK-BE-GI-NEXT:    sshll2 v0.4s, v0.8h, #0
; CHECK-BE-GI-NEXT:    ret
  %x = load <8 x i8>, ptr %a
  %y = sext <8 x i8> %x to <8 x i32>
  ret <8 x i32> %y
}

define <4 x i32> @fzext_v4i32(ptr %a) {
; CHECK-LE-SD-LABEL: fzext_v4i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fzext_v4i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fzext_v4i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    uxtb w8, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[2]
; CHECK-LE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b3, v0.b[3]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    fmov w9, s1
; CHECK-LE-GI-NEXT:    fmov w10, s2
; CHECK-LE-GI-NEXT:    fmov w11, s3
; CHECK-LE-GI-NEXT:    uxtb w9, w9
; CHECK-LE-GI-NEXT:    uxtb w10, w10
; CHECK-LE-GI-NEXT:    uxtb w11, w11
; CHECK-LE-GI-NEXT:    fmov s1, w9
; CHECK-LE-GI-NEXT:    mov v0.h[1], w10
; CHECK-LE-GI-NEXT:    mov v1.h[1], w11
; CHECK-LE-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-GI-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-LE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fzext_v4i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    uxtb w8, w8
; CHECK-BE-GI-NEXT:    mov b1, v0.b[2]
; CHECK-BE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-BE-GI-NEXT:    mov b3, v0.b[3]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    fmov w9, s1
; CHECK-BE-GI-NEXT:    fmov w10, s2
; CHECK-BE-GI-NEXT:    fmov w11, s3
; CHECK-BE-GI-NEXT:    uxtb w9, w9
; CHECK-BE-GI-NEXT:    uxtb w10, w10
; CHECK-BE-GI-NEXT:    uxtb w11, w11
; CHECK-BE-GI-NEXT:    fmov s1, w9
; CHECK-BE-GI-NEXT:    mov v0.h[1], w10
; CHECK-BE-GI-NEXT:    mov v1.h[1], w11
; CHECK-BE-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-GI-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <4 x i8>, ptr %a
  %y = zext <4 x i8> %x to <4 x i32>
  ret <4 x i32> %y
}

; TODO: This codegen could just be:
;   ldrb w0, [x0]
;
define i32 @loadExti32(ptr %ref) {
; CHECK-LE-SD-LABEL: loadExti32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    umov w8, v0.h[0]
; CHECK-LE-SD-NEXT:    and w0, w8, #0xff
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: loadExti32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    umov w8, v0.h[0]
; CHECK-BE-SD-NEXT:    and w0, w8, #0xff
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: loadExti32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldrb w0, [x0]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: loadExti32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldrb w0, [x0]
; CHECK-BE-GI-NEXT:    ret
  %a = load <4 x i8>, ptr %ref
  %vecext = extractelement <4 x i8> %a, i32 0
  %conv = zext i8 %vecext to i32
  ret i32 %conv
}

define <2 x i16> @fsext_v2i16(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v2i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v2i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v2i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldrb w8, [x0]
; CHECK-LE-GI-NEXT:    ldrb w9, [x0, #1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov v0.h[1], w9
; CHECK-LE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    smov w8, v0.h[0]
; CHECK-LE-GI-NEXT:    smov w9, v0.h[1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov v0.s[1], w9
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fsext_v2i16:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldrb w8, [x0, #1]
; CHECK-BE-GI-NEXT:    ldrb w9, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov v0.h[1], w9
; CHECK-BE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    smov w8, v0.h[0]
; CHECK-BE-GI-NEXT:    smov w9, v0.h[1]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov v0.s[1], w9
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i8>, ptr %a
  %y = sext <2 x i8> %x to <2 x i16>
  ret <2 x i16> %y
}



define <4 x i16> @fsext_v4i16(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v4i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v4i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v4i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-LE-GI-NEXT:    mov v2.b[0], v0.b[0]
; CHECK-LE-GI-NEXT:    mov b3, v0.b[2]
; CHECK-LE-GI-NEXT:    mov b0, v0.b[3]
; CHECK-LE-GI-NEXT:    mov v2.b[1], v1.b[0]
; CHECK-LE-GI-NEXT:    mov v2.b[2], v3.b[0]
; CHECK-LE-GI-NEXT:    mov v2.b[3], v0.b[0]
; CHECK-LE-GI-NEXT:    sshll v0.8h, v2.8b, #0
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fsext_v4i16:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-BE-GI-NEXT:    mov v2.b[0], v0.b[0]
; CHECK-BE-GI-NEXT:    mov b3, v0.b[2]
; CHECK-BE-GI-NEXT:    mov b0, v0.b[3]
; CHECK-BE-GI-NEXT:    mov v2.b[1], v1.b[0]
; CHECK-BE-GI-NEXT:    mov v2.b[2], v3.b[0]
; CHECK-BE-GI-NEXT:    mov v2.b[3], v0.b[0]
; CHECK-BE-GI-NEXT:    sshll v0.8h, v2.8b, #0
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    ret
  %x = load <4 x i8>, ptr %a
  %y = sext <4 x i8> %x to <4 x i16>
  ret <4 x i16> %y
}

define <8 x i16> @fsext_v8i16(ptr %a) {
; CHECK-LE-LABEL: fsext_v8i16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldr d0, [x0]
; CHECK-LE-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: fsext_v8i16:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ld1 { v0.8b }, [x0]
; CHECK-BE-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ret
  %x = load <8 x i8>, ptr %a
  %y = sext <8 x i8> %x to <8 x i16>
  ret <8 x i16> %y
}

define <16 x i16> @fsext_v16i16(ptr %a) {
; CHECK-LE-SD-LABEL: fsext_v16i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr q0, [x0]
; CHECK-LE-SD-NEXT:    sshll2 v1.8h, v0.16b, #0
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fsext_v16i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x0]
; CHECK-BE-SD-NEXT:    sshll v1.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    sshll2 v0.8h, v0.16b, #0
; CHECK-BE-SD-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-SD-NEXT:    rev64 v2.8h, v1.8h
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fsext_v16i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr q1, [x0]
; CHECK-LE-GI-NEXT:    sshll v0.8h, v1.8b, #0
; CHECK-LE-GI-NEXT:    sshll2 v1.8h, v1.16b, #0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fsext_v16i16:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ld1 { v0.16b }, [x0]
; CHECK-BE-GI-NEXT:    sshll v1.8h, v0.8b, #0
; CHECK-BE-GI-NEXT:    sshll2 v0.8h, v0.16b, #0
; CHECK-BE-GI-NEXT:    ret
  %x = load <16 x i8>, ptr %a
  %y = sext <16 x i8> %x to <16 x i16>
  ret <16 x i16> %y
}

define <4 x i16> @fzext_v4i16(ptr %a) {
; CHECK-LE-SD-LABEL: fzext_v4i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: fzext_v4i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: fzext_v4i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-LE-GI-NEXT:    mov v2.b[0], v0.b[0]
; CHECK-LE-GI-NEXT:    mov b3, v0.b[2]
; CHECK-LE-GI-NEXT:    mov b0, v0.b[3]
; CHECK-LE-GI-NEXT:    mov v2.b[1], v1.b[0]
; CHECK-LE-GI-NEXT:    mov v2.b[2], v3.b[0]
; CHECK-LE-GI-NEXT:    mov v2.b[3], v0.b[0]
; CHECK-LE-GI-NEXT:    ushll v0.8h, v2.8b, #0
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: fzext_v4i16:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-BE-GI-NEXT:    mov v2.b[0], v0.b[0]
; CHECK-BE-GI-NEXT:    mov b3, v0.b[2]
; CHECK-BE-GI-NEXT:    mov b0, v0.b[3]
; CHECK-BE-GI-NEXT:    mov v2.b[1], v1.b[0]
; CHECK-BE-GI-NEXT:    mov v2.b[2], v3.b[0]
; CHECK-BE-GI-NEXT:    mov v2.b[3], v0.b[0]
; CHECK-BE-GI-NEXT:    ushll v0.8h, v2.8b, #0
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    ret
  %x = load <4 x i8>, ptr %a
  %y = zext <4 x i8> %x to <4 x i16>
  ret <4 x i16> %y
}

define <4 x i16> @anyext_v4i16(ptr %a, ptr %b) {
; CHECK-LE-SD-LABEL: anyext_v4i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ldr s1, [x1]
; CHECK-LE-SD-NEXT:    uaddl v0.8h, v0.8b, v1.8b
; CHECK-LE-SD-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-LE-SD-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: anyext_v4i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    ldr s1, [x1]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    rev32 v1.8b, v1.8b
; CHECK-BE-SD-NEXT:    uaddl v0.8h, v0.8b, v1.8b
; CHECK-BE-SD-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-BE-SD-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: anyext_v4i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    ldr w9, [x1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    fmov s1, w9
; CHECK-LE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b3, v1.b[1]
; CHECK-LE-GI-NEXT:    mov b4, v0.b[2]
; CHECK-LE-GI-NEXT:    mov b5, v0.b[3]
; CHECK-LE-GI-NEXT:    fmov w8, s2
; CHECK-LE-GI-NEXT:    mov b2, v1.b[2]
; CHECK-LE-GI-NEXT:    fmov w9, s3
; CHECK-LE-GI-NEXT:    mov b3, v1.b[3]
; CHECK-LE-GI-NEXT:    mov v0.h[1], w8
; CHECK-LE-GI-NEXT:    mov v1.h[1], w9
; CHECK-LE-GI-NEXT:    fmov w8, s4
; CHECK-LE-GI-NEXT:    fmov w9, s2
; CHECK-LE-GI-NEXT:    mov v0.h[2], w8
; CHECK-LE-GI-NEXT:    mov v1.h[2], w9
; CHECK-LE-GI-NEXT:    fmov w8, s5
; CHECK-LE-GI-NEXT:    fmov w9, s3
; CHECK-LE-GI-NEXT:    mov v0.h[3], w8
; CHECK-LE-GI-NEXT:    mov v1.h[3], w9
; CHECK-LE-GI-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-LE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: anyext_v4i16:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    ldr w9, [x1]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    fmov s1, w9
; CHECK-BE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-BE-GI-NEXT:    mov b3, v1.b[1]
; CHECK-BE-GI-NEXT:    mov b4, v0.b[2]
; CHECK-BE-GI-NEXT:    mov b5, v0.b[3]
; CHECK-BE-GI-NEXT:    fmov w8, s2
; CHECK-BE-GI-NEXT:    mov b2, v1.b[2]
; CHECK-BE-GI-NEXT:    fmov w9, s3
; CHECK-BE-GI-NEXT:    mov b3, v1.b[3]
; CHECK-BE-GI-NEXT:    mov v0.h[1], w8
; CHECK-BE-GI-NEXT:    mov v1.h[1], w9
; CHECK-BE-GI-NEXT:    fmov w8, s4
; CHECK-BE-GI-NEXT:    fmov w9, s2
; CHECK-BE-GI-NEXT:    mov v0.h[2], w8
; CHECK-BE-GI-NEXT:    mov v1.h[2], w9
; CHECK-BE-GI-NEXT:    fmov w8, s5
; CHECK-BE-GI-NEXT:    fmov w9, s3
; CHECK-BE-GI-NEXT:    mov v0.h[3], w8
; CHECK-BE-GI-NEXT:    mov v1.h[3], w9
; CHECK-BE-GI-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-BE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    ret
  %x = load <4 x i8>, ptr %a, align 4
  %y = load <4 x i8>, ptr %b, align 4
  %z = add <4 x i8> %x, %y
  %s = sext <4 x i8> %z to <4 x i16>
  ret <4 x i16> %s
}

define <4 x i32> @anyext_v4i32(ptr %a, ptr %b) {
; CHECK-LE-SD-LABEL: anyext_v4i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ldr s1, [x1]
; CHECK-LE-SD-NEXT:    uaddl v0.8h, v0.8b, v1.8b
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-LE-SD-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: anyext_v4i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    ldr s1, [x1]
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    rev32 v1.8b, v1.8b
; CHECK-BE-SD-NEXT:    uaddl v0.8h, v0.8b, v1.8b
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-BE-SD-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: anyext_v4i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr w8, [x0]
; CHECK-LE-GI-NEXT:    ldr w9, [x1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    fmov s1, w9
; CHECK-LE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b3, v1.b[1]
; CHECK-LE-GI-NEXT:    mov b4, v0.b[2]
; CHECK-LE-GI-NEXT:    mov b5, v0.b[3]
; CHECK-LE-GI-NEXT:    fmov w8, s2
; CHECK-LE-GI-NEXT:    mov b2, v1.b[2]
; CHECK-LE-GI-NEXT:    fmov w9, s3
; CHECK-LE-GI-NEXT:    mov b3, v1.b[3]
; CHECK-LE-GI-NEXT:    mov v0.h[1], w8
; CHECK-LE-GI-NEXT:    mov v1.h[1], w9
; CHECK-LE-GI-NEXT:    fmov w8, s4
; CHECK-LE-GI-NEXT:    fmov w9, s2
; CHECK-LE-GI-NEXT:    mov v0.h[2], w8
; CHECK-LE-GI-NEXT:    mov v1.h[2], w9
; CHECK-LE-GI-NEXT:    fmov w8, s5
; CHECK-LE-GI-NEXT:    fmov w9, s3
; CHECK-LE-GI-NEXT:    mov v0.h[3], w8
; CHECK-LE-GI-NEXT:    mov v1.h[3], w9
; CHECK-LE-GI-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-LE-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-GI-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-LE-GI-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: anyext_v4i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr w8, [x0]
; CHECK-BE-GI-NEXT:    ldr w9, [x1]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    fmov s1, w9
; CHECK-BE-GI-NEXT:    mov b2, v0.b[1]
; CHECK-BE-GI-NEXT:    mov b3, v1.b[1]
; CHECK-BE-GI-NEXT:    mov b4, v0.b[2]
; CHECK-BE-GI-NEXT:    mov b5, v0.b[3]
; CHECK-BE-GI-NEXT:    fmov w8, s2
; CHECK-BE-GI-NEXT:    mov b2, v1.b[2]
; CHECK-BE-GI-NEXT:    fmov w9, s3
; CHECK-BE-GI-NEXT:    mov b3, v1.b[3]
; CHECK-BE-GI-NEXT:    mov v0.h[1], w8
; CHECK-BE-GI-NEXT:    mov v1.h[1], w9
; CHECK-BE-GI-NEXT:    fmov w8, s4
; CHECK-BE-GI-NEXT:    fmov w9, s2
; CHECK-BE-GI-NEXT:    mov v0.h[2], w8
; CHECK-BE-GI-NEXT:    mov v1.h[2], w9
; CHECK-BE-GI-NEXT:    fmov w8, s5
; CHECK-BE-GI-NEXT:    fmov w9, s3
; CHECK-BE-GI-NEXT:    mov v0.h[3], w8
; CHECK-BE-GI-NEXT:    mov v1.h[3], w9
; CHECK-BE-GI-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-BE-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-GI-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-BE-GI-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <4 x i8>, ptr %a, align 4
  %y = load <4 x i8>, ptr %b, align 4
  %z = add <4 x i8> %x, %y
  %s = sext <4 x i8> %z to <4 x i32>
  ret <4 x i32> %s
}

define <4 x i8> @bitcast(i32 %0) {
; CHECK-LE-SD-LABEL: bitcast:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    fmov s0, w0
; CHECK-LE-SD-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: bitcast:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    fmov s0, w0
; CHECK-BE-SD-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: bitcast:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    fmov s0, w0
; CHECK-LE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-LE-GI-NEXT:    mov b2, v0.b[2]
; CHECK-LE-GI-NEXT:    fmov w8, s1
; CHECK-LE-GI-NEXT:    mov b1, v0.b[3]
; CHECK-LE-GI-NEXT:    mov v0.h[1], w8
; CHECK-LE-GI-NEXT:    fmov w8, s2
; CHECK-LE-GI-NEXT:    mov v0.h[2], w8
; CHECK-LE-GI-NEXT:    fmov w8, s1
; CHECK-LE-GI-NEXT:    mov v0.h[3], w8
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: bitcast:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    fmov s0, w0
; CHECK-BE-GI-NEXT:    mov b1, v0.b[1]
; CHECK-BE-GI-NEXT:    mov b2, v0.b[2]
; CHECK-BE-GI-NEXT:    fmov w8, s1
; CHECK-BE-GI-NEXT:    mov b1, v0.b[3]
; CHECK-BE-GI-NEXT:    mov v0.h[1], w8
; CHECK-BE-GI-NEXT:    fmov w8, s2
; CHECK-BE-GI-NEXT:    mov v0.h[2], w8
; CHECK-BE-GI-NEXT:    fmov w8, s1
; CHECK-BE-GI-NEXT:    mov v0.h[3], w8
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    ret
  %2 = bitcast i32 %0 to <4 x i8>
  ret <4 x i8> %2
}


define <2 x i16> @zext_v2i8_v2i16(ptr %a) {
; CHECK-LE-SD-LABEL: zext_v2i8_v2i16:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: zext_v2i8_v2i16:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: zext_v2i8_v2i16:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v1.b }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr b2, [x0, #1]
; CHECK-LE-GI-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-LE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-LE-GI-NEXT:    and v1.8b, v1.8b, v0.8b
; CHECK-LE-GI-NEXT:    mov v0.s[0], v1.s[0]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v1.s[1]
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: zext_v2i8_v2i16:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #1
; CHECK-BE-GI-NEXT:    ldr b2, [x0]
; CHECK-BE-GI-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-BE-GI-NEXT:    ld1 { v1.b }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-BE-GI-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-BE-GI-NEXT:    mov v1.s[0], v0.s[0]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v0.s[1]
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v1.2s
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i8>, ptr %a
  %y = zext <2 x i8> %x to <2 x i16>
  ret <2 x i16> %y
}

define <2 x i32> @zext_v2i8_v2i32(ptr %a) {
; CHECK-LE-SD-LABEL: zext_v2i8_v2i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: zext_v2i8_v2i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: zext_v2i8_v2i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v1.b }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr b2, [x0, #1]
; CHECK-LE-GI-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-LE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-LE-GI-NEXT:    and v1.8b, v1.8b, v0.8b
; CHECK-LE-GI-NEXT:    mov v0.s[0], v1.s[0]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v1.s[1]
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: zext_v2i8_v2i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #1
; CHECK-BE-GI-NEXT:    ldr b2, [x0]
; CHECK-BE-GI-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-BE-GI-NEXT:    ld1 { v1.b }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-BE-GI-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-BE-GI-NEXT:    mov v1.s[0], v0.s[0]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v0.s[1]
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v1.2s
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i8>, ptr %a
  %y = zext <2 x i8> %x to <2 x i32>
  ret <2 x i32> %y
}

define <2 x i64> @zext_v2i8_v2i64(ptr %a) {
; CHECK-LE-SD-LABEL: zext_v2i8_v2i64:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: zext_v2i8_v2i64:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: zext_v2i8_v2i64:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v1.b }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr b2, [x0, #1]
; CHECK-LE-GI-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-LE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-LE-GI-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-LE-GI-NEXT:    fmov w9, s0
; CHECK-LE-GI-NEXT:    mov w8, v0.s[1]
; CHECK-LE-GI-NEXT:    and x9, x9, #0xffff
; CHECK-LE-GI-NEXT:    fmov d0, x9
; CHECK-LE-GI-NEXT:    and x8, x8, #0xffff
; CHECK-LE-GI-NEXT:    mov v0.d[1], x8
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: zext_v2i8_v2i64:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #1
; CHECK-BE-GI-NEXT:    ldr b2, [x0]
; CHECK-BE-GI-NEXT:    movi d0, #0x0000ff000000ff
; CHECK-BE-GI-NEXT:    ld1 { v1.b }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-BE-GI-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-BE-GI-NEXT:    fmov w9, s0
; CHECK-BE-GI-NEXT:    mov w8, v0.s[1]
; CHECK-BE-GI-NEXT:    and x9, x9, #0xffff
; CHECK-BE-GI-NEXT:    fmov d0, x9
; CHECK-BE-GI-NEXT:    and x8, x8, #0xffff
; CHECK-BE-GI-NEXT:    mov v0.d[1], x8
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i8>, ptr %a
  %y = zext <2 x i8> %x to <2 x i64>
  ret <2 x i64> %y
}

define <2 x i32> @zext_v2i16_v2i32(ptr %a) {
; CHECK-LE-SD-LABEL: zext_v2i16_v2i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: zext_v2i16_v2i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: zext_v2i16_v2i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr h0, [x0]
; CHECK-LE-GI-NEXT:    add x8, x0, #2
; CHECK-LE-GI-NEXT:    ld1 { v0.h }[1], [x8]
; CHECK-LE-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: zext_v2i16_v2i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr h0, [x0, #2]
; CHECK-BE-GI-NEXT:    ld1 { v0.h }[1], [x0]
; CHECK-BE-GI-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i16>, ptr %a
  %y = zext <2 x i16> %x to <2 x i32>
  ret <2 x i32> %y
}

define <2 x i64> @zext_v2i16_v2i64(ptr %a) {
; CHECK-LE-SD-LABEL: zext_v2i16_v2i64:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: zext_v2i16_v2i64:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: zext_v2i16_v2i64:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v1.h }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr h2, [x0, #2]
; CHECK-LE-GI-NEXT:    movi d0, #0x00ffff0000ffff
; CHECK-LE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-LE-GI-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-LE-GI-NEXT:    mov w8, v0.s[0]
; CHECK-LE-GI-NEXT:    mov w9, v0.s[1]
; CHECK-LE-GI-NEXT:    fmov d0, x8
; CHECK-LE-GI-NEXT:    mov v0.d[1], x9
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: zext_v2i16_v2i64:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #2
; CHECK-BE-GI-NEXT:    ldr h2, [x0]
; CHECK-BE-GI-NEXT:    movi d0, #0x00ffff0000ffff
; CHECK-BE-GI-NEXT:    ld1 { v1.h }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v2.s[0]
; CHECK-BE-GI-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-BE-GI-NEXT:    mov w8, v0.s[0]
; CHECK-BE-GI-NEXT:    mov w9, v0.s[1]
; CHECK-BE-GI-NEXT:    fmov d0, x8
; CHECK-BE-GI-NEXT:    mov v0.d[1], x9
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i16>, ptr %a
  %y = zext <2 x i16> %x to <2 x i64>
  ret <2 x i64> %y
}

define <4 x i32> @zext_v4i16_v4i32(ptr %a) {
; CHECK-LE-LABEL: zext_v4i16_v4i32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldr d0, [x0]
; CHECK-LE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: zext_v4i16_v4i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ld1 { v0.4h }, [x0]
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ret
  %x = load <4 x i16>, ptr %a
  %y = zext <4 x i16> %x to <4 x i32>
  ret <4 x i32> %y
}

define <2 x i64> @sext_v2i8_v2i64(ptr %a) {
; CHECK-LE-SD-LABEL: sext_v2i8_v2i64:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr h0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    sshll v0.2d, v0.2s, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: sext_v2i8_v2i64:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr h0, [x0]
; CHECK-BE-SD-NEXT:    rev16 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    sshll v0.8h, v0.8b, #0
; CHECK-BE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    sshll v0.2d, v0.2s, #0
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: sext_v2i8_v2i64:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldrb w8, [x0]
; CHECK-LE-GI-NEXT:    ldrb w9, [x0, #1]
; CHECK-LE-GI-NEXT:    fmov s0, w8
; CHECK-LE-GI-NEXT:    mov v0.h[1], w9
; CHECK-LE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-LE-GI-NEXT:    smov x8, v0.h[0]
; CHECK-LE-GI-NEXT:    smov x9, v0.h[1]
; CHECK-LE-GI-NEXT:    fmov d0, x8
; CHECK-LE-GI-NEXT:    mov v0.d[1], x9
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: sext_v2i8_v2i64:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldrb w8, [x0, #1]
; CHECK-BE-GI-NEXT:    ldrb w9, [x0]
; CHECK-BE-GI-NEXT:    fmov s0, w8
; CHECK-BE-GI-NEXT:    mov v0.h[1], w9
; CHECK-BE-GI-NEXT:    shl v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    sshr v0.4h, v0.4h, #8
; CHECK-BE-GI-NEXT:    smov x8, v0.h[0]
; CHECK-BE-GI-NEXT:    smov x9, v0.h[1]
; CHECK-BE-GI-NEXT:    fmov d0, x8
; CHECK-BE-GI-NEXT:    mov v0.d[1], x9
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i8>, ptr %a
  %y = sext <2 x i8> %x to <2 x i64>
  ret <2 x i64> %y
}

define <2 x i32> @sext_v2i16_v2i32(ptr %a) {
; CHECK-LE-SD-LABEL: sext_v2i16_v2i32:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: sext_v2i16_v2i32:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: sext_v2i16_v2i32:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ldr h0, [x0]
; CHECK-LE-GI-NEXT:    add x8, x0, #2
; CHECK-LE-GI-NEXT:    ld1 { v0.h }[1], [x8]
; CHECK-LE-GI-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: sext_v2i16_v2i32:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    ldr h0, [x0, #2]
; CHECK-BE-GI-NEXT:    ld1 { v0.h }[1], [x0]
; CHECK-BE-GI-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-GI-NEXT:    rev64 v0.2s, v0.2s
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i16>, ptr %a
  %y = sext <2 x i16> %x to <2 x i32>
  ret <2 x i32> %y
}

define <2 x i64> @sext_v2i16_v2i64(ptr %a) {
; CHECK-LE-SD-LABEL: sext_v2i16_v2i64:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ldr s0, [x0]
; CHECK-LE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-SD-NEXT:    sshll v0.2d, v0.2s, #0
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: sext_v2i16_v2i64:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ldr s0, [x0]
; CHECK-BE-SD-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-SD-NEXT:    sshll v0.2d, v0.2s, #0
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: sext_v2i16_v2i64:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    ld1 { v0.h }[0], [x0]
; CHECK-LE-GI-NEXT:    ldr h1, [x0, #2]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-LE-GI-NEXT:    shl v0.2s, v0.2s, #16
; CHECK-LE-GI-NEXT:    sshr v0.2s, v0.2s, #16
; CHECK-LE-GI-NEXT:    smov x8, v0.s[0]
; CHECK-LE-GI-NEXT:    smov x9, v0.s[1]
; CHECK-LE-GI-NEXT:    fmov d0, x8
; CHECK-LE-GI-NEXT:    mov v0.d[1], x9
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: sext_v2i16_v2i64:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    add x8, x0, #2
; CHECK-BE-GI-NEXT:    ldr h1, [x0]
; CHECK-BE-GI-NEXT:    ld1 { v0.h }[0], [x8]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-BE-GI-NEXT:    shl v0.2s, v0.2s, #16
; CHECK-BE-GI-NEXT:    sshr v0.2s, v0.2s, #16
; CHECK-BE-GI-NEXT:    smov x8, v0.s[0]
; CHECK-BE-GI-NEXT:    smov x9, v0.s[1]
; CHECK-BE-GI-NEXT:    fmov d0, x8
; CHECK-BE-GI-NEXT:    mov v0.d[1], x9
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %x = load <2 x i16>, ptr %a
  %y = sext <2 x i16> %x to <2 x i64>
  ret <2 x i64> %y
}

define <4 x i32> @sext_v4i16_v4i32(ptr %a) {
; CHECK-LE-LABEL: sext_v4i16_v4i32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldr d0, [x0]
; CHECK-LE-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: sext_v4i16_v4i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ld1 { v0.4h }, [x0]
; CHECK-BE-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ret
  %x = load <4 x i16>, ptr %a
  %y = sext <4 x i16> %x to <4 x i32>
  ret <4 x i32> %y
}
