; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=arm64-eabi -aarch64-neon-syntax=apple | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc < %s -mtriple=aarch64_be-none-eabi | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc < %s -mtriple=arm64-eabi -aarch64-neon-syntax=apple -global-isel | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc < %s -mtriple=aarch64_be-none-eabi -global-isel | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE

define i32 @cnt32_advsimd(i32 %x) nounwind readnone {
; CHECK-SD-LE-LABEL: cnt32_advsimd:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    fmov s0, w0
; CHECK-SD-LE-NEXT:    cnt.8b v0, v0
; CHECK-SD-LE-NEXT:    addv.8b b0, v0
; CHECK-SD-LE-NEXT:    fmov w0, s0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: cnt32_advsimd:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    fmov s0, w0
; CHECK-SD-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    addv b0, v0.8b
; CHECK-SD-BE-NEXT:    fmov w0, s0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: cnt32_advsimd:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov s0, w0
; CHECK-GI-LE-NEXT:    cnt.8b v0, v0
; CHECK-GI-LE-NEXT:    uaddlv.8b h0, v0
; CHECK-GI-LE-NEXT:    fmov w0, s0
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: cnt32_advsimd:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov s0, w0
; CHECK-GI-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.8b
; CHECK-GI-BE-NEXT:    fmov w0, s0
; CHECK-GI-BE-NEXT:    ret
  %cnt = tail call i32 @llvm.ctpop.i32(i32 %x)
  ret i32 %cnt
}

define i32 @cnt32_advsimd_2(<2 x i32> %x) {
; CHECK-SD-LE-LABEL: cnt32_advsimd_2:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SD-LE-NEXT:    fmov w8, s0
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    cnt.8b v0, v0
; CHECK-SD-LE-NEXT:    addv.8b b0, v0
; CHECK-SD-LE-NEXT:    fmov w0, s0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: cnt32_advsimd_2:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    fmov w8, s0
; CHECK-SD-BE-NEXT:    fmov s0, w8
; CHECK-SD-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    addv b0, v0.8b
; CHECK-SD-BE-NEXT:    fmov w0, s0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: cnt32_advsimd_2:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov w8, s0
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    cnt.8b v0, v0
; CHECK-GI-LE-NEXT:    uaddlv.8b h0, v0
; CHECK-GI-LE-NEXT:    fmov w0, s0
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: cnt32_advsimd_2:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-GI-BE-NEXT:    fmov w8, s0
; CHECK-GI-BE-NEXT:    fmov s0, w8
; CHECK-GI-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.8b
; CHECK-GI-BE-NEXT:    fmov w0, s0
; CHECK-GI-BE-NEXT:    ret
  %1 = extractelement <2 x i32> %x, i64 0
  %2 = tail call i32 @llvm.ctpop.i32(i32 %1)
  ret i32 %2
}

define i64 @cnt64_advsimd(i64 %x) nounwind readnone {
; CHECK-SD-LE-LABEL: cnt64_advsimd:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    fmov d0, x0
; CHECK-SD-LE-NEXT:    cnt.8b v0, v0
; CHECK-SD-LE-NEXT:    addv.8b b0, v0
; CHECK-SD-LE-NEXT:    fmov x0, d0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: cnt64_advsimd:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    fmov d0, x0
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    addv b0, v0.8b
; CHECK-SD-BE-NEXT:    fmov x0, d0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: cnt64_advsimd:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov d0, x0
; CHECK-GI-LE-NEXT:    cnt.8b v0, v0
; CHECK-GI-LE-NEXT:    uaddlv.8b h0, v0
; CHECK-GI-LE-NEXT:    mov.s w0, v0[0]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: cnt64_advsimd:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov d0, x0
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.8b
; CHECK-GI-BE-NEXT:    mov w0, v0.s[0]
; CHECK-GI-BE-NEXT:    ret
  %cnt = tail call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %cnt
}

; Do not use AdvSIMD when -mno-implicit-float is specified.
; rdar://9473858

define i32 @cnt32(i32 %x) nounwind readnone noimplicitfloat {
; CHECK-SD-LE-LABEL: cnt32:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    lsr w9, w0, #1
; CHECK-SD-LE-NEXT:    mov w8, #16843009 // =0x1010101
; CHECK-SD-LE-NEXT:    and w9, w9, #0x55555555
; CHECK-SD-LE-NEXT:    sub w9, w0, w9
; CHECK-SD-LE-NEXT:    lsr w10, w9, #2
; CHECK-SD-LE-NEXT:    and w9, w9, #0x33333333
; CHECK-SD-LE-NEXT:    and w10, w10, #0x33333333
; CHECK-SD-LE-NEXT:    add w9, w9, w10
; CHECK-SD-LE-NEXT:    add w9, w9, w9, lsr #4
; CHECK-SD-LE-NEXT:    and w9, w9, #0xf0f0f0f
; CHECK-SD-LE-NEXT:    mul w8, w9, w8
; CHECK-SD-LE-NEXT:    lsr w0, w8, #24
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: cnt32:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    lsr w9, w0, #1
; CHECK-SD-BE-NEXT:    mov w8, #16843009 // =0x1010101
; CHECK-SD-BE-NEXT:    and w9, w9, #0x55555555
; CHECK-SD-BE-NEXT:    sub w9, w0, w9
; CHECK-SD-BE-NEXT:    lsr w10, w9, #2
; CHECK-SD-BE-NEXT:    and w9, w9, #0x33333333
; CHECK-SD-BE-NEXT:    and w10, w10, #0x33333333
; CHECK-SD-BE-NEXT:    add w9, w9, w10
; CHECK-SD-BE-NEXT:    add w9, w9, w9, lsr #4
; CHECK-SD-BE-NEXT:    and w9, w9, #0xf0f0f0f
; CHECK-SD-BE-NEXT:    mul w8, w9, w8
; CHECK-SD-BE-NEXT:    lsr w0, w8, #24
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: cnt32:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    lsr w9, w0, #1
; CHECK-GI-LE-NEXT:    mov w8, #16843009 // =0x1010101
; CHECK-GI-LE-NEXT:    and w9, w9, #0x55555555
; CHECK-GI-LE-NEXT:    sub w9, w0, w9
; CHECK-GI-LE-NEXT:    lsr w10, w9, #2
; CHECK-GI-LE-NEXT:    and w9, w9, #0x33333333
; CHECK-GI-LE-NEXT:    and w10, w10, #0x33333333
; CHECK-GI-LE-NEXT:    add w9, w10, w9
; CHECK-GI-LE-NEXT:    add w9, w9, w9, lsr #4
; CHECK-GI-LE-NEXT:    and w9, w9, #0xf0f0f0f
; CHECK-GI-LE-NEXT:    mul w8, w9, w8
; CHECK-GI-LE-NEXT:    lsr w0, w8, #24
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: cnt32:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    lsr w9, w0, #1
; CHECK-GI-BE-NEXT:    mov w8, #16843009 // =0x1010101
; CHECK-GI-BE-NEXT:    and w9, w9, #0x55555555
; CHECK-GI-BE-NEXT:    sub w9, w0, w9
; CHECK-GI-BE-NEXT:    lsr w10, w9, #2
; CHECK-GI-BE-NEXT:    and w9, w9, #0x33333333
; CHECK-GI-BE-NEXT:    and w10, w10, #0x33333333
; CHECK-GI-BE-NEXT:    add w9, w10, w9
; CHECK-GI-BE-NEXT:    add w9, w9, w9, lsr #4
; CHECK-GI-BE-NEXT:    and w9, w9, #0xf0f0f0f
; CHECK-GI-BE-NEXT:    mul w8, w9, w8
; CHECK-GI-BE-NEXT:    lsr w0, w8, #24
; CHECK-GI-BE-NEXT:    ret
  %cnt = tail call i32 @llvm.ctpop.i32(i32 %x)
  ret i32 %cnt
}

define i64 @cnt64(i64 %x) nounwind readnone noimplicitfloat {
; CHECK-SD-LE-LABEL: cnt64:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    lsr x9, x0, #1
; CHECK-SD-LE-NEXT:    mov x8, #72340172838076673 // =0x101010101010101
; CHECK-SD-LE-NEXT:    and x9, x9, #0x5555555555555555
; CHECK-SD-LE-NEXT:    sub x9, x0, x9
; CHECK-SD-LE-NEXT:    lsr x10, x9, #2
; CHECK-SD-LE-NEXT:    and x9, x9, #0x3333333333333333
; CHECK-SD-LE-NEXT:    and x10, x10, #0x3333333333333333
; CHECK-SD-LE-NEXT:    add x9, x9, x10
; CHECK-SD-LE-NEXT:    add x9, x9, x9, lsr #4
; CHECK-SD-LE-NEXT:    and x9, x9, #0xf0f0f0f0f0f0f0f
; CHECK-SD-LE-NEXT:    mul x8, x9, x8
; CHECK-SD-LE-NEXT:    lsr x0, x8, #56
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: cnt64:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    lsr x9, x0, #1
; CHECK-SD-BE-NEXT:    mov x8, #72340172838076673 // =0x101010101010101
; CHECK-SD-BE-NEXT:    and x9, x9, #0x5555555555555555
; CHECK-SD-BE-NEXT:    sub x9, x0, x9
; CHECK-SD-BE-NEXT:    lsr x10, x9, #2
; CHECK-SD-BE-NEXT:    and x9, x9, #0x3333333333333333
; CHECK-SD-BE-NEXT:    and x10, x10, #0x3333333333333333
; CHECK-SD-BE-NEXT:    add x9, x9, x10
; CHECK-SD-BE-NEXT:    add x9, x9, x9, lsr #4
; CHECK-SD-BE-NEXT:    and x9, x9, #0xf0f0f0f0f0f0f0f
; CHECK-SD-BE-NEXT:    mul x8, x9, x8
; CHECK-SD-BE-NEXT:    lsr x0, x8, #56
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: cnt64:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    lsr x9, x0, #1
; CHECK-GI-LE-NEXT:    mov x8, #72340172838076673 // =0x101010101010101
; CHECK-GI-LE-NEXT:    and x9, x9, #0x5555555555555555
; CHECK-GI-LE-NEXT:    sub x9, x0, x9
; CHECK-GI-LE-NEXT:    lsr x10, x9, #2
; CHECK-GI-LE-NEXT:    and x9, x9, #0x3333333333333333
; CHECK-GI-LE-NEXT:    and x10, x10, #0x3333333333333333
; CHECK-GI-LE-NEXT:    add x9, x10, x9
; CHECK-GI-LE-NEXT:    add x9, x9, x9, lsr #4
; CHECK-GI-LE-NEXT:    and x9, x9, #0xf0f0f0f0f0f0f0f
; CHECK-GI-LE-NEXT:    mul x8, x9, x8
; CHECK-GI-LE-NEXT:    lsr x0, x8, #56
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: cnt64:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    lsr x9, x0, #1
; CHECK-GI-BE-NEXT:    mov x8, #72340172838076673 // =0x101010101010101
; CHECK-GI-BE-NEXT:    and x9, x9, #0x5555555555555555
; CHECK-GI-BE-NEXT:    sub x9, x0, x9
; CHECK-GI-BE-NEXT:    lsr x10, x9, #2
; CHECK-GI-BE-NEXT:    and x9, x9, #0x3333333333333333
; CHECK-GI-BE-NEXT:    and x10, x10, #0x3333333333333333
; CHECK-GI-BE-NEXT:    add x9, x10, x9
; CHECK-GI-BE-NEXT:    add x9, x9, x9, lsr #4
; CHECK-GI-BE-NEXT:    and x9, x9, #0xf0f0f0f0f0f0f0f
; CHECK-GI-BE-NEXT:    mul x8, x9, x8
; CHECK-GI-BE-NEXT:    lsr x0, x8, #56
; CHECK-GI-BE-NEXT:    ret
  %cnt = tail call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %cnt
}

define i32 @ctpop_eq_one(i64 %x) nounwind readnone {
; CHECK-LE-LABEL: ctpop_eq_one:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    sub x8, x0, #1
; CHECK-LE-NEXT:    eor x9, x0, x8
; CHECK-LE-NEXT:    cmp x9, x8
; CHECK-LE-NEXT:    cset w0, hi
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: ctpop_eq_one:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub x8, x0, #1
; CHECK-BE-NEXT:    eor x9, x0, x8
; CHECK-BE-NEXT:    cmp x9, x8
; CHECK-BE-NEXT:    cset w0, hi
; CHECK-BE-NEXT:    ret
  %count = tail call i64 @llvm.ctpop.i64(i64 %x)
  %cmp = icmp eq i64 %count, 1
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ctpop_ne_one(i64 %x) nounwind readnone {
; CHECK-LE-LABEL: ctpop_ne_one:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    sub x8, x0, #1
; CHECK-LE-NEXT:    eor x9, x0, x8
; CHECK-LE-NEXT:    cmp x9, x8
; CHECK-LE-NEXT:    cset w0, ls
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: ctpop_ne_one:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub x8, x0, #1
; CHECK-BE-NEXT:    eor x9, x0, x8
; CHECK-BE-NEXT:    cmp x9, x8
; CHECK-BE-NEXT:    cset w0, ls
; CHECK-BE-NEXT:    ret
  %count = tail call i64 @llvm.ctpop.i64(i64 %x)
  %cmp = icmp ne i64 %count, 1
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i1 @ctpop32_ne_one(i32 %x) nounwind readnone {
; CHECK-LE-LABEL: ctpop32_ne_one:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    sub w8, w0, #1
; CHECK-LE-NEXT:    eor w9, w0, w8
; CHECK-LE-NEXT:    cmp w9, w8
; CHECK-LE-NEXT:    cset w0, ls
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: ctpop32_ne_one:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub w8, w0, #1
; CHECK-BE-NEXT:    eor w9, w0, w8
; CHECK-BE-NEXT:    cmp w9, w8
; CHECK-BE-NEXT:    cset w0, ls
; CHECK-BE-NEXT:    ret
  %count = tail call i32 @llvm.ctpop.i32(i32 %x)
  %cmp = icmp ne i32 %count, 1
  ret i1 %cmp
}

define i1 @ctpop32_eq_one_nonzero(i32 %x) {
; CHECK-LE-LABEL: ctpop32_eq_one_nonzero:
; CHECK-LE:       // %bb.0: // %entry
; CHECK-LE-NEXT:    sub w8, w0, #1
; CHECK-LE-NEXT:    tst w0, w8
; CHECK-LE-NEXT:    cset w0, eq
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: ctpop32_eq_one_nonzero:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    sub w8, w0, #1
; CHECK-BE-NEXT:    tst w0, w8
; CHECK-BE-NEXT:    cset w0, eq
; CHECK-BE-NEXT:    ret
entry:
  %popcnt = call range(i32 1, 33) i32 @llvm.ctpop.i32(i32 %x)
  %cmp = icmp eq i32 %popcnt, 1
  ret i1 %cmp
}

define i1 @ctpop32_ne_one_nonzero(i32 %x) {
; CHECK-LE-LABEL: ctpop32_ne_one_nonzero:
; CHECK-LE:       // %bb.0: // %entry
; CHECK-LE-NEXT:    sub w8, w0, #1
; CHECK-LE-NEXT:    tst w0, w8
; CHECK-LE-NEXT:    cset w0, ne
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: ctpop32_ne_one_nonzero:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    sub w8, w0, #1
; CHECK-BE-NEXT:    tst w0, w8
; CHECK-BE-NEXT:    cset w0, ne
; CHECK-BE-NEXT:    ret
entry:
  %popcnt = tail call range(i32 1, 33) i32 @llvm.ctpop.i32(i32 %x)
  %cmp = icmp ne i32 %popcnt, 1
  ret i1 %cmp
}

define i128 @cnt128(i128 %x) nounwind readnone {
; CHECK-SD-LE-LABEL: cnt128:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    fmov d0, x0
; CHECK-SD-LE-NEXT:    mov.d v0[1], x1
; CHECK-SD-LE-NEXT:    mov x1, xzr
; CHECK-SD-LE-NEXT:    cnt.16b v0, v0
; CHECK-SD-LE-NEXT:    addv.16b b0, v0
; CHECK-SD-LE-NEXT:    fmov x0, d0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: cnt128:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    fmov d0, x0
; CHECK-SD-BE-NEXT:    mov x0, xzr
; CHECK-SD-BE-NEXT:    mov v0.d[1], x1
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    addv b0, v0.16b
; CHECK-SD-BE-NEXT:    fmov x1, d0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: cnt128:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    mov.d v0[0], x0
; CHECK-GI-LE-NEXT:    mov.d v0[1], x1
; CHECK-GI-LE-NEXT:    mov x1, xzr
; CHECK-GI-LE-NEXT:    cnt.16b v0, v0
; CHECK-GI-LE-NEXT:    uaddlv.16b h0, v0
; CHECK-GI-LE-NEXT:    mov.s w0, v0[0]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: cnt128:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    mov v0.d[0], x1
; CHECK-GI-BE-NEXT:    mov v0.d[1], x0
; CHECK-GI-BE-NEXT:    mov x0, xzr
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-BE-NEXT:    mov w1, v0.s[0]
; CHECK-GI-BE-NEXT:    ret
  %cnt = tail call i128 @llvm.ctpop.i128(i128 %x)
  ret i128 %cnt
}

declare i32 @llvm.ctpop.i32(i32) nounwind readnone
declare i64 @llvm.ctpop.i64(i64) nounwind readnone
