; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64 -o - | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc < %s -mtriple=aarch64_be -o - | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc < %s -mtriple=aarch64 -global-isel -o - | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc < %s -mtriple=aarch64_be -global-isel -o - | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE

define i64 @load32_and16_and(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load32_and16_and:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    and w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_and:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    and w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_and:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    and x9, x1, #0xffff
; CHECK-GI-LE-NEXT:    and x0, x9, x8
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_and:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldr w8, [x0]
; CHECK-GI-BE-NEXT:    and x9, x1, #0xffff
; CHECK-GI-BE-NEXT:    and x0, x9, x8
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %ym = and i64 %y, 65535
  %r = and i64 %ym, %xz
  ret i64 %r
}

define i64 @load32_and16_andr(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load32_and16_andr:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    and w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_andr:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    and w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_andr:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    and x8, x1, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_andr:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldr w8, [x0]
; CHECK-GI-BE-NEXT:    and x8, x1, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %a = and i64 %y, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load32_and16_and_sext(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load32_and16_and_sext:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    and w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_and_sext:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    and w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_and_sext:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrsw x8, [x0]
; CHECK-GI-LE-NEXT:    and x8, x1, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_and_sext:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrsw x8, [x0]
; CHECK-GI-BE-NEXT:    and x8, x1, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = sext i32 %x to i64
  %a = and i64 %y, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load32_and16_or(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load32_and16_or:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_or:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    orr w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_or:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    orr x8, x1, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_or:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldr w8, [x0]
; CHECK-GI-BE-NEXT:    orr x8, x1, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %a = or i64 %y, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load32_and16_orr(ptr %p, i64 %y) {
; CHECK-LE-LABEL: load32_and16_orr:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldr w8, [x0]
; CHECK-LE-NEXT:    and x9, x1, #0xffff
; CHECK-LE-NEXT:    orr x0, x9, x8
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load32_and16_orr:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ldr w8, [x0]
; CHECK-BE-NEXT:    and x9, x1, #0xffff
; CHECK-BE-NEXT:    orr x0, x9, x8
; CHECK-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %ym = and i64 %y, 65535
  %r = or i64 %ym, %xz
  ret i64 %r
}

define i64 @load32_and16_xorm1(ptr %p) {
; CHECK-SD-LE-LABEL: load32_and16_xorm1:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    mvn w8, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_xorm1:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    mvn w8, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_xorm1:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    mov w9, #65535 // =0xffff
; CHECK-GI-LE-NEXT:    bic x0, x9, x8
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_xorm1:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldr w8, [x0]
; CHECK-GI-BE-NEXT:    mov w9, #65535 // =0xffff
; CHECK-GI-BE-NEXT:    bic x0, x9, x8
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %a = xor i64 %xz, -1
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load64_and16(ptr %p, i128 %y) {
; CHECK-SD-LE-LABEL: load64_and16:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrh w8, [x0]
; CHECK-SD-LE-NEXT:    and x0, x2, x8
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load64_and16:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrh w8, [x0, #6]
; CHECK-SD-BE-NEXT:    and x0, x3, x8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load64_and16:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr x8, [x0]
; CHECK-GI-LE-NEXT:    and x8, x2, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load64_and16:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldr x8, [x0]
; CHECK-GI-BE-NEXT:    and x8, x3, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i64, ptr %p, align 4
  %xz = zext i64 %x to i128
  %a = and i128 %y, %xz
  %t = trunc i128 %a to i64
  %r = and i64 %t, 65535
  ret i64 %r
}

define i64 @load16_and16(ptr %p, i64 %y) {
; CHECK-LE-LABEL: load16_and16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldrh w8, [x0]
; CHECK-LE-NEXT:    and x0, x1, x8
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load16_and16:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    and x0, x1, x8
; CHECK-BE-NEXT:    ret
  %x = load i16, ptr %p, align 4
  %xz = zext i16 %x to i64
  %a = and i64 %y, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load16_and8(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load16_and8:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrh w8, [x0]
; CHECK-SD-LE-NEXT:    and w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load16_and8:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrh w8, [x0]
; CHECK-SD-BE-NEXT:    and w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load16_and8:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrh w8, [x0]
; CHECK-GI-LE-NEXT:    and x8, x1, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load16_and8:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrh w8, [x0]
; CHECK-GI-BE-NEXT:    and x8, x1, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xff
; CHECK-GI-BE-NEXT:    ret
  %x = load i16, ptr %p, align 4
  %xz = zext i16 %x to i64
  %a = and i64 %y, %xz
  %r = and i64 %a, 255
  ret i64 %r
}

define i64 @load16_and7(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load16_and7:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrh w8, [x0]
; CHECK-SD-LE-NEXT:    and w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0x7f
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load16_and7:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrh w8, [x0]
; CHECK-SD-BE-NEXT:    and w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0x7f
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load16_and7:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrh w8, [x0]
; CHECK-GI-LE-NEXT:    and x8, x1, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0x7f
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load16_and7:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrh w8, [x0]
; CHECK-GI-BE-NEXT:    and x8, x1, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0x7f
; CHECK-GI-BE-NEXT:    ret
  %x = load i16, ptr %p, align 4
  %xz = zext i16 %x to i64
  %a = and i64 %y, %xz
  %r = and i64 %a, 127
  ret i64 %r
}

define i64 @load8_and16(ptr %p, i64 %y) {
; CHECK-LE-LABEL: load8_and16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldrb w8, [x0]
; CHECK-LE-NEXT:    and x0, x1, x8
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load8_and16:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ldrb w8, [x0]
; CHECK-BE-NEXT:    and x0, x1, x8
; CHECK-BE-NEXT:    ret
  %x = load i8, ptr %p, align 4
  %xz = zext i8 %x to i64
  %a = and i64 %y, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load8_and16_zext(ptr %p, i8 %y) {
; CHECK-SD-LE-LABEL: load8_and16_zext:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0]
; CHECK-SD-LE-NEXT:    and w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load8_and16_zext:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrb w8, [x0]
; CHECK-SD-BE-NEXT:    and w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load8_and16_zext:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrb w8, [x0]
; CHECK-GI-LE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-GI-LE-NEXT:    and x9, x1, #0xff
; CHECK-GI-LE-NEXT:    and x0, x9, x8
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load8_and16_zext:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrb w8, [x0]
; CHECK-GI-BE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-GI-BE-NEXT:    and x9, x1, #0xff
; CHECK-GI-BE-NEXT:    and x0, x9, x8
; CHECK-GI-BE-NEXT:    ret
  %x = load i8, ptr %p, align 4
  %xz = zext i8 %x to i64
  %yz = zext i8 %y to i64
  %a = and i64 %yz, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load8_and16_sext(ptr %p, i8 %y) {
; CHECK-SD-LE-LABEL: load8_and16_sext:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0]
; CHECK-SD-LE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-SD-LE-NEXT:    and x0, x1, x8
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load8_and16_sext:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrb w8, [x0]
; CHECK-SD-BE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-SD-BE-NEXT:    and x0, x1, x8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load8_and16_sext:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-GI-LE-NEXT:    ldrb w8, [x0]
; CHECK-GI-LE-NEXT:    sxtb x9, w1
; CHECK-GI-LE-NEXT:    and x0, x9, x8
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load8_and16_sext:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-GI-BE-NEXT:    ldrb w8, [x0]
; CHECK-GI-BE-NEXT:    sxtb x9, w1
; CHECK-GI-BE-NEXT:    and x0, x9, x8
; CHECK-GI-BE-NEXT:    ret
  %x = load i8, ptr %p, align 4
  %xz = zext i8 %x to i64
  %yz = sext i8 %y to i64
  %a = and i64 %yz, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load8_and16_or(ptr %p, i64 %y) {
; CHECK-SD-LE-LABEL: load8_and16_or:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load8_and16_or:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrb w8, [x0]
; CHECK-SD-BE-NEXT:    orr w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load8_and16_or:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrb w8, [x0]
; CHECK-GI-LE-NEXT:    orr x8, x1, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load8_and16_or:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrb w8, [x0]
; CHECK-GI-BE-NEXT:    orr x8, x1, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i8, ptr %p, align 4
  %xz = zext i8 %x to i64
  %a = or i64 %y, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load16_and8_manyext(ptr %p, i32 %y) {
; CHECK-LE-LABEL: load16_and8_manyext:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ldrh w8, [x0]
; CHECK-LE-NEXT:    and w8, w1, w8
; CHECK-LE-NEXT:    and x0, x8, #0xff
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load16_and8_manyext:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    and w8, w1, w8
; CHECK-BE-NEXT:    and x0, x8, #0xff
; CHECK-BE-NEXT:    ret
  %x = load i16, ptr %p, align 4
  %xz = zext i16 %x to i32
  %a = and i32 %y, %xz
  %az = zext i32 %a to i64
  %r = and i64 %az, 255
  ret i64 %r
}

define i64 @multiple_load(ptr %p, ptr %q) {
; CHECK-SD-LE-LABEL: multiple_load:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrh w8, [x0]
; CHECK-SD-LE-NEXT:    ldr w9, [x1]
; CHECK-SD-LE-NEXT:    and w8, w9, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: multiple_load:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrh w8, [x0]
; CHECK-SD-BE-NEXT:    ldr w9, [x1]
; CHECK-SD-BE-NEXT:    and w8, w9, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: multiple_load:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrh w8, [x0]
; CHECK-GI-LE-NEXT:    ldr w9, [x1]
; CHECK-GI-LE-NEXT:    and x8, x9, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: multiple_load:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrh w8, [x0]
; CHECK-GI-BE-NEXT:    ldr w9, [x1]
; CHECK-GI-BE-NEXT:    and x8, x9, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xff
; CHECK-GI-BE-NEXT:    ret
  %x = load i16, ptr %p, align 4
  %xz = zext i16 %x to i64
  %y = load i32, ptr %q, align 4
  %yz = zext i32 %y to i64
  %a = and i64 %yz, %xz
  %r = and i64 %a, 255
  ret i64 %r
}

define i64 @multiple_load_or(ptr %p, ptr %q) {
; CHECK-SD-LE-LABEL: multiple_load_or:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldrh w8, [x0]
; CHECK-SD-LE-NEXT:    ldr w9, [x1]
; CHECK-SD-LE-NEXT:    orr w8, w9, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: multiple_load_or:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldrh w8, [x0]
; CHECK-SD-BE-NEXT:    ldr w9, [x1]
; CHECK-SD-BE-NEXT:    orr w8, w9, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: multiple_load_or:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldrh w8, [x0]
; CHECK-GI-LE-NEXT:    ldr w9, [x1]
; CHECK-GI-LE-NEXT:    orr x8, x9, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: multiple_load_or:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldrh w8, [x0]
; CHECK-GI-BE-NEXT:    ldr w9, [x1]
; CHECK-GI-BE-NEXT:    orr x8, x9, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xff
; CHECK-GI-BE-NEXT:    ret
  %x = load i16, ptr %p, align 4
  %xz = zext i16 %x to i64
  %y = load i32, ptr %q, align 4
  %yz = zext i32 %y to i64
  %a = or i64 %yz, %xz
  %r = and i64 %a, 255
  ret i64 %r
}

define i64 @load32_and16_zexty(ptr %p, i32 %y) {
; CHECK-SD-LE-LABEL: load32_and16_zexty:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_zexty:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    orr w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_zexty:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    mov w9, w1
; CHECK-GI-LE-NEXT:    orr x8, x9, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_zexty:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ldr w8, [x0]
; CHECK-GI-BE-NEXT:    mov w9, w1
; CHECK-GI-BE-NEXT:    orr x8, x9, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %yz = zext i32 %y to i64
  %a = or i64 %yz, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define i64 @load32_and16_sexty(ptr %p, i32 %y) {
; CHECK-SD-LE-LABEL: load32_and16_sexty:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w1, w8
; CHECK-SD-LE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load32_and16_sexty:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ldr w8, [x0]
; CHECK-SD-BE-NEXT:    orr w8, w1, w8
; CHECK-SD-BE-NEXT:    and x0, x8, #0xffff
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load32_and16_sexty:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    sxtw x9, w1
; CHECK-GI-LE-NEXT:    orr x8, x9, x8
; CHECK-GI-LE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load32_and16_sexty:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    // kill: def $w1 killed $w1 def $x1
; CHECK-GI-BE-NEXT:    ldr w8, [x0]
; CHECK-GI-BE-NEXT:    sxtw x9, w1
; CHECK-GI-BE-NEXT:    orr x8, x9, x8
; CHECK-GI-BE-NEXT:    and x0, x8, #0xffff
; CHECK-GI-BE-NEXT:    ret
  %x = load i32, ptr %p, align 4
  %xz = zext i32 %x to i64
  %yz = sext i32 %y to i64
  %a = or i64 %yz, %xz
  %r = and i64 %a, 65535
  ret i64 %r
}

define zeroext i1 @bigger(ptr nocapture readonly %c, ptr nocapture readonly %e, i64 %d, i64 %p1) {
; CHECK-SD-LE-LABEL: bigger:
; CHECK-SD-LE:       // %bb.0: // %entry
; CHECK-SD-LE-NEXT:    ldrb w8, [x1, x2]
; CHECK-SD-LE-NEXT:    ldrb w9, [x0, x2]
; CHECK-SD-LE-NEXT:    and w10, w3, #0x7
; CHECK-SD-LE-NEXT:    mov w11, #8 // =0x8
; CHECK-SD-LE-NEXT:    sub w10, w11, w10
; CHECK-SD-LE-NEXT:    eor w8, w8, w9
; CHECK-SD-LE-NEXT:    mov w9, #5 // =0x5
; CHECK-SD-LE-NEXT:    lsr w8, w8, w10
; CHECK-SD-LE-NEXT:    tst w8, w9
; CHECK-SD-LE-NEXT:    cset w0, eq
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: bigger:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    ldrb w8, [x1, x2]
; CHECK-SD-BE-NEXT:    ldrb w9, [x0, x2]
; CHECK-SD-BE-NEXT:    and w10, w3, #0x7
; CHECK-SD-BE-NEXT:    mov w11, #8 // =0x8
; CHECK-SD-BE-NEXT:    sub w10, w11, w10
; CHECK-SD-BE-NEXT:    eor w8, w8, w9
; CHECK-SD-BE-NEXT:    mov w9, #5 // =0x5
; CHECK-SD-BE-NEXT:    lsr w8, w8, w10
; CHECK-SD-BE-NEXT:    tst w8, w9
; CHECK-SD-BE-NEXT:    cset w0, eq
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: bigger:
; CHECK-GI-LE:       // %bb.0: // %entry
; CHECK-GI-LE-NEXT:    mov w8, #8 // =0x8
; CHECK-GI-LE-NEXT:    and w9, w3, #0x7
; CHECK-GI-LE-NEXT:    ldrb w10, [x0, x2]
; CHECK-GI-LE-NEXT:    sub w8, w8, w9
; CHECK-GI-LE-NEXT:    mov w9, #5 // =0x5
; CHECK-GI-LE-NEXT:    ldrb w11, [x1, x2]
; CHECK-GI-LE-NEXT:    lsl w8, w9, w8
; CHECK-GI-LE-NEXT:    eor w9, w11, w10
; CHECK-GI-LE-NEXT:    and w8, w9, w8
; CHECK-GI-LE-NEXT:    tst w8, #0xff
; CHECK-GI-LE-NEXT:    cset w0, eq
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: bigger:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov w8, #8 // =0x8
; CHECK-GI-BE-NEXT:    and w9, w3, #0x7
; CHECK-GI-BE-NEXT:    ldrb w10, [x0, x2]
; CHECK-GI-BE-NEXT:    sub w8, w8, w9
; CHECK-GI-BE-NEXT:    mov w9, #5 // =0x5
; CHECK-GI-BE-NEXT:    ldrb w11, [x1, x2]
; CHECK-GI-BE-NEXT:    lsl w8, w9, w8
; CHECK-GI-BE-NEXT:    eor w9, w11, w10
; CHECK-GI-BE-NEXT:    and w8, w9, w8
; CHECK-GI-BE-NEXT:    tst w8, #0xff
; CHECK-GI-BE-NEXT:    cset w0, eq
; CHECK-GI-BE-NEXT:    ret
entry:
  %0 = trunc i64 %p1 to i16
  %1 = and i16 %0, 7
  %sh_prom = sub nuw nsw i16 8, %1
  %shl = shl nuw nsw i16 5, %sh_prom
  %arrayidx = getelementptr inbounds i8, ptr %c, i64 %d
  %2 = load i8, ptr %arrayidx, align 1
  %3 = and i16 %shl, 255
  %conv2 = zext i16 %3 to i32
  %arrayidx3 = getelementptr inbounds i8, ptr %e, i64 %d
  %4 = load i8, ptr %arrayidx3, align 1
  %5 = xor i8 %4, %2
  %6 = zext i8 %5 to i32
  %7 = and i32 %6, %conv2
  %cmp.not = icmp eq i32 %7, 0
  ret i1 %cmp.not
}
