; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64-apple-ios -mattr=+sve -o - %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be-unknown-linux -mattr=+sve -o - %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc -mtriple=arm64-apple-ios -global-isel -mattr=+sve -o - %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc -mtriple=aarch64_be-unknown-linux -global-isel -mattr=+sve -o - %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE

define void @zext_of_concat(ptr %a, ptr %b, ptr %c, ptr %d) nounwind {
; CHECK-SD-LE-LABEL: zext_of_concat:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr d0, [x0]
; CHECK-SD-LE-NEXT:    ldr d1, [x1]
; CHECK-SD-LE-NEXT:    add.2s v0, v0, v1
; CHECK-SD-LE-NEXT:    ldr q1, [x2]
; CHECK-SD-LE-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-LE-NEXT:    add.4s v0, v0, v1
; CHECK-SD-LE-NEXT:    str q0, [x2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_of_concat:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-SD-BE-NEXT:    ld1 { v1.2s }, [x1]
; CHECK-SD-BE-NEXT:    add v0.2s, v0.2s, v1.2s
; CHECK-SD-BE-NEXT:    movi v1.2d, #0000000000000000
; CHECK-SD-BE-NEXT:    zip1 v0.4s, v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    trn2 v0.4s, v0.4s, v1.4s
; CHECK-SD-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-SD-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: zext_of_concat:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr d0, [x0]
; CHECK-GI-LE-NEXT:    ldr d1, [x1]
; CHECK-GI-LE-NEXT:    movi.2d v3, #0000000000000000
; CHECK-GI-LE-NEXT:  Lloh0:
; CHECK-GI-LE-NEXT:    adrp x8, lCPI0_0@PAGE
; CHECK-GI-LE-NEXT:    add.2s v2, v0, v1
; CHECK-GI-LE-NEXT:  Lloh1:
; CHECK-GI-LE-NEXT:    ldr q0, [x8, lCPI0_0@PAGEOFF]
; CHECK-GI-LE-NEXT:    ldr q1, [x2]
; CHECK-GI-LE-NEXT:    tbl.16b v0, { v2, v3 }, v0
; CHECK-GI-LE-NEXT:    add.4s v0, v0, v1
; CHECK-GI-LE-NEXT:    str q0, [x2]
; CHECK-GI-LE-NEXT:    ret
; CHECK-GI-LE-NEXT:    .loh AdrpLdr Lloh0, Lloh1
;
; CHECK-GI-BE-LABEL: zext_of_concat:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-GI-BE-NEXT:    ld1 { v1.2s }, [x1]
; CHECK-GI-BE-NEXT:    movi v3.2d, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-GI-BE-NEXT:    add v2.2s, v0.2s, v1.2s
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-GI-BE-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-GI-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-GI-BE-NEXT:    ret
  %i0.a = load <2 x i32>, ptr %a
  %i0.b = load <2 x i32>, ptr %b
  %i0 = add <2 x i32> %i0.a, %i0.b
  %i1 = shufflevector <2 x i32> %i0, <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 undef, i32 undef>
  %i2 = shufflevector <4 x i32> %i1, <4 x i32> zeroinitializer, <4 x i32> <i32 0, i32 5, i32 1, i32 7>
  %i3 = load <4 x i32>, ptr %c
  %i4 = add <4 x i32> %i2, %i3
  store <4 x i32> %i4, ptr %c
  ret void
}

define void @zext_of_concat_extrause(ptr %a, ptr %b, ptr %c, ptr %d, ptr %e) nounwind {
; CHECK-SD-LE-LABEL: zext_of_concat_extrause:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr d0, [x1]
; CHECK-SD-LE-NEXT:    ldr d1, [x0]
; CHECK-SD-LE-NEXT:    add.2s v0, v1, v0
; CHECK-SD-LE-NEXT:    movi.2d v1, #0000000000000000
; CHECK-SD-LE-NEXT:    mov.d v0[1], v0[0]
; CHECK-SD-LE-NEXT:    zip1.4s v1, v0, v1
; CHECK-SD-LE-NEXT:    str q0, [x4]
; CHECK-SD-LE-NEXT:    ldr q0, [x2]
; CHECK-SD-LE-NEXT:    add.4s v0, v1, v0
; CHECK-SD-LE-NEXT:    str q0, [x2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_of_concat_extrause:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ld1 { v0.2s }, [x1]
; CHECK-SD-BE-NEXT:    ld1 { v1.2s }, [x0]
; CHECK-SD-BE-NEXT:    movi v2.2d, #0000000000000000
; CHECK-SD-BE-NEXT:    add v0.2s, v1.2s, v0.2s
; CHECK-SD-BE-NEXT:    mov v0.d[1], v0.d[0]
; CHECK-SD-BE-NEXT:    zip1 v1.4s, v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x4]
; CHECK-SD-BE-NEXT:    trn2 v0.4s, v1.4s, v2.4s
; CHECK-SD-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-SD-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: zext_of_concat_extrause:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr d0, [x0]
; CHECK-GI-LE-NEXT:    ldr d1, [x1]
; CHECK-GI-LE-NEXT:    movi.2d v3, #0000000000000000
; CHECK-GI-LE-NEXT:  Lloh2:
; CHECK-GI-LE-NEXT:    adrp x8, lCPI1_0@PAGE
; CHECK-GI-LE-NEXT:    add.2s v2, v0, v1
; CHECK-GI-LE-NEXT:  Lloh3:
; CHECK-GI-LE-NEXT:    ldr q0, [x8, lCPI1_0@PAGEOFF]
; CHECK-GI-LE-NEXT:    mov.d v2[1], v2[0]
; CHECK-GI-LE-NEXT:    tbl.16b v0, { v2, v3 }, v0
; CHECK-GI-LE-NEXT:    str q2, [x4]
; CHECK-GI-LE-NEXT:    ldr q1, [x2]
; CHECK-GI-LE-NEXT:    add.4s v0, v0, v1
; CHECK-GI-LE-NEXT:    str q0, [x2]
; CHECK-GI-LE-NEXT:    ret
; CHECK-GI-LE-NEXT:    .loh AdrpLdr Lloh2, Lloh3
;
; CHECK-GI-BE-LABEL: zext_of_concat_extrause:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-GI-BE-NEXT:    ld1 { v1.2s }, [x1]
; CHECK-GI-BE-NEXT:    movi v3.2d, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI1_0
; CHECK-GI-BE-NEXT:    add v2.2s, v0.2s, v1.2s
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI1_0]
; CHECK-GI-BE-NEXT:    mov v2.d[1], v2.d[0]
; CHECK-GI-BE-NEXT:    st1 { v2.4s }, [x4]
; CHECK-GI-BE-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-GI-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-GI-BE-NEXT:    ret
  %i0.a = load <2 x i32>, ptr %a
  %i0.b = load <2 x i32>, ptr %b
  %i0 = add <2 x i32> %i0.a, %i0.b
  %i1 = shufflevector <2 x i32> %i0, <2 x i32> %i0, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  store <4 x i32> %i1, ptr %e
  %i2 = shufflevector <4 x i32> %i1, <4 x i32> zeroinitializer, <4 x i32> <i32 0, i32 5, i32 1, i32 7>
  %i3 = load <4 x i32>, ptr %c
  %i4 = add <4 x i32> %i2, %i3
  store <4 x i32> %i4, ptr %c
  ret void
}

define void @aext_of_concat(ptr %a, ptr %b, ptr %c, ptr %d) nounwind {
; CHECK-SD-LE-LABEL: aext_of_concat:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr d0, [x0]
; CHECK-SD-LE-NEXT:    ldr d1, [x1]
; CHECK-SD-LE-NEXT:    add.2s v0, v0, v1
; CHECK-SD-LE-NEXT:    ldr q1, [x2]
; CHECK-SD-LE-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-LE-NEXT:    add.4s v0, v0, v1
; CHECK-SD-LE-NEXT:    str q0, [x2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: aext_of_concat:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-BE-NEXT:    ld1 { v1.2s }, [x1]
; CHECK-BE-NEXT:    add v0.2s, v0.2s, v1.2s
; CHECK-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-BE-NEXT:    zip1 v0.4s, v0.4s, v0.4s
; CHECK-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: aext_of_concat:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr d0, [x0]
; CHECK-GI-LE-NEXT:    ldr d1, [x1]
; CHECK-GI-LE-NEXT:    add.2s v0, v0, v1
; CHECK-GI-LE-NEXT:    ldr q1, [x2]
; CHECK-GI-LE-NEXT:    zip1.4s v0, v0, v0
; CHECK-GI-LE-NEXT:    add.4s v0, v0, v1
; CHECK-GI-LE-NEXT:    str q0, [x2]
; CHECK-GI-LE-NEXT:    ret
  %i0.a = load <2 x i32>, ptr %a
  %i0.b = load <2 x i32>, ptr %b
  %i0 = add <2 x i32> %i0.a, %i0.b
  %i1 = shufflevector <2 x i32> %i0, <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 undef, i32 undef>
  %i2 = shufflevector <4 x i32> %i1, <4 x i32> poison, <4 x i32> <i32 0, i32 undef, i32 1, i32 undef>
  %i3 = load <4 x i32>, ptr %c
  %i4 = add <4 x i32> %i2, %i3
  store <4 x i32> %i4, ptr %c
  ret void
}

define void @aext_of_concat_extrause(ptr %a, ptr %b, ptr %c, ptr %d, ptr %e) nounwind {
; CHECK-SD-LE-LABEL: aext_of_concat_extrause:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr d0, [x1]
; CHECK-SD-LE-NEXT:    ldr d1, [x0]
; CHECK-SD-LE-NEXT:    add.2s v0, v1, v0
; CHECK-SD-LE-NEXT:    mov.16b v1, v0
; CHECK-SD-LE-NEXT:    mov.d v1[1], v0[0]
; CHECK-SD-LE-NEXT:    zip1.4s v0, v0, v0
; CHECK-SD-LE-NEXT:    str q1, [x4]
; CHECK-SD-LE-NEXT:    ldr q1, [x2]
; CHECK-SD-LE-NEXT:    add.4s v0, v0, v1
; CHECK-SD-LE-NEXT:    str q0, [x2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: aext_of_concat_extrause:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ld1 { v0.2s }, [x1]
; CHECK-SD-BE-NEXT:    ld1 { v1.2s }, [x0]
; CHECK-SD-BE-NEXT:    add v0.2s, v1.2s, v0.2s
; CHECK-SD-BE-NEXT:    mov v1.16b, v0.16b
; CHECK-SD-BE-NEXT:    mov v1.d[1], v0.d[0]
; CHECK-SD-BE-NEXT:    zip1 v0.4s, v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x4]
; CHECK-SD-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-SD-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: aext_of_concat_extrause:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr d0, [x0]
; CHECK-GI-LE-NEXT:    ldr d1, [x1]
; CHECK-GI-LE-NEXT:    add.2s v0, v0, v1
; CHECK-GI-LE-NEXT:    mov.d v0[1], v0[0]
; CHECK-GI-LE-NEXT:    zip1.4s v1, v0, v0
; CHECK-GI-LE-NEXT:    str q0, [x4]
; CHECK-GI-LE-NEXT:    ldr q0, [x2]
; CHECK-GI-LE-NEXT:    add.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    str q0, [x2]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: aext_of_concat_extrause:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-GI-BE-NEXT:    ld1 { v1.2s }, [x1]
; CHECK-GI-BE-NEXT:    add v0.2s, v0.2s, v1.2s
; CHECK-GI-BE-NEXT:    mov v0.d[1], v0.d[0]
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x4]
; CHECK-GI-BE-NEXT:    zip1 v0.4s, v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x2]
; CHECK-GI-BE-NEXT:    add v0.4s, v0.4s, v1.4s
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x2]
; CHECK-GI-BE-NEXT:    ret
  %i0.a = load <2 x i32>, ptr %a
  %i0.b = load <2 x i32>, ptr %b
  %i0 = add <2 x i32> %i0.a, %i0.b
  %i1 = shufflevector <2 x i32> %i0, <2 x i32> %i0, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  store <4 x i32> %i1, ptr %e
  %i2 = shufflevector <4 x i32> %i1, <4 x i32> zeroinitializer, <4 x i32> <i32 0, i32 undef, i32 1, i32 undef>
  %i3 = load <4 x i32>, ptr %c
  %i4 = add <4 x i32> %i2, %i3
  store <4 x i32> %i4, ptr %c
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-LE: {{.*}}
