; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64_be-- < %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc -mtriple=aarch64--    < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be-- -global-isel < %s | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE
; RUN: llc -mtriple=aarch64-- -global-isel   < %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE

define i32 @trunc_i64_to_i32_le(i64 %x) {
; CHECK-SD-BE-LABEL: trunc_i64_to_i32_le:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    lsr x0, x0, #32
; CHECK-SD-BE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i64_to_i32_le:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i64_to_i32_le:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov d0, x0
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    fmov w0, s0
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i64_to_i32_le:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov d0, x0
; CHECK-GI-LE-NEXT:    fmov w0, s0
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <2 x i64> undef, i64 %x, i32 0
  %bc = bitcast <2 x i64> %ins to <4 x i32>
  %ext = extractelement <4 x i32> %bc, i32 0
  ret i32 %ext
}

define i32 @trunc_i64_to_i32_be(i64 %x) {
; CHECK-SD-BE-LABEL: trunc_i64_to_i32_be:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i64_to_i32_be:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    lsr x0, x0, #32
; CHECK-SD-LE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i64_to_i32_be:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov d0, x0
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    mov s0, v0.s[1]
; CHECK-GI-BE-NEXT:    fmov w0, s0
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i64_to_i32_be:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov d0, x0
; CHECK-GI-LE-NEXT:    mov s0, v0.s[1]
; CHECK-GI-LE-NEXT:    fmov w0, s0
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <2 x i64> undef, i64 %x, i32 0
  %bc = bitcast <2 x i64> %ins to <4 x i32>
  %ext = extractelement <4 x i32> %bc, i32 1
  ret i32 %ext
}

define i16 @trunc_i64_to_i16_le(i64 %x) {
; CHECK-SD-BE-LABEL: trunc_i64_to_i16_le:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    lsr x0, x0, #48
; CHECK-SD-BE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i64_to_i16_le:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i64_to_i16_le:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov d0, x0
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    umov w0, v0.h[0]
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i64_to_i16_le:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov d0, x0
; CHECK-GI-LE-NEXT:    umov w0, v0.h[0]
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <2 x i64> undef, i64 %x, i32 0
  %bc = bitcast <2 x i64> %ins to <8 x i16>
  %ext = extractelement <8 x i16> %bc, i32 0
  ret i16 %ext
}

define i16 @trunc_i64_to_i16_be(i64 %x) {
; CHECK-SD-BE-LABEL: trunc_i64_to_i16_be:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i64_to_i16_be:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    lsr x0, x0, #48
; CHECK-SD-LE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i64_to_i16_be:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov d0, x0
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    umov w0, v0.h[3]
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i64_to_i16_be:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov d0, x0
; CHECK-GI-LE-NEXT:    umov w0, v0.h[3]
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <2 x i64> undef, i64 %x, i32 0
  %bc = bitcast <2 x i64> %ins to <8 x i16>
  %ext = extractelement <8 x i16> %bc, i32 3
  ret i16 %ext
}

define i8 @trunc_i32_to_i8_le(i32 %x) {
; CHECK-SD-BE-LABEL: trunc_i32_to_i8_le:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    lsr w0, w0, #24
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i32_to_i8_le:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i32_to_i8_le:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov s0, w0
; CHECK-GI-BE-NEXT:    rev32 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    umov w0, v0.b[0]
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i32_to_i8_le:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov s0, w0
; CHECK-GI-LE-NEXT:    umov w0, v0.b[0]
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <4 x i32> undef, i32 %x, i32 0
  %bc = bitcast <4 x i32> %ins to <16 x i8>
  %ext = extractelement <16 x i8> %bc, i32 0
  ret i8 %ext
}

define i8 @trunc_i32_to_i8_be(i32 %x) {
; CHECK-SD-BE-LABEL: trunc_i32_to_i8_be:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i32_to_i8_be:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    lsr w0, w0, #24
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i32_to_i8_be:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov s0, w0
; CHECK-GI-BE-NEXT:    rev32 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    umov w0, v0.b[3]
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i32_to_i8_be:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov s0, w0
; CHECK-GI-LE-NEXT:    umov w0, v0.b[3]
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <4 x i32> undef, i32 %x, i32 0
  %bc = bitcast <4 x i32> %ins to <16 x i8>
  %ext = extractelement <16 x i8> %bc, i32 3
  ret i8 %ext
}

; Weird type (non-power-of-2 vector) is ok.

define i8 @trunc_i64_to_i8_be(i64 %x) {
; CHECK-SD-BE-LABEL: trunc_i64_to_i8_be:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-SD-LE-LABEL: trunc_i64_to_i8_be:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    lsr x0, x0, #56
; CHECK-SD-LE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_i64_to_i8_be:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    fmov d0, x0
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    umov w0, v0.b[7]
; CHECK-GI-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_i64_to_i8_be:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    fmov d0, x0
; CHECK-GI-LE-NEXT:    umov w0, v0.b[7]
; CHECK-GI-LE-NEXT:    ret
  %ins = insertelement <3 x i64> undef, i64 %x, i32 0
  %bc = bitcast <3 x i64> %ins to <24 x i8>
  %ext = extractelement <24 x i8> %bc, i32 7
  ret i8 %ext
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-BE: {{.*}}
; CHECK-LE: {{.*}}
