; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -global-isel=0 -o - %s | FileCheck %s --check-prefixes CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be -global-isel=0 -o - %s | FileCheck %s --check-prefixes CHECK-BE,CHECK-SD-BE
; RUN: llc -mtriple=aarch64 -global-isel=1 -o - %s | FileCheck %s --check-prefixes CHECK-LE,CHECK-GI-LE
; RUN: llc -mtriple=aarch64_be -global-isel=1 -o - %s | FileCheck %s --check-prefixes CHECK-BE,CHECK-GI-BE


define i8 @test1(i32 %a, ptr %pa) {
; CHECK-SD-LE-LABEL: test1:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    str w0, [x1]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test1:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    mov w8, w0
; CHECK-SD-BE-NEXT:    lsr w0, w0, #24
; CHECK-SD-BE-NEXT:    str w8, [x1]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: test1:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    str w0, [x1]
; CHECK-GI-LE-NEXT:    and w0, w0, #0xff
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test1:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    str w0, [x1]
; CHECK-GI-BE-NEXT:    ldrb w0, [x1]
; CHECK-GI-BE-NEXT:    ret
  store i32 %a, ptr %pa
  %res = load i8, ptr %pa
  ret i8 %res
}

define i8 @test2(i32 %a, ptr %pa) {
; CHECK-LE-LABEL: test2:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    ubfx w0, w0, #8, #8
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: test2:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    ldrb w0, [x1, #1]
; CHECK-BE-NEXT:    ret
  %p8 = getelementptr i8, ptr %pa, i32 1
  store i32 %a, ptr %pa
  %res = load i8, ptr %p8
  ret i8 %res
}

define i8 @test3(i32 %a, ptr %pa) {
; CHECK-LE-LABEL: test3:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    ubfx w0, w0, #16, #8
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: test3:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    ldrb w0, [x1, #2]
; CHECK-BE-NEXT:    ret
  %p8 = getelementptr i8, ptr %pa, i32 2
  store i32 %a, ptr %pa
  %res = load i8, ptr %p8
  ret i8 %res
}

define i8 @test4(i32 %a, ptr %pa) {
; CHECK-LE-LABEL: test4:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    lsr w0, w0, #24
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test4:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str w0, [x1]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test4:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    str w0, [x1]
; CHECK-GI-BE-NEXT:    ldrb w0, [x1, #3]
; CHECK-GI-BE-NEXT:    ret
  %p8 = getelementptr i8, ptr %pa, i32 3
  store i32 %a, ptr %pa
  %res = load i8, ptr %p8
  ret i8 %res
}

define i32 @load_i16_store_i8(ptr %p, ptr %q) {
; CHECK-SD-LE-LABEL: load_i16_store_i8:
; CHECK-SD-LE:       // %bb.0: // %entry
; CHECK-SD-LE-NEXT:    ldrb w8, [x0]
; CHECK-SD-LE-NEXT:    mov w0, wzr
; CHECK-SD-LE-NEXT:    strb w8, [x1]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: load_i16_store_i8:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    ldrb w8, [x0, #1]
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    strb w8, [x1]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_i16_store_i8:
; CHECK-GI-LE:       // %bb.0: // %entry
; CHECK-GI-LE-NEXT:    ldrh w8, [x0]
; CHECK-GI-LE-NEXT:    mov w0, wzr
; CHECK-GI-LE-NEXT:    strb w8, [x1]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: load_i16_store_i8:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    ldrh w8, [x0]
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    strb w8, [x1]
; CHECK-GI-BE-NEXT:    ret
entry:
  %l = load i16, ptr %p, align 4
  %tr = trunc i16 %l to i8
  store i8 %tr, ptr %q, align 1
  ret i32 0
}

define i32 @load_i16_store_i8_freeze(ptr %p, ptr %q) {
; CHECK-LE-LABEL: load_i16_store_i8_freeze:
; CHECK-LE:       // %bb.0: // %entry
; CHECK-LE-NEXT:    ldrh w8, [x0]
; CHECK-LE-NEXT:    mov w0, wzr
; CHECK-LE-NEXT:    strb w8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_i16_store_i8_freeze:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    mov w0, wzr
; CHECK-BE-NEXT:    strb w8, [x1]
; CHECK-BE-NEXT:    ret
entry:
  %l = load i16, ptr %p, align 4
  %fr = freeze i16 %l
  %tr = trunc i16 %fr to i8
  store i8 %tr, ptr %q, align 1
  ret i32 0
}
