; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64--    | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc < %s -mtriple=aarch64_be-- | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc < %s -mtriple=aarch64-- -global-isel    | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc < %s -mtriple=aarch64_be-- -global-isel | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE

define void @le_i16_to_i8(i16 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i16_to_i8:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    strh w0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i16_to_i8:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev w8, w0
; CHECK-BE-NEXT:    lsr w8, w8, #16
; CHECK-BE-NEXT:    strh w8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i16 %x, 8
  %t0 = trunc i16 %x to i8
  %t1 = trunc i16 %sh1 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  store i8 %t0, ptr %p0, align 1
  store i8 %t1, ptr %p1, align 1
  ret void
}

define void @le_i16_to_i8_order(i16 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i16_to_i8_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    strh w0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i16_to_i8_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev w8, w0
; CHECK-BE-NEXT:    lsr w8, w8, #16
; CHECK-BE-NEXT:    strh w8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i16 %x, 8
  %t0 = trunc i16 %x to i8
  %t1 = trunc i16 %sh1 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  store i8 %t1, ptr %p1, align 1
  store i8 %t0, ptr %p0, align 1
  ret void
}

define void @be_i16_to_i8_offset(i16 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i16_to_i8_offset:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    rev w8, w0
; CHECK-LE-NEXT:    lsr w8, w8, #16
; CHECK-LE-NEXT:    sturh w8, [x1, #11]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i16_to_i8_offset:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sturh w0, [x1, #11]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i16 %x, 8
  %t0 = trunc i16 %x to i8
  %t1 = trunc i16 %sh1 to i8
  %p11 = getelementptr inbounds i8, ptr %p0, i64 11
  %p12 = getelementptr inbounds i8, ptr %p0, i64 12
  store i8 %t0, ptr %p12, align 1
  store i8 %t1, ptr %p11, align 1
  ret void
}

define void @be_i16_to_i8_order(i16 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i16_to_i8_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    rev w8, w0
; CHECK-LE-NEXT:    lsr w8, w8, #16
; CHECK-LE-NEXT:    strh w8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i16_to_i8_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    strh w0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i16 %x, 8
  %t0 = trunc i16 %x to i8
  %t1 = trunc i16 %sh1 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  store i8 %t1, ptr %p0, align 1
  store i8 %t0, ptr %p1, align 1
  ret void
}

define void @le_i32_to_i8(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i32_to_i8:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i32_to_i8:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev w8, w0
; CHECK-BE-NEXT:    str w8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 8
  %sh2 = lshr i32 %x, 16
  %sh3 = lshr i32 %x, 24
  %t0 = trunc i32 %x to i8
  %t1 = trunc i32 %sh1 to i8
  %t2 = trunc i32 %sh2 to i8
  %t3 = trunc i32 %sh3 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  store i8 %t0, ptr %p0, align 1
  store i8 %t1, ptr %p1, align 1
  store i8 %t2, ptr %p2, align 1
  store i8 %t3, ptr %p3, align 1
  ret void
}

define void @le_i32_to_i8_order(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i32_to_i8_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i32_to_i8_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev w8, w0
; CHECK-BE-NEXT:    str w8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 8
  %sh2 = lshr i32 %x, 16
  %sh3 = lshr i32 %x, 24
  %t0 = trunc i32 %x to i8
  %t1 = trunc i32 %sh1 to i8
  %t2 = trunc i32 %sh2 to i8
  %t3 = trunc i32 %sh3 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  store i8 %t3, ptr %p3, align 1
  store i8 %t1, ptr %p1, align 1
  store i8 %t0, ptr %p0, align 1
  store i8 %t2, ptr %p2, align 1
  ret void
}

define void @be_i32_to_i8(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i32_to_i8:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    rev w8, w0
; CHECK-LE-NEXT:    str w8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i32_to_i8:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 8
  %sh2 = lshr i32 %x, 16
  %sh3 = lshr i32 %x, 24
  %t0 = trunc i32 %x to i8
  %t1 = trunc i32 %sh1 to i8
  %t2 = trunc i32 %sh2 to i8
  %t3 = trunc i32 %sh3 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  store i8 %t0, ptr %p3, align 1
  store i8 %t1, ptr %p2, align 1
  store i8 %t2, ptr %p1, align 1
  store i8 %t3, ptr %p0, align 1
  ret void
}

define void @be_i32_to_i8_order(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i32_to_i8_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    rev w8, w0
; CHECK-LE-NEXT:    str w8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i32_to_i8_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 8
  %sh2 = lshr i32 %x, 16
  %sh3 = lshr i32 %x, 24
  %t0 = trunc i32 %x to i8
  %t1 = trunc i32 %sh1 to i8
  %t2 = trunc i32 %sh2 to i8
  %t3 = trunc i32 %sh3 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  store i8 %t3, ptr %p0, align 1
  store i8 %t2, ptr %p1, align 1
  store i8 %t0, ptr %p3, align 1
  store i8 %t1, ptr %p2, align 1
  ret void
}

define void @le_i32_to_i16(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i32_to_i16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i32_to_i16:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ror w8, w0, #16
; CHECK-BE-NEXT:    str w8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 16
  %t0 = trunc i32 %x to i16
  %t1 = trunc i32 %sh1 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  store i16 %t0, ptr %p0, align 2
  store i16 %t1, ptr %p1, align 2
  ret void
}

define void @le_i32_to_i16_order(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i32_to_i16_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i32_to_i16_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ror w8, w0, #16
; CHECK-BE-NEXT:    str w8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 16
  %t0 = trunc i32 %x to i16
  %t1 = trunc i32 %sh1 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  store i16 %t1, ptr %p1, align 2
  store i16 %t0, ptr %p0, align 2
  ret void
}

define void @be_i32_to_i16(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i32_to_i16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ror w8, w0, #16
; CHECK-LE-NEXT:    str w8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i32_to_i16:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 16
  %t0 = trunc i32 %x to i16
  %t1 = trunc i32 %sh1 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  store i16 %t0, ptr %p1, align 2
  store i16 %t1, ptr %p0, align 2
  ret void
}

define void @be_i32_to_i16_order(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i32_to_i16_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ror w8, w0, #16
; CHECK-LE-NEXT:    str w8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i32_to_i16_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 16
  %t0 = trunc i32 %x to i16
  %t1 = trunc i32 %sh1 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  store i16 %t1, ptr %p0, align 2
  store i16 %t0, ptr %p1, align 2
  ret void
}

define void @le_i64_to_i8(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i64_to_i8:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i64_to_i8:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev x8, x0
; CHECK-BE-NEXT:    str x8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 8
  %sh2 = lshr i64 %x, 16
  %sh3 = lshr i64 %x, 24
  %sh4 = lshr i64 %x, 32
  %sh5 = lshr i64 %x, 40
  %sh6 = lshr i64 %x, 48
  %sh7 = lshr i64 %x, 56
  %t0 = trunc i64 %x to i8
  %t1 = trunc i64 %sh1 to i8
  %t2 = trunc i64 %sh2 to i8
  %t3 = trunc i64 %sh3 to i8
  %t4 = trunc i64 %sh4 to i8
  %t5 = trunc i64 %sh5 to i8
  %t6 = trunc i64 %sh6 to i8
  %t7 = trunc i64 %sh7 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  %p4 = getelementptr inbounds i8, ptr %p0, i64 4
  %p5 = getelementptr inbounds i8, ptr %p0, i64 5
  %p6 = getelementptr inbounds i8, ptr %p0, i64 6
  %p7 = getelementptr inbounds i8, ptr %p0, i64 7
  store i8 %t0, ptr %p0, align 1
  store i8 %t1, ptr %p1, align 1
  store i8 %t2, ptr %p2, align 1
  store i8 %t3, ptr %p3, align 1
  store i8 %t4, ptr %p4, align 1
  store i8 %t5, ptr %p5, align 1
  store i8 %t6, ptr %p6, align 1
  store i8 %t7, ptr %p7, align 1
  ret void
}

define void @le_i64_to_i8_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i64_to_i8_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i64_to_i8_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev x8, x0
; CHECK-BE-NEXT:    str x8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 8
  %sh2 = lshr i64 %x, 16
  %sh3 = lshr i64 %x, 24
  %sh4 = lshr i64 %x, 32
  %sh5 = lshr i64 %x, 40
  %sh6 = lshr i64 %x, 48
  %sh7 = lshr i64 %x, 56
  %t0 = trunc i64 %x to i8
  %t1 = trunc i64 %sh1 to i8
  %t2 = trunc i64 %sh2 to i8
  %t3 = trunc i64 %sh3 to i8
  %t4 = trunc i64 %sh4 to i8
  %t5 = trunc i64 %sh5 to i8
  %t6 = trunc i64 %sh6 to i8
  %t7 = trunc i64 %sh7 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  %p4 = getelementptr inbounds i8, ptr %p0, i64 4
  %p5 = getelementptr inbounds i8, ptr %p0, i64 5
  %p6 = getelementptr inbounds i8, ptr %p0, i64 6
  %p7 = getelementptr inbounds i8, ptr %p0, i64 7
  store i8 %t5, ptr %p5, align 1
  store i8 %t0, ptr %p0, align 1
  store i8 %t3, ptr %p3, align 1
  store i8 %t7, ptr %p7, align 1
  store i8 %t1, ptr %p1, align 1
  store i8 %t6, ptr %p6, align 1
  store i8 %t2, ptr %p2, align 1
  store i8 %t4, ptr %p4, align 1
  ret void
}

define void @be_i64_to_i8(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i64_to_i8:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    rev x8, x0
; CHECK-LE-NEXT:    str x8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i64_to_i8:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str x0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 8
  %sh2 = lshr i64 %x, 16
  %sh3 = lshr i64 %x, 24
  %sh4 = lshr i64 %x, 32
  %sh5 = lshr i64 %x, 40
  %sh6 = lshr i64 %x, 48
  %sh7 = lshr i64 %x, 56
  %t0 = trunc i64 %x to i8
  %t1 = trunc i64 %sh1 to i8
  %t2 = trunc i64 %sh2 to i8
  %t3 = trunc i64 %sh3 to i8
  %t4 = trunc i64 %sh4 to i8
  %t5 = trunc i64 %sh5 to i8
  %t6 = trunc i64 %sh6 to i8
  %t7 = trunc i64 %sh7 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  %p4 = getelementptr inbounds i8, ptr %p0, i64 4
  %p5 = getelementptr inbounds i8, ptr %p0, i64 5
  %p6 = getelementptr inbounds i8, ptr %p0, i64 6
  %p7 = getelementptr inbounds i8, ptr %p0, i64 7
  store i8 %t0, ptr %p7, align 1
  store i8 %t1, ptr %p6, align 1
  store i8 %t2, ptr %p5, align 1
  store i8 %t3, ptr %p4, align 1
  store i8 %t4, ptr %p3, align 1
  store i8 %t5, ptr %p2, align 1
  store i8 %t6, ptr %p1, align 1
  store i8 %t7, ptr %p0, align 1
  ret void
}

define void @be_i64_to_i8_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i64_to_i8_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    rev x8, x0
; CHECK-LE-NEXT:    str x8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i64_to_i8_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str x0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 8
  %sh2 = lshr i64 %x, 16
  %sh3 = lshr i64 %x, 24
  %sh4 = lshr i64 %x, 32
  %sh5 = lshr i64 %x, 40
  %sh6 = lshr i64 %x, 48
  %sh7 = lshr i64 %x, 56
  %t0 = trunc i64 %x to i8
  %t1 = trunc i64 %sh1 to i8
  %t2 = trunc i64 %sh2 to i8
  %t3 = trunc i64 %sh3 to i8
  %t4 = trunc i64 %sh4 to i8
  %t5 = trunc i64 %sh5 to i8
  %t6 = trunc i64 %sh6 to i8
  %t7 = trunc i64 %sh7 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  %p4 = getelementptr inbounds i8, ptr %p0, i64 4
  %p5 = getelementptr inbounds i8, ptr %p0, i64 5
  %p6 = getelementptr inbounds i8, ptr %p0, i64 6
  %p7 = getelementptr inbounds i8, ptr %p0, i64 7
  store i8 %t7, ptr %p0, align 1
  store i8 %t6, ptr %p1, align 1
  store i8 %t5, ptr %p2, align 1
  store i8 %t4, ptr %p3, align 1
  store i8 %t3, ptr %p4, align 1
  store i8 %t2, ptr %p5, align 1
  store i8 %t1, ptr %p6, align 1
  store i8 %t0, ptr %p7, align 1
  ret void
}

define void @le_i64_to_i16(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i64_to_i16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: le_i64_to_i16:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    lsr x8, x0, #16
; CHECK-SD-BE-NEXT:    lsr x9, x0, #32
; CHECK-SD-BE-NEXT:    lsr x10, x0, #48
; CHECK-SD-BE-NEXT:    strh w0, [x1]
; CHECK-SD-BE-NEXT:    strh w8, [x1, #2]
; CHECK-SD-BE-NEXT:    strh w9, [x1, #4]
; CHECK-SD-BE-NEXT:    strh w10, [x1, #6]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: le_i64_to_i16:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ror w8, w0, #16
; CHECK-GI-BE-NEXT:    lsr x9, x0, #32
; CHECK-GI-BE-NEXT:    lsr x10, x0, #48
; CHECK-GI-BE-NEXT:    str w8, [x1]
; CHECK-GI-BE-NEXT:    strh w9, [x1, #4]
; CHECK-GI-BE-NEXT:    strh w10, [x1, #6]
; CHECK-GI-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 16
  %sh2 = lshr i64 %x, 32
  %sh3 = lshr i64 %x, 48
  %t0 = trunc i64 %x to i16
  %t1 = trunc i64 %sh1 to i16
  %t2 = trunc i64 %sh2 to i16
  %t3 = trunc i64 %sh3 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  %p2 = getelementptr inbounds i16, ptr %p0, i64 2
  %p3 = getelementptr inbounds i16, ptr %p0, i64 3
  store i16 %t0, ptr %p0, align 2
  store i16 %t1, ptr %p1, align 2
  store i16 %t2, ptr %p2, align 2
  store i16 %t3, ptr %p3, align 2
  ret void
}

define void @le_i64_to_i16_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i64_to_i16_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i64_to_i16_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr x8, x0, #16
; CHECK-BE-NEXT:    lsr x9, x0, #48
; CHECK-BE-NEXT:    lsr x10, x0, #32
; CHECK-BE-NEXT:    strh w0, [x1]
; CHECK-BE-NEXT:    strh w8, [x1, #2]
; CHECK-BE-NEXT:    strh w9, [x1, #6]
; CHECK-BE-NEXT:    strh w10, [x1, #4]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 16
  %sh2 = lshr i64 %x, 32
  %sh3 = lshr i64 %x, 48
  %t0 = trunc i64 %x to i16
  %t1 = trunc i64 %sh1 to i16
  %t2 = trunc i64 %sh2 to i16
  %t3 = trunc i64 %sh3 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  %p2 = getelementptr inbounds i16, ptr %p0, i64 2
  %p3 = getelementptr inbounds i16, ptr %p0, i64 3
  store i16 %t1, ptr %p1, align 2
  store i16 %t3, ptr %p3, align 2
  store i16 %t0, ptr %p0, align 2
  store i16 %t2, ptr %p2, align 2
  ret void
}

define void @be_i64_to_i16(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i64_to_i16:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ror w8, w0, #16
; CHECK-LE-NEXT:    lsr x9, x0, #32
; CHECK-LE-NEXT:    lsr x10, x0, #48
; CHECK-LE-NEXT:    str w8, [x1, #4]
; CHECK-LE-NEXT:    strh w9, [x1, #2]
; CHECK-LE-NEXT:    strh w10, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i64_to_i16:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str x0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 16
  %sh2 = lshr i64 %x, 32
  %sh3 = lshr i64 %x, 48
  %t0 = trunc i64 %x to i16
  %t1 = trunc i64 %sh1 to i16
  %t2 = trunc i64 %sh2 to i16
  %t3 = trunc i64 %sh3 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  %p2 = getelementptr inbounds i16, ptr %p0, i64 2
  %p3 = getelementptr inbounds i16, ptr %p0, i64 3
  store i16 %t0, ptr %p3, align 2
  store i16 %t1, ptr %p2, align 2
  store i16 %t2, ptr %p1, align 2
  store i16 %t3, ptr %p0, align 2
  ret void
}

define void @be_i64_to_i16_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i64_to_i16_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr x8, x0, #48
; CHECK-LE-NEXT:    lsr x9, x0, #32
; CHECK-LE-NEXT:    lsr x10, x0, #16
; CHECK-LE-NEXT:    strh w0, [x1, #6]
; CHECK-LE-NEXT:    strh w8, [x1]
; CHECK-LE-NEXT:    strh w9, [x1, #2]
; CHECK-LE-NEXT:    strh w10, [x1, #4]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i64_to_i16_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str x0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 16
  %sh2 = lshr i64 %x, 32
  %sh3 = lshr i64 %x, 48
  %t0 = trunc i64 %x to i16
  %t1 = trunc i64 %sh1 to i16
  %t2 = trunc i64 %sh2 to i16
  %t3 = trunc i64 %sh3 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  %p2 = getelementptr inbounds i16, ptr %p0, i64 2
  %p3 = getelementptr inbounds i16, ptr %p0, i64 3
  store i16 %t0, ptr %p3, align 2
  store i16 %t3, ptr %p0, align 2
  store i16 %t2, ptr %p1, align 2
  store i16 %t1, ptr %p2, align 2
  ret void
}

define void @le_i64_to_i32(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i64_to_i32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i64_to_i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ror x8, x0, #32
; CHECK-BE-NEXT:    str x8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 32
  %t0 = trunc i64 %x to i32
  %t1 = trunc i64 %sh1 to i32
  %p1 = getelementptr inbounds i32, ptr %p0, i64 1
  store i32 %t0, ptr %p0, align 4
  store i32 %t1, ptr %p1, align 4
  ret void
}

define void @le_i64_to_i32_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: le_i64_to_i32_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str x0, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: le_i64_to_i32_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ror x8, x0, #32
; CHECK-BE-NEXT:    str x8, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 32
  %t0 = trunc i64 %x to i32
  %t1 = trunc i64 %sh1 to i32
  %p1 = getelementptr inbounds i32, ptr %p0, i64 1
  store i32 %t1, ptr %p1, align 4
  store i32 %t0, ptr %p0, align 4
  ret void
}

define void @be_i64_to_i32(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i64_to_i32:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ror x8, x0, #32
; CHECK-LE-NEXT:    str x8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i64_to_i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str x0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 32
  %t0 = trunc i64 %x to i32
  %t1 = trunc i64 %sh1 to i32
  %p1 = getelementptr inbounds i32, ptr %p0, i64 1
  store i32 %t0, ptr %p1, align 4
  store i32 %t1, ptr %p0, align 4
  ret void
}

define void @be_i64_to_i32_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: be_i64_to_i32_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    ror x8, x0, #32
; CHECK-LE-NEXT:    str x8, [x1]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: be_i64_to_i32_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str x0, [x1]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 32
  %t0 = trunc i64 %x to i32
  %t1 = trunc i64 %sh1 to i32
  %p1 = getelementptr inbounds i32, ptr %p0, i64 1
  store i32 %t1, ptr %p0, align 4
  store i32 %t0, ptr %p1, align 4
  ret void
}

; Negative test - not consecutive addresses

define void @i64_to_i32_wrong_addr(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: i64_to_i32_wrong_addr:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr x8, x0, #32
; CHECK-LE-NEXT:    str w0, [x1]
; CHECK-LE-NEXT:    str w8, [x1, #12]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: i64_to_i32_wrong_addr:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr x8, x0, #32
; CHECK-BE-NEXT:    str w0, [x1]
; CHECK-BE-NEXT:    str w8, [x1, #12]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 32
  %t0 = trunc i64 %x to i32
  %t1 = trunc i64 %sh1 to i32
  %p3 = getelementptr inbounds i32, ptr %p0, i64 3
  store i32 %t1, ptr %p3, align 4
  store i32 %t0, ptr %p0, align 4
  ret void
}

; Negative test - addresses don't line up with shift amounts

define void @i64_to_i16_wrong_order(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: i64_to_i16_wrong_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr x8, x0, #48
; CHECK-LE-NEXT:    lsr x9, x0, #16
; CHECK-LE-NEXT:    lsr x10, x0, #32
; CHECK-LE-NEXT:    strh w0, [x1]
; CHECK-LE-NEXT:    strh w8, [x1, #6]
; CHECK-LE-NEXT:    strh w9, [x1, #4]
; CHECK-LE-NEXT:    strh w10, [x1, #2]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: i64_to_i16_wrong_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr x8, x0, #48
; CHECK-BE-NEXT:    lsr x9, x0, #16
; CHECK-BE-NEXT:    lsr x10, x0, #32
; CHECK-BE-NEXT:    strh w0, [x1]
; CHECK-BE-NEXT:    strh w8, [x1, #6]
; CHECK-BE-NEXT:    strh w9, [x1, #4]
; CHECK-BE-NEXT:    strh w10, [x1, #2]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 16
  %sh2 = lshr i64 %x, 32
  %sh3 = lshr i64 %x, 48
  %t0 = trunc i64 %x to i16
  %t1 = trunc i64 %sh1 to i16
  %t2 = trunc i64 %sh2 to i16
  %t3 = trunc i64 %sh3 to i16
  %p1 = getelementptr inbounds i16, ptr %p0, i64 1
  %p2 = getelementptr inbounds i16, ptr %p0, i64 2
  %p3 = getelementptr inbounds i16, ptr %p0, i64 3
  store i16 %t3, ptr %p3, align 2
  store i16 %t1, ptr %p2, align 2
  store i16 %t2, ptr %p1, align 2
  store i16 %t0, ptr %p0, align 2
  ret void
}

; Negative test - no store of 't1'

define void @i32_to_i8_incomplete(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: i32_to_i8_incomplete:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr w8, w0, #16
; CHECK-LE-NEXT:    lsr w9, w0, #24
; CHECK-LE-NEXT:    strb w0, [x1]
; CHECK-LE-NEXT:    strb w8, [x1, #2]
; CHECK-LE-NEXT:    strb w9, [x1, #3]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: i32_to_i8_incomplete:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr w8, w0, #16
; CHECK-BE-NEXT:    lsr w9, w0, #24
; CHECK-BE-NEXT:    strb w0, [x1]
; CHECK-BE-NEXT:    strb w8, [x1, #2]
; CHECK-BE-NEXT:    strb w9, [x1, #3]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 8
  %sh2 = lshr i32 %x, 16
  %sh3 = lshr i32 %x, 24
  %t0 = trunc i32 %x to i8
  %t1 = trunc i32 %sh1 to i8
  %t2 = trunc i32 %sh2 to i8
  %t3 = trunc i32 %sh3 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  store i8 %t0, ptr %p0, align 1
  store i8 %t2, ptr %p2, align 1
  store i8 %t3, ptr %p3, align 1
  ret void
}

; Negative test - no store of 't3'

define void @i64_to_i8_incomplete(i64 %x, ptr %p0) {
; CHECK-LE-LABEL: i64_to_i8_incomplete:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr x8, x0, #56
; CHECK-LE-NEXT:    lsr x9, x0, #48
; CHECK-LE-NEXT:    lsr x10, x0, #40
; CHECK-LE-NEXT:    strb w0, [x1, #7]
; CHECK-LE-NEXT:    strb w8, [x1]
; CHECK-LE-NEXT:    lsr x8, x0, #32
; CHECK-LE-NEXT:    strb w9, [x1, #1]
; CHECK-LE-NEXT:    lsr x9, x0, #16
; CHECK-LE-NEXT:    strb w10, [x1, #2]
; CHECK-LE-NEXT:    lsr x10, x0, #8
; CHECK-LE-NEXT:    strb w8, [x1, #3]
; CHECK-LE-NEXT:    strb w9, [x1, #5]
; CHECK-LE-NEXT:    strb w10, [x1, #6]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: i64_to_i8_incomplete:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr x8, x0, #56
; CHECK-BE-NEXT:    lsr x9, x0, #48
; CHECK-BE-NEXT:    lsr x10, x0, #40
; CHECK-BE-NEXT:    strb w0, [x1, #7]
; CHECK-BE-NEXT:    strb w8, [x1]
; CHECK-BE-NEXT:    lsr x8, x0, #32
; CHECK-BE-NEXT:    strb w9, [x1, #1]
; CHECK-BE-NEXT:    lsr x9, x0, #16
; CHECK-BE-NEXT:    strb w10, [x1, #2]
; CHECK-BE-NEXT:    lsr x10, x0, #8
; CHECK-BE-NEXT:    strb w8, [x1, #3]
; CHECK-BE-NEXT:    strb w9, [x1, #5]
; CHECK-BE-NEXT:    strb w10, [x1, #6]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i64 %x, 8
  %sh2 = lshr i64 %x, 16
  %sh3 = lshr i64 %x, 24
  %sh4 = lshr i64 %x, 32
  %sh5 = lshr i64 %x, 40
  %sh6 = lshr i64 %x, 48
  %sh7 = lshr i64 %x, 56
  %t0 = trunc i64 %x to i8
  %t1 = trunc i64 %sh1 to i8
  %t2 = trunc i64 %sh2 to i8
  %t3 = trunc i64 %sh3 to i8
  %t4 = trunc i64 %sh4 to i8
  %t5 = trunc i64 %sh5 to i8
  %t6 = trunc i64 %sh6 to i8
  %t7 = trunc i64 %sh7 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  %p4 = getelementptr inbounds i8, ptr %p0, i64 4
  %p5 = getelementptr inbounds i8, ptr %p0, i64 5
  %p6 = getelementptr inbounds i8, ptr %p0, i64 6
  %p7 = getelementptr inbounds i8, ptr %p0, i64 7
  store i8 %t7, ptr %p0, align 1
  store i8 %t6, ptr %p1, align 1
  store i8 %t5, ptr %p2, align 1
  store i8 %t4, ptr %p3, align 1
  store i8 %t2, ptr %p5, align 1
  store i8 %t1, ptr %p6, align 1
  store i8 %t0, ptr %p7, align 1
  ret void
}

; Negative test - not consecutive addresses

define void @i32_to_i16_wrong_addr(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: i32_to_i16_wrong_addr:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr w8, w0, #16
; CHECK-LE-NEXT:    strh w0, [x1]
; CHECK-LE-NEXT:    strh w8, [x1, #4]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: i32_to_i16_wrong_addr:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr w8, w0, #16
; CHECK-BE-NEXT:    strh w0, [x1]
; CHECK-BE-NEXT:    strh w8, [x1, #4]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 16
  %t0 = trunc i32 %x to i16
  %t1 = trunc i32 %sh1 to i16
  %p2 = getelementptr inbounds i16, ptr %p0, i64 2
  store i16 %t1, ptr %p2, align 2
  store i16 %t0, ptr %p0, align 2
  ret void
}

; Negative test - addresses don't line up with shift amounts

define void @i32_to_i8_wrong_order(i32 %x, ptr %p0) {
; CHECK-LE-LABEL: i32_to_i8_wrong_order:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    lsr w8, w0, #24
; CHECK-LE-NEXT:    lsr w9, w0, #16
; CHECK-LE-NEXT:    lsr w10, w0, #8
; CHECK-LE-NEXT:    strb w0, [x1, #3]
; CHECK-LE-NEXT:    strb w8, [x1, #1]
; CHECK-LE-NEXT:    strb w9, [x1]
; CHECK-LE-NEXT:    strb w10, [x1, #2]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: i32_to_i8_wrong_order:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    lsr w8, w0, #24
; CHECK-BE-NEXT:    lsr w9, w0, #16
; CHECK-BE-NEXT:    lsr w10, w0, #8
; CHECK-BE-NEXT:    strb w0, [x1, #3]
; CHECK-BE-NEXT:    strb w8, [x1, #1]
; CHECK-BE-NEXT:    strb w9, [x1]
; CHECK-BE-NEXT:    strb w10, [x1, #2]
; CHECK-BE-NEXT:    ret
  %sh1 = lshr i32 %x, 8
  %sh2 = lshr i32 %x, 16
  %sh3 = lshr i32 %x, 24
  %t0 = trunc i32 %x to i8
  %t1 = trunc i32 %sh1 to i8
  %t2 = trunc i32 %sh2 to i8
  %t3 = trunc i32 %sh3 to i8
  %p1 = getelementptr inbounds i8, ptr %p0, i64 1
  %p2 = getelementptr inbounds i8, ptr %p0, i64 2
  %p3 = getelementptr inbounds i8, ptr %p0, i64 3
  store i8 %t3, ptr %p1, align 1
  store i8 %t2, ptr %p0, align 1
  store i8 %t0, ptr %p3, align 1
  store i8 %t1, ptr %p2, align 1
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-GI-LE: {{.*}}
; CHECK-SD-LE: {{.*}}
