; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64-unknown-unknown | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc < %s -mtriple=aarch64_be-unknown-unknown | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc < %s -global-isel -mtriple=aarch64-unknown-unknown | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc < %s -global-isel -mtriple=aarch64_be-unknown-unknown | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE


; Function Attrs: nobuiltin nounwind readonly
define i8 @popcount128(ptr nocapture nonnull readonly %0) {
; CHECK-SD-LE-LABEL: popcount128:
; CHECK-SD-LE:       // %bb.0: // %Entry
; CHECK-SD-LE-NEXT:    ldr d0, [x0]
; CHECK-SD-LE-NEXT:    add x8, x0, #8
; CHECK-SD-LE-NEXT:    ld1 { v0.d }[1], [x8]
; CHECK-SD-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-LE-NEXT:    addv b0, v0.16b
; CHECK-SD-LE-NEXT:    fmov w0, s0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount128:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    ldr d0, [x0]
; CHECK-SD-BE-NEXT:    add x8, x0, #8
; CHECK-SD-BE-NEXT:    ld1 { v0.d }[1], [x8]
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    addv b0, v0.16b
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    mov w0, v0.s[1]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: popcount128:
; CHECK-GI-LE:       // %bb.0: // %Entry
; CHECK-GI-LE-NEXT:    ldr q0, [x0]
; CHECK-GI-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-LE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-LE-NEXT:    fmov w0, s0
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount128:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    ldr q0, [x0]
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-BE-NEXT:    fmov w0, s0
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = load i128, ptr %0, align 16
  %2 = tail call i128 @llvm.ctpop.i128(i128 %1)
  %3 = trunc i128 %2 to i8
  ret i8 %3
}

; Function Attrs: nounwind readnone speculatable willreturn
declare i128 @llvm.ctpop.i128(i128)

; Function Attrs: nobuiltin nounwind readonly
define i16 @popcount256(ptr nocapture nonnull readonly %0) {
; CHECK-SD-LE-LABEL: popcount256:
; CHECK-SD-LE:       // %bb.0: // %Entry
; CHECK-SD-LE-NEXT:    ldr d0, [x0, #16]
; CHECK-SD-LE-NEXT:    ldr d1, [x0]
; CHECK-SD-LE-NEXT:    add x8, x0, #8
; CHECK-SD-LE-NEXT:    add x9, x0, #24
; CHECK-SD-LE-NEXT:    ld1 { v0.d }[1], [x9]
; CHECK-SD-LE-NEXT:    ld1 { v1.d }[1], [x8]
; CHECK-SD-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-LE-NEXT:    cnt v1.16b, v1.16b
; CHECK-SD-LE-NEXT:    addv b0, v0.16b
; CHECK-SD-LE-NEXT:    addv b1, v1.16b
; CHECK-SD-LE-NEXT:    fmov w8, s0
; CHECK-SD-LE-NEXT:    fmov w9, s1
; CHECK-SD-LE-NEXT:    add w0, w9, w8
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount256:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    ldr d0, [x0]
; CHECK-SD-BE-NEXT:    ldr d1, [x0, #16]
; CHECK-SD-BE-NEXT:    add x8, x0, #24
; CHECK-SD-BE-NEXT:    add x9, x0, #8
; CHECK-SD-BE-NEXT:    ld1 { v0.d }[1], [x9]
; CHECK-SD-BE-NEXT:    ld1 { v1.d }[1], [x8]
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    rev64 v1.16b, v1.16b
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    cnt v1.16b, v1.16b
; CHECK-SD-BE-NEXT:    addv b0, v0.16b
; CHECK-SD-BE-NEXT:    addv b1, v1.16b
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    rev64 v1.4s, v1.4s
; CHECK-SD-BE-NEXT:    mov w8, v0.s[1]
; CHECK-SD-BE-NEXT:    mov w9, v1.s[1]
; CHECK-SD-BE-NEXT:    add w0, w9, w8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: popcount256:
; CHECK-GI-LE:       // %bb.0: // %Entry
; CHECK-GI-LE-NEXT:    ldp x8, x9, [x0]
; CHECK-GI-LE-NEXT:    mov v0.d[0], x8
; CHECK-GI-LE-NEXT:    ldp x8, x10, [x0, #16]
; CHECK-GI-LE-NEXT:    mov v1.d[0], x8
; CHECK-GI-LE-NEXT:    mov v0.d[1], x9
; CHECK-GI-LE-NEXT:    mov v1.d[1], x10
; CHECK-GI-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-LE-NEXT:    cnt v1.16b, v1.16b
; CHECK-GI-LE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-LE-NEXT:    uaddlv h1, v1.16b
; CHECK-GI-LE-NEXT:    mov w8, v0.s[0]
; CHECK-GI-LE-NEXT:    fmov w9, s1
; CHECK-GI-LE-NEXT:    add x0, x8, w9, uxtw
; CHECK-GI-LE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount256:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    ldp x9, x8, [x0, #16]
; CHECK-GI-BE-NEXT:    mov v0.d[0], x8
; CHECK-GI-BE-NEXT:    ldp x10, x8, [x0]
; CHECK-GI-BE-NEXT:    mov v1.d[0], x8
; CHECK-GI-BE-NEXT:    mov v0.d[1], x9
; CHECK-GI-BE-NEXT:    mov v1.d[1], x10
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    rev64 v1.16b, v1.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    cnt v1.16b, v1.16b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-BE-NEXT:    uaddlv h1, v1.16b
; CHECK-GI-BE-NEXT:    mov w8, v0.s[0]
; CHECK-GI-BE-NEXT:    fmov w9, s1
; CHECK-GI-BE-NEXT:    add x0, x8, w9, uxtw
; CHECK-GI-BE-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = load i256, ptr %0, align 16
  %2 = tail call i256 @llvm.ctpop.i256(i256 %1)
  %3 = trunc i256 %2 to i16
  ret i16 %3
}

; Function Attrs: nounwind readnone speculatable willreturn
declare i256 @llvm.ctpop.i256(i256)

define <1 x i128> @popcount1x128(<1 x i128> %0) {
; CHECK-SD-LE-LABEL: popcount1x128:
; CHECK-SD-LE:       // %bb.0: // %Entry
; CHECK-SD-LE-NEXT:    fmov d0, x0
; CHECK-SD-LE-NEXT:    mov v0.d[1], x1
; CHECK-SD-LE-NEXT:    mov x1, xzr
; CHECK-SD-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-LE-NEXT:    addv b0, v0.16b
; CHECK-SD-LE-NEXT:    fmov x0, d0
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount1x128:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    fmov d0, x0
; CHECK-SD-BE-NEXT:    mov x0, xzr
; CHECK-SD-BE-NEXT:    mov v0.d[1], x1
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    addv b0, v0.16b
; CHECK-SD-BE-NEXT:    fmov x1, d0
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: popcount1x128:
; CHECK-GI-LE:       // %bb.0: // %Entry
; CHECK-GI-LE-NEXT:    mov v0.d[0], x0
; CHECK-GI-LE-NEXT:    mov v0.d[1], x1
; CHECK-GI-LE-NEXT:    mov x1, xzr
; CHECK-GI-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-LE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-LE-NEXT:    mov w0, v0.s[0]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount1x128:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    mov v0.d[0], x1
; CHECK-GI-BE-NEXT:    mov v0.d[1], x0
; CHECK-GI-BE-NEXT:    mov x0, xzr
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.16b
; CHECK-GI-BE-NEXT:    mov w1, v0.s[0]
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <1 x i128> @llvm.ctpop.v1i128(<1 x i128> %0)
  ret <1 x i128> %1
}

declare <1 x i128> @llvm.ctpop.v1i128(<1 x i128>)

define <2 x i64> @popcount2x64(<2 x i64> %0) {
; CHECK-LE-LABEL: popcount2x64:
; CHECK-LE:       // %bb.0: // %Entry
; CHECK-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-LE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-LE-NEXT:    uaddlp v0.4s, v0.8h
; CHECK-LE-NEXT:    uaddlp v0.2d, v0.4s
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount2x64:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-SD-BE-NEXT:    uaddlp v0.4s, v0.8h
; CHECK-SD-BE-NEXT:    uaddlp v0.2d, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount2x64:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-GI-BE-NEXT:    uaddlp v0.4s, v0.8h
; CHECK-GI-BE-NEXT:    uaddlp v0.2d, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <2 x i64> @llvm.ctpop.v2i64(<2 x i64> %0)
  ret <2 x i64> %1
}

declare <2 x i64> @llvm.ctpop.v2i64(<2 x i64>)

define <1 x i64> @popcount1x64(<1 x i64> %0) {
; CHECK-SD-LE-LABEL: popcount1x64:
; CHECK-SD-LE:       // %bb.0: // %Entry
; CHECK-SD-LE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-LE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-SD-LE-NEXT:    uaddlp v0.2s, v0.4h
; CHECK-SD-LE-NEXT:    uaddlp v0.1d, v0.2s
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount1x64:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-SD-BE-NEXT:    uaddlp v0.2s, v0.4h
; CHECK-SD-BE-NEXT:    uaddlp v0.1d, v0.2s
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: popcount1x64:
; CHECK-GI-LE:       // %bb.0: // %Entry
; CHECK-GI-LE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-LE-NEXT:    uaddlv h0, v0.8b
; CHECK-GI-LE-NEXT:    mov w8, v0.s[0]
; CHECK-GI-LE-NEXT:    fmov d0, x8
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount1x64:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    uaddlv h0, v0.8b
; CHECK-GI-BE-NEXT:    mov w8, v0.s[0]
; CHECK-GI-BE-NEXT:    fmov d0, x8
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <1 x i64> @llvm.ctpop.v1i64(<1 x i64> %0)
  ret <1 x i64> %1
}

declare <1 x i64> @llvm.ctpop.v1i64(<1 x i64>)

define <4 x i32> @popcount4x32(<4 x i32> %0) {
; CHECK-LE-LABEL: popcount4x32:
; CHECK-LE:       // %bb.0: // %Entry
; CHECK-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-LE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-LE-NEXT:    uaddlp v0.4s, v0.8h
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount4x32:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-SD-BE-NEXT:    uaddlp v0.4s, v0.8h
; CHECK-SD-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount4x32:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    rev32 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-GI-BE-NEXT:    uaddlp v0.4s, v0.8h
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <4 x i32> @llvm.ctpop.v4i32(<4 x i32> %0)
  ret <4 x i32> %1
}

declare <4 x i32> @llvm.ctpop.v4i32(<4 x i32>)

define <2 x i32> @popcount2x32(<2 x i32> %0) {
; CHECK-LE-LABEL: popcount2x32:
; CHECK-LE:       // %bb.0: // %Entry
; CHECK-LE-NEXT:    cnt v0.8b, v0.8b
; CHECK-LE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-LE-NEXT:    uaddlp v0.2s, v0.4h
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount2x32:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-SD-BE-NEXT:    uaddlp v0.2s, v0.4h
; CHECK-SD-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount2x32:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-GI-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-GI-BE-NEXT:    uaddlp v0.2s, v0.4h
; CHECK-GI-BE-NEXT:    rev64 v0.2s, v0.2s
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <2 x i32> @llvm.ctpop.v2i32(<2 x i32> %0)
  ret <2 x i32> %1
}

declare <2 x i32> @llvm.ctpop.v2i32(<2 x i32>)

define <8 x i16> @popcount8x16(<8 x i16> %0) {
; CHECK-LE-LABEL: popcount8x16:
; CHECK-LE:       // %bb.0: // %Entry
; CHECK-LE-NEXT:    cnt v0.16b, v0.16b
; CHECK-LE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount8x16:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-SD-BE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-SD-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-SD-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount8x16:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    rev16 v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    cnt v0.16b, v0.16b
; CHECK-GI-BE-NEXT:    uaddlp v0.8h, v0.16b
; CHECK-GI-BE-NEXT:    rev64 v0.8h, v0.8h
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <8 x i16> @llvm.ctpop.v8i16(<8 x i16> %0)
  ret <8 x i16> %1
}

declare <8 x i16> @llvm.ctpop.v8i16(<8 x i16>)

define <4 x i16> @popcount4x16(<4 x i16> %0) {
; CHECK-LE-LABEL: popcount4x16:
; CHECK-LE:       // %bb.0: // %Entry
; CHECK-LE-NEXT:    cnt v0.8b, v0.8b
; CHECK-LE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: popcount4x16:
; CHECK-SD-BE:       // %bb.0: // %Entry
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-SD-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: popcount4x16:
; CHECK-GI-BE:       // %bb.0: // %Entry
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-GI-BE-NEXT:    rev16 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    cnt v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    uaddlp v0.4h, v0.8b
; CHECK-GI-BE-NEXT:    rev64 v0.4h, v0.4h
; CHECK-GI-BE-NEXT:    ret
Entry:
  %1 = tail call <4 x i16> @llvm.ctpop.v4i16(<4 x i16> %0)
  ret <4 x i16> %1
}

define i32 @ctpop_into_extract(ptr %p) {
; CHECK-SD-LE-LABEL: ctpop_into_extract:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    ldr d0, [x0]
; CHECK-SD-LE-NEXT:    movi v2.2d, #0xffffffffffffffff
; CHECK-SD-LE-NEXT:    mov x8, x0
; CHECK-SD-LE-NEXT:    mov w0, wzr
; CHECK-SD-LE-NEXT:    fmov w9, s0
; CHECK-SD-LE-NEXT:    fmov s1, w9
; CHECK-SD-LE-NEXT:    cnt v1.8b, v1.8b
; CHECK-SD-LE-NEXT:    addv b1, v1.8b
; CHECK-SD-LE-NEXT:    mov v2.s[1], v1.s[0]
; CHECK-SD-LE-NEXT:    sub v0.2s, v0.2s, v2.2s
; CHECK-SD-LE-NEXT:    str d0, [x8]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: ctpop_into_extract:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-SD-BE-NEXT:    movi v2.2d, #0xffffffffffffffff
; CHECK-SD-BE-NEXT:    mov x8, x0
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    fmov w9, s0
; CHECK-SD-BE-NEXT:    fmov s1, w9
; CHECK-SD-BE-NEXT:    cnt v1.8b, v1.8b
; CHECK-SD-BE-NEXT:    addv b1, v1.8b
; CHECK-SD-BE-NEXT:    mov v2.s[1], v1.s[0]
; CHECK-SD-BE-NEXT:    sub v0.2s, v0.2s, v2.2s
; CHECK-SD-BE-NEXT:    st1 { v0.2s }, [x8]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: ctpop_into_extract:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    ldr d0, [x0]
; CHECK-GI-LE-NEXT:    mov x8, x0
; CHECK-GI-LE-NEXT:    mov w0, wzr
; CHECK-GI-LE-NEXT:    fmov w9, s0
; CHECK-GI-LE-NEXT:    fmov s1, w9
; CHECK-GI-LE-NEXT:    mov w9, #-1 // =0xffffffff
; CHECK-GI-LE-NEXT:    fmov s2, w9
; CHECK-GI-LE-NEXT:    cnt v1.8b, v1.8b
; CHECK-GI-LE-NEXT:    uaddlv h1, v1.8b
; CHECK-GI-LE-NEXT:    mov v2.s[1], v1.s[0]
; CHECK-GI-LE-NEXT:    sub v0.2s, v0.2s, v2.2s
; CHECK-GI-LE-NEXT:    str d0, [x8]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: ctpop_into_extract:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ld1 { v0.2s }, [x0]
; CHECK-GI-BE-NEXT:    mov x8, x0
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    fmov w9, s0
; CHECK-GI-BE-NEXT:    fmov s1, w9
; CHECK-GI-BE-NEXT:    mov w9, #-1 // =0xffffffff
; CHECK-GI-BE-NEXT:    fmov s2, w9
; CHECK-GI-BE-NEXT:    cnt v1.8b, v1.8b
; CHECK-GI-BE-NEXT:    uaddlv h1, v1.8b
; CHECK-GI-BE-NEXT:    mov v2.s[1], v1.s[0]
; CHECK-GI-BE-NEXT:    sub v0.2s, v0.2s, v2.2s
; CHECK-GI-BE-NEXT:    st1 { v0.2s }, [x8]
; CHECK-GI-BE-NEXT:    ret
  %1 = load <2 x i32>, ptr %p, align 4
  %2 = extractelement <2 x i32> %1, i64 0
  %3 = call i32 @llvm.ctpop.i32(i32 %2)
  %4 = insertelement <2 x i32> <i32 -1, i32 poison>, i32 %3, i64 1
  %5 = sub <2 x i32> %1, %4
  store <2 x i32> %5, ptr %p, align 4
  ret i32 0
}

define <8 x i8> @bitcast_upper_bits(i32 %b, <8 x i8> %v) {
; CHECK-LE-LABEL: bitcast_upper_bits:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    fmov s1, w0
; CHECK-LE-NEXT:    add v0.8b, v1.8b, v0.8b
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: bitcast_upper_bits:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-BE-NEXT:    fmov s1, w0
; CHECK-BE-NEXT:    add v0.8b, v1.8b, v0.8b
; CHECK-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-BE-NEXT:    ret
  %a = zext i32 %b to i64
  %c = bitcast i64 %a to <8 x i8>
  %d = add <8 x i8> %c, %v
  ret <8 x i8> %d
}


declare <4 x i16> @llvm.ctpop.v4i16(<4 x i16>)
