; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-none-elf %s -o - | FileCheck %s --check-prefixes=CHECK-SD-LE,CHECK-LE
; RUN: llc -mtriple=aarch64_be-none-linux-gnu %s -o - | FileCheck %s --check-prefixes=CHECK-SD-BE,CHECK-BE
; RUN: llc -mtriple=aarch64-none-elf -global-isel %s -o - | FileCheck %s --check-prefixes=CHECK-GI-LE,CHECK-LE
; RUN: llc -mtriple=aarch64_be-none-linux-gnu -global-isel %s -o - | FileCheck %s --check-prefixes=CHECK-GI-BE,CHECK-LE


define void @if_then_else8(ptr %out, i8 %mask, ptr %if_true, ptr %if_false) {
; CHECK-SD-LE-LABEL: if_then_else8:
; CHECK-SD-LE:       // %bb.0: // %start
; CHECK-SD-LE-NEXT:    adrp x8, .LCPI0_1
; CHECK-SD-LE-NEXT:    dup v0.4s, w1
; CHECK-SD-LE-NEXT:    ldr q1, [x8, :lo12:.LCPI0_1]
; CHECK-SD-LE-NEXT:    adrp x8, .LCPI0_0
; CHECK-SD-LE-NEXT:    ldr q2, [x8, :lo12:.LCPI0_0]
; CHECK-SD-LE-NEXT:    ldp q4, q3, [x2]
; CHECK-SD-LE-NEXT:    and v1.16b, v0.16b, v1.16b
; CHECK-SD-LE-NEXT:    and v0.16b, v0.16b, v2.16b
; CHECK-SD-LE-NEXT:    ldp q5, q2, [x3]
; CHECK-SD-LE-NEXT:    cmeq v1.4s, v1.4s, #0
; CHECK-SD-LE-NEXT:    cmeq v0.4s, v0.4s, #0
; CHECK-SD-LE-NEXT:    bsl v1.16b, v2.16b, v3.16b
; CHECK-SD-LE-NEXT:    bsl v0.16b, v5.16b, v4.16b
; CHECK-SD-LE-NEXT:    stp q0, q1, [x0]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: if_then_else8:
; CHECK-SD-BE:       // %bb.0: // %start
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_1
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_1
; CHECK-SD-BE-NEXT:    dup v0.4s, w1
; CHECK-SD-BE-NEXT:    ld1 { v1.4s }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_0
; CHECK-SD-BE-NEXT:    ld1 { v2.4s }, [x8]
; CHECK-SD-BE-NEXT:    add x8, x2, #16
; CHECK-SD-BE-NEXT:    add x9, x3, #16
; CHECK-SD-BE-NEXT:    ld1 { v3.4s }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v4.4s }, [x2]
; CHECK-SD-BE-NEXT:    ld1 { v5.4s }, [x3]
; CHECK-SD-BE-NEXT:    and v1.16b, v0.16b, v1.16b
; CHECK-SD-BE-NEXT:    and v0.16b, v0.16b, v2.16b
; CHECK-SD-BE-NEXT:    ld1 { v2.4s }, [x8]
; CHECK-SD-BE-NEXT:    add x8, x0, #16
; CHECK-SD-BE-NEXT:    cmeq v1.4s, v1.4s, #0
; CHECK-SD-BE-NEXT:    cmeq v0.4s, v0.4s, #0
; CHECK-SD-BE-NEXT:    bsl v1.16b, v3.16b, v2.16b
; CHECK-SD-BE-NEXT:    bsl v0.16b, v5.16b, v4.16b
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x0]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: if_then_else8:
; CHECK-GI-LE:       // %bb.0: // %start
; CHECK-GI-LE-NEXT:    uxtb w8, w1
; CHECK-GI-LE-NEXT:    fmov s0, w1
; CHECK-GI-LE-NEXT:    ldp q2, q5, [x3]
; CHECK-GI-LE-NEXT:    lsr w10, w8, #4
; CHECK-GI-LE-NEXT:    lsr w9, w8, #1
; CHECK-GI-LE-NEXT:    lsr w11, w8, #5
; CHECK-GI-LE-NEXT:    ldp q3, q4, [x2]
; CHECK-GI-LE-NEXT:    fmov s1, w10
; CHECK-GI-LE-NEXT:    mov v0.h[1], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #2
; CHECK-GI-LE-NEXT:    lsr w10, w8, #6
; CHECK-GI-LE-NEXT:    mov v1.h[1], w11
; CHECK-GI-LE-NEXT:    mov v0.h[2], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #3
; CHECK-GI-LE-NEXT:    lsr w8, w8, #7
; CHECK-GI-LE-NEXT:    mov v1.h[2], w10
; CHECK-GI-LE-NEXT:    mov v0.h[3], w9
; CHECK-GI-LE-NEXT:    mov v1.h[3], w8
; CHECK-GI-LE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-GI-LE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-GI-LE-NEXT:    shl v0.4s, v0.4s, #31
; CHECK-GI-LE-NEXT:    shl v1.4s, v1.4s, #31
; CHECK-GI-LE-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-GI-LE-NEXT:    cmlt v1.4s, v1.4s, #0
; CHECK-GI-LE-NEXT:    bsl v0.16b, v3.16b, v2.16b
; CHECK-GI-LE-NEXT:    bsl v1.16b, v4.16b, v5.16b
; CHECK-GI-LE-NEXT:    stp q0, q1, [x0]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: if_then_else8:
; CHECK-GI-BE:       // %bb.0: // %start
; CHECK-GI-BE-NEXT:    uxtb w8, w1
; CHECK-GI-BE-NEXT:    fmov s0, w1
; CHECK-GI-BE-NEXT:    ld1 { v4.4s }, [x2]
; CHECK-GI-BE-NEXT:    ld1 { v5.4s }, [x3]
; CHECK-GI-BE-NEXT:    lsr w10, w8, #4
; CHECK-GI-BE-NEXT:    lsr w9, w8, #1
; CHECK-GI-BE-NEXT:    lsr w11, w8, #5
; CHECK-GI-BE-NEXT:    fmov s1, w10
; CHECK-GI-BE-NEXT:    mov v0.h[1], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #2
; CHECK-GI-BE-NEXT:    lsr w10, w8, #6
; CHECK-GI-BE-NEXT:    mov v1.h[1], w11
; CHECK-GI-BE-NEXT:    mov v0.h[2], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #3
; CHECK-GI-BE-NEXT:    lsr w8, w8, #7
; CHECK-GI-BE-NEXT:    mov v1.h[2], w10
; CHECK-GI-BE-NEXT:    mov v0.h[3], w9
; CHECK-GI-BE-NEXT:    add x9, x3, #16
; CHECK-GI-BE-NEXT:    ld1 { v3.4s }, [x9]
; CHECK-GI-BE-NEXT:    mov v1.h[3], w8
; CHECK-GI-BE-NEXT:    add x8, x2, #16
; CHECK-GI-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ld1 { v2.4s }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x0, #16
; CHECK-GI-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    shl v0.4s, v0.4s, #31
; CHECK-GI-BE-NEXT:    shl v1.4s, v1.4s, #31
; CHECK-GI-BE-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-GI-BE-NEXT:    cmlt v1.4s, v1.4s, #0
; CHECK-GI-BE-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-GI-BE-NEXT:    bsl v1.16b, v4.16b, v5.16b
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x8]
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x0]
; CHECK-GI-BE-NEXT:    ret
start:
  %t = load <8 x i32>, ptr %if_true, align 4
  %f = load <8 x i32>, ptr %if_false, align 4
  %m = bitcast i8 %mask to <8 x i1>
  %s = select <8 x i1> %m, <8 x i32> %t, <8 x i32> %f
  store <8 x i32> %s, ptr %out, align 4
  ret void
}

define <8 x i8> @broadcast_u8_to_v8i8_zext(i8 %x) {
; CHECK-SD-LE-LABEL: broadcast_u8_to_v8i8_zext:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    dup v0.8b, w0
; CHECK-SD-LE-NEXT:    adrp x8, .LCPI1_0
; CHECK-SD-LE-NEXT:    ldr d1, [x8, :lo12:.LCPI1_0]
; CHECK-SD-LE-NEXT:    cmtst v0.8b, v0.8b, v1.8b
; CHECK-SD-LE-NEXT:    ushr v0.8b, v0.8b, #7
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: broadcast_u8_to_v8i8_zext:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    dup v0.8b, w0
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI1_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI1_0
; CHECK-SD-BE-NEXT:    ld1 { v1.8b }, [x8]
; CHECK-SD-BE-NEXT:    cmtst v0.8b, v0.8b, v1.8b
; CHECK-SD-BE-NEXT:    ushr v0.8b, v0.8b, #7
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: broadcast_u8_to_v8i8_zext:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    uxtb w8, w0
; CHECK-GI-LE-NEXT:    fmov s1, w0
; CHECK-GI-LE-NEXT:    movi v0.8b, #1
; CHECK-GI-LE-NEXT:    lsr w9, w8, #1
; CHECK-GI-LE-NEXT:    mov v1.b[1], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #2
; CHECK-GI-LE-NEXT:    mov v1.b[2], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #3
; CHECK-GI-LE-NEXT:    mov v1.b[3], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #4
; CHECK-GI-LE-NEXT:    mov v1.b[4], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #5
; CHECK-GI-LE-NEXT:    mov v1.b[5], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #6
; CHECK-GI-LE-NEXT:    lsr w8, w8, #7
; CHECK-GI-LE-NEXT:    mov v1.b[6], w9
; CHECK-GI-LE-NEXT:    mov v1.b[7], w8
; CHECK-GI-LE-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: broadcast_u8_to_v8i8_zext:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    uxtb w8, w0
; CHECK-GI-BE-NEXT:    fmov s1, w0
; CHECK-GI-BE-NEXT:    movi v0.8b, #1
; CHECK-GI-BE-NEXT:    lsr w9, w8, #1
; CHECK-GI-BE-NEXT:    mov v1.b[1], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #2
; CHECK-GI-BE-NEXT:    mov v1.b[2], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #3
; CHECK-GI-BE-NEXT:    mov v1.b[3], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #4
; CHECK-GI-BE-NEXT:    mov v1.b[4], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #5
; CHECK-GI-BE-NEXT:    mov v1.b[5], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #6
; CHECK-GI-BE-NEXT:    lsr w8, w8, #7
; CHECK-GI-BE-NEXT:    mov v1.b[6], w9
; CHECK-GI-BE-NEXT:    mov v1.b[7], w8
; CHECK-GI-BE-NEXT:    and v0.8b, v1.8b, v0.8b
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    ret
  %v1 = bitcast i8 %x to <8 x i1>
  %v8 = zext <8 x i1> %v1 to <8 x i8>
  ret <8 x i8> %v8
}

define <8 x i8> @broadcast_u8_to_v8i8_sext(i8 %x) {
; CHECK-SD-LE-LABEL: broadcast_u8_to_v8i8_sext:
; CHECK-SD-LE:       // %bb.0:
; CHECK-SD-LE-NEXT:    dup v0.8b, w0
; CHECK-SD-LE-NEXT:    adrp x8, .LCPI2_0
; CHECK-SD-LE-NEXT:    ldr d1, [x8, :lo12:.LCPI2_0]
; CHECK-SD-LE-NEXT:    cmtst v0.8b, v0.8b, v1.8b
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: broadcast_u8_to_v8i8_sext:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    dup v0.8b, w0
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI2_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI2_0
; CHECK-SD-BE-NEXT:    ld1 { v1.8b }, [x8]
; CHECK-SD-BE-NEXT:    cmtst v0.8b, v0.8b, v1.8b
; CHECK-SD-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: broadcast_u8_to_v8i8_sext:
; CHECK-GI-LE:       // %bb.0:
; CHECK-GI-LE-NEXT:    uxtb w8, w0
; CHECK-GI-LE-NEXT:    fmov s0, w0
; CHECK-GI-LE-NEXT:    lsr w9, w8, #1
; CHECK-GI-LE-NEXT:    mov v0.b[1], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #2
; CHECK-GI-LE-NEXT:    mov v0.b[2], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #3
; CHECK-GI-LE-NEXT:    mov v0.b[3], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #4
; CHECK-GI-LE-NEXT:    mov v0.b[4], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #5
; CHECK-GI-LE-NEXT:    mov v0.b[5], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #6
; CHECK-GI-LE-NEXT:    lsr w8, w8, #7
; CHECK-GI-LE-NEXT:    mov v0.b[6], w9
; CHECK-GI-LE-NEXT:    mov v0.b[7], w8
; CHECK-GI-LE-NEXT:    shl v0.8b, v0.8b, #7
; CHECK-GI-LE-NEXT:    cmlt v0.8b, v0.8b, #0
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: broadcast_u8_to_v8i8_sext:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    uxtb w8, w0
; CHECK-GI-BE-NEXT:    fmov s0, w0
; CHECK-GI-BE-NEXT:    lsr w9, w8, #1
; CHECK-GI-BE-NEXT:    mov v0.b[1], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #2
; CHECK-GI-BE-NEXT:    mov v0.b[2], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #3
; CHECK-GI-BE-NEXT:    mov v0.b[3], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #4
; CHECK-GI-BE-NEXT:    mov v0.b[4], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #5
; CHECK-GI-BE-NEXT:    mov v0.b[5], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #6
; CHECK-GI-BE-NEXT:    lsr w8, w8, #7
; CHECK-GI-BE-NEXT:    mov v0.b[6], w9
; CHECK-GI-BE-NEXT:    mov v0.b[7], w8
; CHECK-GI-BE-NEXT:    shl v0.8b, v0.8b, #7
; CHECK-GI-BE-NEXT:    cmlt v0.8b, v0.8b, #0
; CHECK-GI-BE-NEXT:    rev64 v0.8b, v0.8b
; CHECK-GI-BE-NEXT:    ret
  %v1 = bitcast i8 %x to <8 x i1>
  %v8 = sext <8 x i1> %v1 to <8 x i8>
  ret <8 x i8> %v8
}

define void @if_then_else8_i8(ptr %out, i8 %mask, ptr %if_true, ptr %if_false) {
; CHECK-SD-LE-LABEL: if_then_else8_i8:
; CHECK-SD-LE:       // %bb.0: // %start
; CHECK-SD-LE-NEXT:    dup v0.8b, w1
; CHECK-SD-LE-NEXT:    adrp x8, .LCPI3_0
; CHECK-SD-LE-NEXT:    ldr d2, [x3]
; CHECK-SD-LE-NEXT:    ldr d1, [x8, :lo12:.LCPI3_0]
; CHECK-SD-LE-NEXT:    and v0.8b, v0.8b, v1.8b
; CHECK-SD-LE-NEXT:    ldr d1, [x2]
; CHECK-SD-LE-NEXT:    cmeq v0.8b, v0.8b, #0
; CHECK-SD-LE-NEXT:    bsl v0.8b, v2.8b, v1.8b
; CHECK-SD-LE-NEXT:    str d0, [x0]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: if_then_else8_i8:
; CHECK-SD-BE:       // %bb.0: // %start
; CHECK-SD-BE-NEXT:    dup v0.8b, w1
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI3_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI3_0
; CHECK-SD-BE-NEXT:    ld1 { v1.8b }, [x8]
; CHECK-SD-BE-NEXT:    ld1 { v2.8b }, [x3]
; CHECK-SD-BE-NEXT:    and v0.8b, v0.8b, v1.8b
; CHECK-SD-BE-NEXT:    ld1 { v1.8b }, [x2]
; CHECK-SD-BE-NEXT:    cmeq v0.8b, v0.8b, #0
; CHECK-SD-BE-NEXT:    bsl v0.8b, v2.8b, v1.8b
; CHECK-SD-BE-NEXT:    st1 { v0.8b }, [x0]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: if_then_else8_i8:
; CHECK-GI-LE:       // %bb.0: // %start
; CHECK-GI-LE-NEXT:    uxtb w8, w1
; CHECK-GI-LE-NEXT:    fmov s0, w1
; CHECK-GI-LE-NEXT:    ldr d1, [x2]
; CHECK-GI-LE-NEXT:    ldr d2, [x3]
; CHECK-GI-LE-NEXT:    lsr w9, w8, #1
; CHECK-GI-LE-NEXT:    mov v0.b[1], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #2
; CHECK-GI-LE-NEXT:    mov v0.b[2], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #3
; CHECK-GI-LE-NEXT:    mov v0.b[3], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #4
; CHECK-GI-LE-NEXT:    mov v0.b[4], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #5
; CHECK-GI-LE-NEXT:    mov v0.b[5], w9
; CHECK-GI-LE-NEXT:    lsr w9, w8, #6
; CHECK-GI-LE-NEXT:    lsr w8, w8, #7
; CHECK-GI-LE-NEXT:    mov v0.b[6], w9
; CHECK-GI-LE-NEXT:    mov v0.b[7], w8
; CHECK-GI-LE-NEXT:    shl v0.8b, v0.8b, #7
; CHECK-GI-LE-NEXT:    cmlt v0.8b, v0.8b, #0
; CHECK-GI-LE-NEXT:    bsl v0.8b, v1.8b, v2.8b
; CHECK-GI-LE-NEXT:    str d0, [x0]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: if_then_else8_i8:
; CHECK-GI-BE:       // %bb.0: // %start
; CHECK-GI-BE-NEXT:    uxtb w8, w1
; CHECK-GI-BE-NEXT:    fmov s0, w1
; CHECK-GI-BE-NEXT:    ld1 { v1.8b }, [x2]
; CHECK-GI-BE-NEXT:    ld1 { v2.8b }, [x3]
; CHECK-GI-BE-NEXT:    lsr w9, w8, #1
; CHECK-GI-BE-NEXT:    mov v0.b[1], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #2
; CHECK-GI-BE-NEXT:    mov v0.b[2], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #3
; CHECK-GI-BE-NEXT:    mov v0.b[3], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #4
; CHECK-GI-BE-NEXT:    mov v0.b[4], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #5
; CHECK-GI-BE-NEXT:    mov v0.b[5], w9
; CHECK-GI-BE-NEXT:    lsr w9, w8, #6
; CHECK-GI-BE-NEXT:    lsr w8, w8, #7
; CHECK-GI-BE-NEXT:    mov v0.b[6], w9
; CHECK-GI-BE-NEXT:    mov v0.b[7], w8
; CHECK-GI-BE-NEXT:    shl v0.8b, v0.8b, #7
; CHECK-GI-BE-NEXT:    cmlt v0.8b, v0.8b, #0
; CHECK-GI-BE-NEXT:    bsl v0.8b, v1.8b, v2.8b
; CHECK-GI-BE-NEXT:    st1 { v0.8b }, [x0]
; CHECK-GI-BE-NEXT:    ret
start:
  %t = load <8 x i8>, ptr %if_true, align 4
  %f = load <8 x i8>, ptr %if_false, align 4
  %m = bitcast i8 %mask to <8 x i1>
  %s = select <8 x i1> %m, <8 x i8> %t, <8 x i8> %f
  store <8 x i8> %s, ptr %out, align 4
  ret void
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-BE: {{.*}}
; CHECK-LE: {{.*}}
