; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=aarch64--linux-gnu | FileCheck %s --check-prefixes=CHECK-LE,CHECK-LE-SD
; RUN: llc < %s -mtriple=aarch64_be--linux-gnu | FileCheck %s --check-prefixes=CHECK-BE,CHECK-BE-SD
; RUN: llc < %s -mtriple=aarch64--linux-gnu -global-isel | FileCheck %s --check-prefixes=CHECK-LE,CHECK-LE-GI
; RUN: llc < %s -mtriple=aarch64_be--linux-gnu -global-isel | FileCheck %s --check-prefixes=CHECK-BE,CHECK-BE-GI

define <16 x i32> @test_shuf1(<16 x i32> %x, <16 x i32> %y) {
; CHECK-LE-SD-LABEL: test_shuf1:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ext v3.16b, v6.16b, v1.16b, #4
; CHECK-LE-SD-NEXT:    uzp1 v5.4s, v1.4s, v0.4s
; CHECK-LE-SD-NEXT:    uzp2 v16.4s, v2.4s, v4.4s
; CHECK-LE-SD-NEXT:    dup v17.4s, v4.s[0]
; CHECK-LE-SD-NEXT:    trn2 v4.4s, v1.4s, v3.4s
; CHECK-LE-SD-NEXT:    mov v17.s[0], v6.s[3]
; CHECK-LE-SD-NEXT:    trn2 v1.4s, v5.4s, v1.4s
; CHECK-LE-SD-NEXT:    rev64 v3.4s, v7.4s
; CHECK-LE-SD-NEXT:    trn1 v2.4s, v16.4s, v2.4s
; CHECK-LE-SD-NEXT:    mov v4.s[0], v7.s[1]
; CHECK-LE-SD-NEXT:    ext v1.16b, v0.16b, v1.16b, #12
; CHECK-LE-SD-NEXT:    mov v3.d[0], v17.d[0]
; CHECK-LE-SD-NEXT:    mov v2.s[3], v7.s[0]
; CHECK-LE-SD-NEXT:    mov v0.16b, v4.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf1:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    rev64 v3.4s, v6.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v2.4s
; CHECK-BE-SD-NEXT:    rev64 v4.4s, v4.4s
; CHECK-BE-SD-NEXT:    rev64 v5.4s, v7.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v3.16b, v3.16b, v3.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    ext v4.16b, v4.16b, v4.16b, #8
; CHECK-BE-SD-NEXT:    ext v5.16b, v5.16b, v5.16b, #8
; CHECK-BE-SD-NEXT:    ext v6.16b, v3.16b, v1.16b, #4
; CHECK-BE-SD-NEXT:    uzp1 v16.4s, v1.4s, v0.4s
; CHECK-BE-SD-NEXT:    uzp2 v7.4s, v2.4s, v4.4s
; CHECK-BE-SD-NEXT:    dup v4.4s, v4.s[0]
; CHECK-BE-SD-NEXT:    rev64 v17.4s, v5.4s
; CHECK-BE-SD-NEXT:    trn2 v6.4s, v1.4s, v6.4s
; CHECK-BE-SD-NEXT:    mov v4.s[0], v3.s[3]
; CHECK-BE-SD-NEXT:    trn2 v1.4s, v16.4s, v1.4s
; CHECK-BE-SD-NEXT:    trn1 v2.4s, v7.4s, v2.4s
; CHECK-BE-SD-NEXT:    rev64 v3.4s, v17.4s
; CHECK-BE-SD-NEXT:    mov v6.s[0], v5.s[1]
; CHECK-BE-SD-NEXT:    rev64 v4.4s, v4.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v1.16b, #12
; CHECK-BE-SD-NEXT:    mov v2.s[3], v5.s[0]
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v6.4s
; CHECK-BE-SD-NEXT:    mov v3.d[0], v4.d[0]
; CHECK-BE-SD-NEXT:    rev64 v4.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v2.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v3.16b, v3.16b, v3.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v4.16b, v4.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf1:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    mov s16, v7.s[1]
; CHECK-LE-GI-NEXT:    mov s5, v2.s[1]
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI0_0
; CHECK-LE-GI-NEXT:    mov s3, v6.s[3]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    mov v16.s[1], v6.s[2]
; CHECK-LE-GI-NEXT:    mov v5.s[1], v2.s[0]
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI0_0]
; CHECK-LE-GI-NEXT:    mov v3.s[1], v4.s[0]
; CHECK-LE-GI-NEXT:    mov v16.s[2], v1.s[3]
; CHECK-LE-GI-NEXT:    mov v5.s[2], v4.s[1]
; CHECK-LE-GI-NEXT:    mov v3.s[2], v7.s[3]
; CHECK-LE-GI-NEXT:    mov v16.s[3], v1.s[0]
; CHECK-LE-GI-NEXT:    mov v5.s[3], v7.s[0]
; CHECK-LE-GI-NEXT:    tbl v1.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    mov v3.s[3], v7.s[2]
; CHECK-LE-GI-NEXT:    mov v0.16b, v16.16b
; CHECK-LE-GI-NEXT:    mov v2.16b, v5.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf1:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    // kill: def $q3 killed $q3 killed $q3_q4 def $q3_q4
; CHECK-BE-GI-NEXT:    mov s0, v3.s[1]
; CHECK-BE-GI-NEXT:    mov v17.16b, v4.16b
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI0_0
; CHECK-BE-GI-NEXT:    mov s6, v3.s[2]
; CHECK-BE-GI-NEXT:    mov s16, v3.s[3]
; CHECK-BE-GI-NEXT:    mov s19, v5.s[2]
; CHECK-BE-GI-NEXT:    mov s18, v2.s[2]
; CHECK-BE-GI-NEXT:    mov s20, v7.s[1]
; CHECK-BE-GI-NEXT:    mov v3.s[1], v0.s[0]
; CHECK-BE-GI-NEXT:    mov s0, v2.s[1]
; CHECK-BE-GI-NEXT:    mov v3.s[2], v6.s[0]
; CHECK-BE-GI-NEXT:    mov s6, v17.s[1]
; CHECK-BE-GI-NEXT:    mov v3.s[3], v16.s[0]
; CHECK-BE-GI-NEXT:    mov s16, v1.s[1]
; CHECK-BE-GI-NEXT:    mov v6.s[1], v19.s[0]
; CHECK-BE-GI-NEXT:    mov v4.16b, v2.16b
; CHECK-BE-GI-NEXT:    mov v4.s[1], v0.s[0]
; CHECK-BE-GI-NEXT:    mov s0, v5.s[3]
; CHECK-BE-GI-NEXT:    mov s5, v2.s[3]
; CHECK-BE-GI-NEXT:    mov v16.s[1], v1.s[0]
; CHECK-BE-GI-NEXT:    mov s1, v17.s[2]
; CHECK-BE-GI-NEXT:    mov v4.s[2], v18.s[0]
; CHECK-BE-GI-NEXT:    mov s18, v17.s[3]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v7.s[0]
; CHECK-BE-GI-NEXT:    mov v6.s[2], v5.s[0]
; CHECK-BE-GI-NEXT:    mov v16.s[2], v20.s[0]
; CHECK-BE-GI-NEXT:    mov v4.s[3], v5.s[0]
; CHECK-BE-GI-NEXT:    mov v0.s[2], v18.s[0]
; CHECK-BE-GI-NEXT:    ldr q5, [x8, :lo12:.LCPI0_0]
; CHECK-BE-GI-NEXT:    mov v6.s[3], v2.s[0]
; CHECK-BE-GI-NEXT:    mov v16.s[3], v17.s[0]
; CHECK-BE-GI-NEXT:    tbl v2.16b, { v3.16b, v4.16b }, v5.16b
; CHECK-BE-GI-NEXT:    mov v0.s[3], v1.s[0]
; CHECK-BE-GI-NEXT:    mov v3.16b, v6.16b
; CHECK-BE-GI-NEXT:    mov v1.16b, v16.16b
; CHECK-BE-GI-NEXT:    ret
  %s3 = shufflevector <16 x i32> %x, <16 x i32> %y, <16 x i32> <i32 29, i32 26, i32 7, i32 4, i32 3, i32 6, i32 5, i32 2, i32 9, i32 8, i32 17, i32 28, i32 27, i32 16, i32 31, i32 30>
  ret <16 x i32> %s3
}

define <4 x i32> @test_shuf2(<16 x i32> %x, <16 x i32> %y) {
; CHECK-LE-SD-LABEL: test_shuf2:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    zip2 v0.4s, v7.4s, v6.4s
; CHECK-LE-SD-NEXT:    trn2 v2.4s, v7.4s, v0.4s
; CHECK-LE-SD-NEXT:    ext v0.16b, v1.16b, v1.16b, #4
; CHECK-LE-SD-NEXT:    mov v0.d[0], v2.d[0]
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf2:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v6.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v7.4s
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    zip2 v0.4s, v2.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #4
; CHECK-BE-SD-NEXT:    trn2 v0.4s, v2.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    mov v1.d[0], v0.d[0]
; CHECK-BE-SD-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf2:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    mov s0, v7.s[1]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v6.s[2]
; CHECK-LE-GI-NEXT:    mov v0.s[2], v1.s[3]
; CHECK-LE-GI-NEXT:    mov v0.s[3], v1.s[0]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf2:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    mov s0, v5.s[2]
; CHECK-BE-GI-NEXT:    mov s1, v4.s[1]
; CHECK-BE-GI-NEXT:    mov s3, v2.s[3]
; CHECK-BE-GI-NEXT:    mov v1.s[1], v0.s[0]
; CHECK-BE-GI-NEXT:    mov v1.s[2], v3.s[0]
; CHECK-BE-GI-NEXT:    mov v1.s[3], v2.s[0]
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v1.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %s3 = shufflevector <16 x i32> %x, <16 x i32> %y, <4 x i32> <i32 29, i32 26, i32 7, i32 4>
  ret <4 x i32> %s3
}

define <4 x i32> @test_shuf3(<16 x i32> %x, <16 x i32> %y) {
; CHECK-LE-SD-LABEL: test_shuf3:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    uzp1 v2.4s, v1.4s, v0.4s
; CHECK-LE-SD-NEXT:    trn2 v1.4s, v2.4s, v1.4s
; CHECK-LE-SD-NEXT:    ext v0.16b, v0.16b, v1.16b, #12
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf3:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    uzp1 v2.4s, v1.4s, v0.4s
; CHECK-BE-SD-NEXT:    trn2 v1.4s, v2.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v1.16b, #12
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf3:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI2_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI2_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf3:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    // kill: def $q3 killed $q3 def $q3_q4
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI2_0
; CHECK-BE-GI-NEXT:    mov v4.16b, v2.16b
; CHECK-BE-GI-NEXT:    mov s0, v3.s[1]
; CHECK-BE-GI-NEXT:    mov s1, v3.s[2]
; CHECK-BE-GI-NEXT:    mov s2, v3.s[3]
; CHECK-BE-GI-NEXT:    mov s5, v4.s[1]
; CHECK-BE-GI-NEXT:    mov s6, v4.s[2]
; CHECK-BE-GI-NEXT:    mov s7, v4.s[3]
; CHECK-BE-GI-NEXT:    mov v3.s[1], v0.s[0]
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI2_0]
; CHECK-BE-GI-NEXT:    mov v3.s[2], v1.s[0]
; CHECK-BE-GI-NEXT:    mov v3.s[3], v2.s[0]
; CHECK-BE-GI-NEXT:    mov v4.s[1], v5.s[0]
; CHECK-BE-GI-NEXT:    mov v4.s[2], v6.s[0]
; CHECK-BE-GI-NEXT:    mov v4.s[3], v7.s[0]
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v3.16b, v4.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %s3 = shufflevector <16 x i32> %x, <16 x i32> %y, <4 x i32> <i32 3, i32 6, i32 5, i32 2>
  ret <4 x i32> %s3
}

define <4 x i32> @test_shuf4(<16 x i32> %x, <16 x i32> %y) {
; CHECK-LE-SD-LABEL: test_shuf4:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    uzp2 v0.4s, v2.4s, v4.4s
; CHECK-LE-SD-NEXT:    trn1 v0.4s, v0.4s, v2.4s
; CHECK-LE-SD-NEXT:    mov v0.s[3], v7.s[0]
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf4:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v4.4s
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v2.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v7.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    uzp2 v0.4s, v1.4s, v0.4s
; CHECK-BE-SD-NEXT:    trn1 v0.4s, v0.4s, v1.4s
; CHECK-BE-SD-NEXT:    mov v0.s[3], v2.s[0]
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf4:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    mov s0, v2.s[1]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v2.s[0]
; CHECK-LE-GI-NEXT:    mov v0.s[2], v4.s[1]
; CHECK-LE-GI-NEXT:    mov v0.s[3], v7.s[0]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf4:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    mov s0, v1.s[1]
; CHECK-BE-GI-NEXT:    mov s2, v7.s[1]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v1.s[0]
; CHECK-BE-GI-NEXT:    mov v0.s[2], v2.s[0]
; CHECK-BE-GI-NEXT:    mov v0.s[3], v4.s[0]
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %s3 = shufflevector <16 x i32> %x, <16 x i32> %y, <4 x i32> <i32 9, i32 8, i32 17, i32 28>
  ret <4 x i32> %s3
}

define <4 x i32> @test_shuf5(<16 x i32> %x, <16 x i32> %y) {
; CHECK-LE-SD-LABEL: test_shuf5:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ext v1.16b, v6.16b, v4.16b, #12
; CHECK-LE-SD-NEXT:    rev64 v0.4s, v7.4s
; CHECK-LE-SD-NEXT:    mov v0.d[0], v1.d[0]
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf5:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v7.4s
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v4.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v6.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v2.16b, v1.16b, #12
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    mov v0.d[0], v1.d[0]
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf5:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    mov s0, v6.s[3]
; CHECK-LE-GI-NEXT:    mov v0.s[1], v4.s[0]
; CHECK-LE-GI-NEXT:    mov v0.s[2], v7.s[3]
; CHECK-LE-GI-NEXT:    mov v0.s[3], v7.s[2]
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf5:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    mov s0, v5.s[3]
; CHECK-BE-GI-NEXT:    mov s1, v4.s[3]
; CHECK-BE-GI-NEXT:    mov s2, v4.s[2]
; CHECK-BE-GI-NEXT:    mov v0.s[1], v7.s[0]
; CHECK-BE-GI-NEXT:    mov v0.s[2], v1.s[0]
; CHECK-BE-GI-NEXT:    mov v0.s[3], v2.s[0]
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %s3 = shufflevector <16 x i32> %x, <16 x i32> %y, <4 x i32> <i32 27, i32 16, i32 31, i32 30>
  ret <4 x i32> %s3
}

define <4 x i32> @test1503(<4 x i32> %a, <4 x i32> %b)
; CHECK-LE-SD-LABEL: test1503:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    zip1 v1.4s, v0.4s, v1.4s
; CHECK-LE-SD-NEXT:    ext v1.16b, v1.16b, v0.16b, #8
; CHECK-LE-SD-NEXT:    mov v1.s[3], v0.s[3]
; CHECK-LE-SD-NEXT:    mov v0.16b, v1.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test1503:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    zip1 v1.4s, v0.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    mov v1.s[3], v0.s[3]
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test1503:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI5_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI5_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test1503:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI5_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI5_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 1, i32 5, i32 0, i32 3>
  ret <4 x i32> %r
}

define <4 x i32> @test4366(<4 x i32> %a, <4 x i32> %b)
; CHECK-LE-SD-LABEL: test4366:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    trn1 v1.4s, v1.4s, v1.4s
; CHECK-LE-SD-NEXT:    mov v1.s[1], v0.s[3]
; CHECK-LE-SD-NEXT:    mov v0.16b, v1.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test4366:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    trn1 v1.4s, v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    mov v1.s[1], v0.s[3]
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test4366:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI6_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI6_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test4366:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI6_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI6_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 4, i32 3, i32 6, i32 6>
  ret <4 x i32> %r
}

define <4 x i32> @test7367(<4 x i32> %a, <4 x i32> %b)
; CHECK-LE-SD-LABEL: test7367:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    mov v2.16b, v1.16b
; CHECK-LE-SD-NEXT:    mov v2.d[0], v0.d[1]
; CHECK-LE-SD-NEXT:    mov v2.s[0], v1.s[3]
; CHECK-LE-SD-NEXT:    mov v0.16b, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test7367:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    mov v2.d[0], v0.d[1]
; CHECK-BE-SD-NEXT:    ext v0.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v2.4s
; CHECK-BE-SD-NEXT:    mov v1.s[0], v0.s[3]
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test7367:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI7_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI7_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test7367:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI7_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI7_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 7, i32 3, i32 6, i32 7>
  ret <4 x i32> %r
}

define <4 x i32> @test4045(<4 x i32> %a, <4 x i32> %b)
; CHECK-LE-SD-LABEL: test4045:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    trn1 v0.4s, v1.4s, v0.4s
; CHECK-LE-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test4045:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v2.4s, v1.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-BE-SD-NEXT:    trn1 v0.4s, v2.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test4045:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI8_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI8_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test4045:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI8_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI8_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 4, i32 0, i32 4, i32 5>
  ret <4 x i32> %r
}

define <4 x i32> @test0067(<4 x i32> %a, <4 x i32> %b)
; CHECK-LE-SD-LABEL: test0067:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    trn1 v0.4s, v0.4s, v0.4s
; CHECK-LE-SD-NEXT:    mov v0.d[1], v1.d[1]
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test0067:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    trn1 v0.4s, v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    mov v0.d[1], v1.d[1]
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test0067:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI9_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI9_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test0067:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI9_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI9_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 0, i32 0, i32 6, i32 7>
  ret <4 x i32> %r
}

define <4 x i32> @test_shuf6(<4 x i32> %a, <4 x i32> %b)
; CHECK-LE-SD-LABEL: test_shuf6:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    mov v0.s[2], v1.s[3]
; CHECK-LE-SD-NEXT:    trn1 v0.4s, v0.4s, v0.4s
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf6:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v1.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    mov v0.s[2], v1.s[3]
; CHECK-BE-SD-NEXT:    trn1 v0.4s, v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf6:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI10_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI10_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf6:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    rev64 v1.4s, v1.4s
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI10_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI10_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 0, i32 0, i32 7, i32 7>
  ret <4 x i32> %r
}

define <4 x i16> @test_shuf7(<4 x i16> %a, <4 x i16> %b)
; CHECK-LE-SD-LABEL: test_shuf7:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-LE-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-LE-SD-NEXT:    mov v0.h[2], v1.h[3]
; CHECK-LE-SD-NEXT:    trn1 v0.4h, v0.4h, v0.4h
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf7:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.4h, v1.4h
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    mov v0.h[2], v1.h[3]
; CHECK-BE-SD-NEXT:    trn1 v0.4h, v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf7:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-LE-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI11_0
; CHECK-LE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-LE-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI11_0]
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf7:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    rev64 v1.4h, v1.4h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI11_0
; CHECK-BE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-BE-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI11_0]
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; CHECK-BE-GI-NEXT:    rev64 v0.4h, v0.4h
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <4 x i16> %a, <4 x i16> %b, <4 x i32> <i32 0, i32 0, i32 7, i32 7>
  ret <4 x i16> %r
}

define <8 x i8> @test_shuf8(<8 x i8> %a, <8 x i8> %b)
; CHECK-LE-SD-LABEL: test_shuf8:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-LE-SD-NEXT:    mov x8, #8830452760576 // =0x80800000000
; CHECK-LE-SD-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-LE-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-LE-SD-NEXT:    movk x8, #2056, lsl #48
; CHECK-LE-SD-NEXT:    fmov d1, x8
; CHECK-LE-SD-NEXT:    tbl v0.8b, { v0.16b }, v1.8b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf8:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    rev64 v1.8b, v1.8b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI12_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI12_0
; CHECK-BE-SD-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-BE-SD-NEXT:    ld1 { v1.8b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.8b, { v0.16b }, v1.8b
; CHECK-BE-SD-NEXT:    rev64 v0.8b, v0.8b
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf8:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-LE-GI-NEXT:    // kill: def $d1 killed $d1 def $q1
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI12_0
; CHECK-LE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-LE-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI12_0]
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; CHECK-LE-GI-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf8:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8b, v0.8b
; CHECK-BE-GI-NEXT:    rev64 v1.8b, v1.8b
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI12_0
; CHECK-BE-GI-NEXT:    mov v0.d[1], v1.d[0]
; CHECK-BE-GI-NEXT:    ldr d1, [x8, :lo12:.LCPI12_0]
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8b, v0.8b
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x i8> %a, <8 x i8> %b, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 8, i32 8, i32 8, i32 8>
  ret <8 x i8> %r
}

define <8 x i16> @test_shuf9(<8 x i16> %a, <8 x i16> %b)
; CHECK-LE-SD-LABEL: test_shuf9:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI13_0
; CHECK-LE-SD-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    ldr q2, [x8, :lo12:.LCPI13_0]
; CHECK-LE-SD-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf9:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI13_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI13_0
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf9:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI13_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI13_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf9:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    rev64 v1.8h, v1.8h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI13_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI13_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x i16> %a, <8 x i16> %b, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 8, i32 8, i32 8, i32 8>
  ret <8 x i16> %r
}

define <16 x i8> @test_shuf10(<16 x i8> %a, <16 x i8> %b)
; CHECK-LE-SD-LABEL: test_shuf10:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI14_0
; CHECK-LE-SD-NEXT:    ldr q1, [x8, :lo12:.LCPI14_0]
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf10:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI14_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI14_0
; CHECK-BE-SD-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v0.16b }, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf10:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI14_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI14_0]
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf10:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI14_0
; CHECK-BE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI14_0]
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-BE-GI-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <16 x i8> %a, <16 x i8> %b, <16 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32     8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8, i32 8 >
  ret <16 x i8> %r
}

define <8 x half> @test_shuf11(<8 x half> %a, <8 x half> %b)
; CHECK-LE-SD-LABEL: test_shuf11:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI15_0
; CHECK-LE-SD-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    ldr q2, [x8, :lo12:.LCPI15_0]
; CHECK-LE-SD-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf11:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI15_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI15_0
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf11:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI15_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI15_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf11:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    rev64 v1.8h, v1.8h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI15_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI15_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x half> %a, <8 x half> %b, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 8, i32 8, i32 8, i32 8>
  ret <8 x half> %r
}

define <8 x half> @test_shuf12(<8 x half> %a, <8 x half> %b)
; CHECK-LE-SD-LABEL: test_shuf12:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI16_0
; CHECK-LE-SD-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    ldr q2, [x8, :lo12:.LCPI16_0]
; CHECK-LE-SD-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf12:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI16_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI16_0
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf12:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI16_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI16_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf12:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    rev64 v1.8h, v1.8h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI16_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI16_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x half> %a, <8 x half> %b, <8 x i32> <i32 0, i32 0, i32 0, i32 0, i32 0, i32 8, i32 1, i32 15>
  ret <8 x half> %r
}

define <8 x half> @test_shuf13(<8 x half> %a, <8 x half> %b)
; CHECK-LE-SD-LABEL: test_shuf13:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI17_0
; CHECK-LE-SD-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    ldr q2, [x8, :lo12:.LCPI17_0]
; CHECK-LE-SD-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf13:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI17_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI17_0
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf13:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI17_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI17_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf13:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    rev64 v1.8h, v1.8h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI17_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI17_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x half> %a, <8 x half> %b, <8 x i32> <i32 1, i32 2, i32 0, i32 0, i32 0, i32 8, i32 1, i32 15>
  ret <8 x half> %r
}

define <8 x half> @test_shuf14(<8 x half> %a, <8 x half> %b)
; CHECK-LE-SD-LABEL: test_shuf14:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI18_0
; CHECK-LE-SD-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    ldr q2, [x8, :lo12:.LCPI18_0]
; CHECK-LE-SD-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf14:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI18_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI18_0
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf14:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI18_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI18_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf14:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    rev64 v1.8h, v1.8h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI18_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI18_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x half> %a, <8 x half> %b, <8 x i32> <i32 1, i32 2, i32 1, i32 1, i32 0, i32 8, i32 1, i32 15>
  ret <8 x half> %r
}

define <8 x half> @test_shuf15(<8 x half> %a, <8 x half> %b)
; CHECK-LE-SD-LABEL: test_shuf15:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    adrp x8, .LCPI19_0
; CHECK-LE-SD-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    ldr q2, [x8, :lo12:.LCPI19_0]
; CHECK-LE-SD-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-SD-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: test_shuf15:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    adrp x8, .LCPI19_0
; CHECK-BE-SD-NEXT:    add x8, x8, :lo12:.LCPI19_0
; CHECK-BE-SD-NEXT:    ext v2.16b, v1.16b, v1.16b, #8
; CHECK-BE-SD-NEXT:    ext v1.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-BE-SD-NEXT:    tbl v0.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-BE-SD-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: test_shuf15:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    adrp x8, .LCPI19_0
; CHECK-LE-GI-NEXT:    // kill: def $q0 killed $q0 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    ldr q2, [x8, :lo12:.LCPI19_0]
; CHECK-LE-GI-NEXT:    // kill: def $q1 killed $q1 killed $q0_q1 def $q0_q1
; CHECK-LE-GI-NEXT:    tbl v0.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: test_shuf15:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    rev64 v1.8h, v1.8h
; CHECK-BE-GI-NEXT:    adrp x8, .LCPI19_0
; CHECK-BE-GI-NEXT:    ext v2.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ldr q0, [x8, :lo12:.LCPI19_0]
; CHECK-BE-GI-NEXT:    ext v3.16b, v1.16b, v1.16b, #8
; CHECK-BE-GI-NEXT:    tbl v0.16b, { v2.16b, v3.16b }, v0.16b
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
{
  %r = shufflevector <8 x half> %a, <8 x half> %b, <8 x i32> <i32 1, i32 2, i32 7, i32 2, i32 0, i32 3, i32 2, i32 15>
  ret <8 x half> %r
}

define <4 x i32> @extract_shuffle(<8 x i16> %j, <4 x i16> %k) {
; CHECK-LE-SD-LABEL: extract_shuffle:
; CHECK-LE-SD:       // %bb.0:
; CHECK-LE-SD-NEXT:    ushll2 v0.4s, v0.8h, #3
; CHECK-LE-SD-NEXT:    ret
;
; CHECK-BE-SD-LABEL: extract_shuffle:
; CHECK-BE-SD:       // %bb.0:
; CHECK-BE-SD-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ushll2 v0.4s, v0.8h, #3
; CHECK-BE-SD-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-SD-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-SD-NEXT:    ret
;
; CHECK-LE-GI-LABEL: extract_shuffle:
; CHECK-LE-GI:       // %bb.0:
; CHECK-LE-GI-NEXT:    mov d0, v0.d[1]
; CHECK-LE-GI-NEXT:    ushll v0.4s, v0.4h, #3
; CHECK-LE-GI-NEXT:    ret
;
; CHECK-BE-GI-LABEL: extract_shuffle:
; CHECK-BE-GI:       // %bb.0:
; CHECK-BE-GI-NEXT:    rev64 v0.8h, v0.8h
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    mov d0, v0.d[1]
; CHECK-BE-GI-NEXT:    ushll v0.4s, v0.4h, #3
; CHECK-BE-GI-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-GI-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-GI-NEXT:    ret
  %a = shufflevector <8 x i16> %j, <8 x i16> poison, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 poison, i32 poison, i32 poison, i32 poison>
  %b = shufflevector <8 x i16> %a, <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %c = zext <4 x i16> %b to <4 x i32>
  %d = shl <4 x i32> %c, <i32 3, i32 3, i32 3, i32 3>
  ret <4 x i32> %d
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-BE: {{.*}}
; CHECK-LE: {{.*}}
