; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu    | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu | FileCheck %s --check-prefixes=CHECK-BE,CHECK-SD-BE
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-linux-gnu -global-isel   | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64_be-linux-gnu -global-isel   | FileCheck %s --check-prefixes=CHECK-BE,CHECK-GI-BE

define void @test_split_f(<4 x float> %val, ptr %addr) {
; CHECK-LE-LABEL: test_split_f:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str q0, [x0]
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test_split_f:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str q0, [x0]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test_split_f:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x0]
; CHECK-GI-BE-NEXT:    ret
  store <4 x float> %val, ptr %addr, align 8
  ret void
}

define void @test_split_d(<2 x double> %val, ptr %addr) {
; CHECK-LE-LABEL: test_split_d:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str q0, [x0]
; CHECK-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test_split_d:
; CHECK-SD-BE:       // %bb.0:
; CHECK-SD-BE-NEXT:    str q0, [x0]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test_split_d:
; CHECK-GI-BE:       // %bb.0:
; CHECK-GI-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x0]
; CHECK-GI-BE-NEXT:    ret
  store <2 x double> %val, ptr %addr, align 8
  ret void
}

define void @test_split_128(fp128 %val, ptr %addr) {
; CHECK-LE-LABEL: test_split_128:
; CHECK-LE:       // %bb.0:
; CHECK-LE-NEXT:    str q0, [x0]
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: test_split_128:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    str q0, [x0]
; CHECK-BE-NEXT:    ret
  store fp128 %val, ptr %addr, align 8
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-GI-LE: {{.*}}
; CHECK-SD-LE: {{.*}}
