; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=arm64-apple-ios -o - %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be-unknown-linux -o - %s | FileCheck --check-prefixes=CHECK-BE,CHECK-SD-BE %s
; RUN: llc -mtriple=arm64-apple-ios -global-isel -o - %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE


define void @trunc_v11i64_to_v11i8_in_loop(ptr %A, ptr %dst) {
; CHECK-SD-LE-LABEL: trunc_v11i64_to_v11i8_in_loop:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    mov w8, #1000 ; =0x3e8
; CHECK-SD-LE-NEXT:  LBB0_1: ; %loop
; CHECK-SD-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-LE-NEXT:    ldp q4, q0, [x0, #48]
; CHECK-SD-LE-NEXT:    subs x8, x8, #1
; CHECK-SD-LE-NEXT:    ldp q3, q2, [x0]
; CHECK-SD-LE-NEXT:    ldr d1, [x0, #80]
; CHECK-SD-LE-NEXT:    ldr q5, [x0, #32]
; CHECK-SD-LE-NEXT:    add x0, x0, #128
; CHECK-SD-LE-NEXT:    uzp1.4s v0, v0, v1
; CHECK-SD-LE-NEXT:    uzp1.4s v1, v5, v4
; CHECK-SD-LE-NEXT:    uzp1.4s v2, v3, v2
; CHECK-SD-LE-NEXT:    xtn.4h v0, v0
; CHECK-SD-LE-NEXT:    uzp1.8h v1, v2, v1
; CHECK-SD-LE-NEXT:    uzp1.8b v2, v0, v0
; CHECK-SD-LE-NEXT:    uzp1.16b v0, v1, v0
; CHECK-SD-LE-NEXT:    mov b1, v2[2]
; CHECK-SD-LE-NEXT:    mov h2, v0[4]
; CHECK-SD-LE-NEXT:    str d0, [x1]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #10]
; CHECK-SD-LE-NEXT:    str h2, [x1, #8]
; CHECK-SD-LE-NEXT:    add x1, x1, #16
; CHECK-SD-LE-NEXT:    b.eq LBB0_1
; CHECK-SD-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: trunc_v11i64_to_v11i8_in_loop:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    mov w8, #1000 // =0x3e8
; CHECK-BE-NEXT:  .LBB0_1: // %loop
; CHECK-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-BE-NEXT:    add x9, x0, #64
; CHECK-BE-NEXT:    add x10, x0, #16
; CHECK-BE-NEXT:    ld1 { v3.2d }, [x0]
; CHECK-BE-NEXT:    ld1 { v0.2d }, [x9]
; CHECK-BE-NEXT:    add x9, x0, #48
; CHECK-BE-NEXT:    ld1 { v1.2d }, [x10]
; CHECK-BE-NEXT:    add x10, x0, #32
; CHECK-BE-NEXT:    ld1 { v2.2d }, [x9]
; CHECK-BE-NEXT:    ldr d5, [x0, #80]
; CHECK-BE-NEXT:    ld1 { v4.2d }, [x10]
; CHECK-BE-NEXT:    subs x8, x8, #1
; CHECK-BE-NEXT:    add x0, x0, #128
; CHECK-BE-NEXT:    uzp1 v1.4s, v3.4s, v1.4s
; CHECK-BE-NEXT:    uzp1 v0.4s, v0.4s, v5.4s
; CHECK-BE-NEXT:    uzp1 v2.4s, v4.4s, v2.4s
; CHECK-BE-NEXT:    xtn v0.4h, v0.4s
; CHECK-BE-NEXT:    uzp1 v1.8h, v1.8h, v2.8h
; CHECK-BE-NEXT:    uzp1 v1.16b, v1.16b, v0.16b
; CHECK-BE-NEXT:    uzp1 v0.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    rev16 v2.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v1.16b, v1.16b
; CHECK-BE-NEXT:    mov b0, v0.b[2]
; CHECK-BE-NEXT:    mov h2, v2.h[4]
; CHECK-BE-NEXT:    str d1, [x1]
; CHECK-BE-NEXT:    stur b0, [x1, #10]
; CHECK-BE-NEXT:    str h2, [x1, #8]
; CHECK-BE-NEXT:    add x1, x1, #16
; CHECK-BE-NEXT:    b.eq .LBB0_1
; CHECK-BE-NEXT:  // %bb.2: // %exit
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_v11i64_to_v11i8_in_loop:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    mov w8, #1000 ; =0x3e8
; CHECK-GI-LE-NEXT:  LBB0_1: ; %loop
; CHECK-GI-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-LE-NEXT:    ldp q0, q1, [x0]
; CHECK-GI-LE-NEXT:    subs x8, x8, #1
; CHECK-GI-LE-NEXT:    ldp q2, q3, [x0, #32]
; CHECK-GI-LE-NEXT:    ldr q4, [x0, #64]
; CHECK-GI-LE-NEXT:    ldr x9, [x0, #80]
; CHECK-GI-LE-NEXT:    add x0, x0, #128
; CHECK-GI-LE-NEXT:    mov d5, v0[1]
; CHECK-GI-LE-NEXT:    str b0, [x1]
; CHECK-GI-LE-NEXT:    mov d0, v1[1]
; CHECK-GI-LE-NEXT:    str b1, [x1, #2]
; CHECK-GI-LE-NEXT:    mov d1, v2[1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #4]
; CHECK-GI-LE-NEXT:    mov d2, v3[1]
; CHECK-GI-LE-NEXT:    str b3, [x1, #6]
; CHECK-GI-LE-NEXT:    mov d3, v4[1]
; CHECK-GI-LE-NEXT:    str b5, [x1, #1]
; CHECK-GI-LE-NEXT:    str b0, [x1, #3]
; CHECK-GI-LE-NEXT:    str b1, [x1, #5]
; CHECK-GI-LE-NEXT:    str b2, [x1, #7]
; CHECK-GI-LE-NEXT:    str b4, [x1, #8]
; CHECK-GI-LE-NEXT:    str b3, [x1, #9]
; CHECK-GI-LE-NEXT:    strb w9, [x1, #10]
; CHECK-GI-LE-NEXT:    add x1, x1, #16
; CHECK-GI-LE-NEXT:    b.eq LBB0_1
; CHECK-GI-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-LE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <11 x i64>, ptr %A, i64 %iv
  %l.A = load <11 x i64>, ptr %gep.A
  %trunc = trunc <11 x i64> %l.A to <11 x i8>
  %gep.dst = getelementptr inbounds <11 x i8>, ptr %dst, i64 %iv
  store <11 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-LE: {{.*}}
; CHECK-SD-BE: {{.*}}
