; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64-apple-ios -o - %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be-unknown-linux -o - %s | FileCheck --check-prefixes=CHECK-BE,CHECK-SD-BE %s
; RUN: llc -mtriple=arm64-apple-ios -global-isel -o - %s | FileCheck %s --check-prefixes=CHECK-LE,CHECK-GI-LE
; RUN: llc -mtriple=aarch64_be-unknown-linux -global-isel -o - %s | FileCheck --check-prefixes=CHECK-BE,CHECK-GI-BE %s


; CHECK-LABEL: lCPI0_0:
; CHECK-NEXT:	.byte	0                               ; 0x0
; CHECK-NEXT:	.byte	4                               ; 0x4
; CHECK-NEXT:	.byte	8                               ; 0x8
; CHECK-NEXT:	.byte	12                              ; 0xc
; CHECK-NEXT:	.byte	16                              ; 0x10
; CHECK-NEXT:	.byte	20                              ; 0x14
; CHECK-NEXT:	.byte	24                              ; 0x18
; CHECK-NEXT:	.byte	28                              ; 0x1c
; CHECK-NEXT:	.byte	32                              ; 0x20
; CHECK-NEXT:	.byte	36                              ; 0x24
; CHECK-NEXT:	.byte	40                              ; 0x28
; CHECK-NEXT:	.byte	44                              ; 0x2c
; CHECK-NEXT:	.byte	48                              ; 0x30
; CHECK-NEXT:	.byte	52                              ; 0x34
; CHECK-NEXT:	.byte	56                              ; 0x38
; CHECK-NEXT:	.byte	60                              ; 0x3c

; CHECK-BE-LABEL:   .LCPI0_0:
; CHECK-BE-NEXT:   .byte    3                               // 0x3
; CHECK-BE-NEXT:   .byte    7                               // 0x7
; CHECK-BE-NEXT:   .byte    11                              // 0xb
; CHECK-BE-NEXT:   .byte    15                              // 0xf
; CHECK-BE-NEXT:   .byte    19                              // 0x13
; CHECK-BE-NEXT:   .byte    23                              // 0x17
; CHECK-BE-NEXT:   .byte    27                              // 0x1b
; CHECK-BE-NEXT:   .byte    31                              // 0x1f
; CHECK-BE-NEXT:   .byte    35                              // 0x23
; CHECK-BE-NEXT:   .byte    39                              // 0x27
; CHECK-BE-NEXT:   .byte    43                              // 0x2b
; CHECK-BE-NEXT:   .byte    47                              // 0x2f
; CHECK-BE-NEXT:   .byte    51                              // 0x33
; CHECK-BE-NEXT:   .byte    55                              // 0x37
; CHECK-BE-NEXT:   .byte    59                              // 0x3b
; CHECK-BE-NEXT:   .byte    63                              // 0x3f

; It's profitable to use a single tbl.4 instruction to lower the truncate.
define void @trunc_v16i32_to_v16i8_in_loop(ptr %A, ptr %dst) {
; CHECK-LE-LABEL: trunc_v16i32_to_v16i8_in_loop:
; CHECK-LE:       ; %bb.0: ; %entry
; CHECK-LE-NEXT:  Lloh0:
; CHECK-LE-NEXT:    adrp x8, lCPI0_0@PAGE
; CHECK-LE-NEXT:  Lloh1:
; CHECK-LE-NEXT:    ldr q0, [x8, lCPI0_0@PAGEOFF]
; CHECK-LE-NEXT:    mov x8, xzr
; CHECK-LE-NEXT:  LBB0_1: ; %loop
; CHECK-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-LE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-LE-NEXT:    ldp q1, q2, [x9]
; CHECK-LE-NEXT:    ldp q3, q4, [x9, #32]
; CHECK-LE-NEXT:    tbl.16b v1, { v1, v2, v3, v4 }, v0
; CHECK-LE-NEXT:    str q1, [x1, x8, lsl #4]
; CHECK-LE-NEXT:    add x8, x8, #1
; CHECK-LE-NEXT:    cmp x8, #1000
; CHECK-LE-NEXT:    b.eq LBB0_1
; CHECK-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-LE-NEXT:    ret
; CHECK-LE-NEXT:    .loh AdrpLdr Lloh0, Lloh1
;
; CHECK-SD-BE-LABEL: trunc_v16i32_to_v16i8_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB0_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-SD-BE-NEXT:    add x10, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x11, x9, #32
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x10]
; CHECK-SD-BE-NEXT:    add x9, x9, #48
; CHECK-SD-BE-NEXT:    ld1 { v3.16b }, [x11]
; CHECK-SD-BE-NEXT:    ld1 { v4.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, x8, lsl #4
; CHECK-SD-BE-NEXT:    add x8, x8, #1
; CHECK-SD-BE-NEXT:    cmp x8, #1000
; CHECK-SD-BE-NEXT:    tbl v1.16b, { v1.16b, v2.16b, v3.16b, v4.16b }, v0.16b
; CHECK-SD-BE-NEXT:    st1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    b.eq .LBB0_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_v16i32_to_v16i8_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI0_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB0_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-GI-BE-NEXT:    add x10, x9, #48
; CHECK-GI-BE-NEXT:    ld1 { v4.4s }, [x9]
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #32
; CHECK-GI-BE-NEXT:    ld1 { v2.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #16
; CHECK-GI-BE-NEXT:    add x9, x1, x8, lsl #4
; CHECK-GI-BE-NEXT:    ld1 { v3.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x8, x8, #1
; CHECK-GI-BE-NEXT:    rev32 v16.16b, v1.16b
; CHECK-GI-BE-NEXT:    cmp x8, #1000
; CHECK-GI-BE-NEXT:    rev32 v17.16b, v2.16b
; CHECK-GI-BE-NEXT:    rev32 v18.16b, v3.16b
; CHECK-GI-BE-NEXT:    rev32 v19.16b, v4.16b
; CHECK-GI-BE-NEXT:    tbl v1.16b, { v16.16b, v17.16b, v18.16b, v19.16b }, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v1.16b }, [x9]
; CHECK-GI-BE-NEXT:    b.eq .LBB0_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <16 x i32>, ptr %A, i64 %iv
  %l.A = load <16 x i32>, ptr %gep.A
  %trunc = trunc <16 x i32> %l.A to <16 x i8>
  %gep.dst = getelementptr inbounds <16 x i8>, ptr %dst, i64 %iv
  store <16 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; Not profitable to use tbl, as materializing the masks requires more
; instructions.
define void @trunc_v16i32_to_v16i8_no_loop(ptr %A, ptr %dst) {
; CHECK-SD-LE-LABEL: trunc_v16i32_to_v16i8_no_loop:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    ldp q1, q0, [x0]
; CHECK-SD-LE-NEXT:    ldp q3, q2, [x0, #32]
; CHECK-SD-LE-NEXT:    uzp1.8h v0, v1, v0
; CHECK-SD-LE-NEXT:    uzp1.8h v2, v3, v2
; CHECK-SD-LE-NEXT:    uzp1.16b v0, v0, v2
; CHECK-SD-LE-NEXT:    str q0, [x1]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: trunc_v16i32_to_v16i8_no_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    add x8, x0, #16
; CHECK-SD-BE-NEXT:    add x9, x0, #48
; CHECK-SD-BE-NEXT:    add x10, x0, #32
; CHECK-SD-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-SD-BE-NEXT:    ld1 { v1.4s }, [x8]
; CHECK-SD-BE-NEXT:    ld1 { v2.4s }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v3.4s }, [x10]
; CHECK-SD-BE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-SD-BE-NEXT:    uzp1 v2.8h, v3.8h, v2.8h
; CHECK-SD-BE-NEXT:    uzp1 v0.16b, v0.16b, v2.16b
; CHECK-SD-BE-NEXT:    st1 { v0.16b }, [x1]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_v16i32_to_v16i8_no_loop:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    ldp q0, q1, [x0]
; CHECK-GI-LE-NEXT:    ldp q2, q3, [x0, #32]
; CHECK-GI-LE-NEXT:    uzp1.8h v0, v0, v1
; CHECK-GI-LE-NEXT:    uzp1.8h v1, v2, v3
; CHECK-GI-LE-NEXT:    uzp1.16b v0, v0, v1
; CHECK-GI-LE-NEXT:    str q0, [x1]
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_v16i32_to_v16i8_no_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    add x8, x0, #48
; CHECK-GI-BE-NEXT:    add x9, x0, #32
; CHECK-GI-BE-NEXT:    add x10, x0, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.4s }, [x8]
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x9]
; CHECK-GI-BE-NEXT:    ld1 { v2.4s }, [x10]
; CHECK-GI-BE-NEXT:    ld1 { v3.4s }, [x0]
; CHECK-GI-BE-NEXT:    uzp1 v0.8h, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    uzp1 v1.8h, v2.8h, v3.8h
; CHECK-GI-BE-NEXT:    uzp1 v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.16b }, [x1]
; CHECK-GI-BE-NEXT:    ret
entry:
  %l.A = load <16 x i32>, ptr %A
  %trunc = trunc <16 x i32> %l.A to <16 x i8>
  store <16 x i8> %trunc, ptr %dst
  ret void
}


; CHECK-LABEL: lCPI2_0:
; CHECK-NEXT:     .byte    0                               ; 0x0
; CHECK-NEXT:     .byte    4                               ; 0x4
; CHECK-NEXT:     .byte    8                               ; 0x8
; CHECK-NEXT:     .byte    12                              ; 0xc
; CHECK-NEXT:     .byte    16                              ; 0x10
; CHECK-NEXT:     .byte    20                              ; 0x14
; CHECK-NEXT:     .byte    24                              ; 0x18
; CHECK-NEXT:     .byte    28                              ; 0x1c
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff
; CHECK-NEXT:     .byte    255                             ; 0xff

; CHECK-BE-LABEL: .LCPI2_0:
; CHECK-BE-NEXT:     .byte    3                               // 0x3
; CHECK-BE-NEXT:     .byte    7                               // 0x7
; CHECK-BE-NEXT:     .byte    11                              // 0xb
; CHECK-BE-NEXT:     .byte    15                              // 0xf
; CHECK-BE-NEXT:     .byte    19                              // 0x13
; CHECK-BE-NEXT:     .byte    23                              // 0x17
; CHECK-BE-NEXT:     .byte    27                              // 0x1b
; CHECK-BE-NEXT:     .byte    31                              // 0x1f
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; CHECK-BE-NEXT:     .byte    255                             // 0xff
; It's profitable to use a single tbl.2 instruction to lower the truncate.
define void @trunc_v8i32_to_v8i8_in_loop(ptr %A, ptr %dst) {
; CHECK-LE-LABEL: trunc_v8i32_to_v8i8_in_loop:
; CHECK-LE:       ; %bb.0: ; %entry
; CHECK-LE-NEXT:  Lloh2:
; CHECK-LE-NEXT:    adrp x8, lCPI2_0@PAGE
; CHECK-LE-NEXT:  Lloh3:
; CHECK-LE-NEXT:    ldr q0, [x8, lCPI2_0@PAGEOFF]
; CHECK-LE-NEXT:    mov x8, xzr
; CHECK-LE-NEXT:  LBB2_1: ; %loop
; CHECK-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-LE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-LE-NEXT:    ldp q1, q2, [x9]
; CHECK-LE-NEXT:    tbl.16b v1, { v1, v2 }, v0
; CHECK-LE-NEXT:    str d1, [x1, x8, lsl #3]
; CHECK-LE-NEXT:    add x8, x8, #1
; CHECK-LE-NEXT:    cmp x8, #1000
; CHECK-LE-NEXT:    b.eq LBB2_1
; CHECK-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-LE-NEXT:    ret
; CHECK-LE-NEXT:    .loh AdrpLdr Lloh2, Lloh3
;
; CHECK-SD-BE-LABEL: trunc_v8i32_to_v8i8_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI2_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI2_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB2_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-SD-BE-NEXT:    add x10, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, x8, lsl #3
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x10]
; CHECK-SD-BE-NEXT:    add x8, x8, #1
; CHECK-SD-BE-NEXT:    cmp x8, #1000
; CHECK-SD-BE-NEXT:    tbl v1.16b, { v1.16b, v2.16b }, v0.16b
; CHECK-SD-BE-NEXT:    st1 { v1.8b }, [x9]
; CHECK-SD-BE-NEXT:    b.eq .LBB2_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_v8i32_to_v8i8_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI2_0
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI2_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB2_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-GI-BE-NEXT:    add x10, x9, #16
; CHECK-GI-BE-NEXT:    ld1 { v2.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, x8, lsl #3
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x8, x8, #1
; CHECK-GI-BE-NEXT:    cmp x8, #1000
; CHECK-GI-BE-NEXT:    rev32 v3.16b, v1.16b
; CHECK-GI-BE-NEXT:    rev32 v4.16b, v2.16b
; CHECK-GI-BE-NEXT:    tbl v1.16b, { v3.16b, v4.16b }, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v1.8b }, [x9]
; CHECK-GI-BE-NEXT:    b.eq .LBB2_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <8 x i32>, ptr %A, i64 %iv
  %l.A = load <8 x i32>, ptr %gep.A
  %trunc = trunc <8 x i32> %l.A to <8 x i8>
  %gep.dst = getelementptr inbounds <8 x i8>, ptr %dst, i64 %iv
  store <8 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; CHECK-LABEL:   lCPI3_0:
; CHECK-NEXT:   	.byte	0                               ; 0x0
; CHECK-NEXT:   	.byte	8                               ; 0x8
; CHECK-NEXT:   	.byte	16                              ; 0x10
; CHECK-NEXT:   	.byte	24                              ; 0x18
; CHECK-NEXT:   	.byte	32                              ; 0x20
; CHECK-NEXT:   	.byte	40                              ; 0x28
; CHECK-NEXT:   	.byte	48                              ; 0x30
; CHECK-NEXT:   	.byte	56                              ; 0x38
; CHECK-NEXT:   	.byte	64                              ; 0x40
; CHECK-NEXT:   	.byte	72                              ; 0x48
; CHECK-NEXT:   	.byte	80                              ; 0x50
; CHECK-NEXT:   	.byte	88                              ; 0x58
; CHECK-NEXT:   	.byte	96                              ; 0x60
; CHECK-NEXT:   	.byte	104                             ; 0x68
; CHECK-NEXT:   	.byte	112                             ; 0x70
; CHECK-NEXT:   	.byte	120                             ; 0x78

; CHECK-BE-LABEL:    .LCPI3_0:
; CHECK-BE-NEXT:    	.byte	7                               // 0x7
; CHECK-BE-NEXT:    	.byte	15                              // 0xf
; CHECK-BE-NEXT:    	.byte	23                              // 0x17
; CHECK-BE-NEXT:    	.byte	31                              // 0x1f
; CHECK-BE-NEXT:    	.byte	39                              // 0x27
; CHECK-BE-NEXT:    	.byte	47                              // 0x2f
; CHECK-BE-NEXT:    	.byte	55                              // 0x37
; CHECK-BE-NEXT:    	.byte	63                              // 0x3f
; CHECK-BE-NEXT:    	.byte	71                              // 0x47
; CHECK-BE-NEXT:    	.byte	79                              // 0x4f
; CHECK-BE-NEXT:    	.byte	87                              // 0x57
; CHECK-BE-NEXT:    	.byte	95                              // 0x5f
; CHECK-BE-NEXT:    	.byte	103                             // 0x67
; CHECK-BE-NEXT:    	.byte	111                             // 0x6f
; CHECK-BE-NEXT:    	.byte	119                             // 0x77
; CHECK-BE-NEXT:    	.byte	127                             // 0x7f
define void @trunc_v16i64_to_v16i8_in_loop(ptr %A, ptr %dst) {
; CHECK-SD-LE-LABEL: trunc_v16i64_to_v16i8_in_loop:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:  Lloh4:
; CHECK-SD-LE-NEXT:    adrp x8, lCPI3_0@PAGE
; CHECK-SD-LE-NEXT:  Lloh5:
; CHECK-SD-LE-NEXT:    ldr q0, [x8, lCPI3_0@PAGEOFF]
; CHECK-SD-LE-NEXT:    mov x8, xzr
; CHECK-SD-LE-NEXT:  LBB3_1: ; %loop
; CHECK-SD-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-LE-NEXT:    add x9, x0, x8, lsl #7
; CHECK-SD-LE-NEXT:    ldp q1, q2, [x9]
; CHECK-SD-LE-NEXT:    ldp q16, q17, [x9, #64]
; CHECK-SD-LE-NEXT:    ldp q3, q4, [x9, #32]
; CHECK-SD-LE-NEXT:    ldp q18, q19, [x9, #96]
; CHECK-SD-LE-NEXT:    tbl.16b v1, { v1, v2, v3, v4 }, v0
; CHECK-SD-LE-NEXT:    tbl.16b v2, { v16, v17, v18, v19 }, v0
; CHECK-SD-LE-NEXT:    mov.d v1[1], v2[0]
; CHECK-SD-LE-NEXT:    str q1, [x1, x8, lsl #4]
; CHECK-SD-LE-NEXT:    add x8, x8, #1
; CHECK-SD-LE-NEXT:    cmp x8, #1000
; CHECK-SD-LE-NEXT:    b.eq LBB3_1
; CHECK-SD-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-LE-NEXT:    ret
; CHECK-SD-LE-NEXT:    .loh AdrpLdr Lloh4, Lloh5
;
; CHECK-SD-BE-LABEL: trunc_v16i64_to_v16i8_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI3_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI3_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB3_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8, lsl #7
; CHECK-SD-BE-NEXT:    add x13, x9, #64
; CHECK-SD-BE-NEXT:    add x12, x9, #80
; CHECK-SD-BE-NEXT:    add x14, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v16.16b }, [x13]
; CHECK-SD-BE-NEXT:    add x11, x9, #96
; CHECK-SD-BE-NEXT:    add x13, x9, #32
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x14]
; CHECK-SD-BE-NEXT:    ld1 { v17.16b }, [x12]
; CHECK-SD-BE-NEXT:    add x10, x9, #112
; CHECK-SD-BE-NEXT:    add x9, x9, #48
; CHECK-SD-BE-NEXT:    ld1 { v3.16b }, [x13]
; CHECK-SD-BE-NEXT:    ld1 { v18.16b }, [x11]
; CHECK-SD-BE-NEXT:    ld1 { v4.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, x8, lsl #4
; CHECK-SD-BE-NEXT:    ld1 { v19.16b }, [x10]
; CHECK-SD-BE-NEXT:    add x8, x8, #1
; CHECK-SD-BE-NEXT:    cmp x8, #1000
; CHECK-SD-BE-NEXT:    tbl v1.16b, { v1.16b, v2.16b, v3.16b, v4.16b }, v0.16b
; CHECK-SD-BE-NEXT:    tbl v2.16b, { v16.16b, v17.16b, v18.16b, v19.16b }, v0.16b
; CHECK-SD-BE-NEXT:    mov v1.d[1], v2.d[0]
; CHECK-SD-BE-NEXT:    st1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    b.eq .LBB3_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_v16i64_to_v16i8_in_loop:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:  Lloh4:
; CHECK-GI-LE-NEXT:    adrp x8, lCPI3_1@PAGE
; CHECK-GI-LE-NEXT:  Lloh5:
; CHECK-GI-LE-NEXT:    adrp x9, lCPI3_0@PAGE
; CHECK-GI-LE-NEXT:  Lloh6:
; CHECK-GI-LE-NEXT:    ldr q0, [x8, lCPI3_1@PAGEOFF]
; CHECK-GI-LE-NEXT:  Lloh7:
; CHECK-GI-LE-NEXT:    ldr q1, [x9, lCPI3_0@PAGEOFF]
; CHECK-GI-LE-NEXT:    mov x8, xzr
; CHECK-GI-LE-NEXT:  LBB3_1: ; %loop
; CHECK-GI-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-LE-NEXT:    add x9, x0, x8, lsl #7
; CHECK-GI-LE-NEXT:    ldp q2, q3, [x9]
; CHECK-GI-LE-NEXT:    ldp q16, q17, [x9, #64]
; CHECK-GI-LE-NEXT:    ldp q4, q5, [x9, #32]
; CHECK-GI-LE-NEXT:    ldp q18, q19, [x9, #96]
; CHECK-GI-LE-NEXT:    tbl.16b v2, { v2, v3, v4, v5 }, v0
; CHECK-GI-LE-NEXT:    tbl.16b v3, { v16, v17, v18, v19 }, v0
; CHECK-GI-LE-NEXT:    tbl.16b v2, { v2, v3 }, v1
; CHECK-GI-LE-NEXT:    str q2, [x1, x8, lsl #4]
; CHECK-GI-LE-NEXT:    add x8, x8, #1
; CHECK-GI-LE-NEXT:    cmp x8, #1000
; CHECK-GI-LE-NEXT:    b.eq LBB3_1
; CHECK-GI-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-LE-NEXT:    ret
; CHECK-GI-LE-NEXT:    .loh AdrpLdr Lloh5, Lloh7
; CHECK-GI-LE-NEXT:    .loh AdrpLdr Lloh4, Lloh6
;
; CHECK-GI-BE-LABEL: trunc_v16i64_to_v16i8_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI3_1
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI3_0
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI3_1]
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI3_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB3_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8, lsl #7
; CHECK-GI-BE-NEXT:    add x10, x9, #112
; CHECK-GI-BE-NEXT:    add x11, x9, #96
; CHECK-GI-BE-NEXT:    ld1 { v2.2d }, [x10]
; CHECK-GI-BE-NEXT:    ld1 { v3.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x10, x9, #80
; CHECK-GI-BE-NEXT:    add x11, x9, #48
; CHECK-GI-BE-NEXT:    ld1 { v4.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #32
; CHECK-GI-BE-NEXT:    ld1 { v5.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x9, #64
; CHECK-GI-BE-NEXT:    ld1 { v6.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #16
; CHECK-GI-BE-NEXT:    ld1 { v7.2d }, [x11]
; CHECK-GI-BE-NEXT:    rev64 v17.16b, v2.16b
; CHECK-GI-BE-NEXT:    ld1 { v16.2d }, [x10]
; CHECK-GI-BE-NEXT:    ld1 { v2.2d }, [x9]
; CHECK-GI-BE-NEXT:    rev64 v18.16b, v3.16b
; CHECK-GI-BE-NEXT:    rev64 v21.16b, v5.16b
; CHECK-GI-BE-NEXT:    rev64 v19.16b, v4.16b
; CHECK-GI-BE-NEXT:    add x9, x1, x8, lsl #4
; CHECK-GI-BE-NEXT:    rev64 v22.16b, v6.16b
; CHECK-GI-BE-NEXT:    rev64 v20.16b, v7.16b
; CHECK-GI-BE-NEXT:    add x8, x8, #1
; CHECK-GI-BE-NEXT:    rev64 v23.16b, v16.16b
; CHECK-GI-BE-NEXT:    cmp x8, #1000
; CHECK-GI-BE-NEXT:    rev64 v24.16b, v2.16b
; CHECK-GI-BE-NEXT:    tbl v2.16b, { v17.16b, v18.16b, v19.16b, v20.16b }, v0.16b
; CHECK-GI-BE-NEXT:    tbl v3.16b, { v21.16b, v22.16b, v23.16b, v24.16b }, v0.16b
; CHECK-GI-BE-NEXT:    tbl v2.16b, { v2.16b, v3.16b }, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v2.16b }, [x9]
; CHECK-GI-BE-NEXT:    b.eq .LBB3_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <16 x i64>, ptr %A, i64 %iv
  %l.A = load <16 x i64>, ptr %gep.A
  %trunc = trunc <16 x i64> %l.A to <16 x i8>
  %gep.dst = getelementptr inbounds <16 x i8>, ptr %dst, i64 %iv
  store <16 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; CHECK-LABEL: lCPI4_0:
; CHECK-NEXT: 	.byte	0                               ; 0x0
; CHECK-NEXT: 	.byte	8                               ; 0x8
; CHECK-NEXT: 	.byte	16                              ; 0x10
; CHECK-NEXT: 	.byte	24                              ; 0x18
; CHECK-NEXT: 	.byte	32                              ; 0x20
; CHECK-NEXT: 	.byte	40                              ; 0x28
; CHECK-NEXT: 	.byte	48                              ; 0x30
; CHECK-NEXT: 	.byte	56                              ; 0x38
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff
; CHECK-NEXT: 	.byte	255                             ; 0xff

; CHECK-BE-LABEL:   .LCPI4_0:
; CHECK-BE-NEXT:   	.byte	7                               // 0x7
; CHECK-BE-NEXT:   	.byte	15                              // 0xf
; CHECK-BE-NEXT:   	.byte	23                              // 0x17
; CHECK-BE-NEXT:   	.byte	31                              // 0x1f
; CHECK-BE-NEXT:   	.byte	39                              // 0x27
; CHECK-BE-NEXT:   	.byte	47                              // 0x2f
; CHECK-BE-NEXT:   	.byte	55                              // 0x37
; CHECK-BE-NEXT:   	.byte	63                              // 0x3f
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
; CHECK-BE-NEXT:   	.byte	255                             // 0xff
define void @trunc_v8i64_to_v8i8_in_loop(ptr %A, ptr %dst) {
; CHECK-SD-LE-LABEL: trunc_v8i64_to_v8i8_in_loop:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:  Lloh6:
; CHECK-SD-LE-NEXT:    adrp x8, lCPI4_0@PAGE
; CHECK-SD-LE-NEXT:  Lloh7:
; CHECK-SD-LE-NEXT:    ldr q0, [x8, lCPI4_0@PAGEOFF]
; CHECK-SD-LE-NEXT:    mov x8, xzr
; CHECK-SD-LE-NEXT:  LBB4_1: ; %loop
; CHECK-SD-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-LE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-SD-LE-NEXT:    ldp q1, q2, [x9]
; CHECK-SD-LE-NEXT:    ldp q3, q4, [x9, #32]
; CHECK-SD-LE-NEXT:    tbl.16b v1, { v1, v2, v3, v4 }, v0
; CHECK-SD-LE-NEXT:    str d1, [x1, x8, lsl #3]
; CHECK-SD-LE-NEXT:    add x8, x8, #1
; CHECK-SD-LE-NEXT:    cmp x8, #1000
; CHECK-SD-LE-NEXT:    b.eq LBB4_1
; CHECK-SD-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-LE-NEXT:    ret
; CHECK-SD-LE-NEXT:    .loh AdrpLdr Lloh6, Lloh7
;
; CHECK-SD-BE-LABEL: trunc_v8i64_to_v8i8_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI4_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI4_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB4_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-SD-BE-NEXT:    add x10, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x11, x9, #32
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x10]
; CHECK-SD-BE-NEXT:    add x9, x9, #48
; CHECK-SD-BE-NEXT:    ld1 { v3.16b }, [x11]
; CHECK-SD-BE-NEXT:    ld1 { v4.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, x8, lsl #3
; CHECK-SD-BE-NEXT:    add x8, x8, #1
; CHECK-SD-BE-NEXT:    cmp x8, #1000
; CHECK-SD-BE-NEXT:    tbl v1.16b, { v1.16b, v2.16b, v3.16b, v4.16b }, v0.16b
; CHECK-SD-BE-NEXT:    st1 { v1.8b }, [x9]
; CHECK-SD-BE-NEXT:    b.eq .LBB4_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_v8i64_to_v8i8_in_loop:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:  Lloh8:
; CHECK-GI-LE-NEXT:    adrp x8, lCPI4_0@PAGE
; CHECK-GI-LE-NEXT:  Lloh9:
; CHECK-GI-LE-NEXT:    ldr q0, [x8, lCPI4_0@PAGEOFF]
; CHECK-GI-LE-NEXT:    mov x8, xzr
; CHECK-GI-LE-NEXT:  LBB4_1: ; %loop
; CHECK-GI-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-LE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-GI-LE-NEXT:    ldp q1, q2, [x9]
; CHECK-GI-LE-NEXT:    ldp q3, q4, [x9, #32]
; CHECK-GI-LE-NEXT:    tbl.16b v1, { v1, v2, v3, v4 }, v0
; CHECK-GI-LE-NEXT:    str d1, [x1, x8, lsl #3]
; CHECK-GI-LE-NEXT:    add x8, x8, #1
; CHECK-GI-LE-NEXT:    cmp x8, #1000
; CHECK-GI-LE-NEXT:    b.eq LBB4_1
; CHECK-GI-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-LE-NEXT:    ret
; CHECK-GI-LE-NEXT:    .loh AdrpLdr Lloh8, Lloh9
;
; CHECK-GI-BE-LABEL: trunc_v8i64_to_v8i8_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI4_0
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI4_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB4_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8, lsl #6
; CHECK-GI-BE-NEXT:    add x10, x9, #48
; CHECK-GI-BE-NEXT:    ld1 { v4.2d }, [x9]
; CHECK-GI-BE-NEXT:    ld1 { v1.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #32
; CHECK-GI-BE-NEXT:    ld1 { v2.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #16
; CHECK-GI-BE-NEXT:    add x9, x1, x8, lsl #3
; CHECK-GI-BE-NEXT:    ld1 { v3.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x8, x8, #1
; CHECK-GI-BE-NEXT:    rev64 v16.16b, v1.16b
; CHECK-GI-BE-NEXT:    cmp x8, #1000
; CHECK-GI-BE-NEXT:    rev64 v17.16b, v2.16b
; CHECK-GI-BE-NEXT:    rev64 v18.16b, v3.16b
; CHECK-GI-BE-NEXT:    rev64 v19.16b, v4.16b
; CHECK-GI-BE-NEXT:    tbl v1.16b, { v16.16b, v17.16b, v18.16b, v19.16b }, v0.16b
; CHECK-GI-BE-NEXT:    st1 { v1.8b }, [x9]
; CHECK-GI-BE-NEXT:    b.eq .LBB4_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <8 x i64>, ptr %A, i64 %iv
  %l.A = load <8 x i64>, ptr %gep.A
  %trunc = trunc <8 x i64> %l.A to <8 x i8>
  %gep.dst = getelementptr inbounds <8 x i8>, ptr %dst, i64 %iv
  store <8 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}


define void @trunc_v16i16_to_v16i8_in_loop(ptr %A, ptr %dst) {
; CHECK-SD-LE-LABEL: trunc_v16i16_to_v16i8_in_loop:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    mov x8, xzr
; CHECK-SD-LE-NEXT:  LBB5_1: ; %loop
; CHECK-SD-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-LE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-SD-LE-NEXT:    ldp q1, q0, [x9]
; CHECK-SD-LE-NEXT:    uzp1.16b v0, v1, v0
; CHECK-SD-LE-NEXT:    str q0, [x1, x8, lsl #4]
; CHECK-SD-LE-NEXT:    add x8, x8, #1
; CHECK-SD-LE-NEXT:    cmp x8, #1000
; CHECK-SD-LE-NEXT:    b.eq LBB5_1
; CHECK-SD-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-SD-BE-LABEL: trunc_v16i16_to_v16i8_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB5_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-SD-BE-NEXT:    add x10, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, x8, lsl #4
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x10]
; CHECK-SD-BE-NEXT:    add x8, x8, #1
; CHECK-SD-BE-NEXT:    cmp x8, #1000
; CHECK-SD-BE-NEXT:    uzp1 v0.16b, v0.16b, v1.16b
; CHECK-SD-BE-NEXT:    st1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    b.eq .LBB5_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: trunc_v16i16_to_v16i8_in_loop:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    mov x8, xzr
; CHECK-GI-LE-NEXT:  LBB5_1: ; %loop
; CHECK-GI-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-LE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-GI-LE-NEXT:    ldp q0, q1, [x9]
; CHECK-GI-LE-NEXT:    uzp1.16b v0, v0, v1
; CHECK-GI-LE-NEXT:    str q0, [x1, x8, lsl #4]
; CHECK-GI-LE-NEXT:    add x8, x8, #1
; CHECK-GI-LE-NEXT:    cmp x8, #1000
; CHECK-GI-LE-NEXT:    b.eq LBB5_1
; CHECK-GI-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-LE-NEXT:    ret
;
; CHECK-GI-BE-LABEL: trunc_v16i16_to_v16i8_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB5_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8, lsl #5
; CHECK-GI-BE-NEXT:    add x10, x9, #16
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, x8, lsl #4
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x10]
; CHECK-GI-BE-NEXT:    add x8, x8, #1
; CHECK-GI-BE-NEXT:    cmp x8, #1000
; CHECK-GI-BE-NEXT:    uzp1 v0.16b, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    st1 { v0.16b }, [x9]
; CHECK-GI-BE-NEXT:    b.eq .LBB5_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <16 x i16>, ptr %A, i64 %iv
  %l.A = load <16 x i16>, ptr %gep.A
  %trunc = trunc <16 x i16> %l.A to <16 x i8>
  %gep.dst = getelementptr inbounds <16 x i8>, ptr %dst, i64 %iv
  store <16 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

define void @trunc_v8i16_to_v8i8_in_loop(ptr %A, ptr %dst) {
; CHECK-LE-LABEL: trunc_v8i16_to_v8i8_in_loop:
; CHECK-LE:       ; %bb.0: ; %entry
; CHECK-LE-NEXT:    mov x8, xzr
; CHECK-LE-NEXT:  LBB6_1: ; %loop
; CHECK-LE-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-LE-NEXT:    ldr q0, [x0, x8, lsl #4]
; CHECK-LE-NEXT:    xtn.8b v0, v0
; CHECK-LE-NEXT:    str d0, [x1, x8, lsl #3]
; CHECK-LE-NEXT:    add x8, x8, #1
; CHECK-LE-NEXT:    cmp x8, #1000
; CHECK-LE-NEXT:    b.eq LBB6_1
; CHECK-LE-NEXT:  ; %bb.2: ; %exit
; CHECK-LE-NEXT:    ret
;
; CHECK-BE-LABEL: trunc_v8i16_to_v8i8_in_loop:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    mov x8, xzr
; CHECK-BE-NEXT:  .LBB6_1: // %loop
; CHECK-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-BE-NEXT:    add x9, x0, x8, lsl #4
; CHECK-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-BE-NEXT:    add x9, x1, x8, lsl #3
; CHECK-BE-NEXT:    add x8, x8, #1
; CHECK-BE-NEXT:    cmp x8, #1000
; CHECK-BE-NEXT:    xtn v0.8b, v0.8h
; CHECK-BE-NEXT:    st1 { v0.8b }, [x9]
; CHECK-BE-NEXT:    b.eq .LBB6_1
; CHECK-BE-NEXT:  // %bb.2: // %exit
; CHECK-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.A = getelementptr inbounds <8 x i16>, ptr %A, i64 %iv
  %l.A = load <8 x i16>, ptr %gep.A
  %trunc = trunc <8 x i16> %l.A to <8 x i8>
  %gep.dst = getelementptr inbounds <8 x i8>, ptr %dst, i64 %iv
  store <8 x i8> %trunc, ptr %gep.dst
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1000
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

