; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=arm64-apple-macosx -o - %s | FileCheck %s --check-prefixes CHECK-LE,CHECK-SD-LE
; RUN: llc -mtriple=aarch64_be -o - %s | FileCheck --check-prefixes CHECK-BE,CHECK-SD-BE %s
; RUN: llc -mtriple=arm64-apple-macosx -global-isel -o - %s | FileCheck %s --check-prefixes CHECK-LE,CHECK-GI-LE

define <16 x i8> @load_v3i8(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w9, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    umov w8, v0.h[0]
; CHECK-BE-NEXT:    umov w9, v0.h[1]
; CHECK-BE-NEXT:    fmov s0, w8
; CHECK-BE-NEXT:    add x8, x0, #2
; CHECK-BE-NEXT:    mov v0.b[1], w9
; CHECK-BE-NEXT:    ld1 { v0.b }[2], [x8]
; CHECK-BE-NEXT:    rev64 v0.16b, v0.16b
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr b1, [x0]
; CHECK-GI-LE-NEXT:    add x8, x0, #1
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[1], [x8]
; CHECK-GI-LE-NEXT:    add x8, x0, #2
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[2], [x8]
; CHECK-GI-LE-NEXT:    mov b0, v1[0]
; CHECK-GI-LE-NEXT:    mov.b v0[1], v1[1]
; CHECK-GI-LE-NEXT:    mov.b v0[2], v1[2]
; CHECK-GI-LE-NEXT:    mov.b v0[3], v1[3]
; CHECK-GI-LE-NEXT:    mov.b v0[4], v1[4]
; CHECK-GI-LE-NEXT:    mov.b v0[5], v1[5]
; CHECK-GI-LE-NEXT:    mov.b v0[6], v1[6]
; CHECK-GI-LE-NEXT:    mov.b v0[7], v1[7]
; CHECK-GI-LE-NEXT:    mov.b v0[8], v1[8]
; CHECK-GI-LE-NEXT:    mov.b v0[9], v1[9]
; CHECK-GI-LE-NEXT:    mov.b v0[10], v1[10]
; CHECK-GI-LE-NEXT:    mov.b v0[11], v1[11]
; CHECK-GI-LE-NEXT:    mov.b v0[12], v1[12]
; CHECK-GI-LE-NEXT:    mov.b v0[13], v1[13]
; CHECK-GI-LE-NEXT:    mov.b v0[14], v1[14]
; CHECK-GI-LE-NEXT:    mov.b v0[15], v1[15]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 1
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <16 x i32> <i32 3, i32 4, i32 5, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  ret <16 x i8> %s
}

define <4 x i32> @load_v3i8_to_4xi32(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_to_4xi32:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w9, [x0]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_to_4xi32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    ldrsb w8, [x0, #2]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    mov v0.h[1], v0.h[1]
; CHECK-BE-NEXT:    mov v0.h[2], w8
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_to_4xi32:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr b1, [x0]
; CHECK-GI-LE-NEXT:    add x8, x0, #1
; CHECK-GI-LE-NEXT:    movi d0, #0xff00ff00ff00ff
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[1], [x8]
; CHECK-GI-LE-NEXT:    add x8, x0, #2
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[2], [x8]
; CHECK-GI-LE-NEXT:    mov b2, v1[1]
; CHECK-GI-LE-NEXT:    mov b3, v1[2]
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov b2, v1[3]
; CHECK-GI-LE-NEXT:    mov.h v1[1], w8
; CHECK-GI-LE-NEXT:    fmov w8, s3
; CHECK-GI-LE-NEXT:    mov.h v1[2], w8
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov.h v1[3], w8
; CHECK-GI-LE-NEXT:    and.8b v0, v1, v0
; CHECK-GI-LE-NEXT:    mov.h v1[0], v0[2]
; CHECK-GI-LE-NEXT:    mov.h v1[1], v0[3]
; CHECK-GI-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-GI-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-GI-LE-NEXT:    mov.d v0[1], v1[0]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 1
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <4 x i32> <i32 3, i32 4, i32 5, i32 undef>
  %e = zext <4 x i8> %s to <4 x i32>
  ret <4 x i32> %e
}

define <4 x i32> @load_v3i8_to_4xi32_align_2(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_to_4xi32_align_2:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w9, [x0]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_to_4xi32_align_2:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    ldrsb w8, [x0, #2]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    mov v0.h[1], v0.h[1]
; CHECK-BE-NEXT:    mov v0.h[2], w8
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_to_4xi32_align_2:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr b1, [x0]
; CHECK-GI-LE-NEXT:    add x8, x0, #1
; CHECK-GI-LE-NEXT:    movi d0, #0xff00ff00ff00ff
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[1], [x8]
; CHECK-GI-LE-NEXT:    add x8, x0, #2
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[2], [x8]
; CHECK-GI-LE-NEXT:    mov b2, v1[1]
; CHECK-GI-LE-NEXT:    mov b3, v1[2]
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov b2, v1[3]
; CHECK-GI-LE-NEXT:    mov.h v1[1], w8
; CHECK-GI-LE-NEXT:    fmov w8, s3
; CHECK-GI-LE-NEXT:    mov.h v1[2], w8
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov.h v1[3], w8
; CHECK-GI-LE-NEXT:    and.8b v0, v1, v0
; CHECK-GI-LE-NEXT:    mov.h v1[0], v0[2]
; CHECK-GI-LE-NEXT:    mov.h v1[1], v0[3]
; CHECK-GI-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-GI-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-GI-LE-NEXT:    mov.d v0[1], v1[0]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 2
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <4 x i32> <i32 3, i32 4, i32 5, i32 undef>
  %e = zext <4 x i8> %s to <4 x i32>
  ret <4 x i32> %e
}

define <4 x i32> @load_v3i8_to_4xi32_align_4(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_to_4xi32_align_4:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr s0, [x0]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_to_4xi32_align_4:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ldr s0, [x0]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_to_4xi32_align_4:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    movi d0, #0xff00ff00ff00ff
; CHECK-GI-LE-NEXT:    fmov s1, w8
; CHECK-GI-LE-NEXT:    mov b2, v1[1]
; CHECK-GI-LE-NEXT:    mov.b v3[0], v1[0]
; CHECK-GI-LE-NEXT:    mov b1, v1[2]
; CHECK-GI-LE-NEXT:    mov.b v3[1], v2[0]
; CHECK-GI-LE-NEXT:    mov.b v3[2], v1[0]
; CHECK-GI-LE-NEXT:    mov b1, v3[1]
; CHECK-GI-LE-NEXT:    mov b2, v3[2]
; CHECK-GI-LE-NEXT:    fmov w8, s1
; CHECK-GI-LE-NEXT:    mov b1, v3[3]
; CHECK-GI-LE-NEXT:    mov.h v3[1], w8
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov.h v3[2], w8
; CHECK-GI-LE-NEXT:    fmov w8, s1
; CHECK-GI-LE-NEXT:    mov.h v3[3], w8
; CHECK-GI-LE-NEXT:    and.8b v0, v3, v0
; CHECK-GI-LE-NEXT:    mov.h v1[0], v0[2]
; CHECK-GI-LE-NEXT:    mov.h v1[1], v0[3]
; CHECK-GI-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-GI-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-GI-LE-NEXT:    mov.d v0[1], v1[0]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 4
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <4 x i32> <i32 3, i32 4, i32 5, i32 undef>
  %e = zext <4 x i8> %s to <4 x i32>
  ret <4 x i32> %e
}

define <4 x i32> @load_v3i8_to_4xi32_const_offset_1(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_to_4xi32_const_offset_1:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #3]
; CHECK-SD-LE-NEXT:    ldurh w9, [x0, #1]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_to_4xi32_const_offset_1:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldurh w8, [x0, #1]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    ldrsb w8, [x0, #3]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    mov v0.h[1], v0.h[1]
; CHECK-BE-NEXT:    mov v0.h[2], w8
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_to_4xi32_const_offset_1:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldrb w8, [x0, #1]!
; CHECK-GI-LE-NEXT:    add x9, x0, #1
; CHECK-GI-LE-NEXT:    movi d0, #0xff00ff00ff00ff
; CHECK-GI-LE-NEXT:    fmov s1, w8
; CHECK-GI-LE-NEXT:    add x8, x0, #2
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[1], [x9]
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[2], [x8]
; CHECK-GI-LE-NEXT:    mov b2, v1[1]
; CHECK-GI-LE-NEXT:    mov b3, v1[2]
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov b2, v1[3]
; CHECK-GI-LE-NEXT:    mov.h v1[1], w8
; CHECK-GI-LE-NEXT:    fmov w8, s3
; CHECK-GI-LE-NEXT:    mov.h v1[2], w8
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov.h v1[3], w8
; CHECK-GI-LE-NEXT:    and.8b v0, v1, v0
; CHECK-GI-LE-NEXT:    mov.h v1[0], v0[2]
; CHECK-GI-LE-NEXT:    mov.h v1[1], v0[3]
; CHECK-GI-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-GI-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-GI-LE-NEXT:    mov.d v0[1], v1[0]
; CHECK-GI-LE-NEXT:    ret
  %src.1 = getelementptr inbounds i8, ptr %src, i64 1
  %l = load <3 x i8>, ptr %src.1, align 1
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <4 x i32> <i32 3, i32 4, i32 5, i32 undef>
  %e = zext <4 x i8> %s to <4 x i32>
  ret <4 x i32> %e
}

define <4 x i32> @load_v3i8_to_4xi32_const_offset_3(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_to_4xi32_const_offset_3:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #5]
; CHECK-SD-LE-NEXT:    ldurh w9, [x0, #3]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_to_4xi32_const_offset_3:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldurh w8, [x0, #3]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    ldrsb w8, [x0, #5]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    mov v0.h[1], v0.h[1]
; CHECK-BE-NEXT:    mov v0.h[2], w8
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_to_4xi32_const_offset_3:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldrb w8, [x0, #3]!
; CHECK-GI-LE-NEXT:    add x9, x0, #1
; CHECK-GI-LE-NEXT:    movi d0, #0xff00ff00ff00ff
; CHECK-GI-LE-NEXT:    fmov s1, w8
; CHECK-GI-LE-NEXT:    add x8, x0, #2
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[1], [x9]
; CHECK-GI-LE-NEXT:    ld1.b { v1 }[2], [x8]
; CHECK-GI-LE-NEXT:    mov b2, v1[1]
; CHECK-GI-LE-NEXT:    mov b3, v1[2]
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov b2, v1[3]
; CHECK-GI-LE-NEXT:    mov.h v1[1], w8
; CHECK-GI-LE-NEXT:    fmov w8, s3
; CHECK-GI-LE-NEXT:    mov.h v1[2], w8
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov.h v1[3], w8
; CHECK-GI-LE-NEXT:    and.8b v0, v1, v0
; CHECK-GI-LE-NEXT:    mov.h v1[0], v0[2]
; CHECK-GI-LE-NEXT:    mov.h v1[1], v0[3]
; CHECK-GI-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-GI-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-GI-LE-NEXT:    mov.d v0[1], v1[0]
; CHECK-GI-LE-NEXT:    ret
  %src.3 = getelementptr inbounds i8, ptr %src, i64 3
  %l = load <3 x i8>, ptr %src.3, align 1
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <4 x i32> <i32 3, i32 4, i32 5, i32 undef>
  %e = zext <4 x i8> %s to <4 x i32>
  ret <4 x i32> %e
}

define <4 x i32> @volatile_load_v3i8_to_4xi32(ptr %src) {
; CHECK-SD-LE-LABEL: volatile_load_v3i8_to_4xi32:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    sub sp, sp, #16
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    ldrh w8, [x0]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    strh w8, [sp, #12]
; CHECK-SD-LE-NEXT:    ldr s0, [sp, #12]
; CHECK-SD-LE-NEXT:    ldrsb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-LE-NEXT:    mov.h v0[1], v0[1]
; CHECK-SD-LE-NEXT:    mov.h v0[2], w8
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    add sp, sp, #16
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: volatile_load_v3i8_to_4xi32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    ldrsb w8, [x0, #2]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    mov v0.h[1], v0.h[1]
; CHECK-BE-NEXT:    mov v0.h[2], w8
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: volatile_load_v3i8_to_4xi32:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr b1, [x0]
; CHECK-GI-LE-NEXT:    ldr b2, [x0, #1]
; CHECK-GI-LE-NEXT:    movi d0, #0xff00ff00ff00ff
; CHECK-GI-LE-NEXT:    ldr b3, [x0, #2]
; CHECK-GI-LE-NEXT:    mov.b v1[0], v1[0]
; CHECK-GI-LE-NEXT:    mov.b v1[1], v2[0]
; CHECK-GI-LE-NEXT:    mov.b v1[2], v3[0]
; CHECK-GI-LE-NEXT:    mov b2, v1[1]
; CHECK-GI-LE-NEXT:    mov b3, v1[2]
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov b2, v1[3]
; CHECK-GI-LE-NEXT:    mov.h v1[1], w8
; CHECK-GI-LE-NEXT:    fmov w8, s3
; CHECK-GI-LE-NEXT:    mov.h v1[2], w8
; CHECK-GI-LE-NEXT:    fmov w8, s2
; CHECK-GI-LE-NEXT:    mov.h v1[3], w8
; CHECK-GI-LE-NEXT:    and.8b v0, v1, v0
; CHECK-GI-LE-NEXT:    mov.h v1[0], v0[2]
; CHECK-GI-LE-NEXT:    mov.h v1[1], v0[3]
; CHECK-GI-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-GI-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-GI-LE-NEXT:    mov.d v0[1], v1[0]
; CHECK-GI-LE-NEXT:    ret
  %l = load volatile <3 x i8>, ptr %src, align 1
  %s = shufflevector <3 x i8> poison, <3 x i8> %l, <4 x i32> <i32 3, i32 4, i32 5, i32 undef>
  %e = zext <4 x i8> %s to <4 x i32>
  ret <4 x i32> %e
}

define <3 x i32> @load_v3i32(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i32:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr d0, [x0]
; CHECK-SD-LE-NEXT:    add x8, x0, #8
; CHECK-SD-LE-NEXT:    ld1.s { v0 }[2], [x8]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    ldr d0, [x0]
; CHECK-BE-NEXT:    add x8, x0, #8
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ld1 { v0.s }[2], [x8]
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i32:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldr s0, [x0]
; CHECK-GI-LE-NEXT:    add x8, x0, #4
; CHECK-GI-LE-NEXT:    ld1.s { v0 }[1], [x8]
; CHECK-GI-LE-NEXT:    add x8, x0, #8
; CHECK-GI-LE-NEXT:    ld1.s { v0 }[2], [x8]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src, align 1
  ret <3 x i32> %l
}

define <3 x i32> @load_v3i8_zext_to_3xi32(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_zext_to_3xi32:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w9, [x0]
; CHECK-SD-LE-NEXT:    movi.2d v1, #0x0000ff000000ff
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    and.16b v0, v0, v1
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_zext_to_3xi32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    movi v1.2d, #0x0000ff000000ff
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    add x8, x0, #2
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    ld1 { v0.b }[4], [x8]
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_zext_to_3xi32:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldrb w8, [x0]
; CHECK-GI-LE-NEXT:    ldrb w9, [x0, #1]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-GI-LE-NEXT:    mov.s v0[1], w9
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 1
  %e = zext <3 x i8> %l to <3 x i32>
  ret <3 x i32> %e
}

define <3 x i32> @load_v3i8_sext_to_3xi32(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_sext_to_3xi32:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w9, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-LE-NEXT:    shl.4s v0, v0, #24
; CHECK-SD-LE-NEXT:    sshr.4s v0, v0, #24
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_v3i8_sext_to_3xi32:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    add x8, x0, #2
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    ld1 { v0.b }[4], [x8]
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    shl v0.4s, v0.4s, #24
; CHECK-BE-NEXT:    sshr v0.4s, v0.4s, #24
; CHECK-BE-NEXT:    rev64 v0.4s, v0.4s
; CHECK-BE-NEXT:    ext v0.16b, v0.16b, v0.16b, #8
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_sext_to_3xi32:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldrsb w8, [x0]
; CHECK-GI-LE-NEXT:    ldrsb w9, [x0, #1]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    ldrsb w8, [x0, #2]
; CHECK-GI-LE-NEXT:    mov.s v0[1], w9
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 1
  %e = sext <3 x i8> %l to <3 x i32>
  ret <3 x i32> %e
}

define void @store_trunc_from_64bits(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: store_trunc_from_64bits:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    add x8, x0, #4
; CHECK-SD-LE-NEXT:    ld1r.4h { v0 }, [x8]
; CHECK-SD-LE-NEXT:    ldr w8, [x0]
; CHECK-SD-LE-NEXT:    lsr w9, w8, #16
; CHECK-SD-LE-NEXT:    strb w8, [x1]
; CHECK-SD-LE-NEXT:    mov b0, v0[4]
; CHECK-SD-LE-NEXT:    strb w9, [x1, #1]
; CHECK-SD-LE-NEXT:    stur b0, [x1, #2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: store_trunc_from_64bits:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldr s0, [x0]
; CHECK-BE-NEXT:    ldrh w8, [x0, #4]
; CHECK-BE-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-NEXT:    strb w8, [x1, #2]
; CHECK-BE-NEXT:    mov v0.h[2], w8
; CHECK-BE-NEXT:    uzp1 v0.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    rev32 v0.16b, v0.16b
; CHECK-BE-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-BE-NEXT:    str h0, [x1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: store_trunc_from_64bits:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    ldrh w8, [x0]
; CHECK-GI-LE-NEXT:    ldrh w9, [x0, #2]
; CHECK-GI-LE-NEXT:    ldrh w10, [x0, #4]
; CHECK-GI-LE-NEXT:    strb w8, [x1]
; CHECK-GI-LE-NEXT:    strb w9, [x1, #1]
; CHECK-GI-LE-NEXT:    strb w10, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
entry:
  %l = load <3 x i16>, ptr %src, align 1
  %t = trunc <3 x i16> %l to <3 x i8>
  store <3 x i8> %t, ptr %dst, align 1
  ret void
}

define void @store_trunc_add_from_64bits(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: store_trunc_add_from_64bits:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    ldr s0, [x0]
; CHECK-SD-LE-NEXT:    add x9, x0, #4
; CHECK-SD-LE-NEXT:  Lloh0:
; CHECK-SD-LE-NEXT:    adrp x8, lCPI11_0@PAGE
; CHECK-SD-LE-NEXT:  Lloh1:
; CHECK-SD-LE-NEXT:    ldr d1, [x8, lCPI11_0@PAGEOFF]
; CHECK-SD-LE-NEXT:    ld1.h { v0 }[2], [x9]
; CHECK-SD-LE-NEXT:    add.4h v0, v0, v1
; CHECK-SD-LE-NEXT:    mov b1, v0[2]
; CHECK-SD-LE-NEXT:    mov b2, v0[4]
; CHECK-SD-LE-NEXT:    str b0, [x1]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #1]
; CHECK-SD-LE-NEXT:    stur b2, [x1, #2]
; CHECK-SD-LE-NEXT:    ret
; CHECK-SD-LE-NEXT:    .loh AdrpLdr Lloh0, Lloh1
;
; CHECK-BE-LABEL: store_trunc_add_from_64bits:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldr s0, [x0]
; CHECK-BE-NEXT:    add x8, x0, #4
; CHECK-BE-NEXT:    rev32 v0.4h, v0.4h
; CHECK-BE-NEXT:    ld1 { v0.h }[2], [x8]
; CHECK-BE-NEXT:    adrp x8, .LCPI11_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI11_0
; CHECK-BE-NEXT:    ld1 { v1.4h }, [x8]
; CHECK-BE-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: store_trunc_add_from_64bits:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    mov w8, #3 ; =0x3
; CHECK-GI-LE-NEXT:    mov w9, #4 ; =0x4
; CHECK-GI-LE-NEXT:    ldr h1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    add x8, x0, #2
; CHECK-GI-LE-NEXT:    ld1.h { v1 }[1], [x8]
; CHECK-GI-LE-NEXT:    mov w8, #5 ; =0x5
; CHECK-GI-LE-NEXT:    mov.h v0[1], w9
; CHECK-GI-LE-NEXT:    add x9, x0, #4
; CHECK-GI-LE-NEXT:    ld1.h { v1 }[2], [x9]
; CHECK-GI-LE-NEXT:    mov.h v0[2], w8
; CHECK-GI-LE-NEXT:    add.4h v0, v1, v0
; CHECK-GI-LE-NEXT:    mov h1, v0[1]
; CHECK-GI-LE-NEXT:    mov h2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x1]
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
entry:
  %l = load <3 x i16>, ptr %src, align 1
  %a = add <3 x i16> %l, <i16 3, i16 4, i16 5>
  %t = trunc <3 x i16> %a to <3 x i8>
  store <3 x i8> %t, ptr %dst, align 1
  ret void
}

define void @load_ext_to_64bits(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: load_ext_to_64bits:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w9, [x0]
; CHECK-SD-LE-NEXT:    orr w8, w9, w8, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w8
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    bic.4h v0, #255, lsl #8
; CHECK-SD-LE-NEXT:    mov h1, v0[2]
; CHECK-SD-LE-NEXT:    str s0, [x1]
; CHECK-SD-LE-NEXT:    str h1, [x1, #4]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_ext_to_64bits:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    add x8, x0, #2
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    ld1 { v0.b }[4], [x8]
; CHECK-BE-NEXT:    bic v0.4h, #255, lsl #8
; CHECK-BE-NEXT:    rev32 v1.8h, v0.8h
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    str s1, [x1]
; CHECK-BE-NEXT:    str h0, [x1, #4]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_ext_to_64bits:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    ldrb w8, [x0]
; CHECK-GI-LE-NEXT:    ldrb w9, [x0, #1]
; CHECK-GI-LE-NEXT:    ldrb w10, [x0, #2]
; CHECK-GI-LE-NEXT:    uxtb w8, w8
; CHECK-GI-LE-NEXT:    uxtb w9, w9
; CHECK-GI-LE-NEXT:    uxtb w10, w10
; CHECK-GI-LE-NEXT:    strh w8, [x1]
; CHECK-GI-LE-NEXT:    strh w9, [x1, #2]
; CHECK-GI-LE-NEXT:    strh w10, [x1, #4]
; CHECK-GI-LE-NEXT:    ret
entry:
  %l = load <3 x i8>, ptr %src, align 1
  %e = zext <3 x i8> %l to <3 x i16>
  store <3 x i16> %e, ptr %dst, align 1
  ret void
}

define void @load_ext_to_64bits_default_align(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: load_ext_to_64bits_default_align:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    ldr s0, [x0]
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    bic.4h v0, #255, lsl #8
; CHECK-SD-LE-NEXT:    mov h1, v0[2]
; CHECK-SD-LE-NEXT:    str s0, [x1]
; CHECK-SD-LE-NEXT:    str h1, [x1, #4]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_ext_to_64bits_default_align:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    ldr s0, [x0]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    bic v0.4h, #255, lsl #8
; CHECK-BE-NEXT:    rev32 v1.8h, v0.8h
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    str s1, [x1]
; CHECK-BE-NEXT:    str h0, [x1, #4]
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_ext_to_64bits_default_align:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    uxtb w8, w8
; CHECK-GI-LE-NEXT:    strh w8, [x1]
; CHECK-GI-LE-NEXT:    mov b1, v0[1]
; CHECK-GI-LE-NEXT:    mov b2, v0[2]
; CHECK-GI-LE-NEXT:    fmov w9, s1
; CHECK-GI-LE-NEXT:    fmov w10, s2
; CHECK-GI-LE-NEXT:    uxtb w9, w9
; CHECK-GI-LE-NEXT:    uxtb w8, w10
; CHECK-GI-LE-NEXT:    strh w9, [x1, #2]
; CHECK-GI-LE-NEXT:    strh w8, [x1, #4]
; CHECK-GI-LE-NEXT:    ret
entry:
  %l = load <3 x i8>, ptr %src
  %e = zext <3 x i8> %l to <3 x i16>
  store <3 x i16> %e, ptr %dst, align 1
  ret void
}

define void @load_ext_to_64bits_align_4(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: load_ext_to_64bits_align_4:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    ldr s0, [x0]
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    bic.4h v0, #255, lsl #8
; CHECK-SD-LE-NEXT:    mov h1, v0[2]
; CHECK-SD-LE-NEXT:    str s0, [x1]
; CHECK-SD-LE-NEXT:    str h1, [x1, #4]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: load_ext_to_64bits_align_4:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    ldr s0, [x0]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    zip1 v0.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    bic v0.4h, #255, lsl #8
; CHECK-BE-NEXT:    rev32 v1.8h, v0.8h
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    str s1, [x1]
; CHECK-BE-NEXT:    str h0, [x1, #4]
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_ext_to_64bits_align_4:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    ldr w8, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    uxtb w8, w8
; CHECK-GI-LE-NEXT:    strh w8, [x1]
; CHECK-GI-LE-NEXT:    mov b1, v0[1]
; CHECK-GI-LE-NEXT:    mov b2, v0[2]
; CHECK-GI-LE-NEXT:    fmov w9, s1
; CHECK-GI-LE-NEXT:    fmov w10, s2
; CHECK-GI-LE-NEXT:    uxtb w9, w9
; CHECK-GI-LE-NEXT:    uxtb w8, w10
; CHECK-GI-LE-NEXT:    strh w9, [x1, #2]
; CHECK-GI-LE-NEXT:    strh w8, [x1, #4]
; CHECK-GI-LE-NEXT:    ret
entry:
  %l = load <3 x i8>, ptr %src, align 4
  %e = zext <3 x i8> %l to <3 x i16>
  store <3 x i16> %e, ptr %dst, align 1
  ret void
}

define void @load_ext_add_to_64bits(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: load_ext_add_to_64bits:
; CHECK-SD-LE:       ; %bb.0: ; %entry
; CHECK-SD-LE-NEXT:    ldrb w9, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w10, [x0]
; CHECK-SD-LE-NEXT:  Lloh2:
; CHECK-SD-LE-NEXT:    adrp x8, lCPI15_0@PAGE
; CHECK-SD-LE-NEXT:  Lloh3:
; CHECK-SD-LE-NEXT:    ldr d1, [x8, lCPI15_0@PAGEOFF]
; CHECK-SD-LE-NEXT:    orr w9, w10, w9, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w9
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    bic.4h v0, #255, lsl #8
; CHECK-SD-LE-NEXT:    add.4h v0, v0, v1
; CHECK-SD-LE-NEXT:    mov h1, v0[2]
; CHECK-SD-LE-NEXT:    str s0, [x1]
; CHECK-SD-LE-NEXT:    str h1, [x1, #4]
; CHECK-SD-LE-NEXT:    ret
; CHECK-SD-LE-NEXT:    .loh AdrpLdr Lloh2, Lloh3
;
; CHECK-BE-LABEL: load_ext_add_to_64bits:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w8, [x0]
; CHECK-BE-NEXT:    strh w8, [sp, #12]
; CHECK-BE-NEXT:    add x8, x0, #2
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    ld1 { v0.b }[4], [x8]
; CHECK-BE-NEXT:    adrp x8, .LCPI15_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI15_0
; CHECK-BE-NEXT:    ld1 { v1.4h }, [x8]
; CHECK-BE-NEXT:    bic v0.4h, #255, lsl #8
; CHECK-BE-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-BE-NEXT:    rev32 v1.8h, v0.8h
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    str s1, [x1]
; CHECK-BE-NEXT:    str h0, [x1, #4]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_ext_add_to_64bits:
; CHECK-GI-LE:       ; %bb.0: ; %entry
; CHECK-GI-LE-NEXT:    ldrb w9, [x0]
; CHECK-GI-LE-NEXT:    mov w8, #3 ; =0x3
; CHECK-GI-LE-NEXT:    ldrb w10, [x0, #1]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov w11, #4 ; =0x4
; CHECK-GI-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-GI-LE-NEXT:    uxtb w9, w9
; CHECK-GI-LE-NEXT:    uxtb w10, w10
; CHECK-GI-LE-NEXT:    uxtb w8, w8
; CHECK-GI-LE-NEXT:    fmov s1, w9
; CHECK-GI-LE-NEXT:    mov.h v0[1], w11
; CHECK-GI-LE-NEXT:    mov w9, #5 ; =0x5
; CHECK-GI-LE-NEXT:    mov.h v1[1], w10
; CHECK-GI-LE-NEXT:    mov.h v0[2], w9
; CHECK-GI-LE-NEXT:    add x9, x1, #4
; CHECK-GI-LE-NEXT:    mov.h v1[2], w8
; CHECK-GI-LE-NEXT:    add x8, x1, #2
; CHECK-GI-LE-NEXT:    add.4h v0, v1, v0
; CHECK-GI-LE-NEXT:    str h0, [x1]
; CHECK-GI-LE-NEXT:    st1.h { v0 }[1], [x8]
; CHECK-GI-LE-NEXT:    st1.h { v0 }[2], [x9]
; CHECK-GI-LE-NEXT:    ret
entry:
  %l = load <3 x i8>, ptr %src, align 1
  %e = zext <3 x i8> %l to <3 x i16>
  %a = add <3 x i16> %e, <i16 3, i16 4, i16 5>
  store <3 x i16> %a, ptr %dst, align 1
  ret void
}

define void @shift_trunc_store(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: shift_trunc_store:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr q0, [x0]
; CHECK-SD-LE-NEXT:    ushr.4s v0, v0, #16
; CHECK-SD-LE-NEXT:    mov b1, v0[4]
; CHECK-SD-LE-NEXT:    mov b2, v0[8]
; CHECK-SD-LE-NEXT:    str b0, [x1]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #1]
; CHECK-SD-LE-NEXT:    stur b2, [x1, #2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: shift_trunc_store:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    shrn v0.4h, v0.4s, #16
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: shift_trunc_store:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    mov w8, #16 ; =0x10
; CHECK-GI-LE-NEXT:    ldr q1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov.s v0[1], w8
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    neg.4s v0, v0
; CHECK-GI-LE-NEXT:    ushl.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x1]
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src
  %s = lshr <3 x i32> %l, <i32 16, i32 16, i32 16>
  %t = trunc <3 x i32> %s to <3 x i8>
  store <3 x i8> %t, ptr %dst, align 1
  ret void
}

define void @shift_trunc_store_default_align(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: shift_trunc_store_default_align:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr q0, [x0]
; CHECK-SD-LE-NEXT:    ushr.4s v0, v0, #16
; CHECK-SD-LE-NEXT:    mov b1, v0[4]
; CHECK-SD-LE-NEXT:    mov b2, v0[8]
; CHECK-SD-LE-NEXT:    str b0, [x1]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #1]
; CHECK-SD-LE-NEXT:    stur b2, [x1, #2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: shift_trunc_store_default_align:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    shrn v0.4h, v0.4s, #16
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: shift_trunc_store_default_align:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    mov w8, #16 ; =0x10
; CHECK-GI-LE-NEXT:    ldr q1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov.s v0[1], w8
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    neg.4s v0, v0
; CHECK-GI-LE-NEXT:    ushl.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x1]
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src
  %s = lshr <3 x i32> %l, <i32 16, i32 16, i32 16>
  %t = trunc <3 x i32> %s to <3 x i8>
  store <3 x i8> %t, ptr %dst
  ret void
}

define void @shift_trunc_store_align_4(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: shift_trunc_store_align_4:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr q0, [x0]
; CHECK-SD-LE-NEXT:    ushr.4s v0, v0, #16
; CHECK-SD-LE-NEXT:    mov b1, v0[4]
; CHECK-SD-LE-NEXT:    mov b2, v0[8]
; CHECK-SD-LE-NEXT:    str b0, [x1]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #1]
; CHECK-SD-LE-NEXT:    stur b2, [x1, #2]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: shift_trunc_store_align_4:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    shrn v0.4h, v0.4s, #16
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: shift_trunc_store_align_4:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    mov w8, #16 ; =0x10
; CHECK-GI-LE-NEXT:    ldr q1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov.s v0[1], w8
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    neg.4s v0, v0
; CHECK-GI-LE-NEXT:    ushl.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x1]
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src
  %s = lshr <3 x i32> %l, <i32 16, i32 16, i32 16>
  %t = trunc <3 x i32> %s to <3 x i8>
  store <3 x i8> %t, ptr %dst, align 4
  ret void
}

define void @shift_trunc_store_const_offset_1(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: shift_trunc_store_const_offset_1:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr q0, [x0]
; CHECK-SD-LE-NEXT:    ushr.4s v0, v0, #16
; CHECK-SD-LE-NEXT:    mov b1, v0[4]
; CHECK-SD-LE-NEXT:    mov b2, v0[8]
; CHECK-SD-LE-NEXT:    stur b0, [x1, #1]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #2]
; CHECK-SD-LE-NEXT:    stur b2, [x1, #3]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: shift_trunc_store_const_offset_1:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    shrn v0.4h, v0.4s, #16
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #3]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    stur h1, [x1, #1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: shift_trunc_store_const_offset_1:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    mov w8, #16 ; =0x10
; CHECK-GI-LE-NEXT:    ldr q1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov.s v0[1], w8
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    neg.4s v0, v0
; CHECK-GI-LE-NEXT:    ushl.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    fmov w8, s0
; CHECK-GI-LE-NEXT:    strb w8, [x1, #1]!
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src
  %s = lshr <3 x i32> %l, <i32 16, i32 16, i32 16>
  %t = trunc <3 x i32> %s to <3 x i8>
  %dst.1 = getelementptr inbounds i8, ptr %dst, i64 1
  store <3 x i8> %t, ptr %dst.1, align 1
  ret void
}

define void @shift_trunc_store_const_offset_3(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: shift_trunc_store_const_offset_3:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldr q0, [x0]
; CHECK-SD-LE-NEXT:    ushr.4s v0, v0, #16
; CHECK-SD-LE-NEXT:    mov b1, v0[4]
; CHECK-SD-LE-NEXT:    mov b2, v0[8]
; CHECK-SD-LE-NEXT:    stur b0, [x1, #3]
; CHECK-SD-LE-NEXT:    stur b1, [x1, #4]
; CHECK-SD-LE-NEXT:    stur b2, [x1, #5]
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: shift_trunc_store_const_offset_3:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    shrn v0.4h, v0.4s, #16
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #5]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    stur h1, [x1, #3]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: shift_trunc_store_const_offset_3:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    mov w8, #16 ; =0x10
; CHECK-GI-LE-NEXT:    ldr q1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov.s v0[1], w8
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    neg.4s v0, v0
; CHECK-GI-LE-NEXT:    ushl.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    fmov w8, s0
; CHECK-GI-LE-NEXT:    strb w8, [x1, #3]!
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src
  %s = lshr <3 x i32> %l, <i32 16, i32 16, i32 16>
  %t = trunc <3 x i32> %s to <3 x i8>
  %dst.3 = getelementptr inbounds i8, ptr %dst, i64 3
  store <3 x i8> %t, ptr %dst.3, align 1
  ret void
}

define void @shift_trunc_volatile_store(ptr %src, ptr %dst) {
; CHECK-SD-LE-LABEL: shift_trunc_volatile_store:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    sub sp, sp, #16
; CHECK-SD-LE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-SD-LE-NEXT:    ldr q0, [x0]
; CHECK-SD-LE-NEXT:    shrn.4h v0, v0, #16
; CHECK-SD-LE-NEXT:    uzp1.8b v1, v0, v0
; CHECK-SD-LE-NEXT:    mov h0, v0[2]
; CHECK-SD-LE-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-LE-NEXT:    stur b0, [x1, #2]
; CHECK-SD-LE-NEXT:    str h1, [x1]
; CHECK-SD-LE-NEXT:    add sp, sp, #16
; CHECK-SD-LE-NEXT:    ret
;
; CHECK-BE-LABEL: shift_trunc_volatile_store:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ld1 { v0.4s }, [x0]
; CHECK-BE-NEXT:    shrn v0.4h, v0.4s, #16
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x1, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x1]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: shift_trunc_volatile_store:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    mov w8, #16 ; =0x10
; CHECK-GI-LE-NEXT:    ldr q1, [x0]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov.s v0[1], w8
; CHECK-GI-LE-NEXT:    mov.s v0[2], w8
; CHECK-GI-LE-NEXT:    neg.4s v0, v0
; CHECK-GI-LE-NEXT:    ushl.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x1]
; CHECK-GI-LE-NEXT:    str b1, [x1, #1]
; CHECK-GI-LE-NEXT:    str b2, [x1, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i32>, ptr %src
  %s = lshr <3 x i32> %l, <i32 16, i32 16, i32 16>
  %t = trunc <3 x i32> %s to <3 x i8>
  store volatile <3 x i8> %t, ptr %dst, align 1
  ret void
}

define void @load_v3i8_zext_to_3xi32_add_trunc_store(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_zext_to_3xi32_add_trunc_store:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w9, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w10, [x0]
; CHECK-SD-LE-NEXT:  Lloh4:
; CHECK-SD-LE-NEXT:    adrp x8, lCPI22_0@PAGE
; CHECK-SD-LE-NEXT:  Lloh5:
; CHECK-SD-LE-NEXT:    ldr q1, [x8, lCPI22_0@PAGEOFF]
; CHECK-SD-LE-NEXT:    orr w9, w10, w9, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w9
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    uaddw.4s v0, v1, v0
; CHECK-SD-LE-NEXT:    mov b1, v0[8]
; CHECK-SD-LE-NEXT:    mov b2, v0[4]
; CHECK-SD-LE-NEXT:    str b0, [x0]
; CHECK-SD-LE-NEXT:    stur b1, [x0, #2]
; CHECK-SD-LE-NEXT:    stur b2, [x0, #1]
; CHECK-SD-LE-NEXT:    ret
; CHECK-SD-LE-NEXT:    .loh AdrpLdr Lloh4, Lloh5
;
; CHECK-BE-LABEL: load_v3i8_zext_to_3xi32_add_trunc_store:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w9, [x0]
; CHECK-BE-NEXT:    adrp x8, .LCPI22_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI22_0
; CHECK-BE-NEXT:    ld1 { v1.4h }, [x8]
; CHECK-BE-NEXT:    strh w9, [sp, #12]
; CHECK-BE-NEXT:    add x9, x0, #2
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    ld1 { v0.b }[4], [x9]
; CHECK-BE-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x0, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x0]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_zext_to_3xi32_add_trunc_store:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldrb w9, [x0]
; CHECK-GI-LE-NEXT:    mov w8, #1 ; =0x1
; CHECK-GI-LE-NEXT:    ldrb w10, [x0, #1]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov w11, #2 ; =0x2
; CHECK-GI-LE-NEXT:    ldrb w8, [x0, #2]
; CHECK-GI-LE-NEXT:    fmov s1, w9
; CHECK-GI-LE-NEXT:    mov w9, #3 ; =0x3
; CHECK-GI-LE-NEXT:    mov.s v0[1], w11
; CHECK-GI-LE-NEXT:    mov.s v1[1], w10
; CHECK-GI-LE-NEXT:    mov.s v0[2], w9
; CHECK-GI-LE-NEXT:    mov.s v1[2], w8
; CHECK-GI-LE-NEXT:    add.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x0]
; CHECK-GI-LE-NEXT:    str b1, [x0, #1]
; CHECK-GI-LE-NEXT:    str b2, [x0, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 1
  %e = zext <3 x i8> %l to <3 x i32>
  %add = add <3 x i32> %e, <i32 1, i32 2, i32 3>
  %t = trunc <3 x i32> %add to <3 x i8>
  store <3 x i8> %t, ptr %src
  ret void
}

define void @load_v3i8_sext_to_3xi32_add_trunc_store(ptr %src) {
; CHECK-SD-LE-LABEL: load_v3i8_sext_to_3xi32_add_trunc_store:
; CHECK-SD-LE:       ; %bb.0:
; CHECK-SD-LE-NEXT:    ldrb w9, [x0, #2]
; CHECK-SD-LE-NEXT:    ldrh w10, [x0]
; CHECK-SD-LE-NEXT:  Lloh6:
; CHECK-SD-LE-NEXT:    adrp x8, lCPI23_0@PAGE
; CHECK-SD-LE-NEXT:  Lloh7:
; CHECK-SD-LE-NEXT:    ldr q1, [x8, lCPI23_0@PAGEOFF]
; CHECK-SD-LE-NEXT:    orr w9, w10, w9, lsl #16
; CHECK-SD-LE-NEXT:    fmov s0, w9
; CHECK-SD-LE-NEXT:    zip1.8b v0, v0, v0
; CHECK-SD-LE-NEXT:    uaddw.4s v0, v1, v0
; CHECK-SD-LE-NEXT:    mov b1, v0[8]
; CHECK-SD-LE-NEXT:    mov b2, v0[4]
; CHECK-SD-LE-NEXT:    str b0, [x0]
; CHECK-SD-LE-NEXT:    stur b1, [x0, #2]
; CHECK-SD-LE-NEXT:    stur b2, [x0, #1]
; CHECK-SD-LE-NEXT:    ret
; CHECK-SD-LE-NEXT:    .loh AdrpLdr Lloh6, Lloh7
;
; CHECK-BE-LABEL: load_v3i8_sext_to_3xi32_add_trunc_store:
; CHECK-BE:       // %bb.0:
; CHECK-BE-NEXT:    sub sp, sp, #16
; CHECK-BE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-BE-NEXT:    ldrh w9, [x0]
; CHECK-BE-NEXT:    adrp x8, .LCPI23_0
; CHECK-BE-NEXT:    add x8, x8, :lo12:.LCPI23_0
; CHECK-BE-NEXT:    ld1 { v1.4h }, [x8]
; CHECK-BE-NEXT:    strh w9, [sp, #12]
; CHECK-BE-NEXT:    add x9, x0, #2
; CHECK-BE-NEXT:    ldr s0, [sp, #12]
; CHECK-BE-NEXT:    rev32 v0.8b, v0.8b
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    ld1 { v0.b }[4], [x9]
; CHECK-BE-NEXT:    add v0.4h, v0.4h, v1.4h
; CHECK-BE-NEXT:    uzp1 v1.8b, v0.8b, v0.8b
; CHECK-BE-NEXT:    mov h0, v0.h[2]
; CHECK-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-BE-NEXT:    stur b0, [x0, #2]
; CHECK-BE-NEXT:    rev32 v1.4h, v1.4h
; CHECK-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-BE-NEXT:    str h1, [x0]
; CHECK-BE-NEXT:    add sp, sp, #16
; CHECK-BE-NEXT:    ret
;
; CHECK-GI-LE-LABEL: load_v3i8_sext_to_3xi32_add_trunc_store:
; CHECK-GI-LE:       ; %bb.0:
; CHECK-GI-LE-NEXT:    ldrsb w9, [x0]
; CHECK-GI-LE-NEXT:    mov w8, #1 ; =0x1
; CHECK-GI-LE-NEXT:    ldrsb w10, [x0, #1]
; CHECK-GI-LE-NEXT:    fmov s0, w8
; CHECK-GI-LE-NEXT:    mov w11, #2 ; =0x2
; CHECK-GI-LE-NEXT:    ldrsb w8, [x0, #2]
; CHECK-GI-LE-NEXT:    fmov s1, w9
; CHECK-GI-LE-NEXT:    mov w9, #3 ; =0x3
; CHECK-GI-LE-NEXT:    mov.s v0[1], w11
; CHECK-GI-LE-NEXT:    mov.s v1[1], w10
; CHECK-GI-LE-NEXT:    mov.s v0[2], w9
; CHECK-GI-LE-NEXT:    mov.s v1[2], w8
; CHECK-GI-LE-NEXT:    add.4s v0, v1, v0
; CHECK-GI-LE-NEXT:    mov s1, v0[1]
; CHECK-GI-LE-NEXT:    mov s2, v0[2]
; CHECK-GI-LE-NEXT:    str b0, [x0]
; CHECK-GI-LE-NEXT:    str b1, [x0, #1]
; CHECK-GI-LE-NEXT:    str b2, [x0, #2]
; CHECK-GI-LE-NEXT:    ret
  %l = load <3 x i8>, ptr %src, align 1
  %e = sext <3 x i8> %l to <3 x i32>
  %add = add <3 x i32> %e, <i32 1, i32 2, i32 3>
  %t = trunc <3 x i32> %add to <3 x i8>
  store <3 x i8> %t, ptr %src
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-LE: {{.*}}
; CHECK-SD-BE: {{.*}}
