; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64-apple-ios -mattr=+sve -o - %s | FileCheck %s --check-prefixes=CHECK,CHECK-SD
; RUN: llc -mtriple=aarch64_be-unknown-linux -mattr=+sve -o - %s | FileCheck --check-prefixes=CHECK-BE,CHECK-SD-BE %s
; RUN: llc -mtriple=arm64-apple-ios -global-isel -mattr=+sve -o - %s | FileCheck %s --check-prefixes=CHECK,CHECK-GI
; RUN: llc -mtriple=aarch64_be-unknown-linux -global-isel -mattr=+sve -o - %s | FileCheck --check-prefixes=CHECK-BE,CHECK-GI-BE %s

; CHECK-LABEL: lCPI0_0:
; CHECK-NEXT:    .byte   0                               ; 0x0
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   1                               ; 0x1
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   2                               ; 0x2
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   3                               ; 0x3
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:lCPI0_1:
; CHECK-NEXT:    .byte   4                               ; 0x4
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   5                               ; 0x5
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   6                               ; 0x6
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   7                               ; 0x7
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:lCPI0_2:
; CHECK-NEXT:    .byte   8                               ; 0x8
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   9                               ; 0x9
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   10                              ; 0xa
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   11                              ; 0xb
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:lCPI0_3:
; CHECK-NEXT:    .byte   12                              ; 0xc
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   13                              ; 0xd
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   14                              ; 0xe
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   15                              ; 0xf
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff
; CHECK-NEXT:    .byte   255                             ; 0xff

; CHECK-BE: .LCPI0_0:
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	0                               // 0x0
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	1                               // 0x1
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	2                               // 0x2
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	3                               // 0x3
; CHECK-BE-NEXT: .LCPI0_1:
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	4                               // 0x4
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	5                               // 0x5
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	6                               // 0x6
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	7                               // 0x7
; CHECK-BE-NEXT: .LCPI0_2:
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	8                               // 0x8
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	9                               // 0x9
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	10                              // 0xa
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	11                              // 0xb
; CHECK-BE-NEXT: .LCPI0_3:
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	12                              // 0xc
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	13                              // 0xd
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	14                              // 0xe
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	15                              // 0xf

; It's profitable to convert the zext to a shuffle, which in turn will be
; lowered to 4 tbl instructions. The masks are materialized outside the loop.
define void @zext_v16i8_to_v16i32_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i8_to_v16i32_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:  Lloh0:
; CHECK-SD-NEXT:    adrp x8, lCPI0_0@PAGE
; CHECK-SD-NEXT:  Lloh1:
; CHECK-SD-NEXT:    adrp x9, lCPI0_1@PAGE
; CHECK-SD-NEXT:  Lloh2:
; CHECK-SD-NEXT:    adrp x10, lCPI0_2@PAGE
; CHECK-SD-NEXT:  Lloh3:
; CHECK-SD-NEXT:    ldr q0, [x8, lCPI0_0@PAGEOFF]
; CHECK-SD-NEXT:  Lloh4:
; CHECK-SD-NEXT:    adrp x8, lCPI0_3@PAGE
; CHECK-SD-NEXT:  Lloh5:
; CHECK-SD-NEXT:    ldr q1, [x9, lCPI0_1@PAGEOFF]
; CHECK-SD-NEXT:  Lloh6:
; CHECK-SD-NEXT:    ldr q2, [x10, lCPI0_2@PAGEOFF]
; CHECK-SD-NEXT:  Lloh7:
; CHECK-SD-NEXT:    ldr q3, [x8, lCPI0_3@PAGEOFF]
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB0_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q4, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    tbl.16b v5, { v4 }, v3
; CHECK-SD-NEXT:    tbl.16b v6, { v4 }, v2
; CHECK-SD-NEXT:    tbl.16b v7, { v4 }, v1
; CHECK-SD-NEXT:    tbl.16b v4, { v4 }, v0
; CHECK-SD-NEXT:    stp q6, q5, [x1, #32]
; CHECK-SD-NEXT:    stp q4, q7, [x1], #64
; CHECK-SD-NEXT:    b.ne LBB0_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh4, Lloh7
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh2, Lloh6
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh1, Lloh5
; CHECK-SD-NEXT:    .loh AdrpAdrp Lloh0, Lloh4
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh0, Lloh3
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i32_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_1
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_1
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_2
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_2
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI0_3
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI0_3
; CHECK-SD-BE-NEXT:    ld1 { v3.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB0_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v4.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    tbl v5.16b, { v4.16b }, v3.16b
; CHECK-SD-BE-NEXT:    tbl v6.16b, { v4.16b }, v2.16b
; CHECK-SD-BE-NEXT:    tbl v7.16b, { v4.16b }, v1.16b
; CHECK-SD-BE-NEXT:    tbl v4.16b, { v4.16b }, v0.16b
; CHECK-SD-BE-NEXT:    st1 { v5.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v6.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v4.16b }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v7.16b }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB0_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i32_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    movi d1, #0000000000000000
; CHECK-GI-NEXT:  Lloh0:
; CHECK-GI-NEXT:    adrp x8, lCPI0_3@PAGE
; CHECK-GI-NEXT:  Lloh1:
; CHECK-GI-NEXT:    adrp x9, lCPI0_2@PAGE
; CHECK-GI-NEXT:  Lloh2:
; CHECK-GI-NEXT:    ldr q2, [x8, lCPI0_3@PAGEOFF]
; CHECK-GI-NEXT:  Lloh3:
; CHECK-GI-NEXT:    adrp x8, lCPI0_1@PAGE
; CHECK-GI-NEXT:  Lloh4:
; CHECK-GI-NEXT:    adrp x10, lCPI0_0@PAGE
; CHECK-GI-NEXT:  Lloh5:
; CHECK-GI-NEXT:    ldr q3, [x9, lCPI0_2@PAGEOFF]
; CHECK-GI-NEXT:  Lloh6:
; CHECK-GI-NEXT:    ldr q4, [x8, lCPI0_1@PAGEOFF]
; CHECK-GI-NEXT:  Lloh7:
; CHECK-GI-NEXT:    ldr q5, [x10, lCPI0_0@PAGEOFF]
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB0_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    tbl.16b v6, { v0, v1 }, v2
; CHECK-GI-NEXT:    tbl.16b v7, { v0, v1 }, v3
; CHECK-GI-NEXT:    tbl.16b v16, { v0, v1 }, v4
; CHECK-GI-NEXT:    tbl.16b v17, { v0, v1 }, v5
; CHECK-GI-NEXT:    stp q6, q7, [x1]
; CHECK-GI-NEXT:    stp q16, q17, [x1, #32]
; CHECK-GI-NEXT:    add x1, x1, #64
; CHECK-GI-NEXT:    b.ne LBB0_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh4, Lloh7
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh3, Lloh6
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh1, Lloh5
; CHECK-GI-NEXT:    .loh AdrpAdrp Lloh0, Lloh3
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh0, Lloh2
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i32_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    movi d0, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI0_3
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI0_2
; CHECK-GI-BE-NEXT:    ldr q2, [x8, :lo12:.LCPI0_3]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI0_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI0_0
; CHECK-GI-BE-NEXT:    ldr q3, [x9, :lo12:.LCPI0_2]
; CHECK-GI-BE-NEXT:    ldr q4, [x8, :lo12:.LCPI0_1]
; CHECK-GI-BE-NEXT:    ldr q5, [x10, :lo12:.LCPI0_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB0_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    tbl v6.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-GI-BE-NEXT:    tbl v7.16b, { v0.16b, v1.16b }, v3.16b
; CHECK-GI-BE-NEXT:    tbl v17.16b, { v0.16b, v1.16b }, v5.16b
; CHECK-GI-BE-NEXT:    tbl v16.16b, { v0.16b, v1.16b }, v4.16b
; CHECK-GI-BE-NEXT:    rev32 v6.16b, v6.16b
; CHECK-GI-BE-NEXT:    rev32 v7.16b, v7.16b
; CHECK-GI-BE-NEXT:    rev32 v17.16b, v17.16b
; CHECK-GI-BE-NEXT:    rev32 v16.16b, v16.16b
; CHECK-GI-BE-NEXT:    st1 { v6.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v7.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v17.4s }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #64
; CHECK-GI-BE-NEXT:    st1 { v16.4s }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB0_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %ext = zext <16 x i8> %load to <16 x i32>
  %dst.gep = getelementptr i32, ptr %dst, i64 %iv
  store <16 x i32> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v16i8_to_v16i32_in_loop_not_header(ptr %src, ptr %dst, i1 %c) {
; CHECK-SD-LABEL: zext_v16i8_to_v16i32_in_loop_not_header:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:    b LBB1_2
; CHECK-SD-NEXT:  LBB1_1: ; %loop.latch
; CHECK-SD-NEXT:    ; in Loop: Header=BB1_2 Depth=1
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    add x1, x1, #64
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    b.eq LBB1_4
; CHECK-SD-NEXT:  LBB1_2: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    tbz w2, #0, LBB1_1
; CHECK-SD-NEXT:  ; %bb.3: ; %then
; CHECK-SD-NEXT:    ; in Loop: Header=BB1_2 Depth=1
; CHECK-SD-NEXT:    ldr q0, [x0, x8]
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v2, v1, #0
; CHECK-SD-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-NEXT:    ushll2.4s v3, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q2, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q3, [x1]
; CHECK-SD-NEXT:    b LBB1_1
; CHECK-SD-NEXT:  LBB1_4: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i32_in_loop_not_header:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:    b .LBB1_2
; CHECK-SD-BE-NEXT:  .LBB1_1: // %loop.latch
; CHECK-SD-BE-NEXT:    // in Loop: Header=BB1_2 Depth=1
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    add x1, x1, #64
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    b.eq .LBB1_4
; CHECK-SD-BE-NEXT:  .LBB1_2: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    tbz w2, #0, .LBB1_1
; CHECK-SD-BE-NEXT:  // %bb.3: // %then
; CHECK-SD-BE-NEXT:    // in Loop: Header=BB1_2 Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x10, x1, #32
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    st1 { v2.4s }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x10]
; CHECK-SD-BE-NEXT:    st1 { v3.4s }, [x9]
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-SD-BE-NEXT:    b .LBB1_1
; CHECK-SD-BE-NEXT:  .LBB1_4: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i32_in_loop_not_header:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:    b LBB1_2
; CHECK-GI-NEXT:  LBB1_1: ; %loop.latch
; CHECK-GI-NEXT:    ; in Loop: Header=BB1_2 Depth=1
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    add x1, x1, #64
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    b.eq LBB1_4
; CHECK-GI-NEXT:  LBB1_2: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    tbz w2, #0, LBB1_1
; CHECK-GI-NEXT:  ; %bb.3: ; %then
; CHECK-GI-NEXT:    ; in Loop: Header=BB1_2 Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0, x8]
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v2, v1, #0
; CHECK-GI-NEXT:    ushll2.4s v1, v1, #0
; CHECK-GI-NEXT:    ushll.4s v3, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    stp q2, q1, [x1]
; CHECK-GI-NEXT:    stp q3, q0, [x1, #32]
; CHECK-GI-NEXT:    b LBB1_1
; CHECK-GI-NEXT:  LBB1_4: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i32_in_loop_not_header:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:    b .LBB1_2
; CHECK-GI-BE-NEXT:  .LBB1_1: // %loop.latch
; CHECK-GI-BE-NEXT:    // in Loop: Header=BB1_2 Depth=1
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    add x1, x1, #64
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    b.eq .LBB1_4
; CHECK-GI-BE-NEXT:  .LBB1_2: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    tbz w2, #0, .LBB1_1
; CHECK-GI-BE-NEXT:  // %bb.3: // %then
; CHECK-GI-BE-NEXT:    // in Loop: Header=BB1_2 Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x10, x1, #32
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    st1 { v2.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x10]
; CHECK-GI-BE-NEXT:    st1 { v3.4s }, [x9]
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-GI-BE-NEXT:    b .LBB1_1
; CHECK-GI-BE-NEXT:  .LBB1_4: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.latch ]
  br i1 %c, label %then, label %loop.latch

then:
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %ext = zext <16 x i8> %load to <16 x i32>
  %dst.gep = getelementptr i32, ptr %dst, i64 %iv
  store <16 x i32> %ext, ptr %dst.gep
  br label %loop.latch

loop.latch:
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; Not profitable to use shuffle/tbl, as 4 tbls + materializing the masks
; require more instructions than lowering zext directly.
define void @zext_v16i8_to_v16i32_no_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i8_to_v16i32_no_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    ldr q0, [x0]
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v2, v1, #0
; CHECK-SD-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-NEXT:    ushll2.4s v3, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q2, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q3, [x1]
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i32_no_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x0]
; CHECK-SD-BE-NEXT:    add x8, x1, #48
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    st1 { v2.4s }, [x8]
; CHECK-SD-BE-NEXT:    add x8, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-SD-BE-NEXT:    add x8, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v3.4s }, [x8]
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i32_no_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    ldr q0, [x0]
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v2, v1, #0
; CHECK-GI-NEXT:    ushll2.4s v1, v1, #0
; CHECK-GI-NEXT:    ushll.4s v3, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    stp q2, q1, [x1]
; CHECK-GI-NEXT:    stp q3, q0, [x1, #32]
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i32_no_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x0]
; CHECK-GI-BE-NEXT:    add x8, x1, #48
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    st1 { v2.4s }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v3.4s }, [x8]
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-GI-BE-NEXT:    ret
entry:
  %load = load <16 x i8>, ptr %src
  %ext = zext <16 x i8> %load to <16 x i32>
  store <16 x i32> %ext, ptr %dst
  ret void
}

; Avoid using tbl when optimizing for size.
define void @zext_v16i8_to_v16i32_in_loop_optsize(ptr %src, ptr %dst) optsize {
; CHECK-SD-LABEL: zext_v16i8_to_v16i32_in_loop_optsize:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB3_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v2, v1, #0
; CHECK-SD-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-NEXT:    ushll2.4s v3, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q2, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q3, [x1], #64
; CHECK-SD-NEXT:    b.ne LBB3_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i32_in_loop_optsize:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB3_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    st1 { v2.4s }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v3.4s }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB3_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i32_in_loop_optsize:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB3_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v2, v1, #0
; CHECK-GI-NEXT:    ushll2.4s v1, v1, #0
; CHECK-GI-NEXT:    ushll.4s v3, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    stp q2, q1, [x1]
; CHECK-GI-NEXT:    stp q3, q0, [x1, #32]
; CHECK-GI-NEXT:    add x1, x1, #64
; CHECK-GI-NEXT:    b.ne LBB3_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i32_in_loop_optsize:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB3_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    st1 { v2.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #64
; CHECK-GI-BE-NEXT:    st1 { v3.4s }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB3_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %ext = zext <16 x i8> %load to <16 x i32>
  %dst.gep = getelementptr i32, ptr %dst, i64 %iv
  store <16 x i32> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; Avoid using tbl when optimizing for size.
define void @zext_v16i8_to_v16i32_in_loop_minsize(ptr %src, ptr %dst) minsize {
; CHECK-SD-LABEL: zext_v16i8_to_v16i32_in_loop_minsize:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB4_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v2, v1, #0
; CHECK-SD-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-NEXT:    ushll2.4s v3, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q2, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q3, [x1], #64
; CHECK-SD-NEXT:    b.ne LBB4_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i32_in_loop_minsize:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB4_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    st1 { v2.4s }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v3.4s }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB4_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i32_in_loop_minsize:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB4_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v2, v1, #0
; CHECK-GI-NEXT:    ushll2.4s v1, v1, #0
; CHECK-GI-NEXT:    ushll.4s v3, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    stp q2, q1, [x1]
; CHECK-GI-NEXT:    stp q3, q0, [x1, #32]
; CHECK-GI-NEXT:    add x1, x1, #64
; CHECK-GI-NEXT:    b.ne LBB4_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i32_in_loop_minsize:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB4_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    st1 { v2.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #64
; CHECK-GI-BE-NEXT:    st1 { v3.4s }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB4_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %ext = zext <16 x i8> %load to <16 x i32>
  %dst.gep = getelementptr i32, ptr %dst, i64 %iv
  store <16 x i32> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v16i8_to_v16i16_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i8_to_v16i16_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB5_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    stp q0, q1, [x1], #32
; CHECK-SD-NEXT:    b.ne LBB5_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i16_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB5_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    st1 { v0.8h }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v1.8h }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB5_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i16_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB5_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    stp q1, q0, [x1], #32
; CHECK-GI-NEXT:    b.ne LBB5_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i16_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB5_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    st1 { v0.8h }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v1.8h }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB5_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %ext = zext <16 x i8> %load to <16 x i16>
  %dst.gep = getelementptr i16, ptr %dst, i64 %iv
  store <16 x i16> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; CHECK-LABEL: lCPI6_0:
; CHECK-NEXT:     .byte   0                               ; 0x0
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   1                               ; 0x1
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   2                               ; 0x2
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   3                               ; 0x3
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT: lCPI6_1:
; CHECK-NEXT:     .byte   4                               ; 0x4
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   5                               ; 0x5
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   6                               ; 0x6
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   7                               ; 0x7
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff
; CHECK-NEXT:     .byte   255                             ; 0xff

; CHECK-BE:       .LCPI6_0:
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	0                               // 0x0
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	1                               // 0x1
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	2                               // 0x2
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	3                               // 0x3
; CHECK-BE-NEXT: .LCPI6_1:
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	4                               // 0x4
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	5                               // 0x5
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	6                               // 0x6
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	255                             // 0xff
; CHECK-BE-NEXT: 	.byte	7                               // 0x7

define void @zext_v8i8_to_v8i32_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v8i8_to_v8i32_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:  Lloh8:
; CHECK-SD-NEXT:    adrp x8, lCPI6_0@PAGE
; CHECK-SD-NEXT:  Lloh9:
; CHECK-SD-NEXT:    adrp x9, lCPI6_1@PAGE
; CHECK-SD-NEXT:  Lloh10:
; CHECK-SD-NEXT:    ldr q0, [x8, lCPI6_0@PAGEOFF]
; CHECK-SD-NEXT:  Lloh11:
; CHECK-SD-NEXT:    ldr q1, [x9, lCPI6_1@PAGEOFF]
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB6_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr d2, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    tbl.16b v3, { v2 }, v1
; CHECK-SD-NEXT:    tbl.16b v2, { v2 }, v0
; CHECK-SD-NEXT:    stp q2, q3, [x1], #64
; CHECK-SD-NEXT:    b.ne LBB6_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh9, Lloh11
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh8, Lloh10
;
; CHECK-SD-BE-LABEL: zext_v8i8_to_v8i32_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI6_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI6_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI6_1
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI6_1
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB6_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v2.8b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    tbl v3.16b, { v2.16b }, v1.16b
; CHECK-SD-BE-NEXT:    tbl v2.16b, { v2.16b }, v0.16b
; CHECK-SD-BE-NEXT:    st1 { v2.16b }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v3.16b }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB6_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v8i8_to_v8i32_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    movi d1, #0000000000000000
; CHECK-GI-NEXT:  Lloh8:
; CHECK-GI-NEXT:    adrp x8, lCPI6_1@PAGE
; CHECK-GI-NEXT:  Lloh9:
; CHECK-GI-NEXT:    adrp x9, lCPI6_0@PAGE
; CHECK-GI-NEXT:  Lloh10:
; CHECK-GI-NEXT:    ldr q2, [x8, lCPI6_1@PAGEOFF]
; CHECK-GI-NEXT:  Lloh11:
; CHECK-GI-NEXT:    ldr q3, [x9, lCPI6_0@PAGEOFF]
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB6_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr d0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    tbl.16b v4, { v0, v1 }, v2
; CHECK-GI-NEXT:    tbl.16b v5, { v0, v1 }, v3
; CHECK-GI-NEXT:    stp q4, q5, [x1], #64
; CHECK-GI-NEXT:    b.ne LBB6_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh9, Lloh11
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh8, Lloh10
;
; CHECK-GI-BE-LABEL: zext_v8i8_to_v8i32_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    movi d0, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI6_1
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI6_0
; CHECK-GI-BE-NEXT:    ldr q2, [x8, :lo12:.LCPI6_1]
; CHECK-GI-BE-NEXT:    ldr q3, [x9, :lo12:.LCPI6_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB6_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v1.8b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    tbl v5.16b, { v0.16b, v1.16b }, v3.16b
; CHECK-GI-BE-NEXT:    tbl v4.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-GI-BE-NEXT:    rev32 v5.16b, v5.16b
; CHECK-GI-BE-NEXT:    rev32 v4.16b, v4.16b
; CHECK-GI-BE-NEXT:    st1 { v5.4s }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #64
; CHECK-GI-BE-NEXT:    st1 { v4.4s }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB6_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <8 x i8>, ptr %src.gep
  %ext = zext <8 x i8> %load to <8 x i32>
  %dst.gep = getelementptr i32, ptr %dst, i64 %iv
  store <8 x i32> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v16i8_to_v16i64_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i8_to_v16i64_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB7_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v2, v1, #0
; CHECK-SD-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-NEXT:    ushll2.4s v4, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    ushll2.2d v3, v2, #0
; CHECK-SD-NEXT:    ushll.2d v2, v2, #0
; CHECK-SD-NEXT:    ushll2.2d v5, v1, #0
; CHECK-SD-NEXT:    ushll.2d v1, v1, #0
; CHECK-SD-NEXT:    stp q2, q3, [x1, #96]
; CHECK-SD-NEXT:    ushll2.2d v3, v4, #0
; CHECK-SD-NEXT:    ushll.2d v2, v4, #0
; CHECK-SD-NEXT:    ushll2.2d v4, v0, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q5, [x1, #64]
; CHECK-SD-NEXT:    stp q2, q3, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q4, [x1], #128
; CHECK-SD-NEXT:    b.ne LBB7_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i64_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB7_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #112
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v4.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v2.4s, #0
; CHECK-SD-BE-NEXT:    ushll v2.2d, v2.2s, #0
; CHECK-SD-BE-NEXT:    ushll2 v5.2d, v1.4s, #0
; CHECK-SD-BE-NEXT:    ushll v1.2d, v1.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #96
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v4.4s, #0
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #80
; CHECK-SD-BE-NEXT:    ushll v2.2d, v4.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v0.4s, #0
; CHECK-SD-BE-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-SD-BE-NEXT:    add x9, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #128
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB7_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i64_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB7_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v2, v1, #0
; CHECK-GI-NEXT:    ushll2.4s v1, v1, #0
; CHECK-GI-NEXT:    ushll.4s v4, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    ushll.2d v3, v2, #0
; CHECK-GI-NEXT:    ushll2.2d v2, v2, #0
; CHECK-GI-NEXT:    ushll.2d v5, v1, #0
; CHECK-GI-NEXT:    ushll2.2d v1, v1, #0
; CHECK-GI-NEXT:    stp q3, q2, [x1]
; CHECK-GI-NEXT:    ushll.2d v3, v4, #0
; CHECK-GI-NEXT:    ushll2.2d v2, v4, #0
; CHECK-GI-NEXT:    ushll.2d v4, v0, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v0, #0
; CHECK-GI-NEXT:    stp q5, q1, [x1, #32]
; CHECK-GI-NEXT:    stp q3, q2, [x1, #64]
; CHECK-GI-NEXT:    stp q4, q0, [x1, #96]
; CHECK-GI-NEXT:    add x1, x1, #128
; CHECK-GI-NEXT:    b.ne LBB7_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i64_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB7_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #112
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v4.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.2d, v2.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v2.2d, v2.4s, #0
; CHECK-GI-BE-NEXT:    ushll v5.2d, v1.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.2d, v1.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #96
; CHECK-GI-BE-NEXT:    ushll2 v3.2d, v4.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #80
; CHECK-GI-BE-NEXT:    ushll v2.2d, v4.2s, #0
; CHECK-GI-BE-NEXT:    st1 { v5.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #64
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-GI-BE-NEXT:    ushll v1.2d, v0.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v0.4s, #0
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #128
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB7_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %ext = zext <16 x i8> %load to <16 x i64>
  %dst.gep = getelementptr i64, ptr %dst, i64 %iv
  store <16 x i64> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v8i8_to_v8i64_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v8i8_to_v8i64_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB8_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr d0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v1, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    ushll2.2d v2, v1, #0
; CHECK-SD-NEXT:    ushll.2d v1, v1, #0
; CHECK-SD-NEXT:    ushll2.2d v3, v0, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q2, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q3, [x1], #128
; CHECK-SD-NEXT:    b.ne LBB8_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v8i8_to_v8i64_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB8_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.8b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v1.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.2d, v1.4s, #0
; CHECK-SD-BE-NEXT:    ushll v1.2d, v1.2s, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v0.4s, #0
; CHECK-SD-BE-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #128
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB8_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v8i8_to_v8i64_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB8_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr d0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    ushll.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v1, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    ushll.2d v2, v1, #0
; CHECK-GI-NEXT:    ushll2.2d v1, v1, #0
; CHECK-GI-NEXT:    ushll.2d v3, v0, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v0, #0
; CHECK-GI-NEXT:    stp q2, q1, [x1]
; CHECK-GI-NEXT:    stp q3, q0, [x1, #32]
; CHECK-GI-NEXT:    add x1, x1, #128
; CHECK-GI-NEXT:    b.ne LBB8_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v8i8_to_v8i64_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB8_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.8b }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll v1.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    ushll v2.2d, v1.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.2d, v1.4s, #0
; CHECK-GI-BE-NEXT:    ushll v3.2d, v0.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v0.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #128
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB8_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <8 x i8>, ptr %src.gep
  %ext = zext <8 x i8> %load to <8 x i64>
  %dst.gep = getelementptr i64, ptr %dst, i64 %iv
  store <8 x i64> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v8i8_to_v8i16_in_loop(ptr %src, ptr %dst) {
; CHECK-LABEL: zext_v8i8_to_v8i16_in_loop:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:  LBB9_1: ; %loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldr d0, [x0, x8]
; CHECK-NEXT:    add x8, x8, #16
; CHECK-NEXT:    cmp x8, #128
; CHECK-NEXT:    ushll.8h v0, v0, #0
; CHECK-NEXT:    str q0, [x1], #32
; CHECK-NEXT:    b.ne LBB9_1
; CHECK-NEXT:  ; %bb.2: ; %exit
; CHECK-NEXT:    ret
;
; CHECK-BE-LABEL: zext_v8i8_to_v8i16_in_loop:
; CHECK-BE:       // %bb.0: // %entry
; CHECK-BE-NEXT:    mov x8, xzr
; CHECK-BE-NEXT:  .LBB9_1: // %loop
; CHECK-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-BE-NEXT:    add x9, x0, x8
; CHECK-BE-NEXT:    add x8, x8, #16
; CHECK-BE-NEXT:    ld1 { v0.8b }, [x9]
; CHECK-BE-NEXT:    cmp x8, #128
; CHECK-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-BE-NEXT:    st1 { v0.8h }, [x1]
; CHECK-BE-NEXT:    add x1, x1, #32
; CHECK-BE-NEXT:    b.ne .LBB9_1
; CHECK-BE-NEXT:  // %bb.2: // %exit
; CHECK-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <8 x i8>, ptr %src.gep
  %ext = zext <8 x i8> %load to <8 x i16>
  %dst.gep = getelementptr i16, ptr %dst, i64 %iv
  store <8 x i16> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v4i8_to_v4i32_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v4i8_to_v4i32_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB10_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr s0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    str q0, [x1], #64
; CHECK-SD-NEXT:    b.ne LBB10_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v4i8_to_v4i32_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI10_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI10_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB10_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ldr s1, [x0, x8]
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    rev32 v1.16b, v1.16b
; CHECK-SD-BE-NEXT:    tbl v1.16b, { v1.16b }, v0.16b
; CHECK-SD-BE-NEXT:    st1 { v1.16b }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #64
; CHECK-SD-BE-NEXT:    b.ne .LBB10_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v4i8_to_v4i32_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    movi d1, #0000000000000000
; CHECK-GI-NEXT:  Lloh12:
; CHECK-GI-NEXT:    adrp x8, lCPI10_0@PAGE
; CHECK-GI-NEXT:  Lloh13:
; CHECK-GI-NEXT:    ldr q2, [x8, lCPI10_0@PAGEOFF]
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB10_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr s0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    tbl.16b v3, { v0, v1 }, v2
; CHECK-GI-NEXT:    str q3, [x1], #64
; CHECK-GI-NEXT:    b.ne LBB10_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh12, Lloh13
;
; CHECK-GI-BE-LABEL: zext_v4i8_to_v4i32_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    movi d0, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI10_0
; CHECK-GI-BE-NEXT:    ldr q2, [x8, :lo12:.LCPI10_0]
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:    rev32 v1.16b, v0.16b
; CHECK-GI-BE-NEXT:  .LBB10_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ldr s3, [x0, x8]
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    rev32 v0.16b, v3.16b
; CHECK-GI-BE-NEXT:    tbl v3.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-GI-BE-NEXT:    rev32 v3.16b, v3.16b
; CHECK-GI-BE-NEXT:    st1 { v3.4s }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #64
; CHECK-GI-BE-NEXT:    b.ne .LBB10_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <4 x i8>, ptr %src.gep
  %ext = zext <4 x i8> %load to <4 x i32>
  %dst.gep = getelementptr i32, ptr %dst, i64 %iv
  store <4 x i32> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v16i16_to_v16i64_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i16_to_v16i64_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB11_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    add x9, x0, x8
; CHECK-SD-NEXT:    add x8, x8, #32
; CHECK-SD-NEXT:    ldp q1, q0, [x9]
; CHECK-SD-NEXT:    cmp x8, #256
; CHECK-SD-NEXT:    ushll2.4s v2, v0, #0
; CHECK-SD-NEXT:    ushll2.4s v3, v1, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    ushll.4s v1, v1, #0
; CHECK-SD-NEXT:    ushll2.2d v4, v2, #0
; CHECK-SD-NEXT:    ushll.2d v2, v2, #0
; CHECK-SD-NEXT:    ushll2.2d v5, v3, #0
; CHECK-SD-NEXT:    ushll.2d v3, v3, #0
; CHECK-SD-NEXT:    stp q2, q4, [x1, #96]
; CHECK-SD-NEXT:    ushll2.2d v4, v0, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    ushll2.2d v2, v1, #0
; CHECK-SD-NEXT:    ushll.2d v1, v1, #0
; CHECK-SD-NEXT:    stp q3, q5, [x1, #32]
; CHECK-SD-NEXT:    stp q0, q4, [x1, #64]
; CHECK-SD-NEXT:    stp q1, q2, [x1], #128
; CHECK-SD-NEXT:    b.ne LBB11_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i16_to_v16i64_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB11_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #32
; CHECK-SD-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x9, #16
; CHECK-SD-BE-NEXT:    cmp x8, #256
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v4.2d, v2.4s, #0
; CHECK-SD-BE-NEXT:    ushll v2.2d, v2.2s, #0
; CHECK-SD-BE-NEXT:    ushll2 v5.2d, v0.4s, #0
; CHECK-SD-BE-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v4.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    ushll2 v4.2d, v3.4s, #0
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    ushll v2.2d, v3.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #112
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v1.4s, #0
; CHECK-SD-BE-NEXT:    st1 { v4.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #96
; CHECK-SD-BE-NEXT:    ushll v1.2d, v1.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #80
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #128
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB11_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i16_to_v16i64_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB11_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    add x9, x0, x8
; CHECK-GI-NEXT:    add x8, x8, #32
; CHECK-GI-NEXT:    ldp q0, q1, [x9]
; CHECK-GI-NEXT:    cmp x8, #256
; CHECK-GI-NEXT:    ushll.4s v2, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v4, v1, #0
; CHECK-GI-NEXT:    ushll2.4s v1, v1, #0
; CHECK-GI-NEXT:    ushll.2d v3, v2, #0
; CHECK-GI-NEXT:    ushll2.2d v2, v2, #0
; CHECK-GI-NEXT:    ushll.2d v5, v0, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v0, #0
; CHECK-GI-NEXT:    stp q3, q2, [x1]
; CHECK-GI-NEXT:    ushll.2d v3, v4, #0
; CHECK-GI-NEXT:    ushll2.2d v2, v4, #0
; CHECK-GI-NEXT:    stp q5, q0, [x1, #32]
; CHECK-GI-NEXT:    ushll.2d v4, v1, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v1, #0
; CHECK-GI-NEXT:    stp q3, q2, [x1, #64]
; CHECK-GI-NEXT:    stp q4, q0, [x1, #96]
; CHECK-GI-NEXT:    add x1, x1, #128
; CHECK-GI-NEXT:    b.ne LBB11_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i16_to_v16i64_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB11_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x10, x1, #32
; CHECK-GI-BE-NEXT:    add x8, x8, #32
; CHECK-GI-BE-NEXT:    ld1 { v0.8h }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x9, #16
; CHECK-GI-BE-NEXT:    cmp x8, #256
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #48
; CHECK-GI-BE-NEXT:    ushll v2.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v4.2d, v2.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v2.2d, v2.4s, #0
; CHECK-GI-BE-NEXT:    ushll v5.2d, v0.2s, #0
; CHECK-GI-BE-NEXT:    ushll v6.2d, v3.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v3.2d, v3.4s, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v0.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v4.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x10]
; CHECK-GI-BE-NEXT:    ushll v2.2d, v1.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.2d, v1.4s, #0
; CHECK-GI-BE-NEXT:    add x10, x1, #112
; CHECK-GI-BE-NEXT:    st1 { v5.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #96
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x1, #80
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #64
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #128
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x10]
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB11_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i16, ptr %src, i64 %iv
  %load = load <16 x i16>, ptr %src.gep
  %ext = zext <16 x i16> %load to <16 x i64>
  %dst.gep = getelementptr i64, ptr %dst, i64 %iv
  store <16 x i64> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v16i32_to_v16i64_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i32_to_v16i64_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB12_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    add x9, x0, x8
; CHECK-SD-NEXT:    add x8, x8, #64
; CHECK-SD-NEXT:    ldp q1, q0, [x9, #32]
; CHECK-SD-NEXT:    cmp x8, #512
; CHECK-SD-NEXT:    ldp q5, q4, [x9]
; CHECK-SD-NEXT:    ushll2.2d v2, v0, #0
; CHECK-SD-NEXT:    ushll2.2d v3, v1, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    ushll.2d v1, v1, #0
; CHECK-SD-NEXT:    stp q0, q2, [x1, #96]
; CHECK-SD-NEXT:    ushll2.2d v2, v4, #0
; CHECK-SD-NEXT:    ushll2.2d v0, v5, #0
; CHECK-SD-NEXT:    stp q1, q3, [x1, #64]
; CHECK-SD-NEXT:    ushll.2d v3, v4, #0
; CHECK-SD-NEXT:    ushll.2d v1, v5, #0
; CHECK-SD-NEXT:    stp q3, q2, [x1, #32]
; CHECK-SD-NEXT:    stp q1, q0, [x1], #128
; CHECK-SD-NEXT:    b.ne LBB12_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i32_to_v16i64_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB12_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #64
; CHECK-SD-BE-NEXT:    ld1 { v0.4s }, [x9]
; CHECK-SD-BE-NEXT:    add x10, x9, #48
; CHECK-SD-BE-NEXT:    cmp x8, #512
; CHECK-SD-BE-NEXT:    ld1 { v1.4s }, [x10]
; CHECK-SD-BE-NEXT:    add x10, x9, #32
; CHECK-SD-BE-NEXT:    add x9, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v4.4s }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v2.4s }, [x10]
; CHECK-SD-BE-NEXT:    add x9, x1, #16
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v0.4s, #0
; CHECK-SD-BE-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-SD-BE-NEXT:    add x10, x1, #80
; CHECK-SD-BE-NEXT:    ushll2 v5.2d, v1.4s, #0
; CHECK-SD-BE-NEXT:    ushll2 v6.2d, v2.4s, #0
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v4.4s, #0
; CHECK-SD-BE-NEXT:    add x9, x1, #112
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x1]
; CHECK-SD-BE-NEXT:    ushll v0.2d, v1.2s, #0
; CHECK-SD-BE-NEXT:    ushll v1.2d, v2.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    ushll v2.2d, v4.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #64
; CHECK-SD-BE-NEXT:    st1 { v6.2d }, [x10]
; CHECK-SD-BE-NEXT:    add x10, x1, #96
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #32
; CHECK-SD-BE-NEXT:    add x1, x1, #128
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x10]
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x9]
; CHECK-SD-BE-NEXT:    b.ne .LBB12_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i32_to_v16i64_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB12_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    add x9, x0, x8
; CHECK-GI-NEXT:    add x8, x8, #64
; CHECK-GI-NEXT:    ldp q0, q1, [x9]
; CHECK-GI-NEXT:    cmp x8, #512
; CHECK-GI-NEXT:    ldp q4, q5, [x9, #32]
; CHECK-GI-NEXT:    ushll.2d v2, v0, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v0, #0
; CHECK-GI-NEXT:    ushll.2d v3, v1, #0
; CHECK-GI-NEXT:    ushll2.2d v1, v1, #0
; CHECK-GI-NEXT:    stp q2, q0, [x1]
; CHECK-GI-NEXT:    ushll.2d v2, v4, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v4, #0
; CHECK-GI-NEXT:    stp q3, q1, [x1, #32]
; CHECK-GI-NEXT:    ushll.2d v3, v5, #0
; CHECK-GI-NEXT:    ushll2.2d v1, v5, #0
; CHECK-GI-NEXT:    stp q2, q0, [x1, #64]
; CHECK-GI-NEXT:    stp q3, q1, [x1, #96]
; CHECK-GI-NEXT:    add x1, x1, #128
; CHECK-GI-NEXT:    b.ne LBB12_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i32_to_v16i64_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB12_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #64
; CHECK-GI-BE-NEXT:    add x10, x9, #48
; CHECK-GI-BE-NEXT:    ld1 { v4.4s }, [x9]
; CHECK-GI-BE-NEXT:    cmp x8, #512
; CHECK-GI-BE-NEXT:    ld1 { v0.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #32
; CHECK-GI-BE-NEXT:    ld1 { v1.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x9, #16
; CHECK-GI-BE-NEXT:    add x9, x1, #96
; CHECK-GI-BE-NEXT:    ld1 { v3.4s }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x1, #112
; CHECK-GI-BE-NEXT:    ushll v2.2d, v0.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v0.4s, #0
; CHECK-GI-BE-NEXT:    ushll v5.2d, v1.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.2d, v1.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #64
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v3.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x9]
; CHECK-GI-BE-NEXT:    ushll2 v1.2d, v4.4s, #0
; CHECK-GI-BE-NEXT:    add x9, x1, #32
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x10]
; CHECK-GI-BE-NEXT:    ushll v2.2d, v3.2s, #0
; CHECK-GI-BE-NEXT:    ushll v3.2d, v4.2s, #0
; CHECK-GI-BE-NEXT:    add x10, x1, #80
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    st1 { v5.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x1, #48
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x1]
; CHECK-GI-BE-NEXT:    add x1, x1, #128
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x10]
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x9]
; CHECK-GI-BE-NEXT:    b.ne .LBB12_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i32, ptr %src, i64 %iv
  %load = load <16 x i32>, ptr %src.gep
  %ext = zext <16 x i32> %load to <16 x i64>
  %dst.gep = getelementptr i64, ptr %dst, i64 %iv
  store <16 x i64> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

define void @zext_v8i8_to_v8i128_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v8i8_to_v8i128_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, xzr
; CHECK-SD-NEXT:  LBB13_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr d0, [x0, x8]
; CHECK-SD-NEXT:    add x8, x8, #16
; CHECK-SD-NEXT:    str xzr, [x1, #120]
; CHECK-SD-NEXT:    str xzr, [x1, #104]
; CHECK-SD-NEXT:    cmp x8, #128
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    str xzr, [x1, #88]
; CHECK-SD-NEXT:    str xzr, [x1, #72]
; CHECK-SD-NEXT:    str xzr, [x1, #56]
; CHECK-SD-NEXT:    ushll2.4s v1, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    str xzr, [x1, #40]
; CHECK-SD-NEXT:    str xzr, [x1, #24]
; CHECK-SD-NEXT:    str xzr, [x1, #8]
; CHECK-SD-NEXT:    ushll2.2d v2, v1, #0
; CHECK-SD-NEXT:    ushll.2d v1, v1, #0
; CHECK-SD-NEXT:    ushll2.2d v3, v0, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    str d2, [x1, #96]
; CHECK-SD-NEXT:    mov d2, v2[1]
; CHECK-SD-NEXT:    str d1, [x1, #64]
; CHECK-SD-NEXT:    mov d1, v1[1]
; CHECK-SD-NEXT:    str d3, [x1, #32]
; CHECK-SD-NEXT:    mov d3, v3[1]
; CHECK-SD-NEXT:    str d0, [x1]
; CHECK-SD-NEXT:    mov d0, v0[1]
; CHECK-SD-NEXT:    str d2, [x1, #112]
; CHECK-SD-NEXT:    str d1, [x1, #80]
; CHECK-SD-NEXT:    str d3, [x1, #48]
; CHECK-SD-NEXT:    str d0, [x1, #16]
; CHECK-SD-NEXT:    add x1, x1, #256
; CHECK-SD-NEXT:    b.ne LBB13_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v8i8_to_v8i128_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov x8, xzr
; CHECK-SD-BE-NEXT:  .LBB13_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    add x9, x0, x8
; CHECK-SD-BE-NEXT:    add x8, x8, #16
; CHECK-SD-BE-NEXT:    ld1 { v0.8b }, [x9]
; CHECK-SD-BE-NEXT:    str xzr, [x1, #112]
; CHECK-SD-BE-NEXT:    cmp x8, #128
; CHECK-SD-BE-NEXT:    str xzr, [x1, #96]
; CHECK-SD-BE-NEXT:    str xzr, [x1, #80]
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    str xzr, [x1, #64]
; CHECK-SD-BE-NEXT:    str xzr, [x1, #48]
; CHECK-SD-BE-NEXT:    str xzr, [x1, #32]
; CHECK-SD-BE-NEXT:    ushll2 v1.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    str xzr, [x1, #16]
; CHECK-SD-BE-NEXT:    str xzr, [x1]
; CHECK-SD-BE-NEXT:    ushll2 v2.2d, v1.4s, #0
; CHECK-SD-BE-NEXT:    ushll v1.2d, v1.2s, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.2d, v0.4s, #0
; CHECK-SD-BE-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-SD-BE-NEXT:    str d2, [x1, #104]
; CHECK-SD-BE-NEXT:    mov d2, v2.d[1]
; CHECK-SD-BE-NEXT:    str d1, [x1, #72]
; CHECK-SD-BE-NEXT:    mov d1, v1.d[1]
; CHECK-SD-BE-NEXT:    str d3, [x1, #40]
; CHECK-SD-BE-NEXT:    mov d3, v3.d[1]
; CHECK-SD-BE-NEXT:    str d0, [x1, #8]
; CHECK-SD-BE-NEXT:    mov d0, v0.d[1]
; CHECK-SD-BE-NEXT:    str d2, [x1, #120]
; CHECK-SD-BE-NEXT:    str d1, [x1, #88]
; CHECK-SD-BE-NEXT:    str d3, [x1, #56]
; CHECK-SD-BE-NEXT:    str d0, [x1, #24]
; CHECK-SD-BE-NEXT:    add x1, x1, #256
; CHECK-SD-BE-NEXT:    b.ne .LBB13_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v8i8_to_v8i128_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, xzr
; CHECK-GI-NEXT:  LBB13_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr d0, [x0, x8]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    cmp x8, #128
; CHECK-GI-NEXT:    ushll.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.4s v1, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    mov.s w9, v1[0]
; CHECK-GI-NEXT:    mov.s w10, v1[1]
; CHECK-GI-NEXT:    mov.s w11, v1[2]
; CHECK-GI-NEXT:    mov.s w12, v1[3]
; CHECK-GI-NEXT:    mov.d v1[0], x9
; CHECK-GI-NEXT:    mov.s w9, v0[0]
; CHECK-GI-NEXT:    mov.d v2[0], x10
; CHECK-GI-NEXT:    mov.s w10, v0[1]
; CHECK-GI-NEXT:    mov.d v3[0], x11
; CHECK-GI-NEXT:    mov.s w11, v0[2]
; CHECK-GI-NEXT:    mov.d v4[0], x12
; CHECK-GI-NEXT:    mov.s w12, v0[3]
; CHECK-GI-NEXT:    mov.d v0[0], x9
; CHECK-GI-NEXT:    mov.d v1[1], xzr
; CHECK-GI-NEXT:    mov.d v2[1], xzr
; CHECK-GI-NEXT:    mov.d v5[0], x10
; CHECK-GI-NEXT:    mov.d v6[0], x11
; CHECK-GI-NEXT:    mov.d v3[1], xzr
; CHECK-GI-NEXT:    mov.d v7[0], x12
; CHECK-GI-NEXT:    mov.d v4[1], xzr
; CHECK-GI-NEXT:    mov.d v0[1], xzr
; CHECK-GI-NEXT:    stp q1, q2, [x1]
; CHECK-GI-NEXT:    mov.d v5[1], xzr
; CHECK-GI-NEXT:    mov.d v6[1], xzr
; CHECK-GI-NEXT:    mov.d v7[1], xzr
; CHECK-GI-NEXT:    stp q3, q4, [x1, #32]
; CHECK-GI-NEXT:    stp q0, q5, [x1, #64]
; CHECK-GI-NEXT:    stp q6, q7, [x1, #96]
; CHECK-GI-NEXT:    add x1, x1, #256
; CHECK-GI-NEXT:    b.ne LBB13_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v8i8_to_v8i128_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov x8, xzr
; CHECK-GI-BE-NEXT:  .LBB13_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    add x9, x0, x8
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    ld1 { v0.8b }, [x9]
; CHECK-GI-BE-NEXT:    cmp x8, #128
; CHECK-GI-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll v1.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    mov w9, v1.s[0]
; CHECK-GI-BE-NEXT:    mov w10, v1.s[1]
; CHECK-GI-BE-NEXT:    mov w11, v1.s[2]
; CHECK-GI-BE-NEXT:    mov w12, v1.s[3]
; CHECK-GI-BE-NEXT:    mov v1.d[0], x9
; CHECK-GI-BE-NEXT:    mov w9, v0.s[0]
; CHECK-GI-BE-NEXT:    mov v2.d[0], x10
; CHECK-GI-BE-NEXT:    mov w10, v0.s[1]
; CHECK-GI-BE-NEXT:    mov v3.d[0], x11
; CHECK-GI-BE-NEXT:    mov w11, v0.s[2]
; CHECK-GI-BE-NEXT:    mov v4.d[0], x12
; CHECK-GI-BE-NEXT:    mov w12, v0.s[3]
; CHECK-GI-BE-NEXT:    mov v0.d[0], x9
; CHECK-GI-BE-NEXT:    mov v1.d[1], xzr
; CHECK-GI-BE-NEXT:    mov v2.d[1], xzr
; CHECK-GI-BE-NEXT:    mov v5.d[0], x10
; CHECK-GI-BE-NEXT:    mov v6.d[0], x11
; CHECK-GI-BE-NEXT:    mov v3.d[1], xzr
; CHECK-GI-BE-NEXT:    mov v7.d[0], x12
; CHECK-GI-BE-NEXT:    mov v4.d[1], xzr
; CHECK-GI-BE-NEXT:    mov v0.d[1], xzr
; CHECK-GI-BE-NEXT:    stp q2, q1, [x1, #96]
; CHECK-GI-BE-NEXT:    mov v5.d[1], xzr
; CHECK-GI-BE-NEXT:    mov v6.d[1], xzr
; CHECK-GI-BE-NEXT:    mov v7.d[1], xzr
; CHECK-GI-BE-NEXT:    stp q4, q3, [x1, #64]
; CHECK-GI-BE-NEXT:    stp q5, q0, [x1, #32]
; CHECK-GI-BE-NEXT:    stp q7, q6, [x1], #256
; CHECK-GI-BE-NEXT:    b.ne .LBB13_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <8 x i8>, ptr %src.gep
  %ext = zext <8 x i8> %load to <8 x i128>
  %dst.gep = getelementptr i128, ptr %dst, i64 %iv
  store <8 x i128> %ext, ptr %dst.gep
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; multiple back-to-back 'zext' of similar type of vectors combined with arithmetic operations
define void @zext_v8i8_to_v8i64_with_add_in_sequence_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v8i8_to_v8i64_with_add_in_sequence_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:  Lloh12:
; CHECK-SD-NEXT:    adrp x8, lCPI14_0@PAGE
; CHECK-SD-NEXT:  Lloh13:
; CHECK-SD-NEXT:    adrp x9, lCPI14_1@PAGE
; CHECK-SD-NEXT:    mov w10, #128 ; =0x80
; CHECK-SD-NEXT:  Lloh14:
; CHECK-SD-NEXT:    ldr q0, [x8, lCPI14_0@PAGEOFF]
; CHECK-SD-NEXT:  Lloh15:
; CHECK-SD-NEXT:    ldr q1, [x9, lCPI14_1@PAGEOFF]
; CHECK-SD-NEXT:    add x8, x1, #64
; CHECK-SD-NEXT:    add x9, x0, #8
; CHECK-SD-NEXT:  LBB14_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldp d2, d3, [x9, #-8]
; CHECK-SD-NEXT:    subs x10, x10, #16
; CHECK-SD-NEXT:    ldp q7, q5, [x8, #-32]
; CHECK-SD-NEXT:    add x9, x9, #16
; CHECK-SD-NEXT:    ldp q17, q6, [x8, #-64]
; CHECK-SD-NEXT:    tbl.16b v4, { v2 }, v1
; CHECK-SD-NEXT:    tbl.16b v2, { v2 }, v0
; CHECK-SD-NEXT:    tbl.16b v16, { v3 }, v1
; CHECK-SD-NEXT:    tbl.16b v3, { v3 }, v0
; CHECK-SD-NEXT:    uaddw2.2d v5, v5, v4
; CHECK-SD-NEXT:    uaddw2.2d v6, v6, v2
; CHECK-SD-NEXT:    uaddw.2d v4, v7, v4
; CHECK-SD-NEXT:    ldp q18, q7, [x8, #32]
; CHECK-SD-NEXT:    uaddw.2d v2, v17, v2
; CHECK-SD-NEXT:    stp q4, q5, [x8, #-32]
; CHECK-SD-NEXT:    uaddw2.2d v5, v7, v16
; CHECK-SD-NEXT:    stp q2, q6, [x8, #-64]
; CHECK-SD-NEXT:    uaddw.2d v16, v18, v16
; CHECK-SD-NEXT:    ldp q7, q6, [x8]
; CHECK-SD-NEXT:    stp q16, q5, [x8, #32]
; CHECK-SD-NEXT:    uaddw2.2d v4, v6, v3
; CHECK-SD-NEXT:    uaddw.2d v2, v7, v3
; CHECK-SD-NEXT:    stp q2, q4, [x8], #128
; CHECK-SD-NEXT:    b.ne LBB14_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh13, Lloh15
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh12, Lloh14
;
; CHECK-SD-BE-LABEL: zext_v8i8_to_v8i64_with_add_in_sequence_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x9, .LCPI14_0
; CHECK-SD-BE-NEXT:    add x9, x9, :lo12:.LCPI14_0
; CHECK-SD-BE-NEXT:    mov w8, #128 // =0x80
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x9]
; CHECK-SD-BE-NEXT:    adrp x9, .LCPI14_1
; CHECK-SD-BE-NEXT:    add x9, x9, :lo12:.LCPI14_1
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x1, #64
; CHECK-SD-BE-NEXT:    add x10, x0, #8
; CHECK-SD-BE-NEXT:  .LBB14_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ld1 { v2.8b }, [x10]
; CHECK-SD-BE-NEXT:    sub x11, x10, #8
; CHECK-SD-BE-NEXT:    add x15, x9, #32
; CHECK-SD-BE-NEXT:    ld1 { v3.8b }, [x11]
; CHECK-SD-BE-NEXT:    ld1 { v16.2d }, [x15]
; CHECK-SD-BE-NEXT:    sub x11, x9, #64
; CHECK-SD-BE-NEXT:    sub x12, x9, #32
; CHECK-SD-BE-NEXT:    ld1 { v6.2d }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v21.2d }, [x11]
; CHECK-SD-BE-NEXT:    tbl v4.16b, { v2.16b }, v1.16b
; CHECK-SD-BE-NEXT:    tbl v2.16b, { v2.16b }, v0.16b
; CHECK-SD-BE-NEXT:    ld1 { v19.2d }, [x12]
; CHECK-SD-BE-NEXT:    tbl v5.16b, { v3.16b }, v1.16b
; CHECK-SD-BE-NEXT:    tbl v3.16b, { v3.16b }, v0.16b
; CHECK-SD-BE-NEXT:    sub x13, x9, #16
; CHECK-SD-BE-NEXT:    sub x14, x9, #48
; CHECK-SD-BE-NEXT:    add x16, x9, #48
; CHECK-SD-BE-NEXT:    add x17, x9, #16
; CHECK-SD-BE-NEXT:    ld1 { v22.2d }, [x13]
; CHECK-SD-BE-NEXT:    subs x8, x8, #16
; CHECK-SD-BE-NEXT:    add x10, x10, #16
; CHECK-SD-BE-NEXT:    rev32 v7.8b, v4.8b
; CHECK-SD-BE-NEXT:    ext v4.16b, v4.16b, v4.16b, #8
; CHECK-SD-BE-NEXT:    rev32 v17.8b, v2.8b
; CHECK-SD-BE-NEXT:    ext v18.16b, v5.16b, v5.16b, #8
; CHECK-SD-BE-NEXT:    ext v20.16b, v3.16b, v3.16b, #8
; CHECK-SD-BE-NEXT:    ext v2.16b, v2.16b, v2.16b, #8
; CHECK-SD-BE-NEXT:    rev32 v5.8b, v5.8b
; CHECK-SD-BE-NEXT:    rev32 v3.8b, v3.8b
; CHECK-SD-BE-NEXT:    uaddw v7.2d, v16.2d, v7.2s
; CHECK-SD-BE-NEXT:    rev32 v4.8b, v4.8b
; CHECK-SD-BE-NEXT:    uaddw v6.2d, v6.2d, v17.2s
; CHECK-SD-BE-NEXT:    rev32 v17.8b, v18.8b
; CHECK-SD-BE-NEXT:    rev32 v20.8b, v20.8b
; CHECK-SD-BE-NEXT:    rev32 v2.8b, v2.8b
; CHECK-SD-BE-NEXT:    ld1 { v16.2d }, [x16]
; CHECK-SD-BE-NEXT:    ld1 { v18.2d }, [x14]
; CHECK-SD-BE-NEXT:    uaddw v5.2d, v19.2d, v5.2s
; CHECK-SD-BE-NEXT:    uaddw v3.2d, v21.2d, v3.2s
; CHECK-SD-BE-NEXT:    st1 { v7.2d }, [x15]
; CHECK-SD-BE-NEXT:    ld1 { v7.2d }, [x17]
; CHECK-SD-BE-NEXT:    st1 { v6.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x9, #128
; CHECK-SD-BE-NEXT:    uaddw v4.2d, v16.2d, v4.2s
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x12]
; CHECK-SD-BE-NEXT:    uaddw v5.2d, v22.2d, v17.2s
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x11]
; CHECK-SD-BE-NEXT:    uaddw v3.2d, v18.2d, v20.2s
; CHECK-SD-BE-NEXT:    uaddw v2.2d, v7.2d, v2.2s
; CHECK-SD-BE-NEXT:    st1 { v4.2d }, [x16]
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x13]
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x14]
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x17]
; CHECK-SD-BE-NEXT:    b.ne .LBB14_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v8i8_to_v8i64_with_add_in_sequence_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    movi d1, #0000000000000000
; CHECK-GI-NEXT:  Lloh14:
; CHECK-GI-NEXT:    adrp x9, lCPI14_1@PAGE
; CHECK-GI-NEXT:  Lloh15:
; CHECK-GI-NEXT:    adrp x10, lCPI14_0@PAGE
; CHECK-GI-NEXT:  Lloh16:
; CHECK-GI-NEXT:    ldr q2, [x9, lCPI14_1@PAGEOFF]
; CHECK-GI-NEXT:  Lloh17:
; CHECK-GI-NEXT:    ldr q3, [x10, lCPI14_0@PAGEOFF]
; CHECK-GI-NEXT:    add x8, x0, #8
; CHECK-GI-NEXT:    add x9, x1, #64
; CHECK-GI-NEXT:    mov w10, #128 ; =0x80
; CHECK-GI-NEXT:    fmov d5, d1
; CHECK-GI-NEXT:  LBB14_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldp d0, d4, [x8, #-8]
; CHECK-GI-NEXT:    mov x11, x9
; CHECK-GI-NEXT:    ldp q7, q17, [x11, #-64]!
; CHECK-GI-NEXT:    ldp q18, q20, [x11, #32]
; CHECK-GI-NEXT:    subs x10, x10, #16
; CHECK-GI-NEXT:    tbl.16b v6, { v0, v1 }, v2
; CHECK-GI-NEXT:    tbl.16b v16, { v0, v1 }, v3
; CHECK-GI-NEXT:    tbl.16b v19, { v4, v5 }, v2
; CHECK-GI-NEXT:    ldp q21, q22, [x9]
; CHECK-GI-NEXT:    add x8, x8, #16
; CHECK-GI-NEXT:    uaddw.2d v7, v7, v6
; CHECK-GI-NEXT:    uaddw2.2d v6, v17, v6
; CHECK-GI-NEXT:    tbl.16b v17, { v4, v5 }, v3
; CHECK-GI-NEXT:    uaddw.2d v18, v18, v16
; CHECK-GI-NEXT:    uaddw2.2d v16, v20, v16
; CHECK-GI-NEXT:    stp q7, q6, [x11]
; CHECK-GI-NEXT:    ldp q6, q20, [x9, #32]
; CHECK-GI-NEXT:    uaddw.2d v7, v21, v19
; CHECK-GI-NEXT:    uaddw2.2d v19, v22, v19
; CHECK-GI-NEXT:    stp q18, q16, [x11, #32]
; CHECK-GI-NEXT:    uaddw.2d v6, v6, v17
; CHECK-GI-NEXT:    uaddw2.2d v16, v20, v17
; CHECK-GI-NEXT:    stp q7, q19, [x9]
; CHECK-GI-NEXT:    stp q6, q16, [x9, #32]
; CHECK-GI-NEXT:    add x9, x9, #128
; CHECK-GI-NEXT:    b.ne LBB14_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh15, Lloh17
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh14, Lloh16
;
; CHECK-GI-BE-LABEL: zext_v8i8_to_v8i64_with_add_in_sequence_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    movi d0, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI14_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI14_0
; CHECK-GI-BE-NEXT:    ldr q2, [x9, :lo12:.LCPI14_1]
; CHECK-GI-BE-NEXT:    ldr q3, [x10, :lo12:.LCPI14_0]
; CHECK-GI-BE-NEXT:    add x8, x0, #8
; CHECK-GI-BE-NEXT:    add x9, x1, #64
; CHECK-GI-BE-NEXT:    mov w10, #128 // =0x80
; CHECK-GI-BE-NEXT:    fmov d4, d0
; CHECK-GI-BE-NEXT:  .LBB14_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ld1 { v5.8b }, [x8]
; CHECK-GI-BE-NEXT:    sub x11, x8, #8
; CHECK-GI-BE-NEXT:    add x12, x9, #48
; CHECK-GI-BE-NEXT:    ld1 { v1.8b }, [x11]
; CHECK-GI-BE-NEXT:    ld1 { v17.2d }, [x12]
; CHECK-GI-BE-NEXT:    add x13, x9, #32
; CHECK-GI-BE-NEXT:    ld1 { v19.2d }, [x13]
; CHECK-GI-BE-NEXT:    add x14, x9, #16
; CHECK-GI-BE-NEXT:    sub x11, x9, #16
; CHECK-GI-BE-NEXT:    tbl v6.16b, { v4.16b, v5.16b }, v2.16b
; CHECK-GI-BE-NEXT:    tbl v7.16b, { v4.16b, v5.16b }, v3.16b
; CHECK-GI-BE-NEXT:    sub x15, x9, #32
; CHECK-GI-BE-NEXT:    tbl v16.16b, { v0.16b, v1.16b }, v2.16b
; CHECK-GI-BE-NEXT:    tbl v18.16b, { v0.16b, v1.16b }, v3.16b
; CHECK-GI-BE-NEXT:    ld1 { v20.2d }, [x14]
; CHECK-GI-BE-NEXT:    sub x16, x9, #48
; CHECK-GI-BE-NEXT:    sub x17, x9, #64
; CHECK-GI-BE-NEXT:    ld1 { v21.2d }, [x11]
; CHECK-GI-BE-NEXT:    ld1 { v22.2d }, [x15]
; CHECK-GI-BE-NEXT:    ld1 { v23.2d }, [x17]
; CHECK-GI-BE-NEXT:    subs x10, x10, #16
; CHECK-GI-BE-NEXT:    rev32 v6.16b, v6.16b
; CHECK-GI-BE-NEXT:    rev32 v7.16b, v7.16b
; CHECK-GI-BE-NEXT:    add x8, x8, #16
; CHECK-GI-BE-NEXT:    rev32 v16.16b, v16.16b
; CHECK-GI-BE-NEXT:    rev32 v18.16b, v18.16b
; CHECK-GI-BE-NEXT:    uaddw v17.2d, v17.2d, v6.2s
; CHECK-GI-BE-NEXT:    uaddw2 v6.2d, v19.2d, v6.4s
; CHECK-GI-BE-NEXT:    ld1 { v19.2d }, [x16]
; CHECK-GI-BE-NEXT:    uaddw v20.2d, v20.2d, v7.2s
; CHECK-GI-BE-NEXT:    uaddw v21.2d, v21.2d, v16.2s
; CHECK-GI-BE-NEXT:    uaddw2 v16.2d, v22.2d, v16.4s
; CHECK-GI-BE-NEXT:    st1 { v17.2d }, [x12]
; CHECK-GI-BE-NEXT:    ld1 { v17.2d }, [x9]
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x13]
; CHECK-GI-BE-NEXT:    uaddw v6.2d, v19.2d, v18.2s
; CHECK-GI-BE-NEXT:    uaddw2 v18.2d, v23.2d, v18.4s
; CHECK-GI-BE-NEXT:    st1 { v20.2d }, [x14]
; CHECK-GI-BE-NEXT:    uaddw2 v7.2d, v17.2d, v7.4s
; CHECK-GI-BE-NEXT:    st1 { v21.2d }, [x11]
; CHECK-GI-BE-NEXT:    st1 { v16.2d }, [x15]
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x16]
; CHECK-GI-BE-NEXT:    st1 { v7.2d }, [x9]
; CHECK-GI-BE-NEXT:    add x9, x9, #128
; CHECK-GI-BE-NEXT:    st1 { v18.2d }, [x17]
; CHECK-GI-BE-NEXT:    b.ne .LBB14_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <8 x i8>, ptr %src.gep
  %src.gep.2 = getelementptr i8, ptr %src.gep, i64 8
  %load.2 = load <8 x i8>, ptr %src.gep.2
  %ext = zext <8 x i8> %load to <8 x i64>
  %ext.2 = zext <8 x i8> %load.2 to <8 x i64>
  %dst.gep = getelementptr i64, ptr %dst, i64 %iv
  %load.dst = load <8 x i64>, ptr %dst.gep
  %dst.gep.2 = getelementptr i64, ptr %dst.gep, i64 8
  %load.dst.2 = load <8 x i64>, ptr %dst.gep.2
  %sum = add <8 x i64> %load.dst, %ext
  %sum.2 = add <8 x i64> %load.dst.2, %ext.2
  store <8 x i64> %sum, ptr %dst.gep
  store <8 x i64> %sum.2, ptr %dst.gep.2
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; multiple back-to-back 'zext' of similar type of vectors
define void @zext_v16i8_to_v16i64_in_sequence_in_loop(ptr %src, ptr %dst) {
; CHECK-SD-LABEL: zext_v16i8_to_v16i64_in_sequence_in_loop:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov w8, #128 ; =0x80
; CHECK-SD-NEXT:    add x9, x1, #128
; CHECK-SD-NEXT:    add x10, x0, #16
; CHECK-SD-NEXT:  LBB15_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldp q0, q1, [x10, #-16]
; CHECK-SD-NEXT:    subs x8, x8, #16
; CHECK-SD-NEXT:    add x10, x10, #16
; CHECK-SD-NEXT:    ushll2.8h v2, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll2.8h v6, v1, #0
; CHECK-SD-NEXT:    ushll.8h v1, v1, #0
; CHECK-SD-NEXT:    ushll2.4s v3, v2, #0
; CHECK-SD-NEXT:    ushll.4s v2, v2, #0
; CHECK-SD-NEXT:    ushll2.4s v4, v0, #0
; CHECK-SD-NEXT:    ushll.4s v0, v0, #0
; CHECK-SD-NEXT:    ushll2.2d v5, v3, #0
; CHECK-SD-NEXT:    ushll.2d v3, v3, #0
; CHECK-SD-NEXT:    ushll2.2d v7, v2, #0
; CHECK-SD-NEXT:    ushll2.2d v16, v4, #0
; CHECK-SD-NEXT:    ushll.2d v2, v2, #0
; CHECK-SD-NEXT:    ushll.2d v4, v4, #0
; CHECK-SD-NEXT:    stp q3, q5, [x9, #-32]
; CHECK-SD-NEXT:    ushll2.4s v3, v6, #0
; CHECK-SD-NEXT:    ushll2.2d v5, v0, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    stp q4, q16, [x9, #-96]
; CHECK-SD-NEXT:    ushll.4s v6, v6, #0
; CHECK-SD-NEXT:    stp q2, q7, [x9, #-64]
; CHECK-SD-NEXT:    ushll2.4s v4, v1, #0
; CHECK-SD-NEXT:    ushll2.2d v2, v3, #0
; CHECK-SD-NEXT:    ushll.2d v3, v3, #0
; CHECK-SD-NEXT:    stp q0, q5, [x9, #-128]
; CHECK-SD-NEXT:    ushll.4s v0, v1, #0
; CHECK-SD-NEXT:    ushll2.2d v5, v6, #0
; CHECK-SD-NEXT:    ushll.2d v1, v6, #0
; CHECK-SD-NEXT:    stp q3, q2, [x9, #96]
; CHECK-SD-NEXT:    ushll2.2d v2, v4, #0
; CHECK-SD-NEXT:    ushll.2d v3, v4, #0
; CHECK-SD-NEXT:    ushll2.2d v4, v0, #0
; CHECK-SD-NEXT:    ushll.2d v0, v0, #0
; CHECK-SD-NEXT:    stp q1, q5, [x9, #64]
; CHECK-SD-NEXT:    stp q3, q2, [x9, #32]
; CHECK-SD-NEXT:    stp q0, q4, [x9], #128
; CHECK-SD-NEXT:    b.ne LBB15_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: zext_v16i8_to_v16i64_in_sequence_in_loop:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    mov w8, #128 // =0x80
; CHECK-SD-BE-NEXT:    add x9, x1, #128
; CHECK-SD-BE-NEXT:    add x10, x0, #16
; CHECK-SD-BE-NEXT:  .LBB15_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    sub x11, x10, #16
; CHECK-SD-BE-NEXT:    ld1 { v5.16b }, [x10]
; CHECK-SD-BE-NEXT:    sub x12, x9, #32
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x11]
; CHECK-SD-BE-NEXT:    sub x11, x9, #16
; CHECK-SD-BE-NEXT:    subs x8, x8, #16
; CHECK-SD-BE-NEXT:    add x10, x10, #16
; CHECK-SD-BE-NEXT:    ushll2 v1.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v2.4s, v1.8h, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v0.8h, #0
; CHECK-SD-BE-NEXT:    ushll v1.4s, v1.4h, #0
; CHECK-SD-BE-NEXT:    ushll v0.4s, v0.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v4.2d, v2.4s, #0
; CHECK-SD-BE-NEXT:    ushll v2.2d, v2.2s, #0
; CHECK-SD-BE-NEXT:    ushll2 v6.2d, v1.4s, #0
; CHECK-SD-BE-NEXT:    ushll v1.2d, v1.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v4.2d }, [x11]
; CHECK-SD-BE-NEXT:    ushll2 v4.2d, v3.4s, #0
; CHECK-SD-BE-NEXT:    ushll v3.2d, v3.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x12]
; CHECK-SD-BE-NEXT:    ushll2 v2.8h, v5.16b, #0
; CHECK-SD-BE-NEXT:    sub x12, x9, #80
; CHECK-SD-BE-NEXT:    sub x11, x9, #48
; CHECK-SD-BE-NEXT:    st1 { v4.2d }, [x12]
; CHECK-SD-BE-NEXT:    ushll v4.8h, v5.8b, #0
; CHECK-SD-BE-NEXT:    sub x12, x9, #64
; CHECK-SD-BE-NEXT:    ushll2 v5.4s, v2.8h, #0
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x12]
; CHECK-SD-BE-NEXT:    sub x12, x9, #96
; CHECK-SD-BE-NEXT:    ushll2 v1.2d, v0.4s, #0
; CHECK-SD-BE-NEXT:    ushll v2.4s, v2.4h, #0
; CHECK-SD-BE-NEXT:    ushll v0.2d, v0.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v6.2d }, [x11]
; CHECK-SD-BE-NEXT:    sub x11, x9, #128
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x12]
; CHECK-SD-BE-NEXT:    ushll2 v3.4s, v4.8h, #0
; CHECK-SD-BE-NEXT:    ushll2 v6.2d, v5.4s, #0
; CHECK-SD-BE-NEXT:    sub x12, x9, #112
; CHECK-SD-BE-NEXT:    ushll v5.2d, v5.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x11]
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x12]
; CHECK-SD-BE-NEXT:    ushll2 v1.2d, v2.4s, #0
; CHECK-SD-BE-NEXT:    add x11, x9, #112
; CHECK-SD-BE-NEXT:    ushll v4.4s, v4.4h, #0
; CHECK-SD-BE-NEXT:    ushll2 v0.2d, v3.4s, #0
; CHECK-SD-BE-NEXT:    st1 { v6.2d }, [x11]
; CHECK-SD-BE-NEXT:    add x11, x9, #96
; CHECK-SD-BE-NEXT:    ushll v2.2d, v2.2s, #0
; CHECK-SD-BE-NEXT:    ushll v3.2d, v3.2s, #0
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x11]
; CHECK-SD-BE-NEXT:    add x11, x9, #80
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x11]
; CHECK-SD-BE-NEXT:    add x11, x9, #48
; CHECK-SD-BE-NEXT:    ushll2 v1.2d, v4.4s, #0
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x11]
; CHECK-SD-BE-NEXT:    ushll v0.2d, v4.2s, #0
; CHECK-SD-BE-NEXT:    add x11, x9, #64
; CHECK-SD-BE-NEXT:    st1 { v2.2d }, [x11]
; CHECK-SD-BE-NEXT:    add x11, x9, #32
; CHECK-SD-BE-NEXT:    st1 { v3.2d }, [x11]
; CHECK-SD-BE-NEXT:    add x11, x9, #16
; CHECK-SD-BE-NEXT:    st1 { v0.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x9, #128
; CHECK-SD-BE-NEXT:    st1 { v1.2d }, [x11]
; CHECK-SD-BE-NEXT:    b.ne .LBB15_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: zext_v16i8_to_v16i64_in_sequence_in_loop:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov w8, #128 ; =0x80
; CHECK-GI-NEXT:    add x9, x0, #16
; CHECK-GI-NEXT:    add x10, x1, #128
; CHECK-GI-NEXT:  LBB15_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldp q0, q1, [x9, #-16]
; CHECK-GI-NEXT:    mov x11, x10
; CHECK-GI-NEXT:    subs x8, x8, #16
; CHECK-GI-NEXT:    add x9, x9, #16
; CHECK-GI-NEXT:    ushll.8h v2, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll.8h v6, v1, #0
; CHECK-GI-NEXT:    ushll2.8h v1, v1, #0
; CHECK-GI-NEXT:    ushll.4s v3, v2, #0
; CHECK-GI-NEXT:    ushll2.4s v2, v2, #0
; CHECK-GI-NEXT:    ushll.4s v5, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v0, v0, #0
; CHECK-GI-NEXT:    ushll.2d v4, v3, #0
; CHECK-GI-NEXT:    ushll2.2d v3, v3, #0
; CHECK-GI-NEXT:    ushll.2d v7, v2, #0
; CHECK-GI-NEXT:    ushll2.2d v2, v2, #0
; CHECK-GI-NEXT:    stp q4, q3, [x11, #-128]!
; CHECK-GI-NEXT:    ushll.2d v4, v5, #0
; CHECK-GI-NEXT:    ushll.4s v3, v6, #0
; CHECK-GI-NEXT:    ushll2.2d v5, v5, #0
; CHECK-GI-NEXT:    stp q7, q2, [x11, #32]
; CHECK-GI-NEXT:    ushll.2d v7, v0, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v0, #0
; CHECK-GI-NEXT:    ushll2.4s v2, v6, #0
; CHECK-GI-NEXT:    stp q4, q5, [x11, #64]
; CHECK-GI-NEXT:    ushll.2d v4, v3, #0
; CHECK-GI-NEXT:    ushll.4s v5, v1, #0
; CHECK-GI-NEXT:    ushll2.2d v3, v3, #0
; CHECK-GI-NEXT:    stp q7, q0, [x11, #96]
; CHECK-GI-NEXT:    ushll2.4s v0, v1, #0
; CHECK-GI-NEXT:    ushll.2d v6, v2, #0
; CHECK-GI-NEXT:    ushll2.2d v1, v2, #0
; CHECK-GI-NEXT:    ushll.2d v2, v5, #0
; CHECK-GI-NEXT:    stp q4, q3, [x10]
; CHECK-GI-NEXT:    ushll2.2d v3, v5, #0
; CHECK-GI-NEXT:    ushll.2d v4, v0, #0
; CHECK-GI-NEXT:    ushll2.2d v0, v0, #0
; CHECK-GI-NEXT:    stp q6, q1, [x10, #32]
; CHECK-GI-NEXT:    stp q2, q3, [x10, #64]
; CHECK-GI-NEXT:    stp q4, q0, [x10, #96]
; CHECK-GI-NEXT:    add x10, x10, #128
; CHECK-GI-NEXT:    b.ne LBB15_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: zext_v16i8_to_v16i64_in_sequence_in_loop:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    mov w8, #128 // =0x80
; CHECK-GI-BE-NEXT:    add x9, x0, #16
; CHECK-GI-BE-NEXT:    add x10, x1, #128
; CHECK-GI-BE-NEXT:  .LBB15_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    sub x11, x9, #16
; CHECK-GI-BE-NEXT:    ld1 { v4.16b }, [x9]
; CHECK-GI-BE-NEXT:    sub x12, x10, #32
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x11]
; CHECK-GI-BE-NEXT:    sub x11, x10, #16
; CHECK-GI-BE-NEXT:    subs x8, x8, #16
; CHECK-GI-BE-NEXT:    add x9, x9, #16
; CHECK-GI-BE-NEXT:    ushll v1.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v2.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll v5.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    ushll v3.2d, v2.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v2.2d, v2.4s, #0
; CHECK-GI-BE-NEXT:    ushll v6.2d, v1.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.2d, v1.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x12]
; CHECK-GI-BE-NEXT:    ushll v2.8h, v4.8b, #0
; CHECK-GI-BE-NEXT:    sub x12, x10, #64
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x11]
; CHECK-GI-BE-NEXT:    ushll v3.2d, v5.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v5.2d, v5.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x12]
; CHECK-GI-BE-NEXT:    ushll2 v1.8h, v4.16b, #0
; CHECK-GI-BE-NEXT:    sub x11, x10, #48
; CHECK-GI-BE-NEXT:    ushll v4.4s, v2.4h, #0
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x11]
; CHECK-GI-BE-NEXT:    sub x12, x10, #96
; CHECK-GI-BE-NEXT:    ushll2 v2.4s, v2.8h, #0
; CHECK-GI-BE-NEXT:    ushll v6.2d, v0.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v0.4s, #0
; CHECK-GI-BE-NEXT:    sub x11, x10, #80
; CHECK-GI-BE-NEXT:    st1 { v5.2d }, [x12]
; CHECK-GI-BE-NEXT:    sub x12, x10, #112
; CHECK-GI-BE-NEXT:    ushll v5.2d, v4.2s, #0
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x11]
; CHECK-GI-BE-NEXT:    sub x11, x10, #128
; CHECK-GI-BE-NEXT:    ushll v3.4s, v1.4h, #0
; CHECK-GI-BE-NEXT:    ushll2 v4.2d, v4.4s, #0
; CHECK-GI-BE-NEXT:    ushll v7.2d, v2.2s, #0
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #112
; CHECK-GI-BE-NEXT:    ushll2 v0.4s, v1.8h, #0
; CHECK-GI-BE-NEXT:    ushll2 v2.2d, v2.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v5.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #96
; CHECK-GI-BE-NEXT:    ushll v1.2d, v3.2s, #0
; CHECK-GI-BE-NEXT:    st1 { v4.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #80
; CHECK-GI-BE-NEXT:    ushll2 v3.2d, v3.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v7.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #64
; CHECK-GI-BE-NEXT:    ushll v4.2d, v0.2s, #0
; CHECK-GI-BE-NEXT:    ushll2 v0.2d, v0.4s, #0
; CHECK-GI-BE-NEXT:    st1 { v2.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #48
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x12]
; CHECK-GI-BE-NEXT:    st1 { v1.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #32
; CHECK-GI-BE-NEXT:    st1 { v3.2d }, [x11]
; CHECK-GI-BE-NEXT:    add x11, x10, #16
; CHECK-GI-BE-NEXT:    st1 { v0.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x10, #128
; CHECK-GI-BE-NEXT:    st1 { v4.2d }, [x11]
; CHECK-GI-BE-NEXT:    b.ne .LBB15_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src.gep = getelementptr i8, ptr %src, i64 %iv
  %load = load <16 x i8>, ptr %src.gep
  %src.gep.2 = getelementptr i8, ptr %src.gep, i64 16
  %load.2 = load <16 x i8>, ptr %src.gep.2
  %ext = zext <16 x i8> %load to <16 x i64>
  %ext.2 = zext <16 x i8> %load.2 to <16 x i64>
  %dst.gep = getelementptr i64, ptr %dst, i64 %iv
  store <16 x i64> %ext, ptr %dst.gep
  %dst.gep.2 = getelementptr i64, ptr %dst.gep, i64 16
  store <16 x i64> %ext.2, ptr %dst.gep.2
  %iv.next = add nuw i64 %iv, 16
  %ec = icmp eq i64 %iv.next, 128
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

; FIXME: Widening instructions should be used instead of tbl.
define i32 @test_pr62620_widening_instr(ptr %p1, ptr %p2, i64 %lx, i32 %h) {
; CHECK-SD-LABEL: test_pr62620_widening_instr:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    lsl x9, x2, #4
; CHECK-SD-NEXT:    mov x8, x0
; CHECK-SD-NEXT:    mov w0, wzr
; CHECK-SD-NEXT:    ldr q0, [x8, x9]
; CHECK-SD-NEXT:    ldr q1, [x1, x9]
; CHECK-SD-NEXT:    uabdl.8h v2, v0, v1
; CHECK-SD-NEXT:    uabal2.8h v2, v0, v1
; CHECK-SD-NEXT:    uaddlv.8h s0, v2
; CHECK-SD-NEXT:    fmov w8, s0
; CHECK-SD-NEXT:  LBB16_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    subs w3, w3, #1
; CHECK-SD-NEXT:    add w0, w8, w0
; CHECK-SD-NEXT:    b.ne LBB16_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test_pr62620_widening_instr:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    lsl x9, x2, #4
; CHECK-SD-BE-NEXT:    mov x8, x0
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    add x8, x8, x9
; CHECK-SD-BE-NEXT:    add x9, x1, x9
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-SD-BE-NEXT:    uabdl v2.8h, v0.8b, v1.8b
; CHECK-SD-BE-NEXT:    uabal2 v2.8h, v0.16b, v1.16b
; CHECK-SD-BE-NEXT:    uaddlv s0, v2.8h
; CHECK-SD-BE-NEXT:    fmov w8, s0
; CHECK-SD-BE-NEXT:  .LBB16_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    subs w3, w3, #1
; CHECK-SD-BE-NEXT:    add w0, w8, w0
; CHECK-SD-BE-NEXT:    b.ne .LBB16_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: test_pr62620_widening_instr:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:    mov x8, x0
; CHECK-GI-NEXT:    ldr q1, [x1, x2, lsl #4]
; CHECK-GI-NEXT:    movi.2d v4, #0000000000000000
; CHECK-GI-NEXT:    ldr q0, [x8, x2, lsl #4]
; CHECK-GI-NEXT:    mov w0, wzr
; CHECK-GI-NEXT:    usubl.8h v2, v0, v1
; CHECK-GI-NEXT:    usubl2.8h v0, v0, v1
; CHECK-GI-NEXT:    sshll2.4s v1, v2, #0
; CHECK-GI-NEXT:    sshll2.4s v3, v0, #0
; CHECK-GI-NEXT:    sshll.4s v2, v2, #0
; CHECK-GI-NEXT:    sshll.4s v0, v0, #0
; CHECK-GI-NEXT:    abs.4s v1, v1
; CHECK-GI-NEXT:    abs.4s v3, v3
; CHECK-GI-NEXT:    saba.4s v1, v2, v4
; CHECK-GI-NEXT:    saba.4s v3, v0, v4
; CHECK-GI-NEXT:    add.4s v0, v1, v3
; CHECK-GI-NEXT:    addv.4s s0, v0
; CHECK-GI-NEXT:    fmov w8, s0
; CHECK-GI-NEXT:  LBB16_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    subs w3, w3, #1
; CHECK-GI-NEXT:    add w0, w8, w0
; CHECK-GI-NEXT:    b.ne LBB16_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test_pr62620_widening_instr:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    lsl x9, x2, #4
; CHECK-GI-BE-NEXT:    mov x8, x0
; CHECK-GI-BE-NEXT:    movi v4.2d, #0000000000000000
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    add x8, x8, x9
; CHECK-GI-BE-NEXT:    add x9, x1, x9
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-GI-BE-NEXT:    ld1 { v1.16b }, [x9]
; CHECK-GI-BE-NEXT:    usubl v2.8h, v0.8b, v1.8b
; CHECK-GI-BE-NEXT:    usubl2 v0.8h, v0.16b, v1.16b
; CHECK-GI-BE-NEXT:    sshll2 v1.4s, v2.8h, #0
; CHECK-GI-BE-NEXT:    sshll2 v3.4s, v0.8h, #0
; CHECK-GI-BE-NEXT:    sshll v2.4s, v2.4h, #0
; CHECK-GI-BE-NEXT:    sshll v0.4s, v0.4h, #0
; CHECK-GI-BE-NEXT:    abs v1.4s, v1.4s
; CHECK-GI-BE-NEXT:    abs v3.4s, v3.4s
; CHECK-GI-BE-NEXT:    saba v1.4s, v2.4s, v4.4s
; CHECK-GI-BE-NEXT:    saba v3.4s, v0.4s, v4.4s
; CHECK-GI-BE-NEXT:    add v0.4s, v1.4s, v3.4s
; CHECK-GI-BE-NEXT:    addv s0, v0.4s
; CHECK-GI-BE-NEXT:    fmov w8, s0
; CHECK-GI-BE-NEXT:  .LBB16_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    subs w3, w3, #1
; CHECK-GI-BE-NEXT:    add w0, w8, w0
; CHECK-GI-BE-NEXT:    b.ne .LBB16_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %s0 = phi i32 [ 0, %entry ], [ %op.rdx, %loop ]
  %j.0261 = phi i32 [ 0, %entry ], [ %inc, %loop ]
  %gep.1 = getelementptr inbounds <16 x i8>, ptr %p1, i64 %lx
  %gep.2 = getelementptr inbounds <16 x i8>, ptr %p2, i64 %lx
  %l1 = load <16 x i8>, ptr %gep.1
  %z2 = zext <16 x i8> %l1 to <16 x i32>
  %l4 = load <16 x i8>, ptr %gep.2
  %z5 = zext <16 x i8> %l4 to <16 x i32>
  %sub = sub nsw <16 x i32> %z2, %z5
  %abs = tail call <16 x i32> @llvm.abs.v16i32(<16 x i32> %sub, i1 true)
  %red = tail call i32 @llvm.vector.reduce.add.v16i32(<16 x i32> %abs)
  %op.rdx = add i32 %red, %s0
  %inc = add nuw nsw i32 %j.0261, 1
  %exitcond.not = icmp eq i32 %inc, %h
  br i1 %exitcond.not, label %exit, label %loop

exit:
  %s1 = phi i32 [ %op.rdx, %loop ]
  ret i32 %s1
}

declare <16 x i32> @llvm.abs.v16i32(<16 x i32>, i1 immarg)

declare i32 @llvm.vector.reduce.add.v16i32(<16 x i32>)

define i32 @test_widening_instr_mull(ptr %p1, ptr %p2, i32 %h) {
; CHECK-SD-LABEL: test_widening_instr_mull:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, x0
; CHECK-SD-NEXT:  LBB17_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x1], #16
; CHECK-SD-NEXT:    ldr q3, [x0]
; CHECK-SD-NEXT:    ldr q2, [x8, #16]!
; CHECK-SD-NEXT:    subs w2, w2, #1
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    umull2.4s v4, v2, v1
; CHECK-SD-NEXT:    umull.4s v1, v2, v1
; CHECK-SD-NEXT:    umull2.4s v2, v3, v0
; CHECK-SD-NEXT:    umull.4s v0, v3, v0
; CHECK-SD-NEXT:    stp q1, q4, [x0, #32]
; CHECK-SD-NEXT:    str q0, [x0]
; CHECK-SD-NEXT:    mov x0, x8
; CHECK-SD-NEXT:    str q2, [x8]
; CHECK-SD-NEXT:    b.ne LBB17_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    mov w0, wzr
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: test_widening_instr_mull:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:  .LBB17_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x1], #16
; CHECK-SD-BE-NEXT:    add x8, x0, #16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x0]
; CHECK-SD-BE-NEXT:    ld1 { v3.8h }, [x8]
; CHECK-SD-BE-NEXT:    add x9, x0, #48
; CHECK-SD-BE-NEXT:    add x10, x0, #32
; CHECK-SD-BE-NEXT:    subs w2, w2, #1
; CHECK-SD-BE-NEXT:    ushll v2.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    umull v4.4s, v1.4h, v2.4h
; CHECK-SD-BE-NEXT:    umull2 v5.4s, v3.8h, v0.8h
; CHECK-SD-BE-NEXT:    umull v0.4s, v3.4h, v0.4h
; CHECK-SD-BE-NEXT:    umull2 v1.4s, v1.8h, v2.8h
; CHECK-SD-BE-NEXT:    st1 { v4.4s }, [x0]
; CHECK-SD-BE-NEXT:    mov x0, x8
; CHECK-SD-BE-NEXT:    st1 { v5.4s }, [x9]
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x10]
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-SD-BE-NEXT:    b.ne .LBB17_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: test_widening_instr_mull:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:  LBB17_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x1], #16
; CHECK-GI-NEXT:    subs w2, w2, #1
; CHECK-GI-NEXT:    ldp q2, q3, [x0]
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    umull.4s v4, v2, v1
; CHECK-GI-NEXT:    umull2.4s v1, v2, v1
; CHECK-GI-NEXT:    umull.4s v2, v3, v0
; CHECK-GI-NEXT:    umull2.4s v0, v3, v0
; CHECK-GI-NEXT:    stp q4, q1, [x0]
; CHECK-GI-NEXT:    stp q2, q0, [x0, #32]
; CHECK-GI-NEXT:    add x0, x0, #16
; CHECK-GI-NEXT:    b.ne LBB17_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    mov w0, wzr
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: test_widening_instr_mull:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:  .LBB17_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x1]
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x0]
; CHECK-GI-BE-NEXT:    add x8, x0, #16
; CHECK-GI-BE-NEXT:    ld1 { v3.8h }, [x8]
; CHECK-GI-BE-NEXT:    add x9, x0, #48
; CHECK-GI-BE-NEXT:    add x10, x0, #32
; CHECK-GI-BE-NEXT:    subs w2, w2, #1
; CHECK-GI-BE-NEXT:    add x1, x1, #16
; CHECK-GI-BE-NEXT:    ushll2 v2.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    umull2 v4.4s, v1.8h, v2.8h
; CHECK-GI-BE-NEXT:    umull v5.4s, v3.4h, v0.4h
; CHECK-GI-BE-NEXT:    umull2 v0.4s, v3.8h, v0.8h
; CHECK-GI-BE-NEXT:    umull v1.4s, v1.4h, v2.4h
; CHECK-GI-BE-NEXT:    st1 { v4.4s }, [x0]
; CHECK-GI-BE-NEXT:    mov x0, x8
; CHECK-GI-BE-NEXT:    st1 { v5.4s }, [x9]
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x10]
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-GI-BE-NEXT:    b.ne .LBB17_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.1 = getelementptr inbounds <16 x i8>, ptr %p1, i32 %iv
  %gep.2 = getelementptr inbounds <16 x i8>, ptr %p2, i32 %iv
  %l1 = load <16 x i16>, ptr %gep.1
  %z2 = zext <16 x i16> %l1 to <16 x i32>
  %l4 = load <16 x i8>, ptr %gep.2
  %z5 = zext <16 x i8> %l4 to <16 x i32>
  %mul = mul <16 x i32> %z2, %z5
  store <16 x i32> %mul, ptr %gep.1
  %iv.next= add nuw nsw i32 %iv, 1
  %exitcond.not = icmp eq i32 %iv.next, %h
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret i32 0
}

define i32 @test_widening_instr_mull_64(ptr %p1, ptr %p2, i32 %h) {
; CHECK-SD-LABEL: test_widening_instr_mull_64:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:  Lloh16:
; CHECK-SD-NEXT:    adrp x8, lCPI18_0@PAGE
; CHECK-SD-NEXT:  Lloh17:
; CHECK-SD-NEXT:    adrp x9, lCPI18_1@PAGE
; CHECK-SD-NEXT:  Lloh18:
; CHECK-SD-NEXT:    adrp x10, lCPI18_3@PAGE
; CHECK-SD-NEXT:  Lloh19:
; CHECK-SD-NEXT:    ldr q0, [x8, lCPI18_0@PAGEOFF]
; CHECK-SD-NEXT:  Lloh20:
; CHECK-SD-NEXT:    adrp x8, lCPI18_2@PAGE
; CHECK-SD-NEXT:  Lloh21:
; CHECK-SD-NEXT:    ldr q1, [x9, lCPI18_1@PAGEOFF]
; CHECK-SD-NEXT:  Lloh22:
; CHECK-SD-NEXT:    ldr q2, [x8, lCPI18_2@PAGEOFF]
; CHECK-SD-NEXT:  Lloh23:
; CHECK-SD-NEXT:    ldr q3, [x10, lCPI18_3@PAGEOFF]
; CHECK-SD-NEXT:    mov x8, x1
; CHECK-SD-NEXT:  LBB18_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q4, [x0]
; CHECK-SD-NEXT:    ldp q17, q16, [x1, #32]
; CHECK-SD-NEXT:    ldr q18, [x1]
; CHECK-SD-NEXT:    subs w2, w2, #1
; CHECK-SD-NEXT:    tbl.16b v5, { v4 }, v3
; CHECK-SD-NEXT:    tbl.16b v6, { v4 }, v0
; CHECK-SD-NEXT:    tbl.16b v7, { v4 }, v1
; CHECK-SD-NEXT:    tbl.16b v4, { v4 }, v2
; CHECK-SD-NEXT:    ldr q21, [x8, #16]!
; CHECK-SD-NEXT:    mov x1, x8
; CHECK-SD-NEXT:    umull2.2d v19, v5, v16
; CHECK-SD-NEXT:    umull2.2d v20, v6, v17
; CHECK-SD-NEXT:    umull2.2d v22, v7, v18
; CHECK-SD-NEXT:    umull.2d v5, v5, v16
; CHECK-SD-NEXT:    umull2.2d v16, v4, v21
; CHECK-SD-NEXT:    umull.2d v4, v4, v21
; CHECK-SD-NEXT:    umull.2d v7, v7, v18
; CHECK-SD-NEXT:    umull.2d v6, v6, v17
; CHECK-SD-NEXT:    str q20, [x0, #80]
; CHECK-SD-NEXT:    stp q22, q4, [x0, #16]
; CHECK-SD-NEXT:    stp q5, q19, [x0, #96]
; CHECK-SD-NEXT:    str q16, [x0, #48]
; CHECK-SD-NEXT:    str q7, [x0]
; CHECK-SD-NEXT:    str q6, [x0, #64]!
; CHECK-SD-NEXT:    b.ne LBB18_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    mov w0, wzr
; CHECK-SD-NEXT:    ret
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh20, Lloh22
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh18, Lloh23
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh17, Lloh21
; CHECK-SD-NEXT:    .loh AdrpAdrp Lloh16, Lloh20
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh16, Lloh19
;
; CHECK-SD-BE-LABEL: test_widening_instr_mull_64:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI18_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI18_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI18_1
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI18_1
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI18_2
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI18_2
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI18_3
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI18_3
; CHECK-SD-BE-NEXT:    ld1 { v3.16b }, [x8]
; CHECK-SD-BE-NEXT:  .LBB18_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ld1 { v4.16b }, [x0]
; CHECK-SD-BE-NEXT:    add x9, x1, #48
; CHECK-SD-BE-NEXT:    add x8, x1, #32
; CHECK-SD-BE-NEXT:    ld1 { v18.4s }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v16.4s }, [x1]
; CHECK-SD-BE-NEXT:    add x1, x1, #16
; CHECK-SD-BE-NEXT:    ld1 { v20.4s }, [x8]
; CHECK-SD-BE-NEXT:    ld1 { v22.4s }, [x1]
; CHECK-SD-BE-NEXT:    add x8, x0, #96
; CHECK-SD-BE-NEXT:    tbl v5.16b, { v4.16b }, v3.16b
; CHECK-SD-BE-NEXT:    tbl v6.16b, { v4.16b }, v2.16b
; CHECK-SD-BE-NEXT:    tbl v7.16b, { v4.16b }, v1.16b
; CHECK-SD-BE-NEXT:    tbl v4.16b, { v4.16b }, v0.16b
; CHECK-SD-BE-NEXT:    ext v24.16b, v18.16b, v18.16b, #8
; CHECK-SD-BE-NEXT:    add x9, x0, #32
; CHECK-SD-BE-NEXT:    ext v25.16b, v20.16b, v20.16b, #8
; CHECK-SD-BE-NEXT:    add x10, x0, #16
; CHECK-SD-BE-NEXT:    subs w2, w2, #1
; CHECK-SD-BE-NEXT:    ext v17.16b, v5.16b, v5.16b, #8
; CHECK-SD-BE-NEXT:    ext v19.16b, v6.16b, v6.16b, #8
; CHECK-SD-BE-NEXT:    rev32 v5.8b, v5.8b
; CHECK-SD-BE-NEXT:    rev32 v21.8b, v7.8b
; CHECK-SD-BE-NEXT:    rev32 v23.8b, v4.8b
; CHECK-SD-BE-NEXT:    ext v7.16b, v7.16b, v7.16b, #8
; CHECK-SD-BE-NEXT:    ext v4.16b, v4.16b, v4.16b, #8
; CHECK-SD-BE-NEXT:    rev32 v6.8b, v6.8b
; CHECK-SD-BE-NEXT:    rev32 v17.8b, v17.8b
; CHECK-SD-BE-NEXT:    rev32 v19.8b, v19.8b
; CHECK-SD-BE-NEXT:    umull v5.2d, v5.2s, v18.2s
; CHECK-SD-BE-NEXT:    umull v18.2d, v21.2s, v22.2s
; CHECK-SD-BE-NEXT:    ext v21.16b, v22.16b, v22.16b, #8
; CHECK-SD-BE-NEXT:    rev32 v7.8b, v7.8b
; CHECK-SD-BE-NEXT:    umull v22.2d, v23.2s, v16.2s
; CHECK-SD-BE-NEXT:    ext v16.16b, v16.16b, v16.16b, #8
; CHECK-SD-BE-NEXT:    rev32 v4.8b, v4.8b
; CHECK-SD-BE-NEXT:    umull v17.2d, v17.2s, v24.2s
; CHECK-SD-BE-NEXT:    umull v19.2d, v19.2s, v25.2s
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x8]
; CHECK-SD-BE-NEXT:    umull v5.2d, v6.2s, v20.2s
; CHECK-SD-BE-NEXT:    umull v6.2d, v7.2s, v21.2s
; CHECK-SD-BE-NEXT:    add x8, x0, #112
; CHECK-SD-BE-NEXT:    umull v4.2d, v4.2s, v16.2s
; CHECK-SD-BE-NEXT:    st1 { v18.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x0, #80
; CHECK-SD-BE-NEXT:    st1 { v22.2d }, [x0]
; CHECK-SD-BE-NEXT:    st1 { v17.2d }, [x8]
; CHECK-SD-BE-NEXT:    add x8, x0, #64
; CHECK-SD-BE-NEXT:    st1 { v19.2d }, [x9]
; CHECK-SD-BE-NEXT:    add x9, x0, #48
; CHECK-SD-BE-NEXT:    mov x0, x8
; CHECK-SD-BE-NEXT:    st1 { v5.2d }, [x8]
; CHECK-SD-BE-NEXT:    st1 { v6.2d }, [x9]
; CHECK-SD-BE-NEXT:    st1 { v4.2d }, [x10]
; CHECK-SD-BE-NEXT:    b.ne .LBB18_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: test_widening_instr_mull_64:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:  Lloh18:
; CHECK-GI-NEXT:    adrp x8, lCPI18_3@PAGE
; CHECK-GI-NEXT:    movi d5, #0000000000000000
; CHECK-GI-NEXT:  Lloh19:
; CHECK-GI-NEXT:    adrp x9, lCPI18_2@PAGE
; CHECK-GI-NEXT:  Lloh20:
; CHECK-GI-NEXT:    ldr q0, [x8, lCPI18_3@PAGEOFF]
; CHECK-GI-NEXT:  Lloh21:
; CHECK-GI-NEXT:    adrp x8, lCPI18_1@PAGE
; CHECK-GI-NEXT:  Lloh22:
; CHECK-GI-NEXT:    adrp x10, lCPI18_0@PAGE
; CHECK-GI-NEXT:  Lloh23:
; CHECK-GI-NEXT:    ldr q1, [x9, lCPI18_2@PAGEOFF]
; CHECK-GI-NEXT:  Lloh24:
; CHECK-GI-NEXT:    ldr q2, [x8, lCPI18_1@PAGEOFF]
; CHECK-GI-NEXT:  Lloh25:
; CHECK-GI-NEXT:    ldr q3, [x10, lCPI18_0@PAGEOFF]
; CHECK-GI-NEXT:  LBB18_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q4, [x0]
; CHECK-GI-NEXT:    ldp q16, q17, [x1]
; CHECK-GI-NEXT:    subs w2, w2, #1
; CHECK-GI-NEXT:    tbl.16b v6, { v4, v5 }, v0
; CHECK-GI-NEXT:    tbl.16b v7, { v4, v5 }, v1
; CHECK-GI-NEXT:    tbl.16b v18, { v4, v5 }, v2
; CHECK-GI-NEXT:    tbl.16b v20, { v4, v5 }, v3
; CHECK-GI-NEXT:    umull.2d v19, v6, v16
; CHECK-GI-NEXT:    umull2.2d v6, v6, v16
; CHECK-GI-NEXT:    umull.2d v21, v7, v17
; CHECK-GI-NEXT:    umull2.2d v7, v7, v17
; CHECK-GI-NEXT:    ldp q16, q17, [x1, #32]
; CHECK-GI-NEXT:    add x1, x1, #16
; CHECK-GI-NEXT:    umull.2d v22, v18, v16
; CHECK-GI-NEXT:    stp q19, q6, [x0]
; CHECK-GI-NEXT:    umull2.2d v16, v18, v16
; CHECK-GI-NEXT:    umull.2d v6, v20, v17
; CHECK-GI-NEXT:    umull2.2d v17, v20, v17
; CHECK-GI-NEXT:    stp q21, q7, [x0, #32]
; CHECK-GI-NEXT:    stp q22, q16, [x0, #64]
; CHECK-GI-NEXT:    stp q6, q17, [x0, #96]
; CHECK-GI-NEXT:    add x0, x0, #64
; CHECK-GI-NEXT:    b.ne LBB18_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    mov w0, wzr
; CHECK-GI-NEXT:    ret
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh22, Lloh25
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh21, Lloh24
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh19, Lloh23
; CHECK-GI-NEXT:    .loh AdrpAdrp Lloh18, Lloh21
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh18, Lloh20
;
; CHECK-GI-BE-LABEL: test_widening_instr_mull_64:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI18_3
; CHECK-GI-BE-NEXT:    movi d4, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI18_2
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI18_3]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI18_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI18_0
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI18_2]
; CHECK-GI-BE-NEXT:    ldr q2, [x8, :lo12:.LCPI18_1]
; CHECK-GI-BE-NEXT:    ldr q3, [x10, :lo12:.LCPI18_0]
; CHECK-GI-BE-NEXT:  .LBB18_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ld1 { v5.16b }, [x0]
; CHECK-GI-BE-NEXT:    add x8, x1, #48
; CHECK-GI-BE-NEXT:    add x9, x1, #16
; CHECK-GI-BE-NEXT:    ld1 { v18.4s }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x1, #32
; CHECK-GI-BE-NEXT:    ld1 { v20.4s }, [x9]
; CHECK-GI-BE-NEXT:    ld1 { v19.4s }, [x8]
; CHECK-GI-BE-NEXT:    ld1 { v22.4s }, [x1]
; CHECK-GI-BE-NEXT:    add x8, x0, #112
; CHECK-GI-BE-NEXT:    tbl v6.16b, { v4.16b, v5.16b }, v0.16b
; CHECK-GI-BE-NEXT:    tbl v7.16b, { v4.16b, v5.16b }, v1.16b
; CHECK-GI-BE-NEXT:    tbl v16.16b, { v4.16b, v5.16b }, v2.16b
; CHECK-GI-BE-NEXT:    tbl v17.16b, { v4.16b, v5.16b }, v3.16b
; CHECK-GI-BE-NEXT:    add x10, x0, #96
; CHECK-GI-BE-NEXT:    subs w2, w2, #1
; CHECK-GI-BE-NEXT:    mov x1, x9
; CHECK-GI-BE-NEXT:    rev32 v6.16b, v6.16b
; CHECK-GI-BE-NEXT:    rev32 v7.16b, v7.16b
; CHECK-GI-BE-NEXT:    rev32 v16.16b, v16.16b
; CHECK-GI-BE-NEXT:    rev32 v17.16b, v17.16b
; CHECK-GI-BE-NEXT:    umull v21.2d, v6.2s, v18.2s
; CHECK-GI-BE-NEXT:    umull2 v6.2d, v6.4s, v18.4s
; CHECK-GI-BE-NEXT:    umull v18.2d, v7.2s, v19.2s
; CHECK-GI-BE-NEXT:    umull v23.2d, v16.2s, v20.2s
; CHECK-GI-BE-NEXT:    umull2 v16.2d, v16.4s, v20.4s
; CHECK-GI-BE-NEXT:    st1 { v21.2d }, [x8]
; CHECK-GI-BE-NEXT:    umull2 v21.2d, v17.4s, v22.4s
; CHECK-GI-BE-NEXT:    add x8, x0, #80
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x10]
; CHECK-GI-BE-NEXT:    umull2 v6.2d, v7.4s, v19.4s
; CHECK-GI-BE-NEXT:    umull v7.2d, v17.2s, v22.2s
; CHECK-GI-BE-NEXT:    add x10, x0, #48
; CHECK-GI-BE-NEXT:    st1 { v18.2d }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x0, #32
; CHECK-GI-BE-NEXT:    st1 { v23.2d }, [x10]
; CHECK-GI-BE-NEXT:    add x10, x0, #64
; CHECK-GI-BE-NEXT:    st1 { v21.2d }, [x0]
; CHECK-GI-BE-NEXT:    st1 { v16.2d }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x0, #16
; CHECK-GI-BE-NEXT:    mov x0, x10
; CHECK-GI-BE-NEXT:    st1 { v6.2d }, [x10]
; CHECK-GI-BE-NEXT:    st1 { v7.2d }, [x8]
; CHECK-GI-BE-NEXT:    b.ne .LBB18_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.1 = getelementptr inbounds <16 x i32>, ptr %p1, i32 %iv
  %gep.2 = getelementptr inbounds <16 x i8>, ptr %p2, i32 %iv
  %l1 = load <16 x i8>, ptr %gep.1
  %z2 = zext <16 x i8> %l1 to <16 x i64>
  %l4 = load <16 x i32>, ptr %gep.2
  %z5 = zext <16 x i32> %l4 to <16 x i64>
  %mul = mul <16 x i64> %z2, %z5
  store <16 x i64> %mul, ptr %gep.1
  %iv.next= add nuw nsw i32 %iv, 1
  %exitcond.not = icmp eq i32 %iv.next, %h
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret i32 0
}

define i32 @test_widening_instr_mull_2(ptr %p1, ptr %p2, i32 %h) {
; CHECK-SD-LABEL: test_widening_instr_mull_2:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:  Lloh24:
; CHECK-SD-NEXT:    adrp x8, lCPI19_0@PAGE
; CHECK-SD-NEXT:  Lloh25:
; CHECK-SD-NEXT:    adrp x9, lCPI19_1@PAGE
; CHECK-SD-NEXT:  Lloh26:
; CHECK-SD-NEXT:    adrp x10, lCPI19_3@PAGE
; CHECK-SD-NEXT:  Lloh27:
; CHECK-SD-NEXT:    ldr q0, [x8, lCPI19_0@PAGEOFF]
; CHECK-SD-NEXT:  Lloh28:
; CHECK-SD-NEXT:    adrp x8, lCPI19_2@PAGE
; CHECK-SD-NEXT:  Lloh29:
; CHECK-SD-NEXT:    ldr q1, [x9, lCPI19_1@PAGEOFF]
; CHECK-SD-NEXT:  Lloh30:
; CHECK-SD-NEXT:    ldr q2, [x8, lCPI19_2@PAGEOFF]
; CHECK-SD-NEXT:  Lloh31:
; CHECK-SD-NEXT:    ldr q3, [x10, lCPI19_3@PAGEOFF]
; CHECK-SD-NEXT:    mov x8, x0
; CHECK-SD-NEXT:  LBB19_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q4, [x1], #16
; CHECK-SD-NEXT:    ldr q18, [x0]
; CHECK-SD-NEXT:    ldp q16, q17, [x0, #32]
; CHECK-SD-NEXT:    subs w2, w2, #1
; CHECK-SD-NEXT:    tbl.16b v5, { v4 }, v0
; CHECK-SD-NEXT:    tbl.16b v6, { v4 }, v1
; CHECK-SD-NEXT:    tbl.16b v7, { v4 }, v2
; CHECK-SD-NEXT:    tbl.16b v4, { v4 }, v3
; CHECK-SD-NEXT:    mul.4s v5, v16, v5
; CHECK-SD-NEXT:    ldr q16, [x8, #16]!
; CHECK-SD-NEXT:    mul.4s v6, v17, v6
; CHECK-SD-NEXT:    mul.4s v7, v18, v7
; CHECK-SD-NEXT:    mul.4s v4, v16, v4
; CHECK-SD-NEXT:    stp q5, q6, [x0, #32]
; CHECK-SD-NEXT:    str q7, [x0]
; CHECK-SD-NEXT:    mov x0, x8
; CHECK-SD-NEXT:    str q4, [x8]
; CHECK-SD-NEXT:    b.ne LBB19_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    mov w0, wzr
; CHECK-SD-NEXT:    ret
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh28, Lloh30
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh26, Lloh31
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh25, Lloh29
; CHECK-SD-NEXT:    .loh AdrpAdrp Lloh24, Lloh28
; CHECK-SD-NEXT:    .loh AdrpLdr Lloh24, Lloh27
;
; CHECK-SD-BE-LABEL: test_widening_instr_mull_2:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI19_0
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI19_0
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI19_1
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI19_1
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI19_2
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI19_2
; CHECK-SD-BE-NEXT:    ld1 { v2.16b }, [x8]
; CHECK-SD-BE-NEXT:    adrp x8, .LCPI19_3
; CHECK-SD-BE-NEXT:    add x8, x8, :lo12:.LCPI19_3
; CHECK-SD-BE-NEXT:    ld1 { v3.16b }, [x8]
; CHECK-SD-BE-NEXT:  .LBB19_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ld1 { v4.16b }, [x1], #16
; CHECK-SD-BE-NEXT:    add x8, x0, #32
; CHECK-SD-BE-NEXT:    ld1 { v16.4s }, [x0]
; CHECK-SD-BE-NEXT:    add x9, x0, #48
; CHECK-SD-BE-NEXT:    add x10, x0, #16
; CHECK-SD-BE-NEXT:    ld1 { v17.4s }, [x8]
; CHECK-SD-BE-NEXT:    ld1 { v18.4s }, [x9]
; CHECK-SD-BE-NEXT:    ld1 { v19.4s }, [x10]
; CHECK-SD-BE-NEXT:    subs w2, w2, #1
; CHECK-SD-BE-NEXT:    tbl v5.16b, { v4.16b }, v1.16b
; CHECK-SD-BE-NEXT:    tbl v6.16b, { v4.16b }, v3.16b
; CHECK-SD-BE-NEXT:    tbl v7.16b, { v4.16b }, v2.16b
; CHECK-SD-BE-NEXT:    tbl v4.16b, { v4.16b }, v0.16b
; CHECK-SD-BE-NEXT:    rev32 v5.16b, v5.16b
; CHECK-SD-BE-NEXT:    rev32 v6.16b, v6.16b
; CHECK-SD-BE-NEXT:    rev32 v7.16b, v7.16b
; CHECK-SD-BE-NEXT:    rev32 v4.16b, v4.16b
; CHECK-SD-BE-NEXT:    mul v5.4s, v16.4s, v5.4s
; CHECK-SD-BE-NEXT:    mul v6.4s, v17.4s, v6.4s
; CHECK-SD-BE-NEXT:    mul v7.4s, v18.4s, v7.4s
; CHECK-SD-BE-NEXT:    mul v4.4s, v19.4s, v4.4s
; CHECK-SD-BE-NEXT:    st1 { v5.4s }, [x0]
; CHECK-SD-BE-NEXT:    mov x0, x10
; CHECK-SD-BE-NEXT:    st1 { v6.4s }, [x8]
; CHECK-SD-BE-NEXT:    st1 { v7.4s }, [x9]
; CHECK-SD-BE-NEXT:    st1 { v4.4s }, [x10]
; CHECK-SD-BE-NEXT:    b.ne .LBB19_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: test_widening_instr_mull_2:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:  Lloh26:
; CHECK-GI-NEXT:    adrp x8, lCPI19_3@PAGE
; CHECK-GI-NEXT:    movi d5, #0000000000000000
; CHECK-GI-NEXT:  Lloh27:
; CHECK-GI-NEXT:    adrp x9, lCPI19_2@PAGE
; CHECK-GI-NEXT:  Lloh28:
; CHECK-GI-NEXT:    ldr q0, [x8, lCPI19_3@PAGEOFF]
; CHECK-GI-NEXT:  Lloh29:
; CHECK-GI-NEXT:    adrp x8, lCPI19_1@PAGE
; CHECK-GI-NEXT:  Lloh30:
; CHECK-GI-NEXT:    adrp x10, lCPI19_0@PAGE
; CHECK-GI-NEXT:  Lloh31:
; CHECK-GI-NEXT:    ldr q1, [x9, lCPI19_2@PAGEOFF]
; CHECK-GI-NEXT:  Lloh32:
; CHECK-GI-NEXT:    ldr q2, [x8, lCPI19_1@PAGEOFF]
; CHECK-GI-NEXT:  Lloh33:
; CHECK-GI-NEXT:    ldr q3, [x10, lCPI19_0@PAGEOFF]
; CHECK-GI-NEXT:  LBB19_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q4, [x1], #16
; CHECK-GI-NEXT:    subs w2, w2, #1
; CHECK-GI-NEXT:    ldp q17, q18, [x0]
; CHECK-GI-NEXT:    tbl.16b v6, { v4, v5 }, v0
; CHECK-GI-NEXT:    tbl.16b v7, { v4, v5 }, v1
; CHECK-GI-NEXT:    tbl.16b v16, { v4, v5 }, v2
; CHECK-GI-NEXT:    tbl.16b v19, { v4, v5 }, v3
; CHECK-GI-NEXT:    mul.4s v6, v17, v6
; CHECK-GI-NEXT:    ldp q17, q20, [x0, #32]
; CHECK-GI-NEXT:    mul.4s v7, v18, v7
; CHECK-GI-NEXT:    mul.4s v16, v17, v16
; CHECK-GI-NEXT:    mul.4s v17, v20, v19
; CHECK-GI-NEXT:    stp q6, q7, [x0]
; CHECK-GI-NEXT:    stp q16, q17, [x0, #32]
; CHECK-GI-NEXT:    add x0, x0, #16
; CHECK-GI-NEXT:    b.ne LBB19_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    mov w0, wzr
; CHECK-GI-NEXT:    ret
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh30, Lloh33
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh29, Lloh32
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh27, Lloh31
; CHECK-GI-NEXT:    .loh AdrpAdrp Lloh26, Lloh29
; CHECK-GI-NEXT:    .loh AdrpLdr Lloh26, Lloh28
;
; CHECK-GI-BE-LABEL: test_widening_instr_mull_2:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI19_3
; CHECK-GI-BE-NEXT:    movi d4, #0000000000000000
; CHECK-GI-BE-NEXT:    adrp x9, .LCPI19_2
; CHECK-GI-BE-NEXT:    ldr q0, [x8, :lo12:.LCPI19_3]
; CHECK-GI-BE-NEXT:    adrp x8, .LCPI19_1
; CHECK-GI-BE-NEXT:    adrp x10, .LCPI19_0
; CHECK-GI-BE-NEXT:    ldr q1, [x9, :lo12:.LCPI19_2]
; CHECK-GI-BE-NEXT:    ldr q2, [x8, :lo12:.LCPI19_1]
; CHECK-GI-BE-NEXT:    ldr q3, [x10, :lo12:.LCPI19_0]
; CHECK-GI-BE-NEXT:  .LBB19_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ld1 { v5.16b }, [x1]
; CHECK-GI-BE-NEXT:    add x8, x0, #48
; CHECK-GI-BE-NEXT:    ld1 { v18.4s }, [x0]
; CHECK-GI-BE-NEXT:    add x9, x0, #32
; CHECK-GI-BE-NEXT:    add x10, x0, #16
; CHECK-GI-BE-NEXT:    ld1 { v19.4s }, [x8]
; CHECK-GI-BE-NEXT:    ld1 { v20.4s }, [x9]
; CHECK-GI-BE-NEXT:    ld1 { v21.4s }, [x10]
; CHECK-GI-BE-NEXT:    subs w2, w2, #1
; CHECK-GI-BE-NEXT:    tbl v6.16b, { v4.16b, v5.16b }, v3.16b
; CHECK-GI-BE-NEXT:    tbl v7.16b, { v4.16b, v5.16b }, v0.16b
; CHECK-GI-BE-NEXT:    tbl v16.16b, { v4.16b, v5.16b }, v1.16b
; CHECK-GI-BE-NEXT:    tbl v17.16b, { v4.16b, v5.16b }, v2.16b
; CHECK-GI-BE-NEXT:    add x1, x1, #16
; CHECK-GI-BE-NEXT:    rev32 v6.16b, v6.16b
; CHECK-GI-BE-NEXT:    rev32 v7.16b, v7.16b
; CHECK-GI-BE-NEXT:    rev32 v16.16b, v16.16b
; CHECK-GI-BE-NEXT:    rev32 v17.16b, v17.16b
; CHECK-GI-BE-NEXT:    mul v6.4s, v18.4s, v6.4s
; CHECK-GI-BE-NEXT:    mul v7.4s, v19.4s, v7.4s
; CHECK-GI-BE-NEXT:    mul v16.4s, v20.4s, v16.4s
; CHECK-GI-BE-NEXT:    mul v17.4s, v21.4s, v17.4s
; CHECK-GI-BE-NEXT:    st1 { v6.4s }, [x0]
; CHECK-GI-BE-NEXT:    mov x0, x10
; CHECK-GI-BE-NEXT:    st1 { v7.4s }, [x8]
; CHECK-GI-BE-NEXT:    st1 { v16.4s }, [x9]
; CHECK-GI-BE-NEXT:    st1 { v17.4s }, [x10]
; CHECK-GI-BE-NEXT:    b.ne .LBB19_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.1 = getelementptr inbounds <16 x i8>, ptr %p1, i32 %iv
  %gep.2 = getelementptr inbounds <16 x i8>, ptr %p2, i32 %iv
  %l1 = load <16 x i32>, ptr %gep.1
  %l4 = load <16 x i8>, ptr %gep.2
  %z5 = zext <16 x i8> %l4 to <16 x i32>
  %mul = mul <16 x i32> %l1, %z5
  store <16 x i32> %mul, ptr %gep.1
  %iv.next= add nuw nsw i32 %iv, 1
  %exitcond.not = icmp eq i32 %iv.next, %h
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret i32 0
}

; Not profitable to convert when there is an opportunity to partially
; reduce the cost of widening by generating smul
define i32 @mul_zext_16i8_sext_16i8(ptr %p1, ptr %p2, i32 %h) {
; CHECK-SD-LABEL: mul_zext_16i8_sext_16i8:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:  LBB20_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x0]
; CHECK-SD-NEXT:    ldr q1, [x1], #16
; CHECK-SD-NEXT:    subs w2, w2, #1
; CHECK-SD-NEXT:    sshll2.8h v2, v0, #0
; CHECK-SD-NEXT:    ushll2.8h v3, v1, #0
; CHECK-SD-NEXT:    sshll.8h v0, v0, #0
; CHECK-SD-NEXT:    ushll.8h v1, v1, #0
; CHECK-SD-NEXT:    smull2.4s v4, v2, v3
; CHECK-SD-NEXT:    smull.4s v2, v2, v3
; CHECK-SD-NEXT:    smull.4s v3, v0, v1
; CHECK-SD-NEXT:    smull2.4s v0, v0, v1
; CHECK-SD-NEXT:    stp q2, q4, [x0, #32]
; CHECK-SD-NEXT:    str q3, [x0]
; CHECK-SD-NEXT:    str q0, [x0, #16]!
; CHECK-SD-NEXT:    b.ne LBB20_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    mov w0, wzr
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mul_zext_16i8_sext_16i8:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:  .LBB20_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x1], #16
; CHECK-SD-BE-NEXT:    add x8, x0, #48
; CHECK-SD-BE-NEXT:    ld1 { v1.16b }, [x0]
; CHECK-SD-BE-NEXT:    subs w2, w2, #1
; CHECK-SD-BE-NEXT:    sshll2 v2.8h, v1.16b, #0
; CHECK-SD-BE-NEXT:    ushll2 v3.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    sshll v1.8h, v1.8b, #0
; CHECK-SD-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    smull2 v4.4s, v2.8h, v3.8h
; CHECK-SD-BE-NEXT:    smull v2.4s, v2.4h, v3.4h
; CHECK-SD-BE-NEXT:    smull v3.4s, v1.4h, v0.4h
; CHECK-SD-BE-NEXT:    smull2 v0.4s, v1.8h, v0.8h
; CHECK-SD-BE-NEXT:    st1 { v4.4s }, [x8]
; CHECK-SD-BE-NEXT:    add x8, x0, #32
; CHECK-SD-BE-NEXT:    st1 { v3.4s }, [x0]
; CHECK-SD-BE-NEXT:    add x0, x0, #16
; CHECK-SD-BE-NEXT:    st1 { v2.4s }, [x8]
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x0]
; CHECK-SD-BE-NEXT:    b.ne .LBB20_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: mul_zext_16i8_sext_16i8:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:  LBB20_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x0]
; CHECK-GI-NEXT:    ldr q1, [x1], #16
; CHECK-GI-NEXT:    subs w2, w2, #1
; CHECK-GI-NEXT:    sshll.8h v2, v0, #0
; CHECK-GI-NEXT:    ushll.8h v3, v1, #0
; CHECK-GI-NEXT:    sshll2.8h v0, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v1, v1, #0
; CHECK-GI-NEXT:    smull.4s v4, v2, v3
; CHECK-GI-NEXT:    smull2.4s v2, v2, v3
; CHECK-GI-NEXT:    smull.4s v3, v0, v1
; CHECK-GI-NEXT:    smull2.4s v0, v0, v1
; CHECK-GI-NEXT:    stp q4, q2, [x0]
; CHECK-GI-NEXT:    stp q3, q0, [x0, #32]
; CHECK-GI-NEXT:    add x0, x0, #16
; CHECK-GI-NEXT:    b.ne LBB20_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    mov w0, wzr
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mul_zext_16i8_sext_16i8:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:  .LBB20_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x0]
; CHECK-GI-BE-NEXT:    ld1 { v1.16b }, [x1]
; CHECK-GI-BE-NEXT:    add x8, x0, #48
; CHECK-GI-BE-NEXT:    subs w2, w2, #1
; CHECK-GI-BE-NEXT:    add x1, x1, #16
; CHECK-GI-BE-NEXT:    sshll v2.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    ushll v3.8h, v1.8b, #0
; CHECK-GI-BE-NEXT:    sshll2 v0.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll2 v1.8h, v1.16b, #0
; CHECK-GI-BE-NEXT:    smull v4.4s, v2.4h, v3.4h
; CHECK-GI-BE-NEXT:    smull2 v2.4s, v2.8h, v3.8h
; CHECK-GI-BE-NEXT:    smull2 v3.4s, v0.8h, v1.8h
; CHECK-GI-BE-NEXT:    smull v0.4s, v0.4h, v1.4h
; CHECK-GI-BE-NEXT:    st1 { v4.4s }, [x8]
; CHECK-GI-BE-NEXT:    add x8, x0, #32
; CHECK-GI-BE-NEXT:    st1 { v3.4s }, [x0]
; CHECK-GI-BE-NEXT:    add x0, x0, #16
; CHECK-GI-BE-NEXT:    st1 { v2.4s }, [x8]
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x0]
; CHECK-GI-BE-NEXT:    b.ne .LBB20_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.1 = getelementptr inbounds <16 x i8>, ptr %p1, i32 %iv
  %gep.2 = getelementptr inbounds <16 x i8>, ptr %p2, i32 %iv
  %l1 = load <16 x i8>, ptr %gep.1
  %z1 = sext <16 x i8> %l1 to <16 x i32>
  %l4 = load <16 x i8>, ptr %gep.2
  %z5 = zext <16 x i8> %l4 to <16 x i32>
  %mul = mul <16 x i32> %z1, %z5
  store <16 x i32> %mul, ptr %gep.1
  %iv.next= add nuw nsw i32 %iv, 1
  %exitcond.not = icmp eq i32 %iv.next, %h
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret i32 0
}

; Same as above but different type
define i32 @mul_zext_16i8_sext_16i16(ptr %p1, ptr %p2, i32 %h) {
; CHECK-SD-LABEL: mul_zext_16i8_sext_16i16:
; CHECK-SD:       ; %bb.0: ; %entry
; CHECK-SD-NEXT:    mov x8, x0
; CHECK-SD-NEXT:  LBB21_1: ; %loop
; CHECK-SD-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-SD-NEXT:    ldr q0, [x1], #16
; CHECK-SD-NEXT:    ldr q3, [x0]
; CHECK-SD-NEXT:    ldr q2, [x8, #16]!
; CHECK-SD-NEXT:    subs w2, w2, #1
; CHECK-SD-NEXT:    ushll2.8h v1, v0, #0
; CHECK-SD-NEXT:    ushll.8h v0, v0, #0
; CHECK-SD-NEXT:    smull2.4s v4, v2, v1
; CHECK-SD-NEXT:    smull.4s v1, v2, v1
; CHECK-SD-NEXT:    smull2.4s v2, v3, v0
; CHECK-SD-NEXT:    smull.4s v0, v3, v0
; CHECK-SD-NEXT:    stp q1, q4, [x0, #32]
; CHECK-SD-NEXT:    str q0, [x0]
; CHECK-SD-NEXT:    mov x0, x8
; CHECK-SD-NEXT:    str q2, [x8]
; CHECK-SD-NEXT:    b.ne LBB21_1
; CHECK-SD-NEXT:  ; %bb.2: ; %exit
; CHECK-SD-NEXT:    mov w0, wzr
; CHECK-SD-NEXT:    ret
;
; CHECK-SD-BE-LABEL: mul_zext_16i8_sext_16i16:
; CHECK-SD-BE:       // %bb.0: // %entry
; CHECK-SD-BE-NEXT:  .LBB21_1: // %loop
; CHECK-SD-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-SD-BE-NEXT:    ld1 { v0.16b }, [x1], #16
; CHECK-SD-BE-NEXT:    add x8, x0, #16
; CHECK-SD-BE-NEXT:    ld1 { v1.8h }, [x0]
; CHECK-SD-BE-NEXT:    ld1 { v3.8h }, [x8]
; CHECK-SD-BE-NEXT:    add x9, x0, #48
; CHECK-SD-BE-NEXT:    add x10, x0, #32
; CHECK-SD-BE-NEXT:    subs w2, w2, #1
; CHECK-SD-BE-NEXT:    ushll v2.8h, v0.8b, #0
; CHECK-SD-BE-NEXT:    ushll2 v0.8h, v0.16b, #0
; CHECK-SD-BE-NEXT:    smull v4.4s, v1.4h, v2.4h
; CHECK-SD-BE-NEXT:    smull2 v5.4s, v3.8h, v0.8h
; CHECK-SD-BE-NEXT:    smull v0.4s, v3.4h, v0.4h
; CHECK-SD-BE-NEXT:    smull2 v1.4s, v1.8h, v2.8h
; CHECK-SD-BE-NEXT:    st1 { v4.4s }, [x0]
; CHECK-SD-BE-NEXT:    mov x0, x8
; CHECK-SD-BE-NEXT:    st1 { v5.4s }, [x9]
; CHECK-SD-BE-NEXT:    st1 { v0.4s }, [x10]
; CHECK-SD-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-SD-BE-NEXT:    b.ne .LBB21_1
; CHECK-SD-BE-NEXT:  // %bb.2: // %exit
; CHECK-SD-BE-NEXT:    mov w0, wzr
; CHECK-SD-BE-NEXT:    ret
;
; CHECK-GI-LABEL: mul_zext_16i8_sext_16i16:
; CHECK-GI:       ; %bb.0: ; %entry
; CHECK-GI-NEXT:  LBB21_1: ; %loop
; CHECK-GI-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-GI-NEXT:    ldr q0, [x1], #16
; CHECK-GI-NEXT:    subs w2, w2, #1
; CHECK-GI-NEXT:    ldp q2, q3, [x0]
; CHECK-GI-NEXT:    ushll.8h v1, v0, #0
; CHECK-GI-NEXT:    ushll2.8h v0, v0, #0
; CHECK-GI-NEXT:    smull.4s v4, v2, v1
; CHECK-GI-NEXT:    smull2.4s v1, v2, v1
; CHECK-GI-NEXT:    smull.4s v2, v3, v0
; CHECK-GI-NEXT:    smull2.4s v0, v3, v0
; CHECK-GI-NEXT:    stp q4, q1, [x0]
; CHECK-GI-NEXT:    stp q2, q0, [x0, #32]
; CHECK-GI-NEXT:    add x0, x0, #16
; CHECK-GI-NEXT:    b.ne LBB21_1
; CHECK-GI-NEXT:  ; %bb.2: ; %exit
; CHECK-GI-NEXT:    mov w0, wzr
; CHECK-GI-NEXT:    ret
;
; CHECK-GI-BE-LABEL: mul_zext_16i8_sext_16i16:
; CHECK-GI-BE:       // %bb.0: // %entry
; CHECK-GI-BE-NEXT:  .LBB21_1: // %loop
; CHECK-GI-BE-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-GI-BE-NEXT:    ld1 { v0.16b }, [x1]
; CHECK-GI-BE-NEXT:    ld1 { v1.8h }, [x0]
; CHECK-GI-BE-NEXT:    add x8, x0, #16
; CHECK-GI-BE-NEXT:    ld1 { v3.8h }, [x8]
; CHECK-GI-BE-NEXT:    add x9, x0, #48
; CHECK-GI-BE-NEXT:    add x10, x0, #32
; CHECK-GI-BE-NEXT:    subs w2, w2, #1
; CHECK-GI-BE-NEXT:    add x1, x1, #16
; CHECK-GI-BE-NEXT:    ushll2 v2.8h, v0.16b, #0
; CHECK-GI-BE-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-GI-BE-NEXT:    smull2 v4.4s, v1.8h, v2.8h
; CHECK-GI-BE-NEXT:    smull v5.4s, v3.4h, v0.4h
; CHECK-GI-BE-NEXT:    smull2 v0.4s, v3.8h, v0.8h
; CHECK-GI-BE-NEXT:    smull v1.4s, v1.4h, v2.4h
; CHECK-GI-BE-NEXT:    st1 { v4.4s }, [x0]
; CHECK-GI-BE-NEXT:    mov x0, x8
; CHECK-GI-BE-NEXT:    st1 { v5.4s }, [x9]
; CHECK-GI-BE-NEXT:    st1 { v0.4s }, [x10]
; CHECK-GI-BE-NEXT:    st1 { v1.4s }, [x8]
; CHECK-GI-BE-NEXT:    b.ne .LBB21_1
; CHECK-GI-BE-NEXT:  // %bb.2: // %exit
; CHECK-GI-BE-NEXT:    mov w0, wzr
; CHECK-GI-BE-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.1 = getelementptr inbounds <16 x i8>, ptr %p1, i32 %iv
  %gep.2 = getelementptr inbounds <16 x i8>, ptr %p2, i32 %iv
  %l1 = load <16 x i16>, ptr %gep.1
  %z1 = sext <16 x i16> %l1 to <16 x i32>
  %l4 = load <16 x i8>, ptr %gep.2
  %z5 = zext <16 x i8> %l4 to <16 x i32>
  %mul = mul <16 x i32> %z1, %z5
  store <16 x i32> %mul, ptr %gep.1
  %iv.next= add nuw nsw i32 %iv, 1
  %exitcond.not = icmp eq i32 %iv.next, %h
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret i32 0
}
